### ISSUE TITLE
.Net MAUI Compatibility

### ISSUE THREAD

**Issue by SunshineSpring666** [Redth/ZXing.Net.Mobile#1009]
Hi Redth,
    ZXing for Xamarin is great.
    Are there any plan of releasing a version which works with .Net MAUI preview (the latest version of Xamarin)?
    Thanks a lot.

    Best Regards,
    Sunshine

**Comment by thomaskaelin** [comment]
@SunshineSpring666 Possible duplicate, please see #996.

**Comment by SunshineSpring666** [comment]
Thanks Thomas.
