### ISSUE TITLE
How to put it in a view, not always run full screen? 

### ISSUE THREAD

**Issue by linqingfeng** [Redth/ZXing.Net.Mobile#105]
Hello, 

How to put it in a view, not always run full screen? 

I try to set "CustomOverlay", run a scan when everything is normal. 

However, no matter how I set, always run full screen. 

I want to make it and that "CustomOverlay" View, put together in a container UI (for example, a layout or a Tab). 

But always can not find any way, do not see similar examples. 

How do I write code to achieve this effect? 

Thank you very much!

**Comment by ali-h2010** [comment]
@linqingfeng , can you please explain more? I want to implement this as part of the screen of a UWP app but the scanner covers the whole screen.
