### ISSUE TITLE
Project dead? Alternatives?

### ISSUE THREAD

**Issue by LeoJHarris** [Redth/ZXing.Net.Mobile#1082]
Is this project still maintained? Are there stable and active alternatives that can be used for barcode scanning? Anyone body tried using https://github.com/JimmyPun610/BarcodeScanner.Mobile with success, I will be giving it a go.

**Comment by DerErbil** [comment]
Hello @LeoJHarris, 
I know im late but do you/does anyone have a good alternative for this Nuget yet ?

I really can't understand that this Project is not being worked on anymore when so many people rely on it.
Literally ever alternative costs a fortune and I just can't afford that for my little Projects (exp: Scanbot.io)
