### ISSUE TITLE
Need Help / Alternatives / Anything

### ISSUE THREAD

**Issue by DerErbil** [Redth/ZXing.Net.Mobile#1084]
Hello everyone, 
My Name is Erbil and im working on a little **Xamarin.Forms** App that revolves around Scanning Barcodes. 

The Problems im having with this Project:
- Scanning does not seem to work that great in "Real Life Applications" like Scanning a Barcode from a Can of Coke. 
   (It works great if you wanna Scan a Barcode from a flat piece of Paper.. but that's just not very impressing.)
- You can't set the Scanning-Area: The ZXingScannerView detects Barcodes anywhere on the Screen and not just in a defined Space.

Otherwise ZXing.Net.Mobile is really neat and I would like to keep using it.
I know that probably nobody really cares about this Project anymore but I really need a fix for these Problems. 

Is there ANYONE out there that can help me fix this or suggest a better alternative to me that doesn't cost me a Fortune. (like Scanbot.io).

**Comment by FreakyAli** [comment]
The best open-source/free library for barcode scanning in Maui and XF https://github.com/JimmyPun610/BarcodeScanner.Mobile

**Comment by DerErbil** [comment]
> The best open-source/free library for barcode scanning in Maui and XF https://github.com/JimmyPun610/BarcodeScanner.Mobile

Thanks for the recommendation, will look into it.
