### ISSUE TITLE
Windows Phone 8.1 XAML support

### ISSUE THREAD

**Issue by igorkulman** [Redth/ZXing.Net.Mobile#111]
Any plans for Windows Phone 8.1 XAML support?

**Comment by graywill** [comment]
Would like to bump this issue. 8.1 Phone XAML support is much needed.

**Comment by dhavanr** [comment]
Thanks gray will. We are in high need of this in next month.

**Comment by venugopalchary** [comment]
Thanks for fast action , But make it fast my project is struck  with barcode reader in Windows phone 8.1  issue .

**Comment by dhavanr** [comment]
Hi All,

Have anybody found solution on scanning GS1 128 barcode using Zxing or any other API from Windows phone 8.1.

Our golive is not possible without this feature implemented. Any help is highly appreciated!!!

Thanks

**Comment by AmrTealeb** [comment]
Any updates of this issue?

**Comment by IvanGurtler** [comment]
In discussion ...  https://zxingnet.codeplex.com/discussions/566782  ... somebody mentioned VideoEffect lib ... I also tried it ... it is good

**Comment by igorkulman** [comment]
For everyone who needs a working solution, here is a sample app using ZXing.NET and Nokia Imaging Toolkit extracted from a project where I have it working: https://github.com/igorkulman/QRReader.WPA81

**Comment by dhavanr** [comment]
Hi All,

will the above solutions work for scanning GS 1 128 barcodes?  Any update with zxing library to support this barcode format on windows phone 8.1?

**Comment by Redth** [comment]
Please track this in #169 

This is an enhancement.

**Comment by Drakkins** [comment]
Does someone know an alternative bar code scanner which support WIndows phone 8.1 ? I don't find any.

**Comment by Redth** [comment]
Likely not, as there's no managed API for capturing the preview image buffer contents in 8.1.  There are a couple out there that might work on Nokia phones only for example, but nothing that doesn't make use of vendor specific SDK's that I know of.
