### ISSUE TITLE
WP: Windows Phone 8 crash

### ISSUE THREAD

**Issue by davidbritch** [Redth/ZXing.Net.Mobile#118]
If you run the v1.4.5 Windows Phone 8 sample it hangs (most of the time) after successfully scanning a QR code, and doesn't navigate back to the main page. 

Repro steps:
1. Scan a QR code with the default overlay.
2. QR code is recognized, message box appears which you dismiss, and then the app hangs with a frozen camera image. Navigation back to the main page doesn't occur.

This happens 90% of the time for me.

Whatever the issue is, it could also explain an intermittent hang I have with the library in an app I'm writing.

**Comment by Redth** [comment]
I can't reproduce this anymore.  I believe some of the checks when breaking down the camera have resolved this.
