### ISSUE TITLE
Sporadic exception in native objective-c using AVCapureEngine

### ISSUE THREAD

**Issue by matthiashartmann** [Redth/ZXing.Net.Mobile#127]
We are using ZXing as simple barcode scanner embed into a larger app written with Xamarin. Because of the faster processing we want to use the scanner with the option for AVCaptureEngine "true".

The most tests work as expected, but every now and then a native exception is thrown in IOS and then the app crashes without exception in Xamarin. It seems to be a problem in "AVCaptureEngine" causing a nullpointer if i read the stacktrace (below) the right way.

Please check if there is a problem in ZXing and sorry that I cannot describe the cause of the exception with more details or a test case.

The stack from objective-c:

0   libsystem_kernel.dylib        	0x384641f0 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x384ce792 pthread_kill + 54
2   libsystem_c.dylib             	0x38414fd8 abort + 72
3   ???			             	0x00c3af36 mono_handle_native_sigsegv (mini-exceptions.c:2342)
4   ???			             	0x00c441f6 mono_sigsegv_signal_handler (mini.c:6850)
5   libsystem_platform.dylib      	0x384c8f90 _sigtramp + 40

6   AVFoundation                  	0x2c57f2b0 -[AVCaptureMetadataOutput handleNotification:payload:] + 960

7   AVFoundation                  	0x2c5374e0 avcaptureSessionFigRecorderNotification + 476
8   AVFoundation                  	0x2c55d4e4 AVCMNotificationDispatcherCallback + 188
9   CoreFoundation                	0x2d561a5a __CFNotificationCenterAddObserver_block_invoke + 122
10  CoreFoundation                	0x2d5eb1ee __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 10
11  CoreFoundation                	0x2d55f53a _CFXNotificationPost + 1714
12  CoreFoundation                	0x2d57ade0 CFNotificationCenterPostNotification + 104
13  CoreMedia                     	0x2db7ac6e CMNotificationCenterPostNotification + 102
14  Celestial                     	0x312cf93c FigRecorderRemoteCallbacksServer_NotificationIsPending + 1620
15  Celestial                     	0x312cf2c2 _XNotificationIsPending + 42
16  Celestial                     	0x312cf274 figrecordercallbacks_server + 64
17  Celestial                     	0x312ce872 remrec_ClientPortCallBack + 146
18  CoreFoundation                	0x2d5e8ef6 __CFMachPortPerform + 134
19  CoreFoundation                	0x2d5f3ab4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 32
20  CoreFoundation                	0x2d5f3a4e __CFRunLoopDoSource1 + 342
21  CoreFoundation                	0x2d5f2222 __CFRunLoopRun + 1394
22  CoreFoundation                	0x2d55cf0a CFRunLoopRunSpecific + 518
23  CoreFoundation                	0x2d55ccee CFRunLoopRunInMode + 102
24  GraphicsServices              	0x324b565e GSEventRunModal + 134
25  UIKit                         	0x2fea8168 UIApplicationMain + 1132
26  ???			             	0x00116c94 (wrapper managed-to-native) MonoTouch.UIKit.UIApplication:UIApplicationMain + 268
27  ???			             	0x000d502c MonoTouch.UIKit.UIApplication:Main (UIApplication.cs:77)
28  ???			             	0x0008105c Spotawin.Client.Ios.Application:Main (Main.cs:47)
29  ???			             	0x002c8384 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 196
30  ???			             	0x00c463aa mono_jit_runtime_invoke (mini.c:6712)
31  ???			             	0x00c859ce mono_runtime_invoke (object.c:2828)
32  ???			             	0x00c89672 mono_runtime_exec_main (object.c:4085)
33  ???			             	0x00c894ba mono_runtime_run_main (object.c:3711)
34  ???			             	0x00c34328 mono_jit_exec (driver.g.c:1009)
35  ???			             	0x00cbc8d0 main (main.m:446)
36  libdyld.dylib                 	0x383aeab4 start + 0

**Comment by Redth** [comment]
This does look to be in AVCaptureEngine, not sure I can do much more without a bit more detail, hopefully this isn't still an issue.
