### ISSUE TITLE
How to keep the scanner/camera screen open to keep scanning?

### ISSUE THREAD

**Issue by cksodhi** [Redth/ZXing.Net.Mobile#130]
Hi Guys,

I would really appreciate if you could kindly let me know how to keep the camera/scanner open all the time until the user hits the back button?

As of now, once the QR code is scanned, it comes back to the calling screen.

Please help.

Thanks,
Charan

**Comment by omares** [comment]
Hey, any news on this feature or is there a workaround until version 1.5.0 is released?

**Comment by omares** [comment]
Hey @Redth any news on this feature or is there a workaround until version 1.5.0 is released?

**Comment by Redth** [comment]
This is now included, sorry it took so long, and 1.5.0 will be released very soon (days)
