### ISSUE TITLE
 ZXing Barcode scanner on Kitkat is not Capturing the Scaned Image 

### ISSUE THREAD

**Issue by maheshmuni** [Redth/ZXing.Net.Mobile#133]
Please help on what/which to look to solve the issue.
Problem: Barcode Scanner apk opens, Camera preview comes properly with the rectangle. But barcode is not getting captured after scanned for several no. of tries with different bar codes.

In logcat, no error message.
The camera parameters captured by the ZXing app itself is as follows.
BOARD=am437xevm
BRAND=Android
CPU_ABI=armeabi-v7a
DEVICE=am437xevm
DISPLAY=am437xevm-eng 4.4.4 KTU84Q eng.mistral.20140916.151004 test-keys
FINGERPRINT=Android/am437xevm/am437xevm:4.4.4/KTU84Q/eng.mistral.20140916.151004:eng/test-keys
HOST=LAP000167U
ID=KTU84Q
MANUFACTURER=Texas_Instruments_Inc
MODEL=AM437XEVM
PRODUCT=am437xevm
TAGS=test-keys
TIME=1410868264000
TYPE=eng
USER=mistral
VERSION.CODENAME=REL
VERSION.INCREMENTAL=eng.mistral.20140916.151004
VERSION.RELEASE=4.4.4
VERSION.SDK_INT=19
exposure-compensation-step=0
focus-mode-values=fixed
focus-mode=fixed
jpeg-quality=100
picture-format-values=jpeg
picture-format=jpeg
picture-size-values=1280x720,640x480,320x240,352x288,176x144
picture-size=640x480
preview-format-values=yuv422sp
preview-format=yuv422sp
preview-frame-rate-values=20
preview-frame-rate=15
preview-size-values=1280x720,640x480,320x240,352x288,176x144
preview-size=640x480
video-frame-format=yuv420p

the source is https://code.google.com/p/zxing/downloads/list

Is Any further setting is required to make the app work properly?

**Comment by Redth** [comment]
This is a C# ZXing *Mobile* project which uses the upsteam ZXing.Net C# port of the java ZXing.  It looks to me like you are talking about the java project which is unrelated to this.  Sorry.
