### ISSUE TITLE
Upstream: BarcodeWriter does not support cyrillic symbols.

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [Redth/ZXing.Net.Mobile#134]
Hello from cold-cold Russia! =) 
Today I use your BarcodeWriter on iOS platform. 
So, when I tried to generate QRCode with cyrillic symbols (for example: "Привет, Хуй с горы"), I getting barCode similar like "??????, ??? ? ????". 
Is there any support of cyrillic symbols?

**Comment by nesalexy** [comment]
ты решил проблему?

**Comment by Redth** [comment]
Hi, please check to see if the upstream http://zxingnet.codeplex.com project supports Cyrillic and if not, request this there :)  If it does please reply back and I'll take a further look at iOS specifically.
