### ISSUE TITLE
Restart Camera After ShutDown

### ISSUE THREAD

**Issue by lxshertz** [Redth/ZXing.Net.Mobile#139]
I'm using the scanner for bulk barcode scanning, I used the StartScanning and StopScanning methods IZXingScanner interface to define how I want the scanner to work, i.e It wont leave the camera view screen after scanning one barcode.
The camera shuts down when its scans a barcode, which makes sence, I wrote a method that opens the camera, sets caemra previewDisplay, camera previewCallback, CameraDisplayOrienrtation and StartPreview so i can continue to scan until I press the "done" or back button.
 
Please could you add a new method "StartCamera" in the  ZXingSurfaceView class, I can submit my code to you, you review it and see if you can merge it in.

Regards

**Comment by bmacadam** [comment]
I have the same situation where I need to validate the barcode that was read before scanning stops.  Would you be willing to share your modifications?

**Comment by Redth** [comment]
The next release will have continuous scanning (the code is already in master if you want to try it)

**Comment by bmacadam** [comment]
Thanks for the tip.  I tried it out and it worked.
