### ISSUE TITLE
Loading overlay not correctly displayed when in landscape mode on iPad

### ISSUE THREAD

**Issue by wegascee** [Redth/ZXing.Net.Mobile#140]
When the camera starts a loading overlay is displayed. The position of the spinner and the black background are shifted and doesn't cover the full screen. It seems that it doesn't respect the landscape and takes the portrait orientation as base with fixed dimensions. After a few seconds the camera starts up and everything is working fine (background fades to black before camera starts).

I have experienced this behavior on an iPad Air in landscape mode.

**Comment by Redth** [comment]
This should be fixed since this was reported.  Thanks.
