### ISSUE TITLE
Scanner on iOS does not recognize a QR Code

### ISSUE THREAD

**Issue by TMNDevelop** [Redth/ZXing.Net.Mobile#142]
Near every 3rd time, when I start the scanner (setting is QR Code only), it does not recognize the code.

After restarting it works perfect.
I use 1.4.7 release version.

Does anyone else have this issue?

Thanks,
Gerhard

**Comment by TMNDevelop** [comment]
no one else, who had this issue?

Thanks,
Gerhard

**Comment by nverinaud** [comment]
I have the same issue, it seems to happen randomly though.

**Comment by nverinaud** [comment]
After further investigation, I can reproduce this bug only when using Apple's AVCaptureSession mode.

**Comment by TMNDevelop** [comment]
I used a custom overlay, and I had the problems with AVCapture as well!

Thanks.

**Comment by TimurZanagar** [comment]
I've the problem if I use the native mode and not the Apple's AVCaptureSession mode. The only thing, it works perfectly after the second start of the scanner :-(

**Comment by Redth** [comment]
Please share a high resolution image of the barcode you're having issues with and reopen if it's still an issue.
