### ISSUE TITLE
Problem with a iOS custom overlay

### ISSUE THREAD

**Issue by cvarelae** [Redth/ZXing.Net.Mobile#144]
Hello mates,

I want to show a custom overlay with a image with a transparent rectangle where i want to show the image of the cam. The problem is that i don't know how i have to do to reduce the space of the image of the cam to scan what you are watching in the space that i want (The white rectangle in the next image)

Something like this:

![samplecam](https://cloud.githubusercontent.com/assets/8706339/5394922/5f65a59a-8143-11e4-8203-699ef19de8dc.png)

Any idea?

Thanks a lot in advance

**Comment by Redth** [comment]
In this case you would want to use the `ZXingScannerView` directly, so you can manipulate the area which shows the scanner.
