### ISSUE TITLE
Sample.iOS not working with Xamarin.ios 8.6

### ISSUE THREAD

**Issue by keeeew** [Redth/ZXing.Net.Mobile#146]
Unified Sample does not work when deploying on devices and not on simulator with Xamarin.ios 8.6

Failed to resolve "System.Void CoreGraphics.CGBitmapContext::.ctor(System.IntPtr,System.Int32,System.Int32,System.Int32, System.Int32,CoreGraphics.CGColorSpace,CoreGraphics.CGImageAlphaInfo)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

typecast to int from nint fails 
=> https://github.com/Redth/ZXing.Net.Mobile/pull/147

**Comment by Redth** [comment]
This will not occur with newer versions of Xamarin.iOS
