### ISSUE TITLE
Cross-Platform Plugin

### ISSUE THREAD

**Issue by aritchie** [Redth/ZXing.Net.Mobile#148]
Love this project.  I use it everywhere.  I've been maintaining a plugin portion for your library for Xamarin Forms & MvvmCross for several months.  I've recently built the bait & switch version.  I would love to simply supply a PR to your library instead of being a secondary wrapper.

Would you be interested?

**Comment by Redth** [comment]
@aritchie yes!  I've sort of had the idea on my todo list.  I just haven't had the time to implement it.  I have seen your repo, love that you created the plugin!

Question... Without digging into your code, how are you approaching getting the `Context` on Android?  That's the one bigger 'difference' between the platforms for the API.  Are you simply using Application Context?

Anyway, yes, I'd be very happy to work with you on a PR to make this lib officially PCL compatible with bait and switch.

**Comment by aritchie** [comment]
@Redth I avoid Application.Context as much as possible.  The plugin approach requires android to call Init method that takes the initial activity.  The init process also registers an IActivityLifecycleCallbacks so I can always catch the top activity to use.  

Using this approach means you'll have to bump your minimum target up to API 14 though

**Comment by Redth** [comment]
Ahh nice.  I like that approach much better.  I have no problem bumping to API 14.

**Comment by omares** [comment]
:+1: PCL Support would be awesome

**Comment by Redth** [comment]
This should work as a PCL nuget in the next release.
