### ISSUE TITLE
Unable to scan PDF 417

### ISSUE THREAD

**Issue by ViktorBergman** [Redth/ZXing.Net.Mobile#151]
I'm unable to scan PDF 417 from a WP8.1 app using the scannercontrol. I've tested with 3 different codes. XZing online can decode all the codes aswell as a number of other scanners on the store.

Should I take something in consideration when attempting to scan PDF 417?

**Comment by neoncube2** [comment]
I'm also having trouble scanning PDF417 barcodes.

**Comment by Redth** [comment]
Scanning works fine for me in landscape mode.  Could you please provide a high resolution image of the barcode you are trying to scan?
