### ISSUE TITLE
Windows Phone 8.1 - Sample App Freezes Occassionally

### ISSUE THREAD

**Issue by graywill** [Redth/ZXing.Net.Mobile#152]
This is the same issue it seems as #81, which was closed without resolution. I'm using a Nokia 635 and using the Samples/WindowsPhone8 sample app. It freezes about 1 out of every 50 scans. I will see about building the library from source and debugging since it seems you can't reproduce. Just wanted to re-open the issue anyway.

**Comment by graywill** [comment]
Struggling to debug the issue. When it freezes, it never throws any exception anywhere. The screen freezes, the back button doesn't do anything. Only way to exit is the use the Windows button on the phone, or if debugging, you can terminate the process. It definitely appears to happen more frequently when you run from VS2013, rather than deploying and running directly from the phone.

**Comment by graywill** [comment]
On MainPage.xaml.cs Line 41, I commented out the ".ContinueWith", leaving just:
scanner.Scan();

I am now unable to reproduce the issue. Does this give anyone a clue? Is there a better way to handle the result that may not cause the freezing?

**Comment by Redth** [comment]
Thanks, this will be in the next release!
