### ISSUE TITLE
No ability to resize the scannable window

### ISSUE THREAD

**Issue by samichamoun** [Redth/ZXing.Net.Mobile#154]
Hi,

I wanted to point out that the following variables do not appear to be used in the ZXingSurfaceView.cs file:
        private const int MIN_FRAME_WIDTH = 240;
        private const int MIN_FRAME_HEIGHT = 240;
        private const int MAX_FRAME_WIDTH = 600;
        private const int MAX_FRAME_HEIGHT = 400;

I have managed to resize the overlay in half inside of the function GetFramingRect(Canvas canvas) of ZXingOverlayView.cs by reducing the height value, but there is not ability (that I can see) to do this without updating the source. Even so, this reduces the clear window on the scanner, but has no impact on reducing where a barcode can be scanned. Upon holding the barcode outside the window, i can still pickup a result.

Next, I went into ZXingSurfaceView.cs and edited the function OnPreviewFrame(byte[] bytes, Android.Hardware.Camera camera).

I reduced the height variable, which is declared as:
var height = cameraParameters.PreviewSize.Height;

On my local device, the height being picked up was 960. If I reduce this a little bit, it still works, but if I divide by 2 (effectively halving the scannable size, which matches up with how much I reduced the overlay), the scanner won't work.

I created a loop which iteratively calls the barcodeReader.decode function (once it has already found a result) passing in a lower height each time with the same bytes until it fails. Sometimes this fails at around 700 height, sometimes gets down to 570. Any idea why this would be failing? It seems there is more support in the java version than the C# version.

Thank you

**Comment by Redth** [comment]
So if I understand correctly you're trying to make the scanner use a smaller part of the preview image to look for barcodes in.  

To do this, you really can't just change the height variable, you would actually need to crop the image data that comes out of the 'OnPreviewFrame'.  

This is something I've considered doing, however it may add some memory/cpu overhead to do so.  At this point, it's just not supported, sorry.
