### ISSUE TITLE
Hitting cancel crashed app

### ISSUE THREAD

**Issue by empsortberg** [Redth/ZXing.Net.Mobile#157]
When im pressing cancel in the scanning view, the app crashes.
Do i need to handle the cancel click? or is there some options i need to pass to the constructor?

And if so, can you provide with a example?

**Comment by jharr100** [comment]
Hitting cancel does not crash my app. However, when you hit cancel it returns null and you have to handle that. I'm using iOS and Xamarin.

**Comment by empaaa** [comment]
Hmm okey. I will take a look on that at work tomorrow. Thanks for the reply.

**Comment by empsortberg** [comment]
Works like a charm, Cheers!
