### ISSUE TITLE
Mobile Barcode Scanner does work properly

### ISSUE THREAD

**Issue by haktancinkilic** [Redth/ZXing.Net.Mobile#158]
I used mobile barcode scanner in my few applications. In some of them it works, for others, it throws an exception e_accessdenied when scanner.Scan() method is called. What would be the reason?  I am working on windows phone 8.0 and 8.1

**Comment by lxshertz** [comment]
what platform did you get the exception.

**Comment by haktancinkilic** [comment]
Sorry I forgot that. I am working on windows phone 8.0 and 8.1

**Comment by lxshertz** [comment]
I haven't used the scanner on windows, only iOS and android. maybe you should check if the app have access to use the device camera.

**Comment by haktancinkilic** [comment]
If it was the problem then none of the applications would work. They have the same properties, capabilities.

**Comment by fonix232** [comment]
e_accessdenied is definitely a permission problem. Double check if you gave those apps access to the camera!

**Comment by Redth** [comment]
Closing unless there's more info.
