### ISSUE TITLE
How to use on Windows Phone?

### ISSUE THREAD

**Issue by Avalaxy** [Redth/ZXing.Net.Mobile#159]
I'm trying to use this in my Windows Phone app (Universal app, not a Xamarin app) but I can't get it working. The MobileBarcodeScanner needs a Dispatcher in its constructor, but it uses the System.Windows.Threading dispatcher, which isn't even available on Windows Phone. How did other people get this working?

**Comment by wcoder** [comment]
I use this:
```
[assembly: Dependency(typeof(QrCodeScanningService))]

namespace Test1.WinPhone.Services
{
	class QrCodeScanningService : IQrCodeScanningService
	{
		public async Task<string> ScanAsync()
		{
			var scanner = new ZXing.Mobile.MobileBarcodeScanner(App.RootFrame.Dispatcher);
			var scanResults = await scanner.Scan();

			return scanResults.Text;
		}
	}
}
```

**Comment by Avalaxy** [comment]
Can you *please*  read my question? I'm talking about a universal app, not about a Xamarin app. That's the whole point, I could find code for Xamarin, but it doesn't work with the normal Windows Phone.

**Comment by Redth** [comment]
Universal isn't really supported yet.  There's no nice way (thanks Microsoft) to capture camera preview frames that I'm aware of yet (perhaps it's changed in newer sdk versions?).
