### ISSUE TITLE
WP: Flash/torch does not turn on

### ISSUE THREAD

**Issue by andyhammar** [Redth/ZXing.Net.Mobile#163]
Hi! Thanks for a great lib!

I have a problem though, the flash won't turn on.
Trying this with Xamarin Forms, has no effect on either platform. (iOS, Droid, Wp).
(Lib works and we can scan codes - but would really like the flash be on by default).

iOS has a flash button, and that turns on the flash.

But doing:
  scanner.Torch(true);
or
  scanner.ToggleTorch();
before starting to scan has no effect.

(On Droid, scanner.IsTorchOn=true after the call, but on Wp = false)

Am I using it wrong?
Thanks

**Comment by lxshertz** [comment]
did you solve the issue yet? but I think you should be using the toggleTorch() method.. 
that's what i am using with the ZxingScannerView...

**Comment by andyhammar** [comment]
Thanks, I actually forked it and modded so the flash is turned on after the camera is initialized. The problem with creating a scanner, activating the torch then running the modal Scan-method, is that it's trying to activate the torch before the camera is initialized doesn't work.
Will push a pull request when the pressure drops in this project...

**Comment by Redth** [comment]
So apparently Flash doesn't work with the `PhotoCamera` class I'm using unless you are actually capturing an image (not using the preview frame).  I'm going to look into using the `AudioVideoCaptureDevice` class instead (which gives some additional control for other features) which should allow this.  For now, this will be an enhancement, sorry (I never had a device with flash to test on until recently)

**Comment by Redth** [comment]
Please follow #183 for this issue/enhancement

**Comment by wezzix** [comment]
I'm using 2.1.0-beta1 and I had the same issue still.
Workaround was a Delay like so. Has the issue been adressed yet?
            var scanTask = scanner.Scan();
            await Task.Delay(100);
            scanner.Torch(true);
            var result = await scanTask;
            scanner.Torch(false);

**Comment by helzgate** [comment]
@wezzix I still can't set torch on before scanning using the default overlay.   And there is no torch button on the default overlay and no information on the documentation about the restrictions of using the torch like, "you can only use it with a custom overlay".  So many people probably spend countless hours trying to get it to work with the default overlay when I'm guessing it isn't possible.  But it would help if someone would clarify.
