### ISSUE TITLE
Navigate into scanning view instead of presenting it modally

### ISSUE THREAD

**Issue by ciryon** [Redth/ZXing.Net.Mobile#165]
The scanner view is on iOS opened modally (presentViewController), but it would be really, really useful to be able to navigate into the scanning view (pushed onto navigation stack with pushViewController).

**Comment by rgerla** [comment]
Hi,

Since I'm not using a Navigation page for me IOS app, I would also rather have it working via the PushModal functionality. It's functioning perfectly without a navigation page in both Winphone and Android.

Greetings,

**Comment by ciryon** [comment]
On iOS we have a view that's opened modally where the user can enter some text into text fields. In this case we want the user to be able to scan, but this is not possible since it's not possible to open a modal view from a modal view (on iOS).

**Comment by Redth** [comment]
You can use the `ZXingScannerView` class yourself which is just a normal `UIView` with all the scanner functionality built in.  This way you can display a scanner wherever you need to in your app: 
https://github.com/Redth/ZXing.Net.Mobile/blob/master/src/ZXing.Net.Mobile/iOS/ZXingScannerView.cs
