### ISSUE TITLE
WPA: Windows Phone Universal Support

### ISSUE THREAD

**Issue by mlus88laky** [Redth/ZXing.Net.Mobile#169]
Can you release it for windows 8.1?

**Comment by Avalaxy** [comment]
+1 for Windows Phone 8.1 (universal app)

**Comment by Redth** [comment]
Last I checked there's no decent api to capture camera preview frame buffers.  I'll have another look but i'm not too optimistic!

**Comment by Avalaxy** [comment]
Maybe this will help? https://msdn.microsoft.com/en-us/library/windows.phone.media.capture.cameracaptureframe.getpreviewbufferargb.aspx

**Comment by Redth** [comment]
Yes that is one way to accomplish it, but it's not managed code which is what I was hoping for.  This is not within my comfort zone so I won't be getting to it very quickly.

**Comment by tmm360** [comment]
Any news for this? Can be compatible also with UWP applications?

**Comment by Binjaaa** [comment]
I see that there is a WPA8.1 support now, but it's not working. It's looking for the Windows.Phone.dll what is definitely not the right dll.

**Comment by darylw** [comment]
Following on from @Binjaaa - it looks like WPA8.1 support has been added in, but not sure to what extent. I get the same error with the Microsoft.phone.dll not being resolved, (Type universe cannot resolve assembly: Microsoft.Phone, Version=8.0.0.0 etc)

Any update on this would be greatly appreciated as to what is left to do on this if anything, and if not then if this issue could be resolved that would be amazing. This is hugely exciting, as both my Xamarin project and my universal one would be utilising one (excellent) product for its QR code reading, with potentially the same code. @Redth please let us know as soon as is convenient!

**Comment by Redth** [comment]
Sorry folks, wpa81 should not have been in the nuspec file, and will be excluded from future versions.

I'm looking into a couple techniques for UWP support currently.  Hope to have something soon!

**Comment by StacyHenwood** [comment]
+1 for 8.1 support. Updated from nuget today, got all excited, then very disappointed with the windows.phone.dll error :(

**Comment by Redth** [comment]
I don't think wpa81 will be supported. The apis make it really tough to access camera preview buffer data. 

The good news is that I'm already partially done work for windows universal UWP support.

**Comment by ViktorBergman** [comment]
@Redth Really great news about the UWP support. Is there anything that I can help you with to make it more stable? I've been trying out the samples and found some issues but not sure how close to finished you are (before I start filing new issues here)...

**Comment by Redth** [comment]
@ViktorBergman thanks, I think as of right now the code is fairly stabilized (of course that doesnt mean there aren't bugs!) so if you pull from master and start finding issues with UWP, please do report bugs... I'm a bit unfamiliar with UWP so any help in fixing bugs is also greatly appreciated!
