### ISSUE TITLE
Windows Phone 8.1 Silverlight

### ISSUE THREAD

**Issue by s0ulre4ver** [Redth/ZXing.Net.Mobile#170]
So far i have managed to get this working in my silverlight application with the following caveat:

1 when launching the app the scanner initialises correctly. if the user then presses the window key at the bottom of the screen then the app gets suspended. If the user then swipes right to left and navigates to the app and opens the app again that way then the scanner intermittenly doesnt initialise the camera/scanner correctly. if this happens then the app may also crash out completely from time to time.

**Comment by Redth** [comment]
I can't reproduce this with the latest code in master on my Lumia 640 running Windows 10 preview.  Please reopen if it persists with more information about how to reproduce (i've tried a couple ways but maybe I'm not doing it quite like you are).
