### ISSUE TITLE
Android: Rotating the device causes flipped camera orientation

### ISSUE THREAD

**Issue by redwolf2** [Redth/ZXing.Net.Mobile#173]
https://www.youtube.com/watch?v=9hBpF_Zj4OA

How to show the issue
Activate automatic screen rotation. Start your Sample in Landscape Mode. Rotate your device upside down (180°) as fast as you can.

Here is how to avoid the issue:

Create a new Member in ZXingSurfaceView:

            protected ZXingSurfaceViewOrientationChangelistener OrientationChangelistener;

Put this in the constructor initialisation of ZXingSurfaceView:

            OrientationChangelistener = new ZXingSurfaceViewOrientationChangelistener(this, Context);
            if (OrientationChangelistener.CanDetectOrientation())
                OrientationChangelistener.Enable();

Add this class inside ZXingSurfaceView:

        protected class ZXingSurfaceViewOrientationChangelistener : OrientationEventListener
        {
            private readonly ZXingSurfaceView _surfaceView;
            private readonly Context _context;

            public ZXingSurfaceViewOrientationChangelistener(ZXingSurfaceView surfaceView, IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
            {
            }

            public ZXingSurfaceViewOrientationChangelistener(ZXingSurfaceView surfaceView, Context context)
                : base(context)
            {
                _surfaceView = surfaceView;
                _context = context;
            }

            public ZXingSurfaceViewOrientationChangelistener(ZXingSurfaceView surfaceView, Context context, SensorDelay rate)
                : base(context, rate)
            {
                _surfaceView = surfaceView;
                _context = context;
            }

            public override void OnOrientationChanged(int orientation)
            {
                _surfaceView.SetCameraDisplayOrientation(_context);
            }
        }

**Comment by Redth** [comment]
This is an old one i believe has since been fixed :)

**Comment by autosoftmultimedia** [comment]
with xamarin forms, I got this same issue. any way? 
package is up to date.
