### ISSUE TITLE
ZXingScannerFragment crashes on orientation change right after detecting QR code

### ISSUE THREAD

**Issue by GeirSmestad** [Redth/ZXing.Net.Mobile#175]
Using ZXing.Net.Mobile version 1.4.7.2 from the Xamarin Component Store. Xamarin.Android 5.1.3.2 and Xamarin 3.11.590.0 and Android 5.1.1 on Nexus5.

To reproduce: 

(1) Create a basic FragmentActivity with a custom overlay view.
(2) Register a ZXingScannerFragment in the OnCreate of your FragmentActivity, and use the SupportFragmentManager to add the Scanner Fragment to the Activity

(3) Scan a QR code, and as soon as the overlay "freezes" when the QR code is detected (but before the callback is called and executed), flip the device. The app crashes.

Example project: https://www.dropbox.com/s/i8jlbkie43p3yt7/DoesZXingCrash.zip?dl=0

----

Stack trace:

06-22 14:49:50.787 I/MonoDroid(26976): UNHANDLED EXCEPTION:
06-22 14:49:50.798 I/MonoDroid(26976): Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
06-22 14:49:50.798 I/MonoDroid(26976): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
06-22 14:49:50.798 I/MonoDroid(26976): at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) [0x00063] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:571
06-22 14:49:50.798 I/MonoDroid(26976): at Android.Hardware.Camera.SetPreviewCallback (Android.Hardware.Camera/IPreviewCallback) [0x00044] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Hardware.Camera.cs:5121
06-22 14:49:50.798 I/MonoDroid(26976): at ZXing.Mobile.ZXingSurfaceView.ShutdownCamera () <IL 0x0001d, 0x000a7>
06-22 14:49:50.798 I/MonoDroid(26976): at ZXing.Mobile.ZXingScannerFragment.OnPause () <IL 0x0000c, 0x00077>
06-22 14:49:50.798 I/MonoDroid(26976): at Android.Support.V4.App.Fragment.n_OnPause (intptr,intptr) <IL 0x0000a, 0x0009f>
06-22 14:49:50.798 I/MonoDroid(26976): at (wrapper dynamic-method) object.d6a498b0-0e4e-47cd-9163-33a7ce781a3f (intptr,intptr) <IL 0x00011, 0x0003b>
06-22 14:49:50.798 I/MonoDroid(26976):   --- End of managed exception stack trace ---
06-22 14:49:50.798 I/MonoDroid(26976): java.lang.RuntimeException: Camera is being used after Camera.release() was called
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.hardware.Camera.setHasPreviewCallback(Native Method)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.hardware.Camera.setPreviewCallback(Camera.java:779)
06-22 14:49:50.798 I/MonoDroid(26976): 	at md5e1d4744ef128cd013cac92521f1a8e76.ZXingScannerFragment.n_onPause(Native Method)
06-22 14:49:50.798 I/MonoDroid(26976): 	at md5e1d4744ef128cd013cac92521f1a8e76.ZXingScannerFragment.onPause(ZXingScannerFragment.java:46)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.Fragment.performPause(Fragment.java:1947)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:993)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:1931)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:390)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.app.Activity.performPause(Activity.java:6101)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
06-22 14:49:50.798 I/MonoDroid(26976): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3246)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3918)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.app.ActivityThread.access$900(ActivityThread.java:151)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.os.Looper.loop(Looper.java:135)
06-22 14:49:50.799 I/MonoDroid(26976): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
06-22 14:49:50.799 I/MonoDroid(26976): 	at java.lang.reflect.Method.invoke(Native Method)
06-22 14:49:50.799 I/MonoDroid(26976): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-22 14:49:50.799 I/MonoDroid(26976): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
06-22 14:49:50.799 I/MonoDroid(26976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

----

My actual app has a different stack trace for this error. This is probably due to the fact that it uses a different Layout structure, but I'm posting the stack trace just in case there are two separate issues.

06-22 14:13:21.808 I/MonoDroid(21743): UNHANDLED EXCEPTION:
06-22 14:13:21.823 I/MonoDroid(21743): Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
06-22 14:13:21.823 I/MonoDroid(21743): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
06-22 14:13:21.823 I/MonoDroid(21743): at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) [0x00063] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:571
06-22 14:13:21.823 I/MonoDroid(21743): at Android.Hardware.Camera.SetParameters (Android.Hardware.Camera/Parameters) [0x0005a] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.Hardware.Camera.cs:5089
06-22 14:13:21.823 I/MonoDroid(21743): Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.06-22 14:13:21.823 I/MonoDroid(21743): at ZXing.Mobile.ZXingSurfaceView.SurfaceChanged (Android.Views.ISurfaceHolder,Android.Graphics.Format,int,int) <IL 0x001fc, 0x00daf>
06-22 14:13:21.823 I/MonoDroid(21743): at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceChanged_Landroid_view_SurfaceHolder_III (intptr,intptr,intptr,int,int,int) [0x00013] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.Views.ISurfaceHolder.cs:164
06-22 14:13:21.823 I/MonoDroid(21743): at (wrapper dynamic-method) object.de4d3dce-bbf0-472b-9805-8b58a09255d7 (intptr,intptr,intptr,int,int,int) <IL 0x00029, 0x0007b>
06-22 14:13:21.823 I/MonoDroid(21743):   --- End of managed exception stack trace ---
06-22 14:13:21.823 I/MonoDroid(21743): java.lang.RuntimeException: Camera is being used after Camera.release() was called
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.hardware.Camera.native_setParameters(Native Method)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.hardware.Camera.setParameters(Camera.java:1876)
06-22 14:13:21.823 I/MonoDroid(21743): 	at md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView.n_surfaceChanged(Native Method)
06-22 14:13:21.823 I/MonoDroid(21743): 	at md5e1d4744ef128cd013cac92521f1a8e76.ZXingSurfaceView.surfaceChanged(ZXingSurfaceView.java:60)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:591)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.SurfaceView.setFrame(SurfaceView.java:300)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15667)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.View.layout(View.java:15671)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.os.Handler.handleCallback(Handler.java:739)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.os.Looper.loop(Looper.java:135)
06-22 14:13:21.823 I/MonoDroid(21743): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
06-22 14:13:21.823 I/MonoDroid(21743): 	at java.lang.reflect.Method.invoke(Native Method)
06-22 14:13:21.823 I/MonoDroid(21743): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-22 14:13:21.823 I/MonoDroid(21743): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
06-22 14:13:21.823 I/MonoDroid(21743): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by GeirSmestad** [comment]
This appears to be fixed in [the following commit](https://github.com/Redth/ZXing.Net.Mobile/commit/af82bba585bd849df250d33666885e0545e129af), but the fix is not included in the latest Nuget or Xamarin Component Store packages, despite that these were packaged after the above commit was made.

Details: I've checked the latest Nuget version 1.4.7.1 and the Xamarin Component Store version 1.4.7.2. The version of the Nuget and Xamarin Component reflects the correct version number, but the ZXing.Net.Mobile assembly in "References" in Visual Studio is version 1.4.7.0 for both these packages, which is the last version where this issue is not fixed.

Would it be possible to request an updated Nuget/Xamarin Component Store package?

**Comment by Redth** [comment]
Yes this will be updated shortly, thanks.

**Comment by GeirSmestad** [comment]
Many thanks =)
