### ISSUE TITLE
iOS unable to read Code39 (atleast these ones)

### ISSUE THREAD

**Issue by Hendel81** [Redth/ZXing.Net.Mobile#176]
Hi,
 I've attached an image of the type of barcode iOS is mostly unable to read.
 I've tested on: iPhone 5 (can't read ever), iPhone 6 (can't read ever), iPad Retina Display (can't read ever), iPad Air (was able to read a couple of times out of many many trys).

On the 2 Android phones I have, it did take a while and some patience to get it to read, but it would work eventually.
But not so much luck with the iOS devices.

MobileBarcodeScanningOptions options = new MobileBarcodeScanningOptions();
            options.PossibleFormats = new List<ZXing.BarcodeFormat>()
            {
                ZXing.BarcodeFormat.CODE_128,
                ZXing.BarcodeFormat.CODE_39,
                ZXing.BarcodeFormat.CODE_93
            };
            options.AutoRotate = true;
            //options.PureBarcode = true;
            
#if __IOS__
            var result = await _scanner.Scan(options, true);
#else
            var result = await _scanner.Scan(options);
#endif

Thanks,
~Hendel

![image1](https://cloud.githubusercontent.com/assets/13153409/8481678/07df8672-20aa-11e5-98fc-eb1c7cd59f0d.jpeg)
![image2](https://cloud.githubusercontent.com/assets/13153409/8481680/07e3dd3a-20aa-11e5-80af-d19e743c567c.png)
![image3](https://cloud.githubusercontent.com/assets/13153409/8481679/07e2de3a-20aa-11e5-8d31-de516137268a.png)

**Comment by Hendel81** [comment]
2nd image

**Comment by Redth** [comment]
Hi, using latest code in master I can successfully scan that barcode in landscape mode, on an iPhone 4S.

**Comment by Hendel81** [comment]
I um unable to scan it at all using an iPhone 6 in landscape or portrait mode. I'm using Zxing.Net.Mobile version 1.5.1.0.
