### ISSUE TITLE
Android: AutoRotate = false, wont work on certain Android Phones e.g. Asus ZenPhone C

### ISSUE THREAD

**Issue by mingyuen78** [Redth/ZXing.Net.Mobile#182]
There's an issue related to autoRotate being set to false, it seems in certain android Phones they still scan on wrong orientation. This is repeatable in Asus ZenPhone C

**Comment by mingyuen78** [comment]
i found out the real issue, actually autorotate check true/false will fail whenever tryharder is set to true. As if it is try hard to "scan the code when it's landscape" supposedly we locked auto rotate based on portrait.

**Comment by Redth** [comment]
TryHarder basically tries to rotate the captured image and look for a barcode at each rotation (effectively rotating it 4 times and checking 4 times for a barcode per preview frame captured).  Use this only if you absolutely must as it will really affect performance.
