### ISSUE TITLE
WP: Switch to AudioVideoCaptureDevice for Camera Reader

### ISSUE THREAD

**Issue by Redth** [Redth/ZXing.Net.Mobile#183]
Right now PhotoCamera has some drawbacks:
1. It won't turn on the flash unless capturing an image (so not for preview buffers)
2. Preview resolution is not selectable

`AudioVideoCaptureDevice` seems to allow these things.  Need to investigate implementing this.

**Comment by shnaz** [comment]
Hey guys, first of all, thank you for the amazing tool you are providing!

I have recently made an winphone8 app for the company I work for, which uses the Zxing scanner to scan QR codes.

I have the exact same problem, where the torch cant be turned on. Can you maybe give a hint when to expect this solved?

**Comment by Strifex** [comment]
I'm just curious, is anyone currently working on this?

**Comment by shnaz** [comment]
Wondering the same thing...

**Comment by r2d2rigo** [comment]
I'm using this library for a project and have hit the WP flash limitation. I would gladly jump into it and update the `PhotoCamera` code to use `AudioVideoCaptureDevice` instead as I have previous experience on camera capture APIs on WP8.

Any guidelines on how should I proceed with this? Should I still keep the `PhotoCamera` version as a fallback?

**Comment by Redth** [comment]
Thanks to the wonderful contribution, this is done!
