### ISSUE TITLE
Legacy code broken with release 1.5

### ISSUE THREAD

**Issue by timahrentlov** [Redth/ZXing.Net.Mobile#185]
Previously this code worked:

IBarcodeWriter writer = new BarcodeWriter
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new ZXing.Common.EncodingOptions
                {
                    Height = 300,
                    Width = 300
                }
            };
var result = writer.Write("generator works");
var wb = result.ToBitmap() as WriteableBitmap;

//add to image component
image.Source = wb;

How does one do it with 1.5?

https://stackoverflow.com/questions/27984564/how-to-create-a-qr-code-image-using-zxing-on-windows-phone-8-1#new-answer

**Comment by Redth** [comment]
Ahh yes, this is from switching to a portable zxing.net library.  That is not very convient.  I will add back in platform specific barcode writers into the zxing.net.mobile layer and release an update.

Thanks for reporting this!

**Comment by timahrentlov** [comment]
You're welcome. And thanks for all the hard work!

**Comment by Redth** [comment]
So, version 1.5.1.0 is up on NuGet with this functionality back in, just make user to use `ZXing.Mobile.BarcodeWriter` which should give you a `Write (..)` method returning an image/bitmap type native to the platform you're working with.

**Comment by timahrentlov** [comment]
Successfully re-compiled a Xamarin Forms project.
