### ISSUE TITLE
Error running Android Sample

### ISSUE THREAD

**Issue by leo-mck** [Redth/ZXing.Net.Mobile#187]
Running the android sample I am getting the exception
`System.MissingMethodException: Method not found: 'Android.Runtime.JNIEnv.CallObjectMethod'.`

on 

`SupportFragmentManager.BeginTransaction()
.Replace (Resource.Id.fragment_container,scanFragment).Commit(); `

Am I doing something wrong?

**Comment by Redth** [comment]
What version of Xamarin.Android are you on?  This sounds like you are using an old version...

**Comment by jamesatgithub** [comment]
I use "Xamarin.Android   4.20.0.37" and also cannot get the example working with error like:

08-07 14:51:45.031 D/Mono    ( 2989): Assembly Ref addref ZXingNetMobile[0x5c6ac2e0] -> Xamarin.Android.Support.v4[0x5abdcc48]: 2
08-07 14:51:45.265 W/        ( 2989): Missing method Android.Runtime.JNIEnv::CallObjectMethod(intptr,intptr,JValue*) in assembly Mono.Android.dll, referenced in assembly Xamarin.Android.Support.v4.dll
An unhandled exception occured.

**Comment by Redth** [comment]
You need to update to Xamarin.Android 5.1 or later which has been out since April.  Some things were changed in the binding code and you'll be unable to use Support V4 with any versions older than that.
