### ISSUE TITLE
Exclusive access to the camera

### ISSUE THREAD

**Issue by forTAT** [Redth/ZXing.Net.Mobile#189]
I am trying to implement the ZXing barcode library into my Xamarin.Forms project.
Because I am having a few problems there I tried the android demo project from the library: Sample.Android.

This one seems to work well but it crashes when putting the app into background and getting it back into foreground with the following exception:

    [MonoDroid] UNHANDLED EXCEPTION:
    [MonoDroid] System.Exception: Couldn't get exclusive access to the camera
    [MonoDroid] at ZXing.Mobile.ZXingSurfaceView.GetExclusiveAccess () <IL 0x00033, 0x00150>
    [MonoDroid] at ZXing.Mobile.ZXingSurfaceView.StartScanning     (ZXing.Mobile.MobileBarcodeScanningOptions,System.Action`1<ZXing.Result>) <IL 0x00046, 0x0028b>
    [MonoDroid] at ZXing.Mobile.ZXingScannerFragment.scan () <IL 0x00012, 0x0007f>
    [MonoDroid] at ZXing.Mobile.ZXingScannerFragment.OnResume () <IL 0x000fd, 0x00617>
    [MonoDroid] at Android.Support.V4.App.Fragment.n_OnResume (intptr,intptr) <IL 0x0000a, 0x0009f>
    [MonoDroid] at (wrapper dynamic-method) object.2ec0fbbb-3a10-48d4-b1ab-3fe72444ec91 (intptr,intptr) <IL 0x00011, 0x0003b>

Does anybody know how to fix this problem?

**Comment by xillie** [comment]
Also having this problem, would love a release for this fix! Thanks so much, I love the package.

**Comment by PaulAchess** [comment]
Hi,

I have a couple of users that experience this error on a regular basis.
Do you know where it comes from ? Just to know if I can add a check to avoid the application to crash.

Thanks !

**Comment by retv12** [comment]
friend there any way to do direct on the library

**Comment by Redth** [comment]
This should be fixed by #205 

Please reopen if it is still an issue after this patch.

**Comment by PaulAchess** [comment]
Awesome, you're the best !

**Comment by retv12** [comment]
good morning, I'm not very good with someone could publish libraries and DLL already adjusted mistake and thank you

**Comment by Redth** [comment]
https://www.nuget.org/packages/ZXing.Net.Mobile/1.5.3 is available on nuget.

**Comment by moflaherty** [comment]
Hey, we are seeing this pop up now from time to time. Our app is a Xamarin Forms/PCL project with ZXingNetMobile 2.0.4.24. It is intermittent but happening regularly. Any suggestions? I do not know how to reopen this thread (or whether it should be reopened and a new one entered.) Thanks!
![crash](https://cloud.githubusercontent.com/assets/7761823/12819409/016e4a60-cb29-11e5-97af-8a3623fb9dc5.PNG)

**Comment by Redth** [comment]
This looks like StartScanning was called multiple times before the first scan is finished... Maybe evaluate your code to ensure that cannot happen?

**Comment by moflaherty** [comment]
I am assuming what you are seeing is the call stack. In this case, we are using a custom overlay and  _ScanContinuously_. The above call is a result of that call. I put a breakpoint on the _ScanContinuously _and it is not being called more than once. Is that what you mean? Or is there something external we may be calling?

**Comment by tbalcom** [comment]
I've seen this happen rarely with the version 2.0.4.23 from NuGet on some Android devices.  The stack trace is the same as moflaherty shows.  I'm simply adjusting the TopText & BottomText and calling Scan() from a MvvmCross ViewModel.

**Comment by xillie** [comment]
I still get a (this?) crash when I open the scanner, then go to HOME and then back to app.

**Comment by lukegore** [comment]
I'm facing the same issue as xillie and moflaherty using scanner with CustomerOverlay.

> I still get a (this?) crash when I open the scanner, then go to HOME and then back to app.

I'm currently using version 2.1.0-beta1 from NuGet (Xamarin.Android), but had this problem also with earlier stable versions. Any further progress on this issue?

> System.Exception
Couldn't get exclusive access to the camera
  at ZXing.Mobile.ZXingSurfaceView.GetExclusiveAccess () <0x8e9e3880 + 0x000c4>
  at ZXing.Mobile.ZXingSurfaceView.OnSurfaceCreated () <0x8e9e2438 + 0x000d7> 
  at ZXing.Mobile.ZXingSurfaceView.SurfaceCreated (ISurfaceHolder holder)

**Comment by F1nZeR** [comment]
@lukegore PR #325 should fix this, you can try it

**Comment by lukegore** [comment]
Thank you! works like a charm!
