### ISSUE TITLE
Won't scan on Android 4.4 Kit Kat with 3mpx camera

### ISSUE THREAD

**Issue by paulsperanza** [Redth/ZXing.Net.Mobile#190]
I'm new to android development but I bought a cheap phone to test with that has a 3mpx camera. It tries to scan but never gets it. Looking at the scanner in progress it does appear to be a bit blurry. I'm not sure if I am missing a setting or not.

**Comment by Redth** [comment]
You could try and change the default resolution selected by setting up a `MobileBarcodeScanningOptions.CameraResolutionSelector` delegate handler.

3 megapixels is pretttty weak, so it's possible it's not going to scan very well (especially depending on focus).
