### ISSUE TITLE
Cannot scan PDF417 of CT state drivers license

### ISSUE THREAD

**Issue by paulsperanza** [Redth/ZXing.Net.Mobile#191]
Has anyone seen an issue like this? I can scan the state's barcode from their sample document (http://www.ct.gov/dmv/lib/dmv/licensebarcode.doc) but if I try to scan on an actual drivers license it never scans. I have tried this on 3 licenses. I'm on an android samsung gallaxy S4.

Thank you

**Comment by Redth** [comment]
Any way you can privately share an image of an actual license? I can try running it through the scanner without the mobile device as a variable.

**Comment by joelbrito** [comment]
I went through the same problem, but after setting CameraResolutionSelector delegate to return bigger resolutions i was able to scan it successfully most of the times.
By default the lowest resolution is chosen for the preview (https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Android/ZXingSurfaceView.cs#L118).

**Comment by Redth** [comment]
Good to keep in mind, thanks for responding :)
