### ISSUE TITLE
WP: Can't access camera after using Windows (home) button + exception after first attempt

### ISSUE THREAD

**Issue by rmdaustin** [Redth/ZXing.Net.Mobile#193]
Similar to #164 but involving the use of the Windows (home button)

Problem: 
Camera area of scan window is blank after using Windows (home) button and returning to app.  Sometimes an exception is thrown.

Steps to reproduce:

Using Samples/WindowsPhone8/Sample.WindowsPhone8 

Start the app (emulator or device)
Touch "Scan with Default View"
Wait for camera to start
Touch Windows (home) button
Touch and hold back button to get app list
Select ZxingSharp.WindowsPhone to return to app
App will land on menu
Select "Scan with Default View" again
Scan window will show but with white/black (depending on theme) scan area (camera never launches)

On subsequent repeats of home->back->select app an Exception is thrown:

"{"Initialization canceled by .Dispose().\r\nObject name: 'Camera'."}"

Call stack:

>	ZxingSharp.WindowsPhone.Sample.ni.DLL!ZxingSharp.WindowsPhone.Sample.App.Application_UnhandledException(object sender, System.Windows.ApplicationUnhandledExceptionEventArgs e) Line 104	C#
 	System.Windows.ni.dll!MS.Internal.Error.CallApplicationUEHandler(System.Exception e)	Unknown
 	System.Windows.ni.dll!System.Windows.Application.OnPlatformAssemblyUnhandledException(System.Exception e, bool recoverable)	Unknown
 	Microsoft.Devices.Camera.ni.dll!Microsoft.Devices.Camera.InitializeVideoSession.AnonymousMethod__0()	Unknown
 	mscorlib.ni.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.ni.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.ni.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown

Alternate steps to reproduce:

Start the app (emulator or device)
Touch "Scan with Default View"
Wait for camera to start
Touch Windows (home) button
Touch back button
App will land on menu
Select "Scan with Default View" again
Scan window will show but with white/black (depending on theme) scan area (camera never launches)

If you return to the app by instead going to All Apps and selecting it from the list, no exception occurs and the camera runs as normal.

**Comment by Redth** [comment]
I believe this is fixed now with a previous PR.  Please reopen if you can repro this problem on the latest version.
