### ISSUE TITLE
Android: Canceling on ScanContinuously results in infinite loop

### ISSUE THREAD

**Issue by mulhaus1** [Redth/ZXing.Net.Mobile#195]
When canceling the scanner in scan continuously mode, the app locks up due to an infinite loop. I think it's caused by this redundant section of code in the MobileBarcodeScanner's ScanCountinuously Method:

![screen shot 2015-09-01 at 6 32 40 pm](https://cloud.githubusercontent.com/assets/2609153/9619659/edf0df0a-50d7-11e5-9ee6-36f9ec4a2dde.png)

After removing this section of code, the scanner cancels as expected.

**Comment by SivanTR** [comment]
How soon this fix would be available in General Release

**Comment by Redth** [comment]
I will get this up to NuGet sometime this week, and into the component store shortly thereafter.
