### ISSUE TITLE
Options to show the scanner for iOS simulator

### ISSUE THREAD

**Issue by PureKrome** [Redth/ZXing.Net.Mobile#199]
I'm trying to test out the scanner with the iOS simulator and (not sure if this is an issue) Xamarin.Forms.

When I follow [the really simple sample code provided by @Redth](https://gist.github.com/Redth/8e12a1cd3cc84cfdda6e) here it compiles but throws a runtime exception when trying to display the camera to scan the image. The simulator doesn't really have a live camera - so that I get.

It would be really lovely to have an option (nuget package?) that allows us to define the behaviour if the simulator is in use => like to allow us to choose an existing image (eg. finder modal popup which we can browse to a location).

On twitter, [@Redth and I have a convo about this](https://twitter.com/purekrome/status/651364457566736385) and @Redth said some people might not like this suggestion but prefer to use an Overlay. I couldn't figure out what this Overlay thingy is - as the simulator is always crashing, saying that the component `is not implemented for this device type` (suggesting not implemented for the simulator).

So .. maybe this issue could kick start a conversation about what happens with the simulator (as demonstrated with some sample code) and then what could be _offered_ to developers who wish to use the simulator(s) to develop with ZXing.

NOTE: I've only been trying this library on iOS + Xam Forms.

**Comment by Redth** [comment]
@PureKrome could you give a stack trace for the crash?  I can't reproduce the simulator crashing here (could be due to Forms, not sure).  What you should see is something like this:

![sim](https://cloud.githubusercontent.com/assets/271950/11064978/a8bdf95c-878e-11e5-80f1-4466080b0801.gif)

**Comment by PureKrome** [comment]
@Redth ta for the reply. I'll give this a go in a few days or so and report back, for sure. :+1:

**Comment by PureKrome** [comment]
Hi @Redth - sincere appols for the late reply and not getting onto this, sooner

First, what is the repo you are using, in the image, above? 

Is it the iOS samples? => https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/iOS

**Comment by Redth** [comment]
Sorry I missed your response, please let me know if you still need help here.

**Comment by PureKrome** [comment]
all good. np!
