### ISSUE TITLE
Android: ZXingScannerView can't connect to Camera on Resume

### ISSUE THREAD

**Issue by M3psipax** [Redth/ZXing.Net.Mobile#206]
Since version 1.5.4.0 the line 534 in ZXingSurfaceView occasionally throws an exception when called via OnResume() of ZXingScannerFragment because it can't connect to the camera resulting in the scanner overlay being shown without the actual camera view behind it. Causing OnResume() again fixes the issue, but it might occur again at random. 

Here's the stacktrace:

11-13 13:09:05.883 I/mono-stdout(27404): Got Camera Exclusive access
11-13 13:09:05.883 D/ZXing.Net.Mobile(27404): Checking Number of cameras...
11-13 13:09:05.883 D/ZXing.Net.Mobile(27404): Found 2 cameras...
11-13 13:09:05.884 D/ZXing.Net.Mobile(27404): Found Back Camera, opening...
11-13 13:09:05.885 W/CameraBase(27404): An error occurred while connecting to camera: 0
11-13 13:09:05.893 I/mono-stdout(27404): Releasing Exclusive access to camera
11-13 13:09:05.899 I/mono-stdout(27404): Releasing Exclusive access to camera
11-13 13:09:05.914 I/mono-stdout(27404): Setup Error: Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
11-13 13:09:05.915 I/mono-stdout(27404):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 
11-13 13:09:05.915 I/mono-stdout(27404):   at Android.Runtime.JNIEnv.CallStaticObjectMethod (IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1301 
11-13 13:09:05.915 I/mono-stdout(27404):   at Android.Hardware.Camera.Open (Int32 cameraId) [0x00044] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Hardware.Camera.cs:4947 
11-13 13:09:05.915 I/mono-stdout(27404):   at ZXing.Mobile.ZXingSurfaceView.StartScanning (ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1 callback) [0x0011a] in <filename unknown>:0 
11-13 13:09:05.915 I/mono-stdout(27404):   --- End of managed exception stack trace ---
11-13 13:09:05.915 I/mono-stdout(27404): java.lang.RuntimeException: Fail to connect to camera service
11-13 13:09:05.915 I/mono-stdout(27404): 	at android.hardware.Camera.<init>(Camera.java:529)
11-13 13:09:05.915 I/mono-stdout(27404): 	at android.hardware.Camera.open(Camera.java:364)
11-13 13:09:05.915 I/mono-stdout(27404): 	at md5fbe1730f19340e19ad8e4d756e4d2723.ZXingScannerFragment.n_onResume(Native Method)
11-13 13:09:05.915 I/mono-stdout(27404): 	at md5fbe1730f19340e19ad8e4d756e4d2723.ZXingScannerFragment.onResume(ZXingScannerFragment.java:38)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.Fragment.performResume(Fragment.java:2005)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:132711-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2011)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:187)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:426)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:415)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.Activity.performResume(Activity.java:6089)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3008)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3050)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.access$1000(ActivityThread.java:154)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.os.Looper.loop(Looper.java:135)
11-13 13:09:05.916 I/mono-stdout(27404): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
11-13 13:09:05.916 I/mono-stdout(27404): 	at java.lang.reflect.Method.invoke(Native Method)
11-13 13:09:05.916 I/mono-stdout(27404): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-13 13:09:05.916 I/mono-stdout(27404): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-13 13:09:05.916 I/mono-stdout(27404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
11-13 13:09:05.917 I/mono-stdout(27404): SurfaceCreated took 34,2543ms
11-13 13:09:06.014 I/Timeline(27404): Timeline: Activity_idle id: android.os.BinderProxy@3a8e2139 time:6555793

**Comment by Redth** [comment]
Hmm, I'm not sure how to debug this.  It could be the camera not releasing correctly, however I've also seen weird issues in other camera apps with this where rebooting solves this.

Can you do a bit more debugging and see if you are able to create a reproducible set of steps for this?

**Comment by M3psipax** [comment]
I just tried again. I've got the Scanner in a fragment that takes up half of the screen. I just have to switch back and forth betweend portrait and landscape modes and it will eventually give me that error.

**Comment by Redth** [comment]
Ok this is related to #208 then I believe

**Comment by M3psipax** [comment]
Yep, sounds like the same issue.

**Comment by M3psipax** [comment]
Thank you very much for fixing this. It works flawlessly with the latest version!
