### ISSUE TITLE
Automatic screen rotation causes screen to go black

### ISSUE THREAD

**Issue by phmeek** [Redth/ZXing.Net.Mobile#208]
The last version that automatic screen rotation worked correctly was v1.5.1.0.  On versions 1.5.3.0 and 1.5.4.0 when the device is rotated from portrait to landscape (or vice versa) the screen goes black and it is not possible to scan the bar-code.

**Comment by Grzesik** [comment]
Hi, I have the same problem. On my LG G4c (Android 5.0.2) it works, on Samsung SM-T800 (Android 5.0.2) I have the same problem.

**Comment by phmeek** [comment]
I have downgraded to v1.5.1.0 and this seems to work for now.  For some reason it was broken in later releases.  Can this be fixed?
