### ISSUE TITLE
Reverse Image on Nexus 5x

### ISSUE THREAD

**Issue by FatCow8686** [Redth/ZXing.Net.Mobile#209]
Hi, I am using this library for scanning qr code on a Nexus 5x device, and have found that the image is reversed on the screen. After some digging in the web, I have found that there is the same issue in the original zxing project for the case:

https://github.com/zxing/zxing/issues/484

Just wondering if there is a quick fix for this issue on this .net port, thank you very much.

**Comment by Redth** [comment]
#211 fixes this.
