### ISSUE TITLE
Exceptions with "WindowsUniversal/Sample.WindowsUniversal"

### ISSUE THREAD

**Issue by Bob12345** [Redth/ZXing.Net.Mobile#215]
var frame = await mediaCapture.GetPreviewFrameAsync(destFrame) is throwing the following exception on my laptop with a video cam, not the emulators for phone:

System.Exception was unhandled by user code
  HResult=-1072875854
  Message=The request is invalid in the current state. (Exception from HRESULT: 0xC00D36B2)
  Source=Windows
  StackTrace:
       at Windows.Media.Capture.MediaCapture.GetPreviewFrameAsync(VideoFrame destination)
       at ZXing.Mobile.ZXingScannerControl.<>c__DisplayClass1_0.<<StartScanning>b__1>d.MoveNext()
  InnerException: 

To get past the issue I've modified the code in the following way. Also, increasing TimeSpan.FromMilliseconds from 200 ms to a bigger number makes the exceptions go away. I'm new to the async-await thing, but it seems like there's a problem with it here:

   public async Task StartScanning(Action<ZXing.Result> scanCallback, MobileBarcodeScanningOptions options = null)
        {
            ScanCallback = scanCallback;
            ScanningOptions = options ?? MobileBarcodeScanningOptions.Default;

            topText.Text = TopText ?? string.Empty;
            bottomText.Text = BottomText ?? string.Empty;

            if (UseCustomOverlay && CustomOverlay != null)
            {
                gridCustomOverlay.Children.Clear();
                gridCustomOverlay.Children.Add(CustomOverlay);

                gridCustomOverlay.Visibility = Visibility.Visible;
                gridDefaultOverlay.Visibility = Visibility.Collapsed;
            }
            else
            {
                gridCustomOverlay.Visibility = Visibility.Collapsed;
                gridDefaultOverlay.Visibility = Visibility.Visible;
            }

            // Find which device to use
            var preferredCamera = await this.GetFilteredCameraOrDefaultAsync(ScanningOptions);            
            mediaCapture = new MediaCapture();
            
            // Initialize the capture with the settings above
            await mediaCapture.InitializeAsync(new MediaCaptureInitializationSettings()
            {
                StreamingCaptureMode = StreamingCaptureMode.Video,
                VideoDeviceId = preferredCamera.Id
            });

            // Set the capture element's source to show it in the UI
            captureElement.Source = mediaCapture;

            // Start the preview
            await mediaCapture.StartPreviewAsync();
            
            // Get all the available resolutions for preview
            var availableProperties = mediaCapture.VideoDeviceController.GetAvailableMediaStreamProperties(MediaStreamType.VideoPreview);
            var availableResolutions = new List<CameraResolution>();
            foreach (var ap in availableProperties)
            {
                var vp = (VideoEncodingProperties)ap;
                availableResolutions.Add(new CameraResolution { Width = (int)vp.Width, Height = (int)vp.Height });                
            }
            var previewResolution = availableResolutions.FirstOrDefault();
            if (ScanningOptions.CameraResolutionSelector != null)
                previewResolution = ScanningOptions.CameraResolutionSelector(availableResolutions);

            // Find the matching property based on the selection, again
            var chosenProp = availableProperties.FirstOrDefault(ap => ((VideoEncodingProperties)ap).Width == previewResolution.Width && ((VideoEncodingProperties)ap).Height == previewResolution.Height);

            // Set the selected resolution
            await mediaCapture.VideoDeviceController.SetMediaStreamPropertiesAsync(MediaStreamType.VideoPreview, chosenProp);

            // Get our preview properties
            var previewProperties = mediaCapture.VideoDeviceController.GetMediaStreamProperties(MediaStreamType.VideoPreview) as VideoEncodingProperties;
            
            // Setup a frame to use as the input settings
//            var destFrame //= new VideoFrame(Windows.Graphics.Imaging.BitmapPixelFormat.Bgra8, (int)previewProperties.Width, (int)previewProperties.Height);
//                 = new VideoFrame(BitmapPixelFormat.Bgra8, (int)previewProperties.Width, (int)previewProperties.Height);
            var zxing = ScanningOptions.BuildBarcodeReader();

            timerPreview = new Timer(async (state) => {
                System.Diagnostics.Debug.WriteLine("#_TIMER_CALLBACK");

                var destFrame //= new VideoFrame(Windows.Graphics.Imaging.BitmapPixelFormat.Bgra8, (int)previewProperties.Width, (int)previewProperties.Height);
                 = new VideoFrame(BitmapPixelFormat.Bgra8, (int)previewProperties.Width, (int)previewProperties.Height);
                if (stopping)
                {
                    System.Diagnostics.Debug.WriteLine("#STOPPING");
                    return;
                }
                if (mediaCapture == null || mediaCapture.CameraStreamState != Windows.Media.Devices.CameraStreamState.Streaming)
                {
                    System.Diagnostics.Debug.WriteLine("#MC_NULL");
                    return;
                }

                try {
                    // Get preview 
                    using (var frame = await mediaCapture.GetPreviewFrameAsync(destFrame))//????????
                    {
                        System.Diagnostics.Debug.WriteLine("#_GetPreviewFrameAsync");
                        // Create our luminance source
                        var luminanceSource = new SoftwareBitmapLuminanceSource(frame.SoftwareBitmap);

                        //Try decoding the image
                        var result = zxing.Decode(luminanceSource);

                        //Check if a result was found
                        if (result != null && !string.IsNullOrEmpty(result.Text))
                        {
                            if (!ContinuousScanning)
                                await StopScanning();
                            LastScanResult = result;
                            ScanCallback(result);
                        }
                    }
                }
                catch
                {
                    System.Diagnostics.Debug.WriteLine("#pooooooooooooooooop");
                }
            }, null, TimeSpan.FromMilliseconds(200), TimeSpan.FromMilliseconds(200));           
        }

**Comment by Bob12345** [comment]
As you can see I've added my eloquent exception resolution System.Diagnostics.Debug.WriteLine("#pooooooooooooooooop"); It only happens _ONCE_ and then the things continue to work as normal.

**Comment by Redth** [comment]
Not sure which commit you are using but I've changed things up a bit since the code you pasted...

https://github.com/Redth/ZXing.Net.Mobile/blob/xamarin-forms/Source/ZXing.Net.Mobile.WindowsUniversal/ZXingScannerControl.xaml.cs#L191-L207

I now do wrap that in a try/catch, but I think I've isolated the issue causing the exceptions in the first place (I think the timer was firing again before the first callback was done processing - so I've added a flag to check if processing is still happening and skip frames if so).

**Comment by Bob12345** [comment]
Thank you!
