### ISSUE TITLE
Windows Forms applications do not fire / Read Barcodes

### ISSUE THREAD

**Issue by brucemcmillan** [Redth/ZXing.Net.Mobile#219]
Hi,

I have been using the Xamarin components and as a result downloaded and used the zip file from the link on the Xmarin component store.

The ones on the component store work well :-)

I have also downloaded the latest master from GitHub. I notice that the windows phone 8 sample in the master - forms / samples solution does not seem to fire / display the message that it has scanned a barcode. The android one seems to work just fine.

I get the same behaviour if I create a new solution in visual studio and install the librires via the nugget package manager.

B....

**Comment by Redth** [comment]
Yep I had negated the IsAnalyzing check accidentally, this is fixed in 59fb4e89a43
