### ISSUE TITLE
Android / Xamarin Forms sample app crashes with double read of barcode

### ISSUE THREAD

**Issue by brucemcmillan** [Redth/ZXing.Net.Mobile#220]
Hi,

Using the latest xamarin forms for android sample.

when a barcode is scanned, the message is popped onto the screen ( Great) 
Then in the time period between returning to the main page, the app reads the barcode again and then pops a second message , then the app crashes.

If you quickly move the phone away from the barcode after the first message has appeared then the app will return to the main page so you can press the scan with default overlay button again

consistently repeatable..

B....

**Comment by Redth** [comment]
Yep, I think it was scanning too quickly (even before I could set IsAnalyzing = false).  I've changed the sample to set IsScanning = false when it's going to exit the page, I think this is more appropriate and should work around the issue.
