### ISSUE TITLE
Android + ZXing.Net.Mobile 2.0.1: no video from camera displayed, no scan on Windows Phone 8.1

### ISSUE THREAD

**Issue by mariorasch** [Redth/ZXing.Net.Mobile#221]
HI,

I just updated my Xamarin.Forms project from ZXing.Net.Mobile v. 1.5.4.0 to v. 2.0.1. I am using the latest stable release of Xamarin Forms v. 2.0.0.6490.

Alas I experience some issues when trying to scan a QR code.

1. On Windows Phone 8.1 the scanning control is shown with working video. Alas the "Scan" method does not return when hovering a QR code.

My code looks as follows:

            MobileBarcodeScanningOptions mobileBarcodeScanningOptions
                = new MobileBarcodeScanningOptions()
                    {
                        PossibleFormats
                            = new List<BarcodeFormat>()
                                {
                                    BarcodeFormat.QR_CODE
                                }
                    };

            return new MobileBarcodeScanner(this.dispatcher)
                {
                    BottomText
                        = Texts.ViewLogin_Scan_BottomText,

                    CameraUnsupportedMessage
                        = Texts.ViewLogin_Scan_CameraUnsupportedMessage,

                    CancelButtonText
                        = Texts.ViewLogin_Scan_CancelButtonText,

                    FlashButtonText
                        = Texts.ViewLogin_Scan_FlashButtonText,

                    TopText
                        = Texts.ViewLogin_Scan
                }
                .Scan
                    (
                        mobileBarcodeScanningOptions
                    )
                .ContinueWith<string>
                    (
                        t =>
                        {
                            if (t.IsFaulted)
                            {
                                Logging.LogLogin.Instance.Write
                                    (
                                        String.Format
                                            (
                                                XPhoneMobile.UI.Resources.Texts.ViewLogin_Scan_Error,
                                                t.Exception.Message.Trim('.'),
                                                "NULL"
                                            )
                                    );

                                return null;
                            }

                            else if (                         t.Result != null
                                     && !String.IsNullOrEmpty(t.Result.Text))
                                return t.Result.Text;

                            else
                                return String.Empty;
                        }
                    );

2. In the Visual Studio 2015 Android Emulator KitKat 4.4 + Lollipop 5.1.1 and on a real Android device using KitKat 4.4.2 the scanning Activity is shown with a flashing red line, but without showing any video.

My code looks as follows:

            MobileBarcodeScanningOptions mobileBarcodeScanningOptions
                = new MobileBarcodeScanningOptions()
                    {
                        PossibleFormats
                            = new List<BarcodeFormat>()
                                {
                                    BarcodeFormat.QR_CODE
                                }
                    };

            return new MobileBarcodeScanner()
                {
                    BottomText
                        = Texts.ViewLogin_Scan_BottomText,

                    CameraUnsupportedMessage
                        = Texts.ViewLogin_Scan_CameraUnsupportedMessage,

                    CancelButtonText
                        = Texts.ViewLogin_Scan_CancelButtonText,

                    FlashButtonText
                        = Texts.ViewLogin_Scan_FlashButtonText,

                    TopText
                        = Texts.ViewLogin_Scan
                }
                .Scan
                    (
                        mobileBarcodeScanningOptions
                    )
                .ContinueWith<string>
                    (
                        t =>
                        {
                            if (t.IsFaulted)
                            {
                                Logging.LogLogin.Instance.Write
                                    (
                                        String.Format
                                            (
                                                XPhoneMobile.UI.Resources.Texts.ViewLogin_Scan_Error,
                                                t.Exception.Message.Trim('.'),
                                                "NULL"
                                            )
                                    );

                                return null;
                            }

                            else if (                         t.Result != null
                                     && !String.IsNullOrEmpty(t.Result.Text))
                                return t.Result.Text;

                            else
                                return String.Empty;
                        }
                    );

 In the device log I can see:

Android 4.4:

12-17 15:28:33.019 I/ActivityManager(  465): START u0 {flg=0x10000000 cmp=com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity} from pid 1404
12-17 15:28:33.023 D/dalvikvm( 1404): GC_FOR_ALLOC freed 2077K, 28% free 6494K/8988K, paused 3ms, total 3ms
12-17 15:28:33.027 D/dalvikvm( 1404): GC_CONCURRENT freed 7K, 17% free 7517K/8988K, paused 1ms+0ms, total 3ms
12-17 15:28:33.055 D/ZXing.Net.Mobile( 1404): Checking Camera Permissions...
12-17 15:28:33.055 D/ZXing.Net.Mobile( 1404): ZXingScannerFragment->OnResume exit
12-17 15:28:33.083 W/EGL_emulation( 1404): eglSurfaceAttrib not implemented
12-17 15:28:33.135 I/ActivityManager(  465): Displayed com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity: +100ms
12-17 15:28:36.263 W/EGL_emulation( 1404): eglSurfaceAttrib not implemented
12-17 15:28:37.987 D/dalvikvm(  478): GC_CONCURRENT freed 387K, 14% free 3129K/3612K, paused 1ms+0ms, total 3ms
12-17 15:28:48.151 D/Mono    ( 1404): [0xb9535890] hill climbing, change max number of threads 2
12-17 15:29:02.155 D/Mono    ( 1404): [0xb9535890] hill climbing, change max number of threads 3

Android 5.1.1:

12-17 15:31:56.648 I/ActivityManager(  446): START u0 {flg=0x10000000 cmp=com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity} from uid 10074 on display 0
12-17 15:31:56.650 V/WindowManager(  446): addAppToken: AppWindowToken{368f71db token=Token{11d69aea ActivityRecord{57192d5 u0 com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity t16}}} to stack=1 task=16 at 1
12-17 15:31:56.669 D/ZXing.Net.Mobile( 2234): Checking Camera Permissions...
12-17 15:31:56.669 D/ZXing.Net.Mobile( 2234): ZXingScannerFragment->OnResume exit
12-17 15:31:56.670 V/WindowManager(  446): Adding window Window{1c58751 u0 com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity} at 3 of 8 (after Window{be1c2cc u0 com.c4b.mxphoneconnect/md5dd1a8f2c61887f100d086806ca93f457.MainActivity})
12-17 15:31:56.729 W/EGL_emulation( 2234): eglSurfaceAttrib not implemented
12-17 15:31:56.729 W/OpenGLRenderer( 2234): Failed to set EGL_SWAP_BEHAVIOR on surface 0x86108e40, error=EGL_SUCCESS
12-17 15:31:56.732 V/WindowManager(  446): Adding window Window{248950b7 u0 SurfaceView} at 3 of 9 (before Window{1c58751 u0 com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity})
12-17 15:31:56.765 I/ActivityManager(  446): Displayed com.c4b.mxphoneconnect/md56280c0ff0254d3a6dcc87931551a87c9.ZxingActivity: +100ms
12-17 15:31:58.611 W/EGL_emulation( 2234): eglSurfaceAttrib not implemented
12-17 15:31:58.611 W/OpenGLRenderer( 2234): Failed to set EGL_SWAP_BEHAVIOR on surface 0x98d22d40, error=EGL_SUCCESS
12-17 15:31:58.685 W/AudioTrack(  446): AUDIO_OUTPUT_FLAG_FAST denied by client

Can you reproduce these errors and fix them?

Best regards!
Mario.

**Comment by Redth** [comment]
Did you give the android app camera and flashlight permissions?   Your first issue is fixed in #219 and will be released to nuget shortly

**Comment by mariorasch** [comment]
Thanks! Regarding Android I indeed missed the FLASHLIGHT permission.
