### ISSUE TITLE
UWP rootFrame is null

### ISSUE THREAD

**Issue by bruzkovsky** [Redth/ZXing.Net.Mobile#222]
There is a NullReferenceException thrown in the Scan-Method. It happens when the Method is called from a nested Frame, which is the case when using the SplitView control. Possible fix would be to introduce a Frame Property like Dispatcher, so you can decide in which Frame the navigation occurs.

**Comment by Redth** [comment]
Interesting.  I think this is about the only approach to take.

**Comment by Redth** [comment]
This should be an ok workaround, but being as unfamiliar with UWP as I am, can you think of a better way to get the 'current' frame for navigation?

**Comment by bruzkovsky** [comment]
Your approach of getting the current active Window is sufficient for Architectures where Pages reside directly in the root Frame. In the case of a SplitView, the Content property of the WIndow is a Page, not a Frame, so the as-cast results in a null reference.
In this case, casting the Content to a FrameworkElement, you can use VisualTreeHelper to get the child Frame.
I will make a fork for this.

**Comment by Redth** [comment]
Thanks, merged your PR!
