### ISSUE TITLE
xamarin version in component store - issue with continous scanning in IOS

### ISSUE THREAD

**Issue by brucemcmillan** [Redth/ZXing.Net.Mobile#225]
Hi,

Thanks for looking at the other two forms issue for version latest..

Not sure if you have come across this issue, but I'm still working with the version from the Xamarin component store (1.5.4 ? )

In the IOS version in the homeview controller

The continious scanning option calls this line of code

                        //Start scanning
                        scanner.ScanContinuously (opt, true, HandleScanResult);

However using the above you only get one scan and the reader seems to stop scanning or recording the scan

if you change the code to read
                        //Start scanning
                        scanner.ScanContinuously (opt, HandleScanResult);

as per the andriod / windows sample then the coninious scanning option works 

Thanks

B...

**Comment by Redth** [comment]
Try the latest nuget package...

**Comment by Redth** [comment]
Thanks for pointing this out, there was a bug specifically in the AVCaptureScannerView logic that didn't have continuous scanning working correctly.  This has been fixed by 63bdc5ed139fa39c30d52b3d003019e546db0c5c
