### ISSUE TITLE
Stopped working without android.permission.FLASHLIGHT granted

### ISSUE THREAD

**Issue by mikhailmelnik** [Redth/ZXing.Net.Mobile#226]
Recent nuget package update (2.0.3.1) broke existing application functionality as without `<uses-permission android:name="android.permission.FLASHLIGHT" />` permission scanner activity just stays black.

**Comment by jamesmontemagno** [comment]
I believe this is now required.

**Comment by mikhailmelnik** [comment]
If it is not an Android requirement I would prefer to have it optional to keep list of app permissions a bit shorter.

**Comment by jamesmontemagno** [comment]
I don't think it actually is required, and might just be a bug if you
aren't going to use the flash methods (although, it would make a lot of
sense to allow users to turn it on). Only redth can verify

**Comment by jasoncouture** [comment]
Id vote this as a bug either way, either it needs to not fail silently with a missing flashlight permission or permissions should added to the Xamarin.Android platform library

IE:

`[assembly: UsesPermission(Android.Manifest.Permission.Camera)]`
`[assembly: UsesPermission(Android.Manifest.Permission.Flashlight)]`

Just my $0.02

**Comment by jamesmontemagno** [comment]
Yeah, I think if it it isn't required then just fix the "Flashlight" thing, but I vote to add:

[assembly: UsesPermission(Android.Manifest.Permission.Camera)]

**Comment by Redth** [comment]
This is fixed/closed by #227 and #228 Thanks!
