### ISSUE TITLE
Black Screen Marschmallow

### ISSUE THREAD

**Issue by Toubap** [Redth/ZXing.Net.Mobile#227]
Hi,

Using ZXing 2.0.3.1 (last version I guess) with Xamarin last stable release.

I'm getting a black screen while scanning in Marschmallow (Nexus 6P).
Last releases were supposed to fix the issue but I'm still stuck.

ZXing.Net.Mobile] Checking Camera Permissions...
[ZXing.Net.Mobile] ZXingScannerFragment->OnResume exit
StartScanning
[ZXing.Net.Mobile] Checking Camera Permissions...
Getting Camera Exclusive access
Got Camera Exclusive access
[ZXing.Net.Mobile] Checking Number of cameras...
[ZXing.Net.Mobile] Found 2 cameras...
[ZXing.Net.Mobile] Found Back Camera, opening...
Releasing Exclusive access to camera

Thank you.

**Comment by jamesmontemagno** [comment]
Did you request android runtime permissions?

https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

my plugin: 
http://motzcod.es/post/133939517717/simplified-ios-android-runtime-permissions-with

**Comment by Redth** [comment]
@Toubap if you are using the Xamarin.Forms controls the permissions should be requested for you (but they have to be in the manifest).  Otherwise you need to request them yourself (if you're not using the Forms controls).

**Comment by Toubap** [comment]
Apparently not a problem with marshmallow, sorry about that
Fixed by adding Flashlight permission..

**Comment by muthuu** [comment]
@Redth I am working on xamarin android app and I used zxing library for QR scanning.This app is mainly track employees check in/out times. App is running 24 hours for testing and it always keep front camera open by waiting for a scan. It works fine, but sometimes it gives black screen when someone tries to scan. After 4 or 5 second it comes back. Most of the time this happen for the first employee who check in every morning. Can it be the reason app is running 24 hours?

Regards,
Muthu
