### ISSUE TITLE
Android should have a property to lock the orientation to what the developer wants

### ISSUE THREAD

**Issue by andersonjacobd** [Redth/ZXing.Net.Mobile#229]
Currently, the only real control we have over orientation is the bool Auto-Rotate. Setting it to false sets the ScreenOrientation to NoSensor. However this just makes it so that the screen doesn't move when the user rotates their phone.

Right now, ZXing's orientation is determined by what the user has set on their device. Aka if they're in landscape with Auto-Rotate off in the OS Zxing will start in Landscape. Which means if my entire app is supposed to be in Portrait mode, Zxing won't honor this if the user has set their device to landscape.

An additional property for Orientation that the Zxing FragmentActivity can then use for RequestedOrientation would be super helpful and fix this issue.

More than a handful of people have already asked how to lock the scanning orientation, the orientation they want not the orientation the user wants, on StackOverflow and similar sites and with the current code it isn't possible.

**Comment by Redth** [comment]
Not going to do something platform specific here.
