### ISSUE TITLE
How to pause Scanning in continious mode ?

### ISSUE THREAD

**Issue by brucemcmillan** [Redth/ZXing.Net.Mobile#231]
Hello,

I'm working with the 1.5.4 version as per the xamarin component store and the question i have is related to the issue here

https://github.com/Redth/ZXing.Net.Mobile/issues/225

The scenario I am trying to resolve is for the user to be able to scan a barcode and the once the scan has occured ask the user for input in regards to a qty. The use case being that the user wishes to scan 25 or so identical items all have the same barcode, but instead of doing 25 scans, do one scan and enter the qty 25 into some form of input panel.

I have implemented a custom overlay whereby i have a number pad for the user to enter a qty. This should be acivated when the scan has fired.

In the issue logged above, the behaviour whereby the scanner stopped or paused after scanning seems to be what I want as the current behaviour is to exit scanning mode completely in the single scan mode or to continue scanning in the continuous mode.

I would like to be able to pause scanning, ask for qty, ( deal with it in code ) then restart scanning.

The only option scan.cancel does not seem to to this

Is this available in any format ( e.g 2)

also will the latest build implement seamlessly over the top of 1.5.4 ??

All the best

Bruce

**Comment by lxshertz** [comment]
I'm not sure if pause scanning is available, you could implement it in your project though.

**Comment by TNPBruceMcMillan** [comment]
Oh If only I was that clever !!

:-)

**Comment by lxshertz** [comment]
Are you trying to display the inout panel on the camera view or close the camera view when single item is scanned, then open the input panel, and re-open the panel when user is done entering the the quantity..

**Comment by brucemcmillan** [comment]
Hello.

The requirement is /was for after every scan the user should be able to enter the scanned qty or accept the default of 1.

My first attempt was to use a custom overlay to which I had added a jumped made up of buttons and a label to display the qty.

I was hoping to use continuous scanning mode as that would avoid the scan function from being topped when a barcode  was read. The idea was to use a the delegate to ask the user from th qty and the to confirm it with an ok or cancel button.

I wanted to pause the scanning in case the scanner updated the scanned Resilt be reading a new barcode when the user was entering the data. A pause function seemed to be a good idea.

In the end however I resorted to putting the Numpad into a separate view and using a alert dialog in modal form which I presented when a normal scan was selected.

**Comment by Redth** [comment]
So if you were to use the individual `ZXingScannerView` classes directly they already had a concept of `PauseAnalysis` and `ResumeAnalysis` which when you pause analysis, it means the camera feed keeps running however the code won't try and find a barcode in the feed while paused.

I've just added this concept to `MobileBarcodeScanner` as well.

**Comment by brucemcmillan** [comment]
Great news.

Having the option on the scanner is what was needed..

B...


On 13 Jan 2016, at 17:26, Jonathan Dick <notifications@github.com> wrote:

So if you were to use the individual ZXingScannerView classes directly they already had a concept of PauseAnalysis and ResumeAnalysis which when you pause analysis, it means the camera feed keeps running however the code won't try and find a barcode in the feed while paused.

I've just added this concept to MobileBarcodeScanner as well.
