### ISSUE TITLE
Unable to stop Continous scanning

### ISSUE THREAD

**Issue by TNPBruceMcMillan** [Redth/ZXing.Net.Mobile#232]
Using 1.5.4
Possibly related to 
https://github.com/Redth/ZXing.Net.Mobile/issues/231

I have modified the sample to have a second copy of the HandleResult Method, called HandleResultCont I use this as the handler for the continous scanning operation

in testing the sample app I have the std app ( android version ) I have the result handler using handle result and the continous scanning function call the new one above/

Running the app with the debugger I notice the following behaviour.

If I run the sample app and choose the single scan ( std scan ) option the camera scans and then calls the cancel function internally as expected.

If I run the continuous scanning option it works as expected and pressing cancel on the screen exits scanning ( or so it would appear)

However I then run the std single scan function again, the camera / scanner screen appears, scans a barcode then calls the CONTINUOUS handler followed by the std Handler method.

It would appear that the cancel function does not stop or clear the continous scanning setups so calls them both.

Thoughts ?

Do i need to create new activiries ( and xib files for ios ) so that each page / form has it's own MobileScanner variable assigned which would hopefully go out of scope as the page exited ?

**Comment by TNPBruceMcMillan** [comment]
update: 9th Jan 2016
Have tested the above with the latest nuget package  and same behaviour

Once scan continuously has been called it seems impossible to stop.

**Comment by Redth** [comment]
I think this is due to how i'm wiring up events and re-using the same MobileBarcodeScanner instance.

Digging into this... For now you could probably just create a new MobileBarcodeScanner instance always and the problem should go away, but I'm looking into fixing it properly.
