### ISSUE TITLE
Image not updating on XAML databinding BarcodeValue property changed

### ISSUE THREAD

**Issue by chaitanyakale** [Redth/ZXing.Net.Mobile#233]
zxing:ZXingBarcodeImageView 
HorizontalOptions="FillAndExpand" 
VerticalOptions="FillAndExpand" 
BarcodeOptions="{Binding BarcodeOptions}" 
BarcodeFormat="{Binding BarcodeFormat}" 
BarcodeValue="{Binding BarcodeValue}"
/zxing:ZXingBarcodeImageView

First time binding works, but no updates.

**Comment by jessejiang0214** [comment]
I meet the same problem. I'm not sure if it is caused by not in UI thread. I just fix this by manually settings in BindingContext property changed.

**Comment by chaitanyakale** [comment]
This issue has been fixed on Android, UWP not working though perhaps as 599fcb5 updates only for Android.

**Comment by jessejiang0214** [comment]
I found out the iOS renderer still have the binding issues

**Comment by chrismcb** [comment]
I'm seeing the problem. Works on Android but doesn't update on iOS. Can we get this issue reopened?

**Comment by ravindersaini17** [comment]
In my case the same code works for Android but in iOS no image is displayed. I can not see any exception etc, below is the code:

var codeGenerator = new ZXingBarcodeImageView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
            };
            codeGenerator.BarcodeFormat = ZXing.BarcodeFormat.QR_CODE;
            codeGenerator.BarcodeOptions.Width = 50;
            codeGenerator.BarcodeOptions.Height = 50;
            codeGenerator.BarcodeOptions.Margin = 0;
            codeGenerator.BarcodeValue = QRDealCode;
            codeGenerator.SetBinding(ZXingBarcodeImageView.BarcodeValueProperty, QRDealCode);
            stkParent.Children.Add(codeGenerator);
