### ISSUE TITLE
black screen in debug mode

### ISSUE THREAD

**Issue by grisha-v** [Redth/ZXing.Net.Mobile#236]
Hello,
while using Zxing.Net.Mobile in my Xamarin.Forms application on Android,
after calling 
```
scanner.Scan()
```
I see black screen with a red line across it.
The issue occurs only when I run the application in Debug configuration. Release mode works OK.
Thanks in advance.

**Comment by Redth** [comment]
This may be related to #227 

Can you add some more information? Perhaps try the latest code from master...

**Comment by grisha-v** [comment]
Hello Jonathan,

I’m using Zxing.Net.Mobile nuget on Xamarin.Android. Can I add the latest code from master to Xamarin? I just don’t know how…

As you can see from the comments to your video presentation (https://www.youtube.com/watch?v=Oa6y_IAuq2Q)

There are at least two other people experiencing the same issue…

Which kind of additional information can I provide?

I’d also want to emphasize that the problem does not exist when running the application in Release configuration.

 

Best Regards,

Grisha Vinevich

CTO

NegevSoft

 

 <mailto:grisha@negevsoft.com> grisha@negevsoft.com

+972-54-4414518

**Comment by jeremiehelme** [comment]
Hi,
I've ran into the same black screen problem. It was occuring on every second scan (i.e scan / close camera / scan again), even in debug mode.

The problem was that the Navigation.PushAsync wasn't made on the main thread.

`Device.BeginInvokeOnMainThread (() => {
					 App.Navigation.PushAsync (new AddVisitorPage (visitor));
				});`

Maybe it helps...
