### ISSUE TITLE
The type 'Task<>' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by retv12** [Redth/ZXing.Net.Mobile#237]
Hi

update the android SDK, and update version library 2.0.3.0, and after that I generated this error.

any idea that I needed to update

Severity	Code	Description	Project	File	Line	Source
Error	CS0012	The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.0.0, Culture=neutral,

**Comment by Redth** [comment]
Sounds like some of your project references are not quite correct.  Going to need some more info, maybe post a reproducible sample with the error.

**Comment by retv12** [comment]
Hey there
adds reference to the project in VS 2015

" the System.Threading.Tasks.dll explicitly from C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETCore\v4.5.

and compiles and not generates errors

when testing the phone I commented

thanks
