### ISSUE TITLE
ZXing iOS Problems

### ISSUE THREAD

**Issue by samichamoun** [Redth/ZXing.Net.Mobile#238]
I'm hoping this is a really simple misunderstanding, but I cannot for the life of me get this running properly on iOS.

To give you a bit of a background, I have a tab bar controller and one of the nav controllers which comes off of it points to my "Scan" view.

All of the examples I see show the scanner being run inside ViewDidLoad(). This doesn't make much sense to me (I have tried it), because it will only run the first time someone clicks my scan 'button' (or more accurately the tab). It works ok but only will load once for the duration of the app lifecycle.

So I tried putting this into ViewWillAppear(). Causing me all sorts of grief doing this though.

Here's some sample code:

	partial class Scan : ViewControllerBase
	{
		private readonly string logTag = "!!!!!!!! Scan ";
		public Scan(IntPtr handle)
			: base(handle)
		{
		}

		//public override void ViewDidLoad()
		//{
		//  base.ViewDidLoad();

		//  System.Console.WriteLine(logTag + "ViewDidLoad() -> loaded");

		//}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			System.Console.WriteLine(logTag + "ViewWillAppear() -> loaded");

			try
			{
				ScanBarcode();
			}
			catch (Exception e)
			{
				throw new Exception(logTag + " ViewWillAppear() -> An error occurred when trying to scan the barcode", e);
			}
		}

	}

	public class ViewControllerBase : UIViewController
	{
		private readonly string logTag = "!!!!!! ViewControllerBase ";

		//scanner object.
		public static MobileBarcodeScanner scanner;

		public ViewControllerBase(IntPtr handle)
			: base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			scanner = new MobileBarcodeScanner(this);
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);
		}

		public override void ViewWillDisappear(bool animated)
		{
			base.ViewWillDisappear(animated);
		}

		public override void ViewDidDisappear(bool animated)
		{
			base.ViewDidDisappear(animated);
		}

		public async void ScanBarcode()
		{
			try
			{

				//Tell scanner to use the default overlay
				scanner.UseCustomOverlay = false;

				//We can customize the top and bottom text of the default overlay
				scanner.TopText = "Please scan product barcode to order";

				//Start scanning
				try
				{
					ZXing.Result result = await scanner.Scan();

					try
					{
						HandleScanResult(result);
					}
					catch (Exception e)
					{
						throw new Exception("An error occurred when attempting to handle the scan result.", e);
					}
				}
				catch (Exception e)
				{
					throw new Exception("An error occurred when running scanner.", e);
				}

			}
			catch (Exception e)
			{
				throw new Exception(logTag + "ScanBarcode() -> An error has occurred", e);
			}
		}

		// Common function used by scanner to retrieve product code.
		public void HandleScanResult(ZXing.Result result)
		//private void HandleScanResult()
		{
			try
			{
				System.Console.WriteLine("HandleScanResult() -> Now running");

				string productBarcode = "";

				try
				{
					productBarcode = result.Text;
				}
				catch (Exception e)
				{
					throw new Exception("Error occurred when retrieving the result text", e);
				}

				//Do work with product here... I'm running this.NavigationController.PushViewController(product, true); where product is my following view.

			}
			catch (Exception e)
			{
				throw new Exception(logTag + "HandleScanResult() -> An error has occurred", e);
			}
		}
	}

Now this is what happens when I attempt to use this:

1. Scanner loads;
2. I scan a barcode;
3. Control appears to go back to the Scan view;
4. Scanner automatically reloads itself;
5. Scan a second barcode;
6. Product screen loads (first barcode);
7. A couple seconds later, the Product screen reloads (with the second barcode);

So it's like something has gone wrong with the stack - I just have no idea what the issue here is.

I've also been toying around with the below code...

I first tried this in the ViewDidLoad(), but again, only loads once. Inside the ViewWillAppear() it tries to rerun itself twice again also.

        scanner = new MobileBarcodeScanner(this.NavigationController);

        scanner.Scan().ContinueWith((t) =>
        {
            //Our scanning finished callback
            if (t.Status == System.Threading.Tasks.TaskStatus.RanToCompletion)
            {
                string msg = "";
                ZXing.Result result = t.Result;

                if (result != null && !string.IsNullOrEmpty(result.Text))
                {
                    scanner.Cancel();

                    this.InvokeOnMainThread(() =>
                    {
                        System.Console.WriteLine("Lets load the shopping cart!");
                        LoadShoppingCart();
                        // if(this.ticketScreen == null) {
                        //       this.ticketScreen = new TicketScreen();
                        //   } 

                        //    this.ticketScreen.ticketUrl = result.Text;
                        //    this.NavigationController.PushViewController(this.ticketScreen, true);
                    });
                }
                else
                {
                    msg = "Code nicht erkannt!";
                    this.InvokeOnMainThread(() =>
                    {
                        System.Console.WriteLine("We cant load teh shopping cart!");
                    });
                }

                //runScanner();

                System.Console.WriteLine("Thread finished");

                //runScanner();
                //var result = await scanner.Scan();

                //if (result != null)
                //  Console.WriteLine("Scanned Barcode: " + result.Text);

                //System.Console.WriteLine(logTag + "Scan complete");

                //LoadShoppingCart();

                //this.NavigationController.PopToRootViewController(true);
            }
        });

If anyone has some pointers I would be eternally grateful.

**Comment by Redth** [comment]
This sounds to me like you really want to use `ZXingScannerView` directly, inside your own view controller, in your tab controller.  The `MobileBarcodeScanner` class is really meant to be an easy way to launch a modal scanning view controller.

Look at how I implement the scanner view inside `ZXingScannerViewController`, you might want to take a similar approach.

Does that make sense?

**Comment by samichamoun** [comment]
Great I'll have a play with this.

Getting an error from this in your source:



			Task.Factory.StartNew (() =>
			{
				BeginInvokeOnMainThread(() => scannerView.StartScanning (result => {

Cannot convert lambda expression to type 'ZXing.Mobile.MobileBarcodeScanningOptions' because it is not a delegate type

What am I doing wrong mate?

**Comment by Redth** [comment]
First of all make sure your `ZXing.Result result` is not null.  I believe it's possible for you to receive a null result, and it may be failing when you access `result.Text` when result is null.

As for your UI Thread error, I think you need to instantiate the storyboard in an `InvokeOnMainThread` call (since it won't be on the main thread in the event callback.
