### ISSUE TITLE
Windows Universal: Fix preview buffer rotation

### ISSUE THREAD

**Issue by Redth** [Redth/ZXing.Net.Mobile#241]
Currently it seems that sometimes the preview buffer image data is rotated.  This can cause barcodes not to scan unless the TryHarder option is used.  

The code should really figure out what orientation the preview buffer is in, and rotate it properly.

Splitting this off from #223

**Comment by danardelean** [comment]
The solution is also rotate the video stream. Here is ta version that works without TryHarder:

  private async Task SetPreviewRotationAsync()
        {
            // Only need to update the orientation if the camera is mounted on the device
            //if (_externalCamera) return;

            // Calculate which way and how far to rotate the preview
            //int rotationDegrees = ConvertDisplayOrientationToDegrees(displayOrientation);

            // The rotation direction needs to be inverted if the preview is being mirrored
            //if (_mirroringPreview)
            //{
            //    rotationDegrees = (360 - rotationDegrees) % 360;
            //}

            // Add rotation metadata to the preview stream to make sure the aspect ratio / dimensions match when rendering and getting preview frames
            //var props = mediaCapture.VideoDeviceController.GetMediaStreamProperties(MediaStreamType.VideoPreview);
            //props.Properties.Add(RotationKey, rotationDegrees);
            //await mediaCapture.SetEncodingPropertiesAsync(MediaStreamType.VideoPreview, props, null);

            switch(displayOrientation)
            {
                case DisplayOrientations.Portrait:
                    mediaCapture.SetPreviewRotation(VideoRotation.Clockwise90Degrees);
                    mediaCapture.SetRecordRotation(VideoRotation.Clockwise90Degrees);
                    break;
                case DisplayOrientations.LandscapeFlipped:
                    mediaCapture.SetPreviewRotation(VideoRotation.Clockwise180Degrees);
                    mediaCapture.SetRecordRotation(VideoRotation.Clockwise180Degrees);
                    break;
                case DisplayOrientations.PortraitFlipped:
                    mediaCapture.SetPreviewRotation(VideoRotation.Clockwise270Degrees);
                    mediaCapture.SetRecordRotation(VideoRotation.Clockwise270Degrees);
                    break;
                case DisplayOrientations.Landscape:
                default:
                    mediaCapture.SetPreviewRotation(VideoRotation.None);
                    mediaCapture.SetRecordRotation(VideoRotation.None);
                    break;
            }

          
        }
