### ISSUE TITLE
UWP: Exception during AutoFocus in sample app

### ISSUE THREAD

**Issue by tmm360** [Redth/ZXing.Net.Mobile#242]
I'm trying the UWP sample app on a Win10 Mobile device, and if I tap on screen during "Scan with default View" I get an exception with message:
`Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))`

The stack trace is:
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at ZXing.Mobile.ZXingScannerControl.&lt;AutoFocusAsync&gt;d__65.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at ZXing.Mobile.ZXingScannerControl.&lt;OnPointerPressed&gt;d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;&gt;c.&lt;ThrowAsync&gt;b__6_0(Object state)
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by Redth** [comment]
it seems like somehow autofocus must not be supported on your device... I've added a try/catch block to make sure it's at least not going to crash the app.

Please reopen if you have more info or the fix is still not working.

**Comment by AlfaSierra92** [comment]
There is a way to see if the autofocus is enabled?

**Comment by Hashemalrifai** [comment]
Hello and thanks for your hard work:
I get this exception when running the Windows Universal sample app on my Lumia 920 Win10:
```

AutoFocusAsync Error: System.Exception: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ZXing.Mobile.ZXingScannerControl.<AutoFocusAsync>d__65.MoveNext()
```

Debugging the core code, the FocusControl.Supported is true. Is there a way to have a fix, I'm trying to scan a small QR Code with no success. 

![del](https://cloud.githubusercontent.com/assets/3750953/13522260/c4fa6a8c-e1ee-11e5-8189-1af3efdedb45.PNG)
