### ISSUE TITLE
iOS: method "MobileBarcodeScanner.Scan" does not return

### ISSUE THREAD

**Issue by mariorasch** [Redth/ZXing.Net.Mobile#244]
Hi,

if have a Xamarin.Forms (2.0.0.6490) app that uses ZXing 2.0.4.19.

On iOS 9.2 when deleting the app, then reinstalling & launching it and trying to scan a QR code for the first time the method "MobileBarcodeScanner.Scan" does not return. I am using the default scanning view. The second try of scanning a QR code works.

Do you have an idea what could go wrong or do you need any additional info?

Best regards!
Mario.

**Comment by Redth** [comment]
I'd suggest trying the [ZXing.Net.Mobile for Forms](https://components.xamarin.com/view/zxing.net.mobile.forms) component in a Forms specific app.  There are some weird issues that can occur due to the page/view controller navigation manager in forms when trying to use the `MobileBarcodeScanner` class.  In the component now meant for Forms, there's a `ZXingScannerPage` and `ZXingScannerView` you can use :)

**Comment by mariorasch** [comment]
Hi Jonathan,

thanks for telling me about the Forms specific version - I didn't know it exists. :-)

I just ported my Xamarin.Forms project to use that version but alas I ran into some trouble:

1. On iOS neither the ZXingScannerPage nor a custom page using a ZXingScannerView displays a camera picture whereas both the ZXingScannerPage and the custom page are displaying correctly in an Android emulator (I did not test Windows Phone so far). On iOS camera access for my app is allowed in the Settings app.

2. ZXingScannerView.HasTorch delivers false on a real iOS device (iPhone 6s Plus with iOS 9.2).

3. ZXingScannerView.IsTorchOn delivers false on the same iOS device even when the LED is switched on using Control Center.

And a question: is there any property aleady that I could use to query whether camera access is enabled on iOS?

Best regards!
Mario.


Am 18. Januar 2016 um 15:06 schrieb Jonathan Dick <notifications@github.com>:

I'd suggest trying the ZXing.Net.Mobile for Forms component in a Forms specific app. There are some weird issues that can occur due to the page/view controller navigation manager in forms when trying to use the MobileBarcodeScanner class. In the component now meant for Forms, there's a ZXingScannerPage and ZXingScannerView you can use :)
