### ISSUE TITLE
Question: Windows 8.1 RT Support

### ISSUE THREAD

**Issue by TNPBruceMcMillan** [Redth/ZXing.Net.Mobile#246]
Hi,

Currently the package supports windows phone 8 / 8.1 ( silverlight ) and universal.

Any reason why it does not support windows phone RT ( which seems to be the same as the universal app ) ??

Thanks

B.....

**Comment by Redth** [comment]
Yes, Windows Phone RT has no managed way to get camera preview frame buffers.  You basically have to write some unmanaged filter code - something I'm not keen on doing, especially considering Windows Phone RT has a pretty finite future.  Sorry!

**Comment by TNPBruceMcMillan** [comment]
Thanks for the quick reply... It'll be interesting to see what happens when I run a universal app on the phone ! :-)

B....

**Comment by Redth** [comment]
The universal support is for Windows 10 UWP, which afaik won't run on windows phone 8.x devices...

**Comment by TNPBruceMcMillan** [comment]
Ah OK..

To be honest I'm heading off down a track here... I started this possible upgrade based on looking at modal input in silverlight version and then found lots of options in 8.1 ( RT) so thought I'd have a test conversion and see what happened.

Also quick other question I notice that the latest version dropped the previous IOS-Classic project. Was this just rationalisation as I notice that when i applied the new nuget package to it some things in that project stopped working altogether ( custom overlay no longer was an option for example)

Not that it was a problem I just dropped the classic project going forward.

Regards.

**Comment by Redth** [comment]
This may be better to discuss in https://gitter.im/Redth/ZXing.Net.Mobile 

For iOS Classic, it really has been deprecated for a long time now and I decided it was time for me to stop spending effort on it.  People should be all migrated to Unified by now, if not, well you better get to it :)
