### ISSUE TITLE
Android: Crashes when trying to Open ZXingScannerPage

### ISSUE THREAD

**Issue by chrismcb** [Redth/ZXing.Net.Mobile#248]
Android throws an Object reference not set to an instance of an object error when you try to open ZXingScannerPage.

I verified this with the sample using Nuget packages. It works with 2.0.3.1 but crashes with 2.0.4.17+
I was unable to get the sources to build properly to track it down any further

**Comment by Redth** [comment]
Going to need a lot more info here....

**Comment by alexsandro-xpt** [comment]
async void CallScanner(object sender, EventArgs e)
        {
            var scanPage = new ZXingScannerPage();


`Unhandled Exception:`
`System.MissingMethodException: Method 'Element.set_AutomationId' not found.`

**Comment by teerasej** [comment]
I found same problem with @alexsandro-xpt. 

The exception raised after this statement: 
`await Navigation.PushAsync (scanPage);`

Tested on this device:
- LG Nexus 5
- Android 6.0.1
- Xamarin.Forms 2.0.1.6495

**Comment by srsivaprasad** [comment]
same issue for me also.

**Comment by alexsandro-xpt** [comment]
I forget the XF implementantion and call the native UI and Scanner Engine, it's mutch more responsive.

**Comment by almirvuk** [comment]
Same here, any info about this issue?

**Comment by mishanatsvlishvili** [comment]
have the same problem, any news?

**Comment by timothyparez** [comment]
Same issue here

**Comment by EmreErinc** [comment]
2 months ago there is no issue on my app but now i am getting that issue.
