### ISSUE TITLE
 scan only horizontal

### ISSUE THREAD

**Issue by yiji** [Redth/ZXing.Net.Mobile#253]
test with nokia 920 and tablet dell venue pro 11

**Comment by netonian** [comment]
Scanning PDF417 barcodes on Samsung Note 3 (Android-  5.0) 
Works if phone is horizontal and PDF417 barcode is horizontal - but doesn't decode barcode if phone is Vertical and barcode is held vertically.  By Vertical, I mean both the phone and the barcode are rotated 90 degrees from Horizontal.

However, the ZXING Android app on Google App store works in both orientations.

**Comment by himion0** [comment]
I'm having the same problem. I've tested it on Windows 10 mobile UWP Lumia 640. Galaxy s6

**Comment by Redth** [comment]
As an easy work around you can set the MobileBarcodScanningOptions instance's AutoRotate property to true

**Comment by Redth** [comment]
Also, if you're talking Xamarin.Forms, you'll have to do a bit more leg work but you can lock screen orientation: http://www.wintellect.com/devcenter/jprosise/responding-to-orientation-changes-in-xamarin-forms

Of course if you're working right on the native platforms, they each have a way of locking orientation as well.  This is something you need to handle in your code and not something this library is going to do for you.

**Comment by yiji** [comment]
it's work, thank you
