### ISSUE TITLE
Android scanner lost autofocus ability after page switch

### ISSUE THREAD

**Issue by abaddon201** [Redth/ZXing.Net.Mobile#260]
Got Page that contains ZXingScannerView, on that page have also a button to navigate to the other page. After return from other page, everything is working except Autofocus. Found that on restoring scanner status with reenabling IsScanning scanner don't pass check for if (!tokenSource.IsCancellationRequested)... bla-bla-bla, enable autofocus.
Solved that with this code added on start of StartScanningAsync method:

            if (tokenSource.IsCancellationRequested)
            {
                tokenSource.Dispose();
                tokenSource = new CancellationTokenSource();
            }

Not sure that this snipped is correct, so please check and fix it:)

**Comment by mav2307** [comment]
I have a similar problem. Using the Forms Version for my Scanner View.
I'm inheritance my Page from ZXingScannerPage. This is all working. But when I got a result and want to scan again after this result there is no autofocus with Android.

This is my code to reactivate the scanning. Maybe I did this wrong. Maybe this is a bug. Don't know.

```
this.IsScanning = true;
                    
this.IsAnalyzing = true;
                   
 this.AutoFocus();
```

**Comment by Redth** [comment]
Thanks!
