### ISSUE TITLE
15 frames per second?

### ISSUE THREAD

**Issue by PelleRavn** [Redth/ZXing.Net.Mobile#261]
Hi

I wonder why the library limit the frame rate for iOS to 15 fps? The performance is widely available for 30 fps, and is the default for Android. I can't seem to find a scenario where 15 fps is preferable, and will just give a bad experience for the users.
Should this be 30 fps, and then a ScanningOption to limit it, if you want to? (Or maybe a ScanningOption to put it back to 30 fps?)

Code is found here:
https://github.com/Redth/ZXing.Net.Mobile/blob/27b71560ed7854754f2563304ec8ad239d115dcf/Source/ZXing.Net.Mobile.iOS/AVCaptureScannerView.cs#L285

Thanks
Pelle Ravn

**Comment by mariorasch** [comment]
If possible to remove this limitation I'd appreciate to do so as the low framerate looks somehow erroneous on iOS - especially on new devices.

**Comment by PelleRavn** [comment]
As I see it, it's a intensional limitation. In my eyes, it looks like you could remove the following lines (in the link), and it would make use of the default settings in iOS (30 fps, or lower on older devices) - And not the 15 (or 10, as I see the code) fps that the code dictates.
We've successfully made it run on 30 fps earlier, by compiling to our own DLLs and use them instead, so it is possible.

https://github.com/Redth/ZXing.Net.Mobile/blob/27b71560ed7854754f2563304ec8ad239d115dcf/Source/ZXing.Net.Mobile.iOS/AVCaptureScannerView.cs#L285-L305

**Comment by Redth** [comment]
Thanks folks, as explained in the commit, this is really just an artifact of the original code that inspired this library... There's really no good reason for it anymore, so thanks to bringing it to my attention!

**Comment by mariorasch** [comment]
Thanks Redth! Could you please update the NuGet packages?
