### ISSUE TITLE
MobileBarcodeScanner.Initialize?

### ISSUE THREAD

**Issue by moflaherty** [Redth/ZXing.Net.Mobile#264]
Can someone explain what this call does? I looked online and didn't find anything useful. Everything works without it, but I saw it in a sample and would like to understand it better.
![capture](https://cloud.githubusercontent.com/assets/7761823/13179936/6a59d1da-d6f4-11e5-8b88-8a5b571f185c.PNG)

**Comment by tbalcom** [comment]
It's for tracking the current context according to the readme.md file:

```
#if __ANDROID__
    // Initialize the scanner first so it can track the current context
    MobileBarcodeScanner.Initialize (Application);
#endif
```

**Comment by Redth** [comment]
@tbalcom  :+1:

That is correct, it tracks the current context.  If it can't find this, it will try and use the Application Context however this can cause issues.  Best to call Initialize.

**Comment by moflaherty** [comment]
Thanks! I will leave it in. Now if you could fix https://github.com/Redth/ZXing.Net.Mobile/issues/189, I would be very happy! :)

**Comment by Redth** [comment]
It's definitely on my radar :)

**Comment by donkanmcleod** [comment]
I tried to follow instructions but there is no point on wasting more time trying to get it work. This library is too unstable to be used. Maybe within next years it will be useful.

**Comment by FatihSonmez2005** [comment]
Now, VS2019 is giving a warning 
CS0618	'MobileBarcodeScanner.Initialize(Application)' is obsolete: 'Use Xamarin.Essentials.Platform.Init instead' 
Should i keep it or can i use Essentials initialization?
