### ISSUE TITLE
Scanner Overlay Size

### ISSUE THREAD

**Issue by jaydenis** [Redth/ZXing.Net.Mobile#266]
Is there an easy way to reduce the size of the scanner screen? Would it be possible to display the scanner as a small window within an existing app screen?

**Comment by rizzman** [comment]
Foremost, my apologies for any noob questions or description. I am very new to programming.

 I am having the same issue with this. I have an application running various tasks, and am attempting to place the scanner inside of a PivotItem and call the scanner via a button. I noticed that when I activate the scanner, it seems to wipe out / take over my UI while running, then attempts to re-initialize the MainPage() method when the scanner.Cancel() is called and causes my program to crash and Gui to no longer be responsive. 

I suspect that it has something to do with the dispatcher / threading but do now know how to kick off the scanner in its own thread. The sample you have provided is great for basic functionality as a standalone App, however it definitely would be useful to see an example running within a Grid Cell if possible.

Any advice would be greatly appreciated.

Best,
David

**Comment by Redth** [comment]
So, if you are using the Xamarin.Forms add-on for ZXing.Net.Mobile you can just choose to not use the `ZXingScannerPage` and instead use the `ZXingScannerView` class itself on your own page and you can make that view whatever size you like.  You can look at the source of the CustomScanPage in the Forms sample to see how to use the view directly: https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Forms/Core/CustomScanPage.cs

**Comment by Redth** [comment]
I should add, if you're not using the forms add-on library, you can use each platform's individual scanner view to the same effect.

**Comment by zipgenius** [comment]
I'm sorry for commenting this closed issue but I don't want to open a duplicate request.
What about in UWP apps? How to make a custom sized overlay for scanner?

**Comment by rizzman** [comment]
Thanks for getting back, particularly, we are trying to use the library to
display the  scan video feed inside of a grid box, but the example you have
takes over the whole screen which also, attempts to re-run the main method
upon exiting the scanner. Which is crashing our program. Could you please
provide an example of the program running inside of a grid row/colum?

Thanks again for getting back with me.

Best,
David
