### ISSUE TITLE
Can't read 44-digit barcode

### ISSUE THREAD

**Issue by ataquino** [Redth/ZXing.Net.Mobile#271]
Hi. First of all, thanks for the effort you put into this library.

I'm trying to scan an Interleaved 2 of 5 barcode with 44 digits, but I only get around 8 or 9 digits every time. Maybe there's something I'm missing, could you help me out? I've tried specifying TryHarder, and setting ITF as PossibleFormat. Maybe its a focusing issue?

![ar9sea8gfy3kdhzupvft7fd0zawdtfypoeuxvet5gny1 1](https://cloud.githubusercontent.com/assets/3901785/13506550/69e0f882-e15d-11e5-81bb-1f46f65e9331.jpg)

**Comment by Redth** [comment]
Thanks for the answer to that @redwolf2  :)

Just looking at that image i would agree, it's going to be tough to get working well.  I would also suggest playing with the resolution selection used for the image that gets decoded.  You can set the `CameraResolutionSelector` delegate of your `MobileBarcodeScanningOptions` class to get a list of and return the desired resolution for scanning.
