### ISSUE TITLE
Android: Preview is black after app resumes from background

### ISSUE THREAD

**Issue by rmdaustin** [Redth/ZXing.Net.Mobile#277]
Steps to reproduce:

1. Build Sample.Android from current master.
2. Run app and choose any scan mode.
3. With Preview showing, press device home button.
4. Return to app either from running apps list or launch from app icon.

Result:
Overlay will be visible, but camera preview area will be black.

While preview is black, if device is rotated, preview appears.

Preview will restart successfully if return to main menu and restart scanning.  

Preview restores correctly if device is put to sleep with app in foreground.

Tried on Nexus 7 with Android 6.0.1 and Galaxy S5 with Android 5.0

**Comment by Redth** [comment]
I believe PR #302 should fix this
