### ISSUE TITLE
QR code scan crashes on Samsung Galaxy S7

### ISSUE THREAD

**Issue by firepol** [Redth/ZXing.Net.Mobile#278]
Hi there,

I'm using ZXing.Net.Mobile 2.0.4.46 in a Xamarin Forms project and during/after scanning a QR ccode the app is crashing on a Samsung Galaxy S7 (sm-g935f) device, with Android M.

With other devices we don't have this problem so it may be already interesting if you test it on a S7 device and see if you can reproduce the problem as well.

In Xamarin Insights I get such a stack trace:

> ZXing.Mobile.ZXingSurfaceView.AutoFocus()
> ZXing.Mobile.ZXingSurfaceView.SurfaceChanged(ISurfaceHolder, Format, int, int)
> Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceChanged_Landroid_view_SurfaceHolder_III(intptr, intptr, intptr, int, int, int)
> at (wrapper dynamic-method) object.658aaa4c-693f-456a-b27d-7a0ccf491e31 (intptr,intptr,intptr,int,int,int) <0x0003f>

Maybe this is related (also the official camera app has problems because of the auto-focus): http://www.trustedreviews.com/opinions/samsung-galaxy-s7-problems

Best regards, Paolo

**Comment by Redth** [comment]
Sorry, I do not have access to an S7 for testing.  A full stack trace would be helpful, but it does sound like what you mentioned is possibly related...

**Comment by firepol** [comment]
A tester could reproduce the bug where she works. I asked her to test the camera as well, but the camera works just fine. Unluckily she'll come in the office only on Thursday, then I'll be able to debug the app on the device and I'll share the full stack.

For now I call the scanner in an async methos, like this:

```
    public async Task<string> Scan()
    {
      var result = string.Empty;

      var scanner = new MobileBarcodeScanner
      {
        TopText = Resources.QrResources.ScannerTopText
      };

      var options = new MobileBarcodeScanningOptions
      {
        PossibleFormats = new List<BarcodeFormat>
        {
          BarcodeFormat.QR_CODE
        }
      };

      var scanResult = await scanner.Scan(options);

      if (scanResult != null)
      {
        result = scanResult.Text;
      }

      return result;
    }
```

Can you suggest an option or something that potentially could help to deal with auto-focus issues? Any idea/suggestion is welcome, I'll try it asap I get the device ;) thx again and cheers

**Comment by Redth** [comment]
Hard to say without actually seeing the full stack trace, but the autofocus call is executed here: https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Android/ZXingSurfaceView.cs#L225

Which is already wrapped in a try/catch.

**Comment by firepol** [comment]
Check what solved the issue in my case: http://forums.xamarin.com/discussion/62635/samsung-galaxy-s7-sm-g935f-crashes

I think that somewhere in the zxing codebase there is a feature not fully supporting arm64-v8a. In fact, building the app without arm64-v8a solved the issue.

**Comment by Redth** [comment]
Thanks, this does not appear to be an issue with ZXing.Net.Mobile, but rather Xamarin itself.

**Comment by junaidjavaid971** [comment]
I'm facing this issue in Android. Zxing is crashing in Samsung galaxy S7 and running perfectly fine in all other devices. I think it's related to hardware of the phone.
