### ISSUE TITLE
Windows Universal Samples crashes/unhandled exception

### ISSUE THREAD

**Issue by MrGManish** [Redth/ZXing.Net.Mobile#279]
Hi,

the sample solution for universal windows crashes with an unhandled exception. I get some nullpointers, but i dont know what to do with that.

![error](https://cloud.githubusercontent.com/assets/17853577/13783398/33e5a8b2-eac3-11e5-8f35-20d6d523c635.png)

**Comment by mersadwm** [comment]
I tried it many times and I have the same problem in UWP project , it is not working att all and I couldn't find any solution for it or any working sample for UWP

**Comment by Redth** [comment]
Closing for now, will reopen if it's still an issue after 2.1.0 is released.
