### ISSUE TITLE
Continous Scan Mode - Custom View - Recents Button Crash on Android

### ISSUE THREAD

**Issue by moflaherty** [Redth/ZXing.Net.Mobile#280]
If the user has the scan screen (camera) displayed and presses the "recents" button (square), the app minimizes fine, but when trying to restore, it crashes with a `Java.Lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup` error.

Thanks!

**Comment by Redth** [comment]
I believe PR #302 should fix this
