### ISSUE TITLE
ZXing.Net.Mobile.Forms.Android generates Resources String.Hello mapping in Designer and breaks build.

### ISSUE THREAD

**Issue by sjwaight** [Redth/ZXing.Net.Mobile#282]
I have added 2.0.4.46 (Mobile & Mobile.Forms) to an existing Xamarin project (Forms v2.1.0.6526) and started getting this in my Droid project on each clean build:

C:\XXXProject\XXXProject.Mobile\XXXProject.Mobile.Droid\Resources\Resource.Designer.cs(805,113,805,118): error CS0117: 'Resource.String' does not contain a definition for 'Hello'

global::ZXing.Net.Mobile.Forms.Android.Resource.String.Hello = global::XXXXProject.Mobile.Droid.Resource.String.Hello;

I can delete the reference and the project compiles cleanly. Have checked all Android XML files and am unable to find any reference to 'hello'.

**Comment by sjwaight** [comment]
Looks to be related to this issue on SO. Work around fixes for me, but frustrating none-the-less.

http://stackoverflow.com/questions/34042690/xamarin-forms-error-droid-resource-does-not-contain-a-definition-for-string

**Comment by Redth** [comment]
This should be fixed in 2.1.0-beta1 and higher.
