### ISSUE TITLE
Crash with onresume event if buttons pressed during scan

### ISSUE THREAD

**Issue by edynamic90** [Redth/ZXing.Net.Mobile#285]
Hello,

I developp with Xamarin (android) and when my staff has the scan screen is enabled and presses the home, back button and shutdown button, no problem with onresume vent, but when to restore, it crashes with a Java.Lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup error. I can't intercept onresume event too.

This code is the source of problem for me

View oView = LayoutInflater.FromContext (this).Inflate (Resource.Layout.ZxingOverlay, null);

I think that there is not viewgroup object as argument by default, we have must set null argument 

Do you known this issue ?

Best

**Comment by Redth** [comment]
I believe PR #302 should fix this.
