### ISSUE TITLE
Custom view and rotation

### ISSUE THREAD

**Issue by Vandersteen** [Redth/ZXing.Net.Mobile#288]
Hello,

I've run into some trouble using a custom overlay like explained [here](https://github.com/Redth/ZXing.Net.Mobile/blob/master/Component-Forms/GettingStarted.md#usage) in Xamarin.Forms

Showing the scan view initially with the overlay works great, but once you rotate the device the scanview does not rotate with the rest of the page in iOS.
In Android the image gets distorted and flipped around.

For iOS you can see the 2 screenshots:

![img_0278](https://cloud.githubusercontent.com/assets/9284334/14000381/4a02eac2-f141-11e5-8395-34d9ffff9511.PNG)

![img_0279](https://cloud.githubusercontent.com/assets/9284334/14000241/a04af696-f140-11e5-8b7e-7241cbc069e3.PNG)

Setting AutoRotate in the Options to true or false does not seem to change anything.

I've tried to 'reset' the view in 

```
protected override void OnSizeAllocated(double width, double height) ...
```

But even in there I do not seem to be able to make changes to the view. 
Any chance someone could point me out what I am missing here ? Would be greatly appreciated.

**Comment by Redth** [comment]
This was actually fixed in 2.1.12 release :)
