### ISSUE TITLE
Crash on process restart

### ISSUE THREAD

**Issue by vijayinworld** [Redth/ZXing.Net.Mobile#289]
ZxingActivity got crashed while app process getting killed. 
Follow the below steps to reproduce the crash,
1. Open scanner
2. Press home button to keep app in background
3. Do any one of the below step
 3.1. Marshmallow : settings > apps > scanner app > permission > uncheck camera. Open scanner app from task manager
 3.2 All android versions : Execute 'adb shell am kill com.altusapps.zxingnetmobile'
4. ScanningOptions (static variable) reset to null, hence null reference exception causing crash.

**Comment by tmson90** [comment]
Are you using zxingfragment for sanning? If your scanner is working and you press power button or home button and open the app again the error will be appeared. Because from ZxingFragment.cs there are some function does not check the scanner is null first and stopscanning function set scanner equal null so that is the problem. You can create your custom fragment and add some condition to prevent that. Hope that help :)

**Comment by vijayinworld** [comment]
Refer below (scanner is internally launching ZxingActivity.cs),
MobileBarcodeScanner.Initialize (Application);
var scanner = new ZXing.Mobile.MobileBarcodeScanner();
scanner.Scan();

In ZxingActivity class ScanningOptions is static variable, while restarting app process its reassigned with null.

**Comment by tmson90** [comment]
as I saw from Git that they edit the code to use the global variable option, last time they use the option from parameter so that make the error when you don't pass this variable while start scanning.

**Comment by vijayinworld** [comment]
As I seen in the history, ZxingActivity is having ScanningOptions as static variable more than an year. App process kill (can happen any time by android OS -when app in background) clears all static variables. For fixing this ScanningOptions should be passed via intent (and via onsaveintentstate app can retain). Anyhow to implement that ScanningOptions should implement Parcelable class.

**Comment by Redth** [comment]
This should be fixed in master now.

**Comment by muteddisk** [comment]
Hi,  
I just took the code and put it in vs 2017. my phone samsung s4 running 5.0.1. Sample works fine in emulator put keep crashing on my S4. any ideas?

thanks
