### ISSUE TITLE
Code 39 first character incorrect

### ISSUE THREAD

**Issue by PierreCourt** [Redth/ZXing.Net.Mobile#290]
I need to get a VIN Code (EU version). So I used the code_39 format.

I tried the sample project for Android and the ZXing.Net.Mobile for forms and both returns me **L**VWZZZ6RZFY16746201 but should return **W**VWZZZ6RZFY16746201 (The first character is incorrect). I tried with a OnePlus X and a Sony Xperia C5 Ultra. I tried with another VIN Code and I had the same false first character, with always a difference of 11 in the alphabet (L instead of W and I instead of T).

I also tried that VIN Code with an app that decoded it right, so the VIN Code is right.

Thanks for your help

![img_20160330_172923](https://cloud.githubusercontent.com/assets/18171034/14147927/c0c945b4-f69d-11e5-8758-43ae38f1c8eb.jpg)

[EDIT] Added some precisions about the first incorrect character.

**Comment by bmacadam** [comment]
The string returned from the reader is correct.  Virtually all barcodes on VIN plates are 18 characters and you simply need to strip the first character off of the string that is returned from the reader.

**Comment by PierreCourt** [comment]
The problem is not that I have too many characters, but that the first character I get is "L" instead of "W".

**Comment by PierreCourt** [comment]
I also tried on an iPhone 4S and the same bug occured.

**Comment by Redth** [comment]
This is likely an issue with ZXing.Net itself.

As a workaround an I suggest trying the AVCapture engine implementation of ZXing.Net.Mobile?

**Comment by PierreCourt** [comment]
Isn't AVCapture engine an iOS specific ? I'm using this scanner for both Android and iOS.

**Comment by Redth** [comment]
Yep, so it'll only be used on iOS of course.  There's lots of platform specific stuff in both the iOS and Android implementations even though they use the same ZXing.Net PCL to actually detect barcodes, so it's no big deal to have the iOS platform specific bits use the AVCapture based engine under the hood... this is the beauty of bait and switch :)
