### ISSUE TITLE
ZXing.Net.Mobile for Windows Phone 8.1

### ISSUE THREAD

**Issue by NilkOne** [Redth/ZXing.Net.Mobile#291]
Hello,

Is the support of WP 8.1 for ZXing.Net.Mobile planned?
(in order to use it in Xamarin.Forms PCL project)

**Comment by Redth** [comment]
Nope, not at this time.

Given that Windows 10 UWP is now coming out, it's too much effort to make Windows Phone 8.1 native work (you can't do it in managed code).
