### ISSUE TITLE
iOS 9.3 Blank/black screen

### ISSUE THREAD

**Issue by PierreCourt** [Redth/ZXing.Net.Mobile#292]
I tried to use zxing.net.mobile.forms with "var scanPage = new ZXingScannerPage(options);" on iOS 9.3 (iPhone 5s and 6s) and the camera didn't open, there was only the overlay with the text below and above the scanner.

 I also tried on a 4s with iOS 8.3 and it worked. Any idea why it didn't work ?

Thanks for your help.

**Comment by agence-glanum** [comment]
We have exactly the same problem with a custom layout.

Thanks for a quick fix.

**Comment by blackice2999** [comment]
Sounds like a duplicate from #201

**Comment by PierreCourt** [comment]
I tested it again, without changing anything (as far as I can see), and know it works. So I will now close this issue.
