### ISSUE TITLE
UWP Windows 10 App always returns to the MainPage.xaml is there a way to stay on calling page?

### ISSUE THREAD

**Issue by bleachedbug** [Redth/ZXing.Net.Mobile#293]
I have the following code on the Identify.xaml.cs page:

 private async void btnBarcodeScan_Click(object sender, RoutedEventArgs e)
        {
            var scanner = new MobileBarcodeScanner();
            var result = await scanner.Scan();

            scanner.UseCustomOverlay = false;
            scanner.TopText = "Hold camera up to barcode";
            scanner.BottomText = "Press red line to focus and scan barcode";

            var dialog = new MessageDialog("Scanned Barcode: " + result.ToString());
            await dialog.ShowAsync();
        }

Which works great, the barcode scanner appears and the MessageDialogue shows the barcode code scanned. As soon as I click 'OK' on the MessageDialogue it returns me to the MainPage.xaml. I wish to stay on the original calling page which is named Identify.xaml

Really hope you can help almost got this app over the line and the barcode scanning is the last hurdle.

Many thanks in advance,

Jose

**Comment by Hoithebest** [comment]
I am also interested in how this is possible. I think it's worth to mention that when the method that contains the scanning process (in your case btnBarcodeScan_Click), the Output window shows two lines that make it look like this redirect is not supposed to happen:
`Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll`
`WinRT information: The op is invalid.`
I hope for a fix for this!

**Comment by Redth** [comment]
You could make your own scan page by following how it's done in the source: https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.WindowsUniversal/ScanPage.xaml.cs

Just don't navigate backwards in the part where the result is handled.

Having said that, I'm going to try and dig into this a bit further and see if there's anything I can do from navigating back too far.  I suspect it has something to do with the way the `Frame` that's used to navigate to the scan page is captured....

**Comment by bleachedbug** [comment]
@Redth - Thanks so much for the reply!

So here is an update, I created the following:

IdentifyPage.xaml which opens the ScanPage.xaml (as per your advise on the link) this now opens the scanner and scans as expected, the bonus is it now returns me to IdentifyPage.xaml which is excellent. Previously I was being returned to the MainPage.xaml.

Also if I navigate to my ContactUsPage.xaml and use the camera it works and is not returning a black screen. SO this seemed to be job done until I noticed this oddity. 

Scenario is as follows:

Go to IdentifyPage.xaml and click link to scanPage.xaml and scan as expected; result is nicely returned to the IdentifyPage.xaml (so far so good). Then if I click the ScanPage.xaml link again from the IdentifyPage.xaml the scanpage returns the folloing stack trace expception:

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ZXing.Mobile.ZXingScannerControl.<StartScanningAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ZXing.Mobile.ZXingScannerControl.<StartScanning>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

Note that if I navigate to another page and then back to the IdnetifyPage.xaml and click the scanPage.xaml link everything continues to work.

 Pretty sure this is what @Hoithebest identified.

Thanks again in advance for any assistance.

Jose

**Comment by romanryba** [comment]
btw you are using UWP solution in UWP.Xamarin.Forms , it does not work well like in Android and iOS you should be using ZXing.Mobile.Forms not ZXing.Mobile if you have Xamarin.Forms app

**Comment by chromos33** [comment]
Any News on the Bug Fix?

I currently also have this problem but can't work ar.
My Project (xamarin.forms) contains of 3 Xaml Pages whereas the ScanPage (Page with button that fires DependencyService to Start Scan Natively and return scanned value)
In Android this works Flawelessly.
On UWP I gathered through some Debugging it does not actually "navigate" back to MainPage.xaml as much as it "starts" the app anew. As the (Xamarin PCL) Application Construktor gets Called.
The Scan itself succeeds.

Any Ideas how to Fix that?

**Comment by Redth** [comment]
Moving this to #366 which has the same issue, and looking for the best solution to it.
