### ISSUE TITLE
UWP 10 Mobile App - Camera functionality crashes after using the barcode scanner

### ISSUE THREAD

**Issue by bleachedbug** [Redth/ZXing.Net.Mobile#294]
I have the following page Identify.xaml.cs which has the code below to call the barcode scanner:

 private async void btnBarcodeScan_Click(object sender, RoutedEventArgs e)
        {
            var scanner = new MobileBarcodeScanner();
            var result = await scanner.Scan();

```
        scanner.UseCustomOverlay = false;
        scanner.TopText = "Hold camera up to barcode";
        scanner.BottomText = "Press red line to focus and scan barcode";

        var dialog = new MessageDialog("Scanned Barcode: " + result.ToString());
        await dialog.ShowAsync();
    }
```

This works as expected. However after using this I have another page called Contact.xaml.cs which utilizes the device camera; code below:

private async void btnCamera_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                CameraCaptureUI captureUI = new CameraCaptureUI();
                captureUI.PhotoSettings.Format = CameraCaptureUIPhotoFormat.Jpeg;
                captureUI.PhotoSettings.CroppedSizeInPixels = new Size(200, 200);
                captureUI.PhotoSettings.MaxResolution = CameraCaptureUIMaxPhotoResolution.HighestAvailable;
                StorageFile file = await captureUI.CaptureFileAsync(CameraCaptureUIMode.Photo);
                string _fileNameConvention = Guid.NewGuid().ToString() + ".jpg";
                StorageFile fileCopy = await file.CopyAsync(KnownFolders.PicturesLibrary, _fileNameConvention, NameCollisionOption.GenerateUniqueName);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Exception Message: " + ex.Message);
            }

And this fails everytime on the following line of code after the barcode scanner has been used:

StorageFile file = await captureUI.CaptureFileAsync(CameraCaptureUIMode.Photo);

This generally returns a black screen and times out. I really hope you can assist with a solution as this is a blocker to me using the Zxing.mobile.net solution.

Many thanks in advance,

Jose

**Comment by Redth** [comment]
What kind of exception are you getting?  A stack trace would be helpful.  My guess is something's not being cleaned up properly from ZXing...

**Comment by bleachedbug** [comment]
Following the code as per this link https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.WindowsUniversal/ScanPage.xaml.cs resolves this issue from happening.

**Comment by romanryba** [comment]
i have the same problem, when you use camera first it works than scanner and than camera again it does not work, but the scanner works allways, it is like the scanner has some exclusive permission for camera that it does not releases, btw the camera does not give any exceprion in output just opens black screen and closes it self in like 3 seconds

**Comment by dktechindia** [comment]
I am also facing the same issue. For android it is working fine but for UWP/Windows 8.1 it if giving unhandled exception at below line even after adding try catch block, exception is not being caught. 
`var result = await scanner.Scan();`

any one have working scanner with UWP/WIndows 8.1 ?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
