### ISSUE TITLE
PDF417 SA Driver License scanning not working

### ISSUE THREAD

**Issue by bnroode** [Redth/ZXing.Net.Mobile#295]
Could you perhaps have a look at the scanning of South African driver's licenses? 

I have implemented a cross-platform Xamarin application and am able to scan Vehicle License Disks successfully on Winphone, iOS and Android but Driver's License scanning doesn't work at all on any one of the platforms.

I have used different CameraResolution settings on a Samsung Galaxy S4, I have tried native scanning on an iPhone 5s, but nothing works so far.

Any advice would be appreciated. I've attached a small sample, can privately share a higher quality image.

![sa-driving-licence-back](https://cloud.githubusercontent.com/assets/16605509/14284769/4124a654-fb49-11e5-9a75-54a8494cfef1.jpg)

**Comment by Redth** [comment]
The best thing to do in this case is try the upstream project without the variables of a device thrown in the mix.  You can load the image directly with ZXing.Net and see if it's able to analyze it.

**Comment by Thorocaine** [comment]
@bnroode did you come right with this?
Out of interest, what are you using to decode once you get the barcode data?

**Comment by bnroode** [comment]
@Thorocaine I couldn't get ZXing and a few other PDF417 scanners to scan the SA driver's license barcode. One package worked - [PDF417](https://github.com/PDF417/pdf417-xamarin). PDF417 is not free and therefore our client decided against the functionality. To decode I used a local provider's APK [VerifyID](http://www.verifyid.co.za/), this also costs money per decode but is very reasonably priced, depending on your use case obviously. Hope this helps.

**Comment by Thorocaine** [comment]
Thank you, I found a service to decode, I was just interested to see what
else is there.
I am having a hard time getting the camera scanning working, but it is good
(I guess) to know that I don't need to carry on trying with ZXing.

I saw PDF427 yesterday, it did not look as easy to implement, but maybe I
must give that a try.
For now I just need to get a demo unit working, that will give me time then
to decide if I want to pay for a licence, or try find a different solution.

**Comment by bnroode** [comment]
@Thorocaine may I ask which service you use to decode? Were you able to get the PDF427 working on Xamarin Forms?

**Comment by Thorocaine** [comment]
I haven't tried PDF417/Blink yet. I found a scanner called Manatee which seems to be working, and very easy to implement (I would be happy to share anything with you).

For decoding, I am using http://apextechnology.co.za
Their website didn't seem to have a sign-up, but I can share contact details if you need them.

**Comment by zkrige** [comment]
yeh - https://scan.apextechnology.co.za seem to be able to decrypt the data and the image in the barcode just fine

**Comment by deonvisser** [comment]
Hi Guys
Thorocaine, you said Manatee works for you. I tried their Cognex Scanner on both PDF 417 Standard and PDF417 Micro. Neither worked. Just got garbage. What scanner are you using?

**Comment by Thorocaine** [comment]
I am using PDF417 with Manatee.
The result looks like garbage, but it isn't. The barcode on the driving
licence is binary data, not a string.

So you want to use `result.bytes` to get a byte array.

**Comment by zkrige** [comment]
To follow on, those hex bytes need to then be decrypted to get anything useful out of them.

**Comment by deonvisser** [comment]
Hey Guys

Thank you for pointing in the right direction. That explains the garbage :):)

Baby steps for me. 

Have you managed to decrypt. I see there is something here that may help https://github.com/ugommirikwe/sa-license-decoder

**Comment by zkrige** [comment]
Unfortunately the link you posted has 2 flaws

1) it only works with a small percentage of licenses
2) it cannot decode the image

there is a link above that handles everything

**Comment by deonvisser** [comment]
Ok, thank you. I see they charge per scan though.

**Comment by deonvisser** [comment]
Ok, getting somewhere. @Thorocaine or @zkrige do you perhaps have contact details for Apex Technology? Their online reg does not work, neither does their contact form. A bit dodgy if you ask me but if you guys are using them, I will give them a shot.
Thxs

**Comment by Thorocaine** [comment]
Did you manage to get hold of them?

**Comment by deonvisser** [comment]
Yes, I did. Will not work for my requirements due to a few reasons. I have the public keys and currently busy decrypting it myself now.

**Comment by zkrige** [comment]
I've seen public keys floating around, but have yet to see a successful implementation. Also, the public keys wont help you much getting the image out of the barcode. Thats a whole other layer of pain. Good luck and let us know of any progress

**Comment by deonvisser** [comment]
I will bear that in mind, thks.
