### ISSUE TITLE
Android - first scan never works, works only after permissions are given.

### ISSUE THREAD

**Issue by ghost** [Redth/ZXing.Net.Mobile#297]
First; thanks for the great lib, your effort is appricated :+1: 

First scan never works in android;

To reproduce;
-do a total uninstall of the app on device (remove previously given permissions)
-install the app using zxing.net.mobile
-try scanning a bar code. 
-scanner/app asks for permissions, you grant permission 'allow'
-scanner appears, with active camera
-scanner does'nt pick up QR-code
-press back, or quit app
-try scanning again
-scanner/app doesnt ask for permission, because it was given before...
-scanner picks up the QR-code
-every next scan works as expected

Details;
-I use android 6.x (Nexus 9/Nexus 6p)
-I use zxing.net.mobile 2.0.4.46
-Visual studio update 2
-Xamarin forms 2.1.0.6529

-In my android manifest; 

`	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />`

-In my mainactivity.cs I have;

`            ZXing.Net.Mobile.Forms.Android.Platform.Init();
            ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);`

and also;

`        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }`

-In my view;

`private ZXingScannerPage scanPage;`

`try
            {
                scanPage = new ZXingScannerPage(new ZXing.Mobile.MobileBarcodeScanningOptions { AutoRotate = false, TryHarder = true, PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE } });
                scanPage.OnScanResult += (result) =>
                {
                    scanPage.IsScanning = false;

                    Device.BeginInvokeOnMainThread(() =>
                    {
                        Navigation.PopAsync();
                        textKey.Text = result.Text;
                    });
                };

                await Navigation.PushAsync(scanPage);
            } catch { textKey.Text = "error scanning..."; }`

-juist did a test with an 'old' Android Galaxy Nexus Api level 19, problem does not occour there. 

So I suspect, is has to do with the new way of asking permissions...

**Comment by Redth** [comment]
Fixed in master and will be released soon.

**Comment by Nixon-Joseph** [comment]
@Redth  I'm running into this exact same thing on 2.4.1.

Here's my scanning page

```
public class BarcodeScanningPage : FirebaseContentPage, IPageNavigation
    {
        ZXingScannerView ZXingView { get; set; }
        ZXingDefaultOverlay Overlay { get; set; }

        public BarcodeScanningPage() : base()
        {
            Title = "Scanning...";

            ZXingView = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingScannerView",
                Options = new ZXing.Mobile.MobileBarcodeScanningOptions()
                {
                    PossibleFormats = new List<ZXing.BarcodeFormat>() {
                        ZXing.BarcodeFormat.CODE_39, ZXing.BarcodeFormat.QR_CODE
                    }
                }
            };
            ZXingView.OnScanResult += (result) => Device.BeginInvokeOnMainThread(async () =>
            {
                // Stop analysis until we navigate away so we don't keep reading barcodes
                ZXingView.IsAnalyzing = false;

                await NavigationHelper.PushAsync(new SearchResultsPage(new ApiModels.SearchItemsParams()
                {
                    Keyword = result.Text,
                    ResultsPerPage = App.AppConfig.SearchResultsPerPage
                }, result.Text, true));

                //await NavigationHelper.PopAsync();
            });

            Overlay = new ZXingDefaultOverlay()
            {
                BottomText = "Scan Barcodes or QR Codes",
                ShowFlashButton = ZXingView.HasTorch,
                AutomationId = "zxingDefaultOverlay",
            };
            Overlay.FlashButtonClicked += (sender, e) =>
            {
                ZXingView.IsTorchOn = !ZXingView.IsTorchOn;
            };
            var grid = new Grid()
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };
            grid.Children.Add(ZXingView);
            grid.Children.Add(Overlay);

            // The root page of your application
            Content = grid;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            ZXingView.IsScanning = true;
        }

        protected override void OnDisappearing()
        {
            ZXingView.IsScanning = false;

            base.OnDisappearing();
        }
}
```

Any ideas how I might get around this? Thanks! Great plugin.

**Comment by TonyC5** [comment]
I am experiencing the same problem on Android.  My PCL project (for iOS and Android) is built with Xamarin Forms and ZXing Mobile (versions below).  First scan after granting cameral permissions on Android does not work (continues to scan without recognizing QR Code).  Tapping "Back" (to cancel scan) and then scanning again works.  All subsequent scans work without problems. Problem is easily duplicated by removing and reinstalling the app on Android.  Problem does not happen on iOS.

My development environment is as follows:

- Xamarin.Mac Version: 5.0.0.0 (Visual Studio Community) Build date: 2018-09-27 11:41:37-0400
- Xamarin.iOS Version: 12.0.0.15 (Visual Studio Community) Build date: 2018-09-17 21:54:33-0400
- Xamarin.Android Version: 9.0.0.20 (Visual Studio Community)
- Visual Studio Community 2017 for Mac Version 7.6.9 (build 22)
- ZXing.Net.Mobile Version 2.4.1
- ZXing.Net.Mobile.Forms Version 2.4.1
- Operating System Mac OS X 10.13.6

**Comment by helzgate** [comment]
@riyasv The reason you run into this issue is because camera permissions are being checked after the scanner is already initialized.  Check permissions before ever initializing the scanner and this won't happen.

Here is the code I use:

```
private async Task<bool> CheckCameraPermissionOtherwiseItWontWorkOnFirstUse()
        {
            try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
                if (status != PermissionStatus.Granted)
                {
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera))
                    {
                        //await DisplayAlert("Need location", "Gunna need that location", "OK");
                        await dialogService.ShowMessage("Need Camera", "We need camera for this function to work.", "OK", null);
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Camera);
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Permission.Camera))
                        status = results[Permission.Camera];
                }

                if (status == PermissionStatus.Granted)
                {
                    return true;
                }
                else if (status != PermissionStatus.Unknown)
                {
                    await dialogService.ShowMessage( "This function doesn't work without camera permissions being enabled.", "Need Camera", "OK", null);
                    return false;
                }
            }
            catch (Exception ex)
            {
                Crashes.TrackError(ex);
                await dialogService.ShowError(ex, "Error setting camera permission", "OK", null);
                return false;
            }
            return false;
        }
```

**Comment by wegascee** [comment]
@helzgate:

The initialization of the scanner is done in `OnCreate()` in `MainActivity.cs` with

` ZXing.Net.Mobile.Forms.Android.Platform.Init();`

I'm already checking for permissions first before putting the scanner page onto the navigation stack. I'm using Zxing v.2.4.1
