### ISSUE TITLE
ZXingBarcodeImageView not working in iOS??

### ISSUE THREAD

**Issue by Hoejer** [Redth/ZXing.Net.Mobile#298]
I'm currently working on an crossplatform app using Xamarin Forms (shared). I need to generate a EAN-13 barcode, and my code works fine on Android, but nothing happens on iOS. I'm using ZXingBarcodeImageView. This is my code.

```
public class CardPage : ContentPage
{
  ZXingBarcodeImageView barcode = new ZXingBarcodeImageView
  {
    HorizontalOptions = LayoutOptions.Center,
    VerticalOptions = LayoutOptions.Center,
  };

  barcode.BarcodeFormat = ZXing.BarcodeFormat.EAN_13;
  barcode.BarcodeOptions.Height = 25;
  barcode.BarcodeOptions.Width = 75;
  barcode.BarcodeValue = "2800100028014";

  Content = barcode;
}
```

**Comment by Dennis9347** [comment]
Did you do the init?

**Comment by Hoejer** [comment]
Forgot the global::ZXing.Net.Mobile.Forms.iOS.Platform.Init(); in the AppDelegate.cs.
