### ISSUE TITLE
Universal App Qr-Code Generation not working

### ISSUE THREAD

**Issue by MJoehl** [Redth/ZXing.Net.Mobile#299]
I created a new Xamarin.Forms app with a Universal-Project. Then I added the ZXing.Net.Mobile (2.0.4.46) package via Nuget to all my platform projects.

I implemented an interface to generate a qr-image from my pcl-project (via DI). Following code shows the implementation for the UWP-Project:

```
var options = new ZXing.QrCode.QrCodeEncodingOptions
{
    Height = 200,
    Width = 200,
    Margin = 0,
    PureBarcode = true
};

var writer = new ZXing.Mobile.BarcodeWriter
{
    Format = ZXing.BarcodeFormat.QR_CODE,
    Options = options
};

var bitmap = writer.Write("testcontent");
```

It Looks like everything works fine. But when I try to show the created Image on the screen or I try to save it to the disk, the image is corrupted and can't be shown. No exception and no error in my ouput window...

**Comment by redwolf2** [comment]
You can use zxing.net directly, like this:

```
var content = "123456789012345678";
var writer = new ZXing.Rendering.BarcodeWriter { Format = BarcodeFormat.QR_CODE };
var bitmap = writer.Write(content);
```

**Comment by Redth** [comment]
Yep, what @redwolf2 said, or do it in the platform specific layer, or use the Forms control if you're using Xamarin.Forms...
