### ISSUE TITLE
Doesn't recognize required line in Page Contructor for UWP

### ISSUE THREAD

**Issue by tfierens** [Redth/ZXing.Net.Mobile#303]
Hi,

I'm trying the version available from Nuget as I just realized that the version I've been using from GitHub work fairly well with continuous scanning but only when the configuration is in debug mode. Once I got to release mode and try it either on a Windows Phone or on my laptop, it bombs out quite badly.

Anyway, reading your documentation, it requires to add this to the Page's constructor

ZXing.Net.Mobile.Forms.WindowsUniversal.ZXingScannerViewRenderer.Init();

But it doesn't like it. It doesn't find the required command.

When I check the namespace, this is what it has: 

ZXing.Net.Mobile.ZXing_Net_Mobile_WindowsUniversal_XamlTypeInfo

Any ideas?

Thanks.

**Comment by Redth** [comment]
I'm really not sure what's happening here.   Try the 2.1.0 prerelease version or wait for the 2.1.0 stable version to be released (or better yet, try the code in master).  We can reopen it if it's still an issue after that.
