### ISSUE TITLE
iOS Forms scanning unable to scan large QR Codes

### ISSUE THREAD

**Issue by mdkitzman** [Redth/ZXing.Net.Mobile#306]
I have set up a Xamarin Forms project for iOS, Android and UWP.  It is a simple application that scans a QR code and connects to a website with the scanned information.  The QR codes that we are scanning contain a fair amount of information, and scan relatively well in Android and UWP.  iOS seems to have a lot of trouble scanning these QR codes.

We then created a native app using the built-in bar code scanning functionality in iOS, and it is able to scan the same QRCode much faster.  Here is the page that we have for scanning the QR code

```
public partial class Start : ContentPage
{
    ZXingScannerPage scanPage;
    
    public Start()
    {
        InitializeComponent();
        licenseService = new LicenseService();
        scanPage = new ZXingScannerPage(new ZXing.Mobile.MobileBarcodeScanningOptions()
        {
            AutoRotate= false,
            PossibleFormats = { BarcodeFormat.QR_CODE },
            UseNativeScanning = true
        });
        
        scanPage.DefaultOverlayTopText = null;
        scanPage.DefaultOverlayBottomText = null;

        scanPage.OnScanResult += AfterQRCodeScanned;
    }

    private void AfterQRCodeScanned(Result result)
    {
        scanPage.IsScanning = false;

        Device.BeginInvokeOnMainThread(async () =>
        {
            await Navigation.PopAsync();

            if (result != null && !string.IsNullOrEmpty(result.Text))
            {
                // Do stuff with the resulting text
            }
        });
    }

    public async void ScanQRCode(object sender, EventArgs args)
    {
        await Navigation.PushAsync(scanPage);
    }
}
```
Here is an example of the QRCode that iOS cannot seem to scan properly.

![largeqrcode](https://cloud.githubusercontent.com/assets/11448209/14831284/3eb72ad0-0bb2-11e6-8a87-c2b3e6325925.jpg)

**Comment by Redth** [comment]
You can also use the native reader with ZXing.... 

https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/iOS/Sample.iOS/HomeViewController.cs#L88-L96

However in Forms I don't think there's a clear way to enable that engine... I'll need to add support for this.

**Comment by Redth** [comment]
Not sure why iOS is slow for this, there could be a number of reasons, but if the AVCapture engine works, let's call this issue resolved by being able to use AVCapture engine instead.

Track issue #323 instead
