### ISSUE TITLE
Not compatible with Xamarin.Forms 2.2.0.31

### ISSUE THREAD

**Issue by jenscski** [Redth/ZXing.Net.Mobile#309]
When upgrading to Xamarin.Forms 2.2.0.31, the Android-app will no build, after uninstalling ZXing.Net.Mobile.Forms the project compiles again.

When using  Xamarin.Forms 2.1.0.6529, there is no problem compiling.

**Comment by michaeldimoudis** [comment]
Got the exact same issue. Not really a fan of component vendors relying on certain versions of Xamarin.Forms and/or Android versions, but not sure how else we can get around that at the moment...

Any ETA for an updated Nuget package?

**Comment by marlonconstante** [comment]
I am also having the same problem here, specifically in the file "Resource.designer.cs" generated during compilation.

**Comment by madhatter14641** [comment]
Same problem. Many lines in the Resource.Designer.cs file are flagged ("Resource.Id does not contain a definition for 'art'").

**Comment by ilber** [comment]
Same problem ;)

**Comment by michaeldimoudis** [comment]
Silence regarding this issue? This is a pretty serious blocking issue for anyone wanting to upgrade... I think I'll have to revert to building this myself if no updated nuget packages are released soon :(

**Comment by Redth** [comment]
Has anyone tried the beta that's on nuget? it should fix this.  I will be updating a stable release soon, sorry folks, catching up from Evolve!

**Comment by michaeldimoudis** [comment]
I just saw the open source Xamarin Evolve app by James is on Forms 2.3 with the beta of this library. Nice I'll give the beta a go and see if I can compile 👍🏼

**Comment by VSchneider** [comment]
I'm not Xamarin experienced user, so, I spend more than 20 hours without sleep to reach here. The warning and errors Windows focused out the output window, where has some help to resolve...

Well, finally I saw, I'm not alone! 

No, I was, because I opened a Full Updated new Solution, instaled ZXing Stable and CRASHES like my Project.. and...

I uninstalled, Works fine again and..


S O L V E D 👍 👍  👍  INSTALED THE BETA VERSION, AND IS COMPATIBLE!

**Comment by wezzix** [comment]
I can confirm that installing ZXing 2.1.0-beta1 resolves the problems with Xamarin.Forms 2.2.0.31
In order to install beta with VS NuGet package manager, you need to check "Include Prerelease" which makes beta available.

**Comment by Redth** [comment]
The stable release with this will go out soon, thanks!
