### ISSUE TITLE
UWP camera use

### ISSUE THREAD

**Issue by romanryba** [Redth/ZXing.Net.Mobile#314]
I am using Xamarin Forms and UWP.
If you use scanner
`ZXingScannerPage scanPage = new ZXingScannerPage();`
`scanPage.OnScanResult += async (result) =>`
`{ ... }`

than CameraCaptureUI is not working or any cammera usage after using the scanner and not killing the app. Only exception is the ZXingScannerPage that works after closing and opening the page.
I dont know if it is feature of UWP or actual bug...

**Comment by Redth** [comment]
Needs more information, like stack traces...

I suspect you are not setting it up right in your project, maybe not calling the Init function for the platform?  Take a look at how the sample is setup and see what you might be missing.
