### ISSUE TITLE
Lower dependency version

### ISSUE THREAD

**Issue by r0b0t3d** [Redth/ZXing.Net.Mobile#315]
Dear @Redth,
I got an problem when installing for Xamarin Forms.

```
Adding ZXing.Net.Mobile.Forms...
Attempting to resolve dependency 'ZXing.Net.Mobile (≥ 2.0.4.46)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.0.6490)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.0.1.3)'.
Already referencing a newer version of 'Xamarin.Android.Support.v4'.

```

I did try the beta version but it did not work too.
Could you please change the dependency of Xamarin.Forms to newer version? 
Currently, it is 2.2.0.31

**Comment by timahrentlov** [comment]
I'm getting the same error. Also tried with beta1, but to no avail:

Adding ZXing.Net.Mobile.Forms...
Attempting to resolve dependency 'ZXing.Net.Mobile (≥ 2.1.0-beta1)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.0.6490)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.0.1.3)'.
Already referencing a newer version of 'Xamarin.Android.Support.v4'.

**Comment by Redth** [comment]
use the prerelease version...

**Comment by timahrentlov** [comment]
Does not work. Will await stable.
