### ISSUE TITLE
Make a Portable Image / LuminanceSource for Decoding barcodes

### ISSUE THREAD

**Issue by Warthar** [Redth/ZXing.Net.Mobile#317]
I have done some extensive searching on this issue and finding very few support documents.

I am trying to take an already existing image [download here](https://drive.google.com/open?id=0B42XN3-a_tIoanlvVVpnenRoSUU) with a simple barcode on it and process the barcode in a PCL layer of the project.

Here is the code i am processing:

```
private void ReadBarcode()
        {
            try
            {
                var imageBytes =imagingHelper.GetImage(ImagePath);
                var width = imagingHelper.GetWidth(ImagePath);
                var height = imagingHelper.GetHeight(ImagePath);
                LuminanceSource source = new ZXing.RGBLuminanceSource(imageBytes, (int)width, (int)height);
                HybridBinarizer hb = new HybridBinarizer(source);
                var a = hb.createBinarizer(source);
                BinaryBitmap bBitmap = new BinaryBitmap(a);
                BarcodeReader reader = new BarcodeReader();
                reader.Options.TryHarder = true;

                MultiFormatReader reader1 = new MultiFormatReader();
                try
                {
                    var r = reader1.decodeWithState(bBitmap);
                    var result = reader.Decode(source);
                    var result2 = reader.DecodeMultiple(source);
                    if (result != null)
                    {
                        return;
                    }
                    return;
                }
                catch (Exception ex)
                {
                    HandleError("ReadBarcode Error: ",ex.Message);
                }
            }
            catch (Exception ex)
            {
                HandleError("ReadBarcode Error: ", ex.Message);
            }
        }
```

for the image helper (at the android level)

```
public override uint GetWidth(string photoPath)
        {
            BitmapFactory.Options options = new BitmapFactory.Options();
            options.InPreferredConfig = Bitmap.Config.Argb8888;
            Bitmap bitmap = BitmapFactory.DecodeFile(photoPath, options);
            return bitmap.GetBitmapInfo().Width;
        }

        public override uint GetHeight(string photoPath)
        {
            BitmapFactory.Options options = new BitmapFactory.Options();
            options.InPreferredConfig = Bitmap.Config.Argb8888;
            Bitmap bitmap = BitmapFactory.DecodeFile(photoPath, options);
            return bitmap.GetBitmapInfo().Height;
        }
        public override byte[] GetImage(string photoPath)
        {
            BitmapFactory.Options options = new BitmapFactory.Options();
            options.InPreferredConfig = Bitmap.Config.Argb8888;
            Bitmap bitmap = BitmapFactory.DecodeFile(photoPath, options);

            var width = bitmap.GetBitmapInfo().Width;
            var height = bitmap.GetBitmapInfo().Height;
            int size = bitmap.RowBytes * (int)bitmap.GetBitmapInfo().Height;
            ByteBuffer byteBuffer = ByteBuffer.Allocate(size);
            bitmap.CopyPixelsToBuffer(byteBuffer);
            byte[] byteArray = new byte[byteBuffer.Remaining()];
            byteBuffer.Get(byteArray);
            return byteArray;
        }
```

Every single one of my results are turning up null and i'm unsure how to proceed.  I have downloaded the latest beta package and on xamarin forms 2.1.0.6529

any help in this would be great i'm not sure if there is something wrong or what.

I should also note that even at the android level it appears to not return a result.

**Comment by mhawman** [comment]
added note: my image is coming in as a 1 bit image which it looks like is not currently supported by the platform.

**Comment by Redth** [comment]
I'm not entirely sure the best way to try and make this PCL friendly.  Currently obviously a very specific image format is expected.  You could do this much more easily with platform specific code (using the luminance sources for each specific platform just like the barcode reader from live preview does).

I think first step is to have some image format agreed upon across all the platforms.  This will require some research.

**Comment by mhawman** [comment]
@Redth We have agreed that for our android side of things it will be a 1 bit bitmap image.  I don't really have a say in this however i will consider pushing this down to the android layer.  Are there plans to make this able to be done at a PCL level in the future? (i know there are some restrictions based on xamarin, Mono, and MS.) however if allowed would this be updated to work in the PCL?

**Comment by DevRach** [comment]
Hi,
@mhawman , Were you able to find a solution for this issue that you were facing? I am also stuck with the same issue and I am trying to figure out a solution. :(

**Comment by mhawman** [comment]
@DevRach Unfortunately I no longer work at that company or on that project, we had to abandon the Zxing framework as we could not take our images from 1 bit to 8bit due to hardware limitations. you will need a 8bit image to make it work properly at the pcl level hope this helps.

**Comment by DevRach** [comment]
@mhawman  Thanks for your reply. :) I am still not successful at decoding the image. Hoping for the best. :)

**Comment by Redth** [comment]
Not going to do this, as I want to keep the default scanning engine consistent across platforms.
