### ISSUE TITLE
UWP App "restarts" after trying to Navigate Back

### ISSUE THREAD

**Issue by chromos33** [Redth/ZXing.Net.Mobile#320]
I already posted this one some other Issues just wanted a Post with more Clarity.

I also have the problem that #318 and #319 have, that UI Elements do not change after Scan Result is inserted.

What i found out so far is that this has nothing to directly with the Elements or the Scan but rather with Navigation. While debugging i found it strange that the OnStarted function or rather the Constructor of the MainPage gets called which then reloads the Application.

This makes me suspect Navigation is the culprit since the code that reads the Bar/QRCode actually finishes and returns the Result.

Code

> public async void OnScanBtnClicked(object sender, EventArgs args)
{
            string qrcode = await DependencyService.Get<IDependencyService>().ScanQRCode();
            TestLabel.Text = qrcode;
}
public async Task<string> ScanQRCode()
{
            string qrcode = "";
            var scanner = new MobileBarcodeScanner();
            var result = await scanner.Scan();
            if(result != null)
            {
                qrcode = result.Text;
            }
            return qrcode;
}

With debug stop points set at "return qrcode;" and "TestLabel.Text = qrcode;" it stops execution at both points and the Value of qrcode is correct on both accounts.
No Exception, just the App "restart".

Hope this helps finding the Bug or the Solution to this Problem

**Comment by Strifex** [comment]
If you're not familiar with the UWP navigation pattern you may want to take a look at this...

https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.page.navigationcachemode.aspx

By default pages are not cached and therefore, navigating will create a new instance.  Turning this cache on will cause the GoBack() to return to existing copy of page/frame.

**Comment by chromos33** [comment]
Thanks a lot that was actually it. This might also be the solution to #319 #318 and #293.

**Comment by Redth** [comment]
Added this to the sample's xaml and a note about it in the readme in 4b45f9079366fc62ff6aeec12fbbe02db597b53b
