### ISSUE TITLE
Win10 UWP : App freeze after scanning barcode a few times

### ISSUE THREAD

**Issue by SahanaMG** [Redth/ZXing.Net.Mobile#326]
I am using the MobileBarcodeScanner.Scan() to scan barcodes/QRCodes. Everything works fine while I'm scanning the barcodes on Desktop, while on a Mobile device (Microsoft Lumia 650) the app freezes with a white screen with a red line in the middle or freezes with the image captured with the red line in the middle. Typically this happens after scanning 6-7 barcodes.
Sometimes the app crashes 4-5 seconds after the freeze
Exception : -		**Exception	{"Value does not fall within the expected range."}  
 System.Exception {System.ArgumentException}**
Stack Trace : `"   at Windows.Media.Devices.VideoDeviceController.SetMediaStreamPropertiesAsync(MediaStreamType mediaStreamType, IMediaEncodingProperties mediaEncodingProperties)\r\n   
				at ZXing.Mobile.ZXingScannerControl.<StartScanningAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n  
 				at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
				at ZXing.Mobile.ScanPage.<OnNavigatedTo>d__73.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)\r\n 
 			 	at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()"`
Code:
`
 public async void BarcodeScanHandle()
        {
            scanner = new MobileBarcodeScanner(this.Dispatcher);
            var options = new MobileBarcodeScanningOptions { TryHarder = true };
            
            var result = await scanner.Scan(options);
            MessageDialog dialog = new MessageDialog(result.Text);

            await dialog.ShowAsync();
        }
`

**Comment by AlessioVecchi** [comment]
We have the same problem. 
The app on dell device freeze after 20 seconds.

This is the code (very standard):

 `      public QRCodeView()
        {
            this.InitializeComponent();
        }
                
        private MobileBarcodeScanner _scanner;       

        private async void ScanButton_Click(object sender, RoutedEventArgs e)
        {
            _scanner = new MobileBarcodeScanner(this.Dispatcher);
            _scanner.UseCustomOverlay = false;
            _scanner.TopText = "Hold camera up to QR code";
            _scanner.BottomText = "Camera will automatically scan QR code\r\n\rPress the 'Back' button to cancel";

            
            var result = await _scanner.Scan();
            ProcessScanResult(result);

        }


       private async void ProcessScanResult(ZXing.Result result)
        {
            string message = string.Empty;

            message = (result != null && !string.IsNullOrEmpty(result.Text)) ? "Found QR code: " + result.Text : "Scanning cancelled";

            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
            {
                await ShowMessageToUser(message);
            });

        }

        private async Task ShowMessageToUser(string message)
        {
            var dialog = new MessageDialog(message);
            await dialog.ShowAsync();
        }`

**Comment by huangjinshe** [comment]
Are you UWP support scan EAN 8 and EAN 13?  It can't recognize in my UW10 phone. even I set the format manually.

**Comment by F1nZeR** [comment]
@huangjinshe I've tested UWP sample (from master) on random EAN8 and EAN13 barcodes and everything works great. You can check it now.

**Comment by Redth** [comment]
Tested here too, working fine.  Closing issue for now.

**Comment by hacheyj** [comment]
I was able to reproduce this exception using the Homepage.cs from  https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/WindowsUniversal/Sample.WindowsUniversal.

By running it in **Debug in Visual Studio 2015** on a Windows 10 Professional laptop, this error would occur once you scanned a barcode (using the first button), went back to the homepage, and then clicked the first button again.

WARNING: It was not reproducible in the emulator nor when deploying a developer store package of the same code.
