### ISSUE TITLE
Android front camera inverted upside down

### ISSUE THREAD

**Issue by abelgs1987** [Redth/ZXing.Net.Mobile#328]
I'm facing with a really weird issue.

ZXing in my android mobile with front camera is inverted and thus i don't get the barcode to work. Instead, in iOS works perfectly.

I'm wondering if this is a possible bug with this component in Android version.

I would appreciate any advice.
Many thanks

**Comment by borjagarciac** [comment]
I've the same problem using the samples of this repository.

Devices tested: Samsung Galaxy S7 Edge (marshmallow), Sumsung Galaxy Tab 4 (kitkat). 

Thanks!

**Comment by cbartonnh** [comment]
I am also having this issue with the 2.1.0 beta. Tested on Galaxy Note 3 running Lollipop.

**Comment by Redth** [comment]
Should be fixed in master now.
