### ISSUE TITLE
Zxing camera becomes slow when calling StartScanning second time after calling PauseAnalysis()

### ISSUE THREAD

**Issue by bwwilliam** [Redth/ZXing.Net.Mobile#329]
I have three tabs in my app.
The first time swipe from tab1 to Scan tab where the scan window is located, it works perfectly fine. However, if I swipe to another tab then swipe back to Scan tab again. It takes about 8 seconds for the ScanFragment to come back. I'm using Xamarin for Android. I tried to use PauseAnalysis when swipe to a tab other than Scan tab that is when it becomes slow. I tried to use StopScanning when swipe away from Scan tab, but the problem is when swipe back to Scan tab, the camera does not really focus.

**Comment by bwwilliam** [comment]
please see this link 
http://stackoverflow.com/questions/37295838/zxing-camera-becomes-slow-when-calling-startscanning-second-time-in-xamarin

**Comment by bwwilliam** [comment]
please let me know if sample code need to be supplied.

**Comment by Redth** [comment]
Have you tried using ResumeAnalysis () instead of StartScanning on subsequent tries?

**Comment by bwwilliam** [comment]
Yes, I tried. 

ResumeAnalysis() works in a way that solves the camera focus issue. But it has very slow performance, it takes about 8 seconds for the method run.

**Comment by Redth** [comment]
Do you have a solution that reproduces the issue you could share?

**Comment by bwwilliam** [comment]
Thank you. I will upload the source code to github tonight and let you know.

**Comment by bwwilliam** [comment]
Hi Redth, please see the source code here 
https://github.com/bwwilliam/OT.git
Thank you again.

**Comment by bwwilliam** [comment]
Thanks for your email. Sorry to ask a dumb question, how do I actually to pull https://github.com/Redth/ZXing.Net.Mobile/pull/361. Did you mean i need to pull the latest source code and compile it? Or is there a nuget package available for that version?

**Comment by bwwilliam** [comment]
I just downloaded latest source code and compiled it, unfortunately, I'm keep getting null object exception.

**Comment by Redth** [comment]
@bwwilliam you shouldn't get a null exception now with the latest source.  Please try it again.

**Comment by bwwilliam** [comment]
thank you very much Redth. That has resolved my problem after weeks of trying to find a solution. Very much appreciated.
