### ISSUE TITLE
Unable to Scan 1d Barcode in Windows Surface Pro 3

### ISSUE THREAD

**Issue by SahanaMG** [Redth/ZXing.Net.Mobile#330]
Faced the similar issue with the mobile device and could fix the issue by setting the TryHarder property. But still does not work for Windows Surface Pro 3

**Comment by SahanaMG** [comment]
Update : Works like a charm with the Front Camera. But no luck with the back Camera.

**Comment by redwolf2** [comment]
Can you provide an image of the barcode?

**Comment by SahanaMG** [comment]
![samplebarcode](https://cloud.githubusercontent.com/assets/19387180/15699650/2c942f14-27ec-11e6-8c42-e52051960677.gif)

**Comment by F1nZeR** [comment]
This should be fixed in master (even without TryHarder property).

**Comment by Redth** [comment]
Agreed, this should be fixed in master, will reopen if it's still a problem after 2.1.0 release.
