### ISSUE TITLE
Support for WinPhone RT 8.1

### ISSUE THREAD

**Issue by balivo** [Redth/ZXing.Net.Mobile#331]
Provide Support for WinPhone RT 8.1...

**Comment by Redth** [comment]
Sorry, but not going to happen without someone committing a big PR, since there's no managed API for accessing the camera preview buffer in RT 8.1.

**Comment by balivo** [comment]
Maybe I do this PR... If I have some time to do this in a few weeks... Tks for ans, @Redth!
