### ISSUE TITLE
Error When adding zxing.net.mobile.forms to Project

### ISSUE THREAD

**Issue by paranormal39** [Redth/ZXing.Net.Mobile#334]
When I Try and use zxing.net.mobile.android Init() in my main activity I get tons of Resource designer errors. only when i remove the zxing.net.mobile.froms from my droid file does the error go away and im able to make a build. But in doing so I cant get camera view for the scanner

**Comment by faceoffers28** [comment]
@paranormal39 I had the same issue when trying to use this package in my Android project. This is a pretty big problem as evidenced by this bug. https://github.com/XLabs/Xamarin-Forms-Labs/issues/1125#issuecomment-222151930 The package needs to be compiled with the AppCombat for API 23. Until this is done, the package will have these Resource designer issues. Hopefully, the developer will address this soon.

**Comment by paranormal39** [comment]
Well That Sucks any other barcode scanner easy to implement with xamarin forms? Been stuck on this one problem for almost a week and scanner is important to the application. Considering I have the code implemented Would love to resolve this issue and use zxing

**Comment by faceoffers28** [comment]
I'm using ZXing.Net.Mobile for Forms in my app that's targeting PCL 259. It's working great in iOS, but I'm having this issue as well as another (https://forums.xamarin.com/discussion/66403/xamarin-forms-android-app-crashing-due-to-xlabs-camera-code-after-upgrade-to-xamarin-forms-2-2-0-31#latest) in my Android app. Both issues are a result of Xamarin.Forms 2.0. As for your error, I found this bit of information, but I'm not sure how to use it. I've only been developing for less than a year and working with Xamarin for even less. What do you make of this? https://gist.github.com/rid00z/76906292010e080c7f5eadfb5ca7b107

**Comment by paranormal39** [comment]
Hey I actually solved the issue I just commented out zxing.net.mobile.forms.android.Int() to see if it was the zxingforms package and it build! Now the camera works and im able to scan !!!

**Comment by faceoffers28** [comment]
Glad you got it working! So, you just installed the package and now it is working in your Android app.??? Are you referencing the ZXing.Net.Mobile for Forms anywhere in your MainActivity? I guess it might work for me too if I can just get the Camera working. I'm using the XLabs Camera and it won't work in my Xamarin.Forms 2.2.0.31 Android app.

**Comment by Redth** [comment]
This is fixed in master already and in the 2.1.0 release.
