### ISSUE TITLE
enhancement request: ZXingSurfaceView could use a "preview displaying" event

### ISSUE THREAD

**Issue by kenkyee** [Redth/ZXing.Net.Mobile#335]
Use case is the UX designers gave me a design for a screen that has a toggle that goes from displaying a QR code to identify the user on one "side" of the screen, and on the other "side" you get to via the toggle button, there's a QR scanner that's full screen w/ an overlay.
To handle this, I add and remove ZXingSurfaceView to a ViewGroup depending on which "side" it's on.  Android cameras take forever to spin up, so there's a delay of .5 to 2sec (depending on the phone) when all you see is a blank screen where I'd like to put up an indeterminate progress spinner over the QR scanner view that isn't showing any camera preview data yet. What I need is an event that says "QR scanner displayed it's first preview frame".  The closest thing I've found is the ViewAttachedToWindow event, but it fires immediately when the ZXingSurfaceView is added to the ViewGroup, so it's not useful for turning off a progress spinner.

On a different note, the screen seems to have a dark translucent scrim on it that's not the overlay (I've also tried turning off the overlay and hiding all the overlapping widgets and even making the screen's background transparent). that I can't get rid of.  Still not sure where this oddness is coming from :-(

FYI, I hacked around not having the callback for now by using a System.Timers.Timer and setting up a delay of 3 seconds.  I display the busy indicator just before the ZXingSurfaceView is added to the viewgroup, then when the timer fires, I hide the busy indicator frame that covers the ZXingSurfaceView.  ZXingSurfaceView also seems to be doing too much on the UI thread because the busy indicator doesn't display smoothly initially...just seems to stall out while ZXingSurfaceView is getting set up :-(

**Comment by kenkyee** [comment]
I think the brightness issue is related to this:
http://stackoverflow.com/questions/31330098/android-surfaceview-preview-too-dark

But we can't set the preview_FPS parameter inside the ZXingSurfaceView?

**Comment by Redth** [comment]
I think long term it would be ideal to allow the Camera instance to be directly manipulated.  For right now, hopefully this helps :)

**Comment by Redth** [comment]
Closing this issue in favour of the enhancement issue I opened.

**Comment by kenkyee** [comment]
Thanks! :-)
BTW, turned out the brightness issue was because of a theme that added a dimmed background because the UX folks wanted to see the previous screen underneath. Surfaceviews are below your other views on most phones.

**Comment by Redth** [comment]
Ahh that is a fun one to debug :)

It's probably good practice to set the FPS range anyway, so, win-win !
