### ISSUE TITLE
Animation on Cancel whilst scanning [enhancement]

### ISSUE THREAD

**Issue by JSmyth886** [Redth/ZXing.Net.Mobile#341]
I think you could apply your boolean greater than iOS7 logic to the Cancel method within MobileBarcodeScanner class. This will allow animations for anything greater than iOS7 whilst still maintaining the bug fix for the black screen on iOS7.

**Comment by JSmyth886** [comment]
I have updated my fork with the necessary changes to allow the use of this boolean to allow the animations.

**Comment by Redth** [comment]
This deals with PR #345

**Comment by Redth** [comment]
Closing, let's move the conversation to #345
