### ISSUE TITLE
No image on 2.1.0-beta1 - WinPhone 8.1

### ISSUE THREAD

**Issue by BrunoAndrade** [Redth/ZXing.Net.Mobile#346]
Hello there.
First of all thanks for this amazing library.
So i am pretty new to it and i am developing a Xamarin.Forms app for Android / iOS / WinPhone 8.1.
Apparently this is the only library that works with all 3 platforms, and i know i am using the latest beta to date (mainly because it's the only version that supports Windows Phone 8.1).

I have this code @MainPage.xaml.cs

> ZXing.Net.Mobile.Forms.WindowsPhone.ZXingScannerViewRenderer.Init();

and this on on shared project:

>  Image image = new Image
            {
                Source = "scan.png",
                HorizontalOptions = LayoutOptions.End,
                HeightRequest = 48,
            };
            var tapGestureRecognizer = new TapGestureRecognizer();
            tapGestureRecognizer.Tapped += async (s, e) => {

                var scanner = new ZXing.Mobile.MobileBarcodeScanner();
                scanner.TopText = "Aponte para o Código de Barras do cartão que contém o NIF";
                scanner.CameraUnsupportedMessage = "Cam nao suportada";

                var result = await scanner.Scan();

                if (result != null)
                    entry_nif.Text = result.ToString();
            };
            image.GestureRecognizers.Add(tapGestureRecognizer);

It seems to work fine at Android, but at _Windows Phone_, all i get is a black background, a red line, and the toptext.
Phone camera seems to work fine elsewhere.

Any idea? Best regards.

**Comment by martinobordin** [comment]
Are you using PCL project? wich frameworks are you targeting?

**Comment by BrunoAndrade** [comment]
Hello martinobordin!

I am using Xamarin Forms Shared Project. Using Windows Phone 8.1 Silverlight.
Regarding the packages, i am using those for Windows Phone:
![image](https://cloud.githubusercontent.com/assets/19933968/16541790/b5e9d618-4085-11e6-9c32-dd808aca4ce8.png)
![image](https://cloud.githubusercontent.com/assets/19933968/16541791/cecc5642-4085-11e6-902c-4e2193499480.png)
![image](https://cloud.githubusercontent.com/assets/19933968/16541792/da26317a-4085-11e6-9940-75cd26ec1479.png)

**Comment by Redth** [comment]
Did you add camera permissions to your WP81 app? And is the WP81 app silverlight?

**Comment by BrunoAndrade** [comment]
Redth, yes, it's a Windows Phone 8.1 Silverlight app and i got webcam permission. Did i miss something?
![image](https://cloud.githubusercontent.com/assets/19933968/16818205/7e34df80-493e-11e6-9bb2-dabc97836351.png)

**Comment by Redth** [comment]
I'd suggest trying the sample and if that's working for you, compare to your app to see what the differences are. Eg: app init code, manifest declarations, etc

**Comment by BrunoAndrade** [comment]
I don't have access to a physical  Windows Phone right now to test, but i noticed i was giving the cam permission in a different file. The camera was not allowed under the Properties -> WMAppManifest.xml file!

**Comment by Redth** [comment]
That is likely the case, should work after you add that!
