### ISSUE TITLE
Event handlers should receive two parameters

### ISSUE THREAD

**Issue by sdebruyn** [Redth/ZXing.Net.Mobile#348]
Event handlers should aways receive the sender of the event as an `object` and arguments of the event as a subclass of `EventArgs`. This is currently not the case.

Event handler registration:

```
var scanner = new ZXingScannerView();
scanner.OnScanResult += MyHandler;
```

The handler itself:

```
void MyHandler(object sender, ScanResultEventArgs eventArgs)
{

}
```

At the moment, the handler only receives a custom object with the result inside.

**Comment by redwolf2** [comment]
Samuel is correct:

https://msdn.microsoft.com/de-de/library/system.eventhandler(v=vs.110).aspx
According to MSDN

> This method's first parameter is of type Object and refers to the instance that raises the event. Its second parameter is derived from type EventArgs and holds the event data.

**Comment by Redth** [comment]
While this is true, making this change right now will break API.   Moving this to a major release milestone for now.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
