### ISSUE TITLE
ZXing.Net namespace missing after Install ZXing.Net.Mobile?

### ISSUE THREAD

**Issue by huangjinshe** [Redth/ZXing.Net.Mobile#349]
Then I trying to install ZXing.Net, still show like that.

Is there anyone could tell me what step do I need to do for install it for Xamarin?

**Comment by huangjinshe** [comment]
`The type or namespace name 'Net' does not exist in the namespace 'ZXing'`

**Comment by huangjinshe** [comment]
Looks like Xamarin.IOS even not support to install `ZXing.Net`

**Comment by Redth** [comment]
ZXing.Net is a different project than ZXing.Net.Mobile.  ZXing.Net.Mobile directly includes ZXing.Net as a dependency, however there are some small changes in the distribution of it to make it work properly for mobile.  ZXing.Net.Mobile adds support for making real time barcode scanning from a live camera preview simple on Mobile platforms.

**Comment by huangjinshe** [comment]
@Redth So How should I do now? I even can't add something like:
`ZXing.Net.Mobile.Forms.Android.Platform.Init();` It telling me: Not found `ZXing.Net` namespace. It won't let the project build.

**Comment by huangjinshe** [comment]
Looks like I found the reason. We will not only need `ZXing.Net.Mobile` packages, We will also need to add `ZXing.Net.Mobile.Forms`   packages. the 2 package all description all same, easy let people confuse. I just hope this thread will help people.

**Comment by ExtremeKaos** [comment]
Thanks @huangjinshe, your are right !!, anyway thanks to all

**Comment by nath1ndaba** [comment]
> Looks like I found the reason. We will not only need `ZXing.Net.Mobile` packages, We will also need to add `ZXing.Net.Mobile.Forms` packages. the 2 package all description all same, easy let people confuse. I just hope this thread will help people.

having both of these result in my screeen being white after the first time of installation. please advise
