### ISSUE TITLE
Profile259 not really supported

### ISSUE THREAD

**Issue by TOuhrouche** [Redth/ZXing.Net.Mobile#352]
Thanks a million for this awesome port of ZXing! Any chance to make the latest beta build support Profile259 instead of Profile78?

**Comment by faceoffers28** [comment]
You can get it to work my manually adding all 3 DLLs as References in the Portable. You will find the DLLs in their associated folder under Packages. Once this is done, you can add the Nuget Packages to your iOS or Android Project as usual. This should work. If you are using Xamarin.Forms 2+, you will need to use the latest beta1 release of the Package for Android. I've written a detailed explanation on how to do this. I will see if I can find it.

**Comment by faceoffers28** [comment]
Please my last comment here for some more details. https://github.com/Redth/ZXing.Net.Mobile/issues/258 Hope this helps.

**Comment by TOuhrouche** [comment]
Thanks a lot for the very fast response. I actually saw the comments and the fix suggested on the other issue but I don't think it is a good idea to juggle with DLLs as this defeats the purpose of using Nuget packages.

**Comment by Redth** [comment]
This will be fixed in 2.1.0 which is due out very soon
