### ISSUE TITLE
Latency with iOS

### ISSUE THREAD

**Issue by Clowning** [Redth/ZXing.Net.Mobile#353]
Hello there,

i use Zxing for my mobile application and i have a trouble.

On my android smartphone, everything is good but when i launch the scanner on my iPhone there are lot of lag :/ ! Do you have a solution?

Thanks

**Comment by Redth** [comment]
Can you please try and quantify the lag?  How many milliseconds are we talking here, and what iPhone model are you using?

**Comment by pontino** [comment]
i solved downgrading the image resolution, passing to the `ZXing.Mobile.MobileBarcodeScanningOptions`
`CameraResolutionSelector = (li) =>
            {
                var stop = false;
                var good = new ZXing.Mobile.CameraResolution
                {
                    Width = 640,
                    Height = 480
                };
                var ordered = from it in li
                              orderby it.Width, it.Height
                              select it;
                ordered.ToList().ForEach(s =>
                {
                    if (stop) return;
                    if (s.Width > 1280)
                        stop = true;
                    else
                        good = s;
                });
                return good;
            }`
