### ISSUE TITLE
The application called an interface that was marshalled for a different thread

### ISSUE THREAD

**Issue by leo-mck** [Redth/ZXing.Net.Mobile#355]
I created a new xamarin forms project with XF 2.3.0.49 and using ZXing.Net.Mobile.Forms 2.1.0-beta1.  
 I added a ZXingScannerView on the page. On the `OnScanResult` I am trying to navigate to another page and when running on UWP I'm getting the exception:

`"The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"`

Is there a workaround this issue?

**Comment by Redth** [comment]
How are you calling the navigation?  Are you doing it from the UI thread?
