### ISSUE TITLE
Not able to add in a .forms (shared) project

### ISSUE THREAD

**Issue by FredyWenger** [Redth/ZXing.Net.Mobile#356]
Hi
I have installed the nuget ZXing.Net.Mobile.Forms 2.0.4.46 to my .forms (2.3.0.49) shared project.
Now, I have **155 errors** in the **.android project** (not able to build anymore), like. e.g.:
'Resource.Attribute' does not contain a definition for 'mediaRouteSettingsDrawable'
The errors came from **resource.designer.cs** - one example:
global::ZXing.Net.Mobile.Forms.Android.Resource.Attribute.mediaRouteSettingsDrawable = global::CSCockpit.Droid.Resource.Attribute.mediaRouteSettingsDrawable;
**What can I do...?**
Updated for the .droid project now to **2.10-beta1**.
=> The errors are gone, but I had crashes...
==> I have to investigate it more in detail.

It also works for iOS :-)

**Update:**
**I'm not able to install the nuget to the Windows Phone 8.1 project.**
**Error message:**
Could not install package 'ZXing.Net.Mobile 2.0.4.46'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
So... I now **have** contacted the package Autor ;-)
**What can I do..?
Thanks for a feedback**

**Comment by Redth** [comment]
This should be fixed in master now (will be in 2.1.0 shortly), although if you're trying to add this to a project that targets WP8.1 native (as opposed to silverlight) you'll just get a stubbed out version of the dll since WP81 native is not supported.  This should allow you to install into a PCL profile though now with that profile in it.
