### ISSUE TITLE
Xamarin.Android.Support required version blocks adding package on Xamarin.Forms Android side 

### ISSUE THREAD

**Issue by inkrh** [Redth/ZXing.Net.Mobile#359]
Having an issue using X.F in adding ZXing.Net.Mobile and ZXing.Net.Mobile.Forms on the Android side - apparently X.F. 2.3.0.107 requires a newer Xamarin.Android.Support (v23.3.0?), which the ZXing.Net.Mobile.Forms requires to be == 23.0.1.3 rather than >= 23.0.1.3, so the Xamarin.Android.Support required by the current Xamarin.Forms blocks installation?

<img width="568" alt="e7d34b4a-4379-11e6-8ce6-a069a436068c" src="https://cloud.githubusercontent.com/assets/16457014/16663468/c7b7cf02-4441-11e6-9f85-c7e464ce74e9.png">

**Comment by redwolf2** [comment]
Go here:

https://www.nuget.org

Paste "Xamarin Support" in the search box. You will be able to get the packages from there. ".nuget" packages can be opened with any zip package tool like 7zip. Inside these packages you will find the relevant .dll files for Xamarin. You can build yourself an own Version of XZing.Net.Mobile using the files from there.

You may also be able to enforce the using of the newer files using app.config settings.

Search for "app.config binding redirect"

https://msdn.microsoft.com/library/7wd6ex19(v=vs.110).aspx
https://stackoverflow.com/questions/33780101/xamarin-forms-conflicting-references

**Comment by inkrh** [comment]
Thanks - my team will work on either our own version of ZXing.net.mobile following your advice, or if that fails switch to using native barcode APIs on iOS and Android using the dependency  service.
