### ISSUE TITLE
[UWP] Hardware back button exit application

### ISSUE THREAD

**Issue by WiliamGP** [Redth/ZXing.Net.Mobile#362]
When I'm on the scanner screen and click on the back of the phone hardware button, the application is closed. Is there any solution for this? Best Regards!

**Comment by Redth** [comment]
Duplicate of #366

**Comment by F1nZeR** [comment]
@WiliamGP you need to add custom hardware back button handler in your app, for example:

```cs
SystemNavigationManager.GetForCurrentView().BackRequested += (sender, e) =>
{
   Frame rootFrame = Window.Current.Content as Frame;
   if (!e.Handled && rootFrame != null && rootFrame.CanGoBack)
   {
      e.Handled = true;
      rootFrame.GoBack();
   }
}
```

**Comment by WiliamGP** [comment]
@F1nZeR thanks, I add this code and works for me. Thank you. Best regards! :)
