### ISSUE TITLE
cannot convert from 'CoreVideo.CVPixelBufferLock' to 'CoreVideo.CVOptionFlags'

### ISSUE THREAD

**Issue by sethom** [Redth/ZXing.Net.Mobile#364]
I downloaded the latest version and attempted to build in Visual Studio and it's giving me the following error:

Argument 1: cannot convert from 'CoreVideo.CVPixelBufferLock' to 'CoreVideo.CVOptionFlags'

At file:  C:\ZXing.Net.Mobile-master\Source\ZXing.Net.Mobile.iOS\ZXingScannerView.cs

Line numbers: 555 and 568

Can someone tell me how to resolve this?

Thanks,

Sean

**Comment by Redth** [comment]
Make sure you have the latest version of Xamarin installed.

**Comment by sethom** [comment]
That was the issue, thanks Redth.
