### ISSUE TITLE
Can't scan qr code in UWP

### ISSUE THREAD

**Issue by abelgs1987** [Redth/ZXing.Net.Mobile#369]
Hello

I have downloaded the sample projects and i can't get work any sample with a QR code in UWP (desktop) application, the camera opens but there is no scan result.
Is there support for QR in UWP? 

THanks

**Comment by F1nZeR** [comment]
Hi! Can you provide QR code images?

**Comment by abelgs1987** [comment]
Hi

This is a simple qr code with a text

![qr](https://cloud.githubusercontent.com/assets/9784407/17018669/1b3f4e46-4f39-11e6-8c2c-e95378383a9c.png)

Thanks

**Comment by raget** [comment]
Do you have an internal or external camera?

**Comment by faceoffers28** [comment]
I'm having the same issue, however I can scan the QR Code @abelgs1987 posted on Jul 21. I can't scan this QR Code with my Windows 10 phone. I am using an Acer Liquid M330 as my test device, which has two 5MP cameras.

![qrcode](https://cloud.githubusercontent.com/assets/10619627/17832764/4a4d0c7e-66d0-11e6-9295-149a19634657.png)

I am using ZXing.Net.Mobile -Version 2.1.0-beta1 -Pre and ZXing.Net.Mobile.Forms -Version 2.1.0-beta1 -Pre.

I can scan the QR Code I posted with my iOS and Android apps.

Any idea what's going on? Thanks!

**Comment by faceoffers28** [comment]
It seems to me like the camera is not focusing, which is why it can't read the tighter QR Code that I posted. In fact, I just tested with my iOS and Android apps. I can see that they are focusing on the text and the QR Code. My Windows 10 device doesn't focus on the text or the QR Code.

**Comment by F1nZeR** [comment]
Hi, @faceoffers28 
Please, check latest version (2.1.44).

**Comment by faceoffers28** [comment]
@F1nZeR That worked! Thanks ever so much.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
