### ISSUE TITLE
Kindle Fire

### ISSUE THREAD

**Issue by ryanherman** [Redth/ZXing.Net.Mobile#370]
We have about 10 Kindle Fire's and the camera area comes up a dark gray.  

My code is working with all other devices, any idea whats going on?

Xamarin.Forms + ZXing Forms

**Comment by F1nZeR** [comment]
Hello! Can you try this branch https://github.com/F1nZeR/ZXing.Net.Mobile/tree/android-dark-camera ?

**Comment by Redth** [comment]
I'll fire up my Kindle fire and see if I can repro...

**Comment by ryanherman** [comment]
I have downgraded to just ZXing.Net.Mobile 1.5.4 and it works fine on the FIre.  Its strange, thank you.
