### ISSUE TITLE
stop doing beep.

### ISSUE THREAD

**Issue by retv12** [Redth/ZXing.Net.Mobile#371]
Greetings friends,

since upgrade to the latest version when scanning is successful I stop doing beep.

**Comment by ryanherman** [comment]
BEEP

**Comment by retv12** [comment]
yes BEEP

**Comment by Redth** [comment]
I am so very confused.

**Comment by retv12** [comment]
hello when scanning does not generate the beep sound

**Comment by Redth** [comment]
You will have to write the code yourself to do this. Sorry.
