### ISSUE TITLE
Barcode Scanner not working in FreshMVVM framework

### ISSUE THREAD

**Issue by KathirveluM** [Redth/ZXing.Net.Mobile#373]
Hi ,

In our Xamarin.Forms application, BarCode Scanner is not working and showing black screen. 

Note: 
**We are using FreshMVVM Framework.** 

Kindly suggest us to implement the Barcode scanner with Fresh MVVM framework. 

Thank you so much for your support. 
Best Regards,
Kathirvelu M

**Comment by Redth** [comment]
Can you post a solution with this using freshmvvm so I can further debug?

**Comment by KathirveluM** [comment]
Hi @Redth , 
Sorry , as I missed to include the Camera and Flashlight permissions for Android. 
Now its working perfectly as expected. Thanks for the support. 

Best Regards,
Kathirvelu M

**Comment by Redth** [comment]
Appreciate you circling back to close this :)
