### ISSUE TITLE
Android: how to show camera preview with aspect ratio

### ISSUE THREAD

**Issue by opcodewriter** [Redth/ZXing.Net.Mobile#378]
When using ZXingScannerFragment or even ZXingSurfaceView is it possible to have the preview use the aspect ratio?

**Comment by alexsandro-xpt** [comment]
Good question, no body?

**Comment by varun-raj** [comment]
Still nobody?

**Comment by alexsandro-xpt** [comment]
No body @varun-raj

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
