### ISSUE TITLE
Crash V 2.1.13

### ISSUE THREAD

**Issue by Wallysantos** [Redth/ZXing.Net.Mobile#379]
Guys

There is a crash when accessing component. 

Stack trace:
 at ZXing.Mobile.MobileBarcodeScanner.GetContext (Android.Content.Context context) [0x0001f] in <filename unknown>:0 
  at ZXing.Mobile.MobileBarcodeScanner.Scan (Android.Content.Context context, ZXing.Mobile.MobileBarcodeScanningOptions options) [0x00015] in <filename unknown>:0 
  at ZXing.Mobile.MobileBarcodeScanner.Scan (ZXing.Mobile.MobileBarcodeScanningOptions options) [0x00001] in <filename unknown>:0 
 ...

Implemented code is like your sample:
var scanner = new MobileBarcodeScanner();
scanner.UseCustomOverlay = false;
scanner.TopText = Resources.GetText(Resource.String.scannerTopText);
scanner.BottomText = Resources.GetText(Resource.String.scannerBottomText);
scanner.CancelButtonText = Resources.GetText(Resource.String.buttonCancel);
var options = new MobileBarcodeScanningOptions ();
options.PossibleFormats = new List<BarcodeFormat> () { 
	BarcodeFormat.EAN_8, BarcodeFormat.EAN_13, BarcodeFormat.QR_CODE
};
//Start scanning
var result = await scanner.Scan(options);// => Crash happens here!
....

It's just happening at Android version. On iOS works fine.

Best

**Comment by Redth** [comment]
Make sure you call `Initialize (..)` first:

https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Android/Sample.Android/MainActivity.cs#L28

**Comment by Wallysantos** [comment]
Hi Jonathan

Thank you for your very fast answer. In fact, this was the problem. I’m sorry for importunate you with this situation, but once I’m using this component from early versions, this line of code was new for me and I didn’t read the last update notes.

All the best

Wallace Santos
