### ISSUE TITLE
ZXing for Xamarin Forms with XAML/Mvvm

### ISSUE THREAD

**Issue by sethom** [Redth/ZXing.Net.Mobile#382]
Hi,

I haven't been able to find a sample showing how to use zxing with Xamarin.Forms using xaml views. Whenever I run the FormsSample and try to scan a barcode it scans fine. However, when I try to do the same using XAML with MVVM, it doesn't work. Are there any issues with this approach?

I built a sample app with XForms/Caliburn.Micro and ZXing. I start by creating a XAML view which is a ZXingScannerPage and then attached the OnScanResult event. I have a "DefaultOverlayViewModel" class that Caliburn.Micro loads as the DataContext to this View:

<?xml version="1.0" encoding="utf-8" ?>
<forms:ZXingScannerPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:forms="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"
             xmlns:cal="clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms"
             x:Class="Hello.Forms.Views.DefaultOverlayView" 
                        DefaultOverlayShowFlashButton="False" 
                        DefaultOverlayTopText="Hello" DefaultOverlayBottomText="Hello"
                        cal:Message.Attach="[Event OnScanResult] = [Action ProcessResult]">

/forms:ZXingScannerPage

When I run the application the Default Scanning page opens up. The torch works fine. But the "OnScanResult" event is never fired in response. (The sample apps that come with ZXing.Net.Mobile are able to scan this barcode)

So, I tried to attach the event handler in the constructor to DefaultOverlayView in the code behind file just to try that way:

this.OnScanResult += (result) =>
            {
                this.IsScanning = false;

```
            Device.BeginInvokeOnMainThread(() =>
            {
                //Navigation.PopAsync();
                DisplayAlert("Scanned Barcode", result.Text, "OK");
            });
        };
```

Still the event handler doesn't fire.

Does anyone know what might be going on here with using ZXingScannerPage as a Xaml page?

**Comment by ZobairQ** [comment]
I have the samme issue. I do also have an issue with the autofocus of the camera. However I used the ScanResultCommand but it should do the same thing. It is just not firing!

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
