### ISSUE TITLE
zxing.portable error in Windows Store (8.1) app

### ISSUE THREAD

**Issue by LynoDesu** [Redth/ZXing.Net.Mobile#383]
I have been using ZXing successfully with our Xamarin.iOS project, but I am having trouble using it with our Windows Store app (sharing the same code).

The error I'm getting is:

`Referenced assembly 'zxing.portable, Version=2.1.13.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by redwolf2** [comment]
It seems that the Windows Store enforces signed assemblys. Therefore no assembly with PublicKeyToken=null would be supported. In that case you have to build zxing.portable with the project settings "Sign Assembly". https://i.stack.imgur.com/Lbf0V.png

**Comment by LynoDesu** [comment]
Can I request the project to be signed? I would like to have ZXing.NET included as a NuGet package, rather than include the dllin my project

**Comment by redwolf2** [comment]
Only Redth, the maintainer can do that.

**Comment by LynoDesu** [comment]
Thanks @Redth for adding it to the 2.1.12 milestone! Much appreciated.
