### ISSUE TITLE
Support for new Xamarin.Forms PCL solutions that are based on WinRT

### ISSUE THREAD

**Issue by mariorasch** [Redth/ZXing.Net.Mobile#384]
Hi,

is it possible for you to provide un updated NuGet package "ZXing.Net.Mobile Barcode Scanner for Xamarin.Forms" that is compatible to new Xamarin.Forms PCL solutions that are based on WinRT (instead of Silverlight as in former Xamarin.Forms PCL solutions)?

Many thanks in advance & best regards!
Mario.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
