### ISSUE TITLE
MobileBarcodeScanningOptions.UseNativeScanning never used

### ISSUE THREAD

**Issue by fredrikhaglund** [Redth/ZXing.Net.Mobile#386]
As far as I can see property [**MobileBarcodeScanningOptions.UseNativeScanning**](https://github.com/Redth/ZXing.Net.Mobile/blob/60cf0f854d3899546c216f2305d729da2e1c43a9/Source/ZXing.Net.Mobile.Core/MobileBarcodeScanningOptions.cs#L33) is never used anywhere in the project. It should either be [marked as obsolete](https://msdn.microsoft.com/en-us/library/22kk2b44%28v=vs.90%29.aspx) or implemented.

I guess the intended use for this option was to enable **ZXingScannerPage** for the Xamarin.Forms stack to use **AVCaptureScannerView** or set the **useAVCaptureEngine** flag further down the chain?

Regardless, the documentation is unclear on how to enable iOS native AV capture engine when using Xamarin.Forms.

**Comment by alexsandro-xpt** [comment]
So, what about that?

**Comment by gmarbury** [comment]
There appears to be no way to set useAVCaptureEngine from ZXingScannerPage or  ZXingScannerView

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
