### ISSUE TITLE
problem with aztec decoding

### ISSUE THREAD

**Issue by darsoftpl** [Redth/ZXing.Net.Mobile#387]
zxing is not able to  detect aztec barcode like this:
[aztec.pdf](https://github.com/Redth/ZXing.Net.Mobile/files/393279/aztec.pdf)

**Comment by redwolf2** [comment]
Problems seem to be zxing (zxing.net in specific) related. Even the java based zxing app from the play store can't decode it. The Scandit demo app works.

**Comment by darsoftpl** [comment]
yes i know, but scandit is expensive.

**Comment by redwolf2** [comment]
You may take a look at Googles Vision API, depending on the platform you work with.

https://developers.google.com/vision/barcodes-overview

**Comment by Redth** [comment]
Eventually the plan is to make Google's Vision API an option for the scanning engine in ZXing.Net.Mobile, but that's going to take some time yet...

**Comment by micjahn** [comment]
I could successfully decode the aztec code with ZXing.Net. I used a png image which I created with the snipping tool from the PDF file.
![aztec pdf as PNG](https://cloud.githubusercontent.com/assets/3475026/18142130/7dee732a-6fbc-11e6-9ecd-db05beaaef7f.PNG)

**Comment by Redth** [comment]
This may be a case of needing to use higher resolution preview buffer which you can do by implementing the `MobileBarcodeScanningOptions.CameraResolutionSelector` delegate and choosing the resolution yourself.

**Comment by darsoftpl** [comment]
I use maximum camera resolution:
public CameraResolution GetResolution(List<CameraResolution> availableResolutions)
		{
			CameraResolution cr = availableResolutions.FirstOrDefault(c => c.Width == 1920);
			if (cr != null)
				return cr;
			
			return availableResolutions[0];
		}

**Comment by F1nZeR** [comment]
Yep, I've tried with maximum resolution too. Aztec barcode by micjahn can't be decoded (also with original ZXing app from the market), but more simple barcodes works well.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
