### ISSUE TITLE
Scan from file

### ISSUE THREAD

**Issue by kyluke** [Redth/ZXing.Net.Mobile#390]
Hey, any ideas on how to scan from a file/photo that was selected using Xam.Plugin.Media?

**Comment by Redth** [comment]
You really just need the core ZXing.Net library to do this.

Check out how I've done it in some unit tests: 
https://github.com/Redth/ZXing.Net.Mobile/blob/master/Tests/ZXing.Net.Mobile.NUnit/Test.cs#L23

**Comment by kyluke** [comment]
Hey man, doesn't work at all if you're using Xamarin forms due to the lack of System.Drawings.Bitmap. Can a byte[] from a stream of the image be passed to it? I'm trying that at the moment but I'm not getting anywhere.

**Comment by kyluke** [comment]
@Redth, any ideas on what can be done here?

**Comment by Redth** [comment]
It's definitely possible to create a luminance source based on a byte array. 

This is on my todo list, but the image format would have to be agreed to cross platform.

For now, you could use the Dependency Service pattern: https://developer.xamarin.com/guides/xamarin-forms/dependency-service/introduction/

**Comment by kyluke** [comment]
Hi @Redth,

I have moved the code over to platform specific code and am calling it using a dependency service. At the moment I am only trying to get the Android project working and instead of using System.Drawing.Bitmap, I am using Android.Graphics.Bitmap.

However, that doesn't work. I have tried converting it from Android.Graphics.Bitmap to a byte array using various different methods including using MemoryStreams and some other weird methods but with no luck. 

I keep running into

[AndroidRuntime] Caused by: android.runtime.JavaProxyThrowable: System.IndexOutOfRangeException: Index was outside the bounds of the array.
[AndroidRuntime]   at ZXing.RGBLuminanceSource.CalculateLuminanceRGB24 (System.Byte[] rgbRawBytes) <0xeeea4cc8 + 0x00070> in <filename unknown>:0

I have tried to compress the image, scale it in different ways etc but nothing has helped. Do you perhaps have any working example of how ZXing can be used in Xamarin to read a QR Code from a file? I thought this would be a common usage of the ZXing library aside from the camera but I cannot find anything useful on the web.

Any ideas on where to look from here?

Thanks Jonathan.

**Comment by kyluke** [comment]
Any ideas on this yet?

**Comment by liis00** [comment]
@kyluke Did you ever find a way to do this? I'm also running across this same problem.

**Comment by kyluke** [comment]
I don't think so, unfortunately. The requirement changed on my end. But I will check for you when I get a moment.
