### ISSUE TITLE
zxing.net.mobile.forms giving an error during build

### ISSUE THREAD

**Issue by umairali612** [Redth/ZXing.Net.Mobile#392]
I have added zxing.net.mobile and zxing.net.mobile.forms packages in my pcl project(Android and ios)
I have also added all the necessary lines but 2nd package is giving an error upon building 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'System.Void Xamarin.Forms.Element::set_AutomationId(System.String)' (defined in 'ZXing.Net.Mobile.Forms, Version=2.1.13.0, Culture=neutral, PublicKeyToken=null') from 'ZXing.Net.Mobile.Forms, Version=2.1.13.0, Culture=neutral, PublicKeyToken=null' could not be resolved. (Phoneword.Droid)

**Comment by F1nZeR** [comment]
You should update Xamarin Forms
