### ISSUE TITLE
Windows Phone 8.1 App support

### ISSUE THREAD

**Issue by hofand** [Redth/ZXing.Net.Mobile#397]
I'm trying to call the Scan method of the MobileBarcodeScanner in my Windows Phone 8.1 App but the Method throws a NotSupportedException with message "Use the platform specific implementation instead!"

What is wrong?

**Comment by Redth** [comment]
Non-silverlight windows phone 8.1 is not supported and won't ever be unless someone else does the work, since there are no managed APIs available for capturing the camera preview buffers. Given that UWP is the new way to to, efforts will be focused there instead.
