### ISSUE TITLE
XF iOS app "System.Void CoreGraphics.CGPoint::.ctor(System.Single,System.Single)"

### ISSUE THREAD

**Issue by faceoffers28** [Redth/ZXing.Net.Mobile#403]
I upgraded to version 2.1.44 for both ZXing.Net.Mobile and ZXing.Net.Mobile.Forms in my Portable Project to work with my UWP app.

I then tried to upgrade to version 2.1.44 in my iOS app and got this error.
 
Failed to resolve "System.Void CoreGraphics.CGPoint::.ctor(System.Single,System.Single)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"		

In order to fix the issue, I downgraded back to the following versions in my iOS app.

Install-Package Zxing.Net.Mobile -Version 2.0.4.46
Install-Package Zxing.Net.Mobile.Forms -Version 2.0.4.17 

My dev environment is Windows 10 Visual Studio Enterprise 2015 Update 3, Xamarin 4.0.4.4 and Xamarin.iOS 9.6.2.2. My app is a PCL Project targeting Profile 259 and running Xamarin.Forms v2.2.0.31. Is this a bug? Hope this helps.

**Comment by Redth** [comment]
Hmm, try updating to the latest stable version of Xamarin.iOS.
