### ISSUE TITLE
[Question] Additional Options for QR Code Generation.

### ISSUE THREAD

**Issue by kentliaw** [Redth/ZXing.Net.Mobile#404]
Hi Redth,

Would like to check currently does the ZXing.Net.Mobile included additional options when generating the QR code ? Do we have options like encoding, barcode size, error correction like this https://zxing.appspot.com/generator?

Also is there any limitation of length on the input text that used to generate the qr code ?

Thanks,
Kent Liaw

**Comment by Redth** [comment]
ZXing.Net.Mobile really doesn't do anything above what the core library ZXing.Net offers for generating barcodes, so best to check out the upstream project for that info: http://zxingnet.codeplex.com/

It does seem like you can pass in a `IDictionary<EncodeHintType, object> hints` parameter which depending on the barcode format you use, can suggest things like error correction.

Best thing you can do is pull down the code and have a look :)
