### ISSUE TITLE
 the red line does not move up and down When I scan，can  you resolve this？

### ISSUE THREAD

**Issue by guoleigl** [Redth/ZXing.Net.Mobile#407]

**Comment by Redth** [comment]
It's not really supposed to?

Feel free to make your own custom overlay with a red bar that moves up and down when you scan.

**Comment by guoleigl** [comment]
![20130902134540375](https://cloud.githubusercontent.com/assets/10026493/18164232/5edaf96c-7071-11e6-9402-2f1ce3b9e875.gif)
How to achieve this effect?
i alert  the ZxingOverlayView  file，but  it dos not work
