### ISSUE TITLE
Camera View Stucks on UI after capturing barcode successfully

### ISSUE THREAD

**Issue by vitthalpatil** [Redth/ZXing.Net.Mobile#408]
I am having issue in Xamarin.Forms.Android with below scenario:

I am testing and able to reproduce issue in ZXing Xamarin.Forms [sample](https://github.com/Redth/ZXing.Net.Mobile).

In Samples -> FormsSample.Droid:

I have created copy of CustomScanPage.cs and using copied page to scan barcode again after scanning successfully in first CustomScanPage.

I am not doing PopAsync with first CustomScanPage.

My issue is when I go to second CustomScanPage(say CustomScanPage1) I can see camera view is stucked to old captured barcode image. Although it captures barcode in background but UI is not updated as I can not see camera preview.

Means, Issue arises when I have already CustomScanPage in backstack.

Note: This happens in case of android only, working fine in iOS.

**This is simple scenario**: Page stucks right after you completed scan, that same stucked page is displayed on next page

**Comment by vitthalpatil** [comment]
@Redth , do you need any more info?...We are checking inside ZxingScannerView code...found some issues in Holder or SurfaceView. They are not released from memory when we ShutdownCamera. So Holder, SurfaceView is reused when camera is reused in next page.

**Comment by vitthalpatil** [comment]
I have studied inside..looks like issue is in this.Holder, it is common. May be Old View is displayed on SurfaceView due to this case.

**Comment by vitthalpatil** [comment]
I have this conclusion finally, SurfaceDestroyed event is not fired from Xanarin.Android ZXing library. It is called when Page is Poped out. (Additionaly in iOS ShutDownCamera code surface view is destroyed, which is not present in android StopScanning method.)

So, I made a workaround of removing previous page from stack and maintained it in somewhere, after scanning from next page, and going back inserted that persisted page again. So, I am just taking care that only one page which contains scanner will be there in stack.

**Comment by nurhasyim354** [comment]
Hello @vitthalpatil ,

you can try add await Task.Delay(1000) before start your own camera service.

**Comment by vitthalpatil** [comment]
We tried this already, it will not work.

**Comment by nurhasyim354** [comment]
for me it works. at least for release camera service. Before I add the delays, exception "Fail to connect to camera service" thrown when opening camera.

for graphics, try to put zxing camera view and  custom camera view at same container, in my case I put in a relative layout on base content page class and fill the container with view I want to show.

**Comment by freever** [comment]
I am having the same problem. I'd rather not have to maintain a single scan page though - hope there's a fix for this sometime.

**Comment by freever** [comment]
UPDATE: I have found a workaround which may be useful. If I instantiate the scanner and add it to Content in OnAppearing, then set Content = null OnDisappearing, then the camera image on the second scan is no longer frozen. Nulling the Content seems to trigger the necessary cleanups up the stack.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
