### ISSUE TITLE
How to release camera service 

### ISSUE THREAD

**Issue by nurhasyim354** [Redth/ZXing.Net.Mobile#410]
Hello,

Could Anyone please give some suggestion about the right way to release ZXing camera service after scanning?
Currently I put IsScanning=false at MyPage.OnDisappearing, 

When I start my own camera on other page view, I got exception "Fail to connect to camera service" while initializing the camera.

Thank you,

**Comment by minimalisticMe** [comment]
@nurhasyim354 are you using ZXing.Net.Mobile for Windows UWP/Desktop/Mobile, Android or iOS?

**Comment by nurhasyim354** [comment]
Thanks for responding,

Currently for Android.

Thanks,

**Comment by nurhasyim354** [comment]
Hello,

I realized that camera need some delay to release resources physically.
So It worked perfectly after I add Task.Delay(1000) after scan completed and than start my camera services.

Hope it useful for some one.

Thank you,
