### ISSUE TITLE
[Request] Change QR Output

### ISSUE THREAD

**Issue by minimalisticMe** [Redth/ZXing.Net.Mobile#419]
Hi,

I can create a QR Code into an image like this:

```
private WriteableBitmap getQRCode(string message)
{
    // calculate size of barcode
    int size = Convert.ToInt32(Math.Min(Window.Current.Bounds.Width, Window.Current.Bounds.Height));

    // setup barcode
    var barcodeWriter = new BarcodeWriter
    {
        Format = ZXing.BarcodeFormat.QR_CODE,
        Options = new ZXing.Common.EncodingOptions
        {
            Width = size,
            Height = size,
            Margin = 5
        }
    };

    // set barcode message
    return barcodeWriter.Write(message);
}
```

And get a nice output. Now I want to modify the output, that instead of squares my QR encoding is more **round** like in the image [here](http://goqr.me/_Resources/Persistent/c51e9cb94c6c3e953542c764bb97a0e1cf033ca3/qrcode-logo-design-starbucks.png).

**Comment by micjahn** [comment]
You have to write your own IBarcodeRenderer<WriteableBitmap> implementation. You can use it with the BarcodeWriter afterwards.

**Comment by redwolf2** [comment]
Seriously: Don't do that
I know, it is nowaday hip to include images in QR-Codes for branding. But you have to realise, that you are creating a non conform QR-Code that acts outside of the Specification. The only reason, why it works is, that QR-Codes do come with error checking und redundancy inside. When you got one working, you may find out later, that there is a Barcode Reader, that won't read your code.

**Comment by minimalisticMe** [comment]
@redwolf2 that's a good point, that one Barcode Reader might not be able to read it. Thou I was counting on the robustness of the QR Code and the error-correction when doing the shape thing.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
