### ISSUE TITLE
iOS - Default scan overlay opens on top of existing view temporarily

### ISSUE THREAD

**Issue by jfren484** [Redth/ZXing.Net.Mobile#42]
When I call .Scan() using the default overlay the scanner view slides over the top of my existing screen, and then after a second or two, the previous screen disappears and is replaced by the camera display.  The behavior should be to blank the screen first, then display the overlay (and then when the camera is ready it can replace the black screen under the overlay).

Using:
PC: VS 2012 update 2
Mac: Xamarin Studio 4.0.8, Xamarin.iOS 6.2.5
iPhone: iOS 6.1.3

**Comment by Redth** [comment]
This has been fixed since, just cleaning up this old issue.
