### ISSUE TITLE
Get Image Stream

### ISSUE THREAD

**Issue by minimalisticMe** [Redth/ZXing.Net.Mobile#420]
Hi,

I would like to get the video stream from `ZXing.Net.Mobile` for UWP.

I intend to duplicate the `stream` into two outputs. So the underlying stream can be passed through a `Gaussian Blur` Filter and the stream on top will be shown clearly as a quadratic geometry on the center of the screen (no distortion, just like a 'cut out window'). This gives the effect, that the user is scanning and focusing on the non-blurred area (in the middle of the screen) and the surrounding is blurred.

I intend to do the blurring with either the `Lumia SDK` or the new `Composition API`, which are both supposed to be very fast with video manipulation.

**Comment by redwolf2** [comment]
WPF supports a transparent Blur-Filter:
https://msdn.microsoft.com/en-us/library/ms742795(v=vs.90).aspx

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
