### ISSUE TITLE
Initialize crash on Android using Xamarin.Forms 2.3.3.152-pre-release

### ISSUE THREAD

**Issue by richardpike** [Redth/ZXing.Net.Mobile#424]
I get a crash using XForms 2.3.3 at the very start of my app on the "ZXing.Net.Mobile.Forms.Android.Platform.Init();" line.

Xamarin Insights report:

Message:
Could not load type 'ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer' from assembly 'ZXing.Net.Mobile.Forms.Android, Version=2.1.47.0, Culture=neutral, PublicKeyToken=null'.
Stack Trace:
ZXing.Net.Mobile.Forms.Android.Platform.Init()
MyAppName.Droid.MainActivity.OnCreate(Android.OS.Bundle bundle)
Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)

**Comment by richardpike** [comment]
I've created a simple project with the error:
https://www.dropbox.com/s/p4g7470g65vdiva/ZxingXForms2-3-3_test.zip?dl=0

I simply create a new project, update Xamarin.Forms to the latest pre-release, then add latest ZXing (Currently 2.1.47). Then in my android project add ZXing.Net.Mobile.Forms.Android.Platform.Init(); to the Oncreate(..)

**Comment by richardpike** [comment]
I was able to fix this for myself by downloading the source code and updating the xamarin forms package to the pre-release (2.3.3.152-pre2)

This required 2 new override functions in ZXingScannerViewRenderer.cs, and ZXingBarcodeImageViewRenderer.cs (from the ZXing.Net.Mobile.Forms.Android project). All I did was make them return null.

This builds successfully and I was able to use the resulting dll in my project without it crashing.

I would make a pull request, but I've never done one before using github...

**Comment by Darth-Alex** [comment]
@richardpike could you please post which overrides you added?
i also get this error with xamarin forms 2.3.2.127 and zxing 2.1.47

**Comment by jfversluis** [comment]
@richardpike it's not that hard to make a PR, just fork the source code to your own account, clone it, fix it, commit it and open a pull request merging your repo with the ZXing one. I would say this is a great opportunity to lean!

**Comment by richardpike** [comment]
@jfversluis You're right definitely a good opportunity to learn. I've done this now, the pull request is #438 I wouldn't be too surprised if it's not accepted into the master due to the need for a pre-release of Xamarin Forms.

@Darth-Alex I've done a pull request now so you can see the required changes. As a complete guess - you might be ok just updating the Xamarin forms to the same version you're using. (The master I forked uses 2.3.0.107). The issue might well be we were using a later version and Redth hasn't had a chance to put the update in.
If you do that you wont need the override functions I've added (in fact you'll get a compilation error if you  do).

**Comment by richardpike** [comment]
Fixed in master commit 266a348
