### ISSUE TITLE
Scanner doesn't dispose of memory used correctly.

### ISSUE THREAD

**Issue by RudolphKalp** [Redth/ZXing.Net.Mobile#425]
Hi I am using the scanner in multiple parts of my application so I created a custom scanner view to be referenced everywhere it needs to be used but the current problem is that everytime I use the scanner it consumes a lot of memory but doesn't dispose of it when I am done scanning and return to my initial page. I am using a Xamarin Forms PCL project and I have ran Performace Profile on my application multiple times and I have seen that my memory jumps with 90 to 100 MB when ever the scanner is initialized and the memory doesn't get disposed of when the scanner has disappeared.

**Comment by pauldiston** [comment]
I am also experiencing some very similar, if not the same. I am using version 2.1.47 in my application. Are there any fixes or work arounds for this?

**Comment by pauldiston** [comment]
After further investigation, the situation is helped greater by using AVCaptureSession rather than the ZXing engine, using this overload :- 
//Scan(MobileBarcodeScanningOptions options, bool useAVCaptureEngine)
scanner.Scan(options, true);

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
