### ISSUE TITLE
Is recomended do Forms call to native Page for ZXing.Net.Mobile each plataform?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Redth/ZXing.Net.Mobile#426]
I have a problem, is very hard to read large QR Codes with ZXing.Net.Mobile.Forms as mentionate in https://github.com/Redth/ZXing.Net.Mobile/issues/306

And in Android, the ZXing.Net.Mobile.Forms camara sometimes stop at continuous scanning.

So, I'm test those native samples https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/iOS/Sample.iOS and ZXing.Net.Mobile is more and more faster and fluid.

Can I make the Xamarin Forms Page calls de Native Page with ZXing.Net.Mobile and to lage back to Forms?

**Comment by alexsandro-xpt** [comment]
Somebody help me please?

I found those links https://github.com/xamarin/xamarin-forms-samples/tree/master/Forms2Native/Forms2Native.Android

https://blog.xamarin.com/customize-your-xamarin-forms-app-with-pages-for-each-platform/

But not success yet.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
