### ISSUE TITLE
Image gets rotated when the devide is rotating

### ISSUE THREAD

**Issue by noChamp** [Redth/ZXing.Net.Mobile#428]
Hi
I have downloaded and run the Android version of Forms sample app.
when I rotate the device, meaning I change the orientation from landscape to portrait, the image of the camera feed also gets rotated....
I run it on a 4.1 jelly bean Samsung s3 device.
Any way to workaround\fix this bug?
Thanks in advance
M>

**Comment by salvador-guerrero** [comment]
I'm having the same issue on a Nexus 4 running Cyanogenmod

![screenshot_20160929-115625](https://cloud.githubusercontent.com/assets/2680390/18968050/5822600c-863c-11e6-9a45-f99d28fabdfd.png)
![screenshot_20160929-115717](https://cloud.githubusercontent.com/assets/2680390/18968049/5821eabe-863c-11e6-8a10-e7372c484787.png)
![screenshot_20160929-115700](https://cloud.githubusercontent.com/assets/2680390/18968051/58250690-863c-11e6-99ff-e9a1ba67077c.png)

**Comment by hmoratopcs** [comment]
Same issue in Moto G. I applied the following workaround to prevent screen rotation:
```
// activity is the instance of MainActivity currently running
activity.RequestedOrientation = ScreenOrientation.Nosensor;
```
Remember to restore the field when after the scan to allow rotation again.

**Comment by hmoratopcs** [comment]
Fixed at master with [commit 858d1a5](https://github.com/Redth/ZXing.Net.Mobile/commit/858d1a5278054f68f1900663620803a72c4da3d6) on 2016-11-15. Tested on Moto G. Should be fixed in the next release.

**Comment by adamcogx** [comment]
Is this released yet?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
