### ISSUE TITLE
Multitouch on ZxingScannerFragment

### ISSUE THREAD

**Issue by Franczi** [Redth/ZXing.Net.Mobile#429]
Hi!
In my application i'm using your library. I'm developing in Xamarin for Android platform. 
In case when ZixingScannerFragment is on foreground, user can focus camera by tapping screen. If user tap fast enough at 2(or more) different places, error occurs. You can propagate this error by using ADB monkey test on ZxingScannerFragment. Content of error:

09-26 14:17:07.620 E/mono-rt (19636): [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: pointerIndex out of range
09-26 14:17:07.620 E/mono-rt (19636):   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
09-26 14:17:07.620 E/mono-rt (19636): java.lang.IllegalArgumentException: pointerIndex out of range
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.MotionEvent.nativeGetAxisValue(Native Method)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.MotionEvent.getX(MotionEvent.java:2074)
09-26 14:17:07.620 E/mono-rt (19636):   at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.n_onTouchEvent(Native Method)
09-26 14:17:07.620 E/mono-rt (19636):   at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.onTouchEvent(ZXingSurfaceView.java:61)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.View.dispatchTouchEvent(View.java:9300)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
09-26 14:17:07.620 E/mono-rt (19636):   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
09-26 14:17:07.620 E/mono-rt (19636):   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
09-26 14:17:07.620 E/mono-rt (19636):   at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
09-26 14:17:07.620 E/mono-rt (19636):   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.View.dispatchPointerEvent(View.java:9520)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
09-26 14:17:07.620 E/mono-rt (19636):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-26 14:17:07.620 E/mono-rt (19636):   at android.os.MessageQueue.nativePollOnce(Native Method)
09-26 14:17:07.620 E/mono-rt (19636):   at android.os.MessageQueue.next(MessageQueue.java:323)
09-26 14:17:07.620 E/mono-rt (19636):   at android.os.Looper.loop(Looper.java:135)
09-26 14:17:07.620 E/mono-rt (19636):   at android.app.ActivityThread.main(ActivityThread.java:5422)
09-26 14:17:07.620 E/mono-rt (19636):   at java.lang.reflect.Method.invoke(Native Method)
09-26 14:17:07.620 E/mono-rt (19636):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-26 14:17:07.620 E/mono-rt (19636):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-26 14:17:07.620 E/mono-rt (19636): 

Thanks in advance
Bartosz

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
