### ISSUE TITLE
integrating this crashes my test android app

### ISSUE THREAD

**Issue by alindzon** [Redth/ZXing.Net.Mobile#431]
i am trying to use the azure/xamarin todo list app (mobile quickstart on azure) as a testbed. I am trying to add this in, and as soon as I try any of the sample code to scan my app crashes.

I am using the mobile quickstart because it integrates with azure, sql etc... so it shortcuts a number of issues I would have to figure out on my first azure app.  now I am just trying to figure out how to add a quick scan ability to see how I can work it into my app.

**Comment by Redth** [comment]
Please include a stack trace
