### ISSUE TITLE
getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by PaulARoy** [Redth/ZXing.Net.Mobile#433]
Hi !

Some of my users are experiencing a crash, the stacktrace gives me:

```
Java.Interop.JniEnvironmentgetParameters failed (empty parameters)

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args)
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
Android.Hardware.Camera.GetParameters()
ZXing.Mobile.ZXingSurfaceView.AutoFocus(int x, int y, bool useCoordinates)
ZXing.Mobile.ZXingSurfaceView.AutoFocus(int x, int y)
ZXing.Mobile.ZXingSurfaceView.OnTouchEvent(MotionEvent e)
Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_(IntPtr jnienv, IntPtr native__this, IntPtr native_e)
at (wrapper dynamic-method) System.Object:d69639e9-7fa4-4d3d-b9f6-409629ad6230 (intptr,intptr,intptr)
--- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: getParameters failed (empty parameters)
android.hardware.Camera.native_getParameters(Native Method)
at android.hardware.Camera.getParameters(Camera.java:3078)
md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.n_onTouchEvent(Native Method)
at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.onTouchEvent(ZXingSurfaceView.java:53)
at android.view.View.dispatchTouchEvent(View.java:9415)
…
```

It seems to crash on this line of Autofocus https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Android/ZXingSurfaceView.cs#L396

which is not embedded in the try catch.

Has anyone experienced this before?

**Comment by alexsandro-xpt** [comment]
I was problem call Autofocus in OnCreate method, change call it before and after Scan method doning some thing like this `this.RunOnUiThread(() => ff.AutoFocus());`

The error is gonne, but Autofocus keeping not working..

**Comment by wireless-r** [comment]
Having this too. It comes after navigating to/from the page with the scanner view a few times. Full stack trace: https://hastebin.com/ulequfucim.sql

**Comment by bensafeag** [comment]
I have the same case as @wireless-r. 
Can scan QR codes sucessfully, but (randomly/inconsistently) after the first scan, I encounter the following exception. `Java.Lang.RuntimeException: getParameters failed (empty parameters)`

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
