### ISSUE TITLE
OFF: What is the scanner engine QR Droid Code Scanner app use?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Redth/ZXing.Net.Mobile#435]
I'm looking for performatic scanner engine for large QR Codes and ai can I the QR Droid ( https://play.google.com/store/apps/details?id=la.droid.qr&hl=pt_BR ) is more efficient.

How can I know a really good scanner?

Thanks

**Comment by Redth** [comment]
This isn't really a place to ask that question.  If you have specific questions about ZXing.Net.Mobile then please open an issue for them.
