### ISSUE TITLE
Barcode Scanning Code misreading

### ISSUE THREAD

**Issue by thfaix** [Redth/ZXing.Net.Mobile#436]
I have made a forms App which use zxing.mobile.forms and I have experienced an error with the barcode scanning of the code 39 barcodes.
The barcode I should read begin with this characters : %WBA...
When I scan the barcode with a ZxingScannerView the scanned barcode result is this one : LBA...
The result is the same on both platforms.
I tried with other scanners on the google play store (including zxing on) and apple store and this is the right code which is read.
If someone have a solution it would be grateful.
Thanks

**Comment by F1nZeR** [comment]
Can you share barcode?

**Comment by thfaix** [comment]
Yes for sure 
![barcode](https://cloud.githubusercontent.com/assets/17575835/19211093/db693680-8d34-11e6-9411-9a76740a4eab.PNG)

**Comment by thfaix** [comment]
Any news?

**Comment by F1nZeR** [comment]
@micjahn any ideas? tested on latest zxing.net sources even with enabled UseCode39ExtendedMode

**Comment by F1nZeR** [comment]
@thfaix new option will be available soon for your case.
By default it tries to use full ASCII character set so %W decodes to L.
You need to set `UseCode39ExtendedMode = false` in `MobileBarcodeScanningOptions` to prevent this behavior.

**Comment by thfaix** [comment]
Thanks a lot! I can not wait to see it work like I want. 👍

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
