### ISSUE TITLE
Outdated nuget packages for UWP

### ISSUE THREAD

**Issue by nuwannnz** [Redth/ZXing.Net.Mobile#437]
I installed the latest Zxing.Net.Mobile nuget package for my UWP app. Version is 2.1.47 . Everything works fine but the camera doesn't detect any barcode / QR code . I downloaded the latest sample project from github and that sample worked perfectly. So I copied the assemblies from that sample project to my project. Now everything works fine but when I start scanning , scan page throws an XAML parse exception.  

The assemblies of nuget package are from 8/24/2016, and of sample project they are 10/6/2016

any work around?

**Comment by limefrogyank** [comment]
I'm seeing the same or related issue.  Using the latest Nuget package, I can get the camera to run in UWP, however, on *desktop*, OnScanResult is never called.  However, on UWP phone, the same code works fine.

(FYI, on desktop, I'm using one of the Microsoft HD Lifecams.... so the resolution is fine.)

**Comment by nuwannnz** [comment]
Yeah, works perfectly on the phone. But doesn't work on the desktop.

**Comment by niwrA** [comment]
I'm seeing something that could be related. I have a really good auto-focus 1080p webcam on one desktop. On the laptop right next to it, I have a much cheaper built-in webcam without autofocus. This last one can in fact even with it's pretty bad camera feed detect some barcodes. But the 1080p HD webcam doesn't detect anything.

Using the UWP built-in barcode detection however gives me the exact opposite. The 1080p HD webcam works great, super fast detection, but doesn't work at all on the laptop. 

Extremely frustrating.

**Comment by tmm360** [comment]
I've found that linking projects from source instead of nuget versions it works also on desktop. #480

**Comment by nuwannnz** [comment]
Yeah, but that's not convenient though.

**Comment by tmm360** [comment]
In the meantime is better than nothing :)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
