### ISSUE TITLE
Barcode Component crash the App os iOS 10.0

### ISSUE THREAD

**Issue by mvegaca** [Redth/ZXing.Net.Mobile#439]
I was using your component on iOS 9.3 and all works fine. When I target the application to new iOS 10.0, and I open the barcode reader, my App Crash unsespectedly. Could you review that? Thank you a lot.

**Comment by Vandersteen** [comment]
I'm having the same issue.

Sadly I cannot give you error logs as none are to be found (strangly)

Was working on 9.3

On 10 it instantly crashes

**Comment by Vandersteen** [comment]
https://github.com/Redth/ZXing.Net.Mobile/issues/421 solved it for me

**Comment by catchappapp** [comment]
I have a scenario where it works on iPhone 6 but crashes on iPhone 5

**Comment by thfaix** [comment]
have you tried to had this to your info.plist ?:
<key>NSCameraUsageDescription</key>
	<string>The app need to access the camera</string>

**Comment by mvegaca** [comment]
Solved for me updating info.plist

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
