### ISSUE TITLE
PDF417 Drivers License Scanning

### ISSUE THREAD

**Issue by adamhockemeyer** [Redth/ZXing.Net.Mobile#440]
I've tried scanning several drivers license PDF417 bar codes and cannot seem to get ZXing to scan them.  I downloaded and tried the Scandit SDK and it recognizes and scans the drivers license PDF417 bar code right away.

I am able to scan simple PDF417 bar codes found on the internet, but drivers license won't scan unfortunately.

**Comment by redwolf2** [comment]
Please post a picture of an unreadable code.

**Comment by hock2k5** [comment]
Here is an example ID I found online.  I compared to the MicroBlink BlinkID SDK trial and it scans this instantly, but the ZXing unfortunately won't scan this (set to PDF417).

https://idscanner.files.wordpress.com/2010/11/georgia_new_back-scaled1000.jpg

Hope this helps.

**Comment by micjahn** [comment]
I tried it with the Windows Forms Demo application of ZXing.Net. Works like a charme.

**Comment by hock2k5** [comment]
I just tried again with no avail.

Device is an iPhone 7 iOS 10.

**Comment by adamhockemeyer** [comment]
I did not, I ended up using the BlinkID sdk.

**Comment by joeseggie** [comment]
Guess I should look at another option. Thank you @adamhockemeyer

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
