### ISSUE TITLE
Cannot focus - Galaxy Note 6

### ISSUE THREAD

**Issue by Thx1137** [Redth/ZXing.Net.Mobile#443]
Hi,

Tapping on the screen when a barcode is visible causes it to focus for a fraction of a second then it goes to blurry again. 

The only way I can get it to work is if I focus on something a couple of inches away that is not a barcode (using the screen tap method) then scan the code. I don't think there is a way to do manual focus is there?

The much older version I was using seemed to work better in this aspect. I can't remember the version unfortunately.

**Comment by maurizioceravolo** [comment]
I tries on a P9 and a G3 and I have big problem. The focus doesn't work.

**Comment by alexsandro-xpt** [comment]
Not working for me on Moto E on 2 Generation

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
