### ISSUE TITLE
Nougat rotation can't open camera

### ISSUE THREAD

**Issue by brepetti** [Redth/ZXing.Net.Mobile#444]
When I build using the Nougat SDK I am noticing an issue when rotating.  The camera launches perfectly fine in any orientation.  But when you rotate it the camera goes to a black screen.  If you rotate back the camera returns.  I do not see this issue when building against Marshmallow.

Here is the stack trace when rotating:
`10-17 16:18:50.768 D/dalvikvm(21686): GC_FOR_ALLOC freed 0K, 12% free 12416K/14020K, paused 39ms, total 39ms
10-17 16:18:50.803 D/dalvikvm(21686): GC_CONCURRENT freed 1013K, 19% free 11405K/14020K, paused 10ms+2ms, total 35ms
Releasing Exclusive access to camera
10-17 16:18:50.818 I/mono-stdout(21686): Releasing Exclusive access to camera
Releasing Exclusive access to camera
10-17 16:18:50.818 I/mono-stdout(21686): Releasing Exclusive access to camera
10-17 16:18:50.853 W/dalvikvm(21686): No implementation found for native Ldalvik/system/VMRuntime;.pauseGc:(Ljava/lang/String;)I
10-17 16:18:50.858 E/ActivityThread(21686): Pause GC
10-17 16:18:50.858 E/ActivityThread(21686): java.lang.reflect.InvocationTargetException
10-17 16:18:50.858 E/ActivityThread(21686):     at java.lang.reflect.Method.invokeNative(Native Method)
10-17 16:18:50.858 E/ActivityThread(21686):     at java.lang.reflect.Method.invoke(Method.java:515)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.pauseGC(ActivityThread.java:5525)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.access$1000(ActivityThread.java:175)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.os.Looper.loop(Looper.java:146)
10-17 16:18:50.858 E/ActivityThread(21686):     at android.app.ActivityThread.main(ActivityThread.java:5602)
10-17 16:18:50.858 E/ActivityThread(21686):     at java.lang.reflect.Method.invokeNative(Native Method)
10-17 16:18:50.858 E/ActivityThread(21686):     at java.lang.reflect.Method.invoke(Method.java:515)
10-17 16:18:50.858 E/ActivityThread(21686):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-17 16:18:50.858 E/ActivityThread(21686):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-17 16:18:50.858 E/ActivityThread(21686):     at dalvik.system.NativeStart.main(Native Method)
10-17 16:18:50.858 E/ActivityThread(21686): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: dalvik.system.VMRuntime.pauseGc:(Ljava/lang/String;)I
10-17 16:18:50.858 E/ActivityThread(21686):     at dalvik.system.VMRuntime.pauseGc(Native Method)
10-17 16:18:50.858 E/ActivityThread(21686):     ... 16 more
10-17 16:18:50.883 D/ZXing.Net.Mobile(21686): ZXingScannerFragment->OnResume exit
10-17 16:18:50.883 D/ZXing.Net.Mobile(21686): ZXingScannerFragment->OnResume exit
StartScanning
Getting Camera Exclusive access
Got Camera Exclusive access
Releasing Exclusive access to camera
10-17 16:18:50.963 I/mono-stdout(21686): StartScanning
10-17 16:18:50.963 D/ZXing.Net.Mobile(21686): Checking android.permission.CAMERA...
10-17 16:18:50.963 I/mono-stdout(21686): Getting Camera Exclusive access
10-17 16:18:50.963 I/mono-stdout(21686): Got Camera Exclusive access
10-17 16:18:50.963 D/ZXing.Net.Mobile(21686): Checking Number of cameras...
10-17 16:18:50.963 D/ZXing.Net.Mobile(21686): Found 2 cameras...
10-17 16:18:50.963 D/ZXing.Net.Mobile(21686): Found Back Camera, opening...
10-17 16:18:50.968 W/CameraBase(21686): An error occurred while connecting to camera: 0
10-17 16:18:50.968 I/mono-stdout(21686): Releasing Exclusive access to camera
Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
10-17 16:18:51.008 I/mono-stdout(21686): Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
10-17 16:18:51.008 I/mono-stdout(21686):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
10-17 16:18:51.008 I/mono-stdout(21686):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
10-17 16:18:51.008 I/mono-stdout(21686):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
  at Android.Hardware.Camera.Open (System.Int32 cameraId) [0x00017] in /Users/builder/data/lanes/3819/96c7ba6c/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Hardwar
e.Camera.cs:4480 
  at ZXing.Mobile.ZXingSurfaceView.OnSurfaceCreated () [0x00122] in <d2ded791291e4d068726d4015ae32fb0>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Fail to connect to camera service
10-17 16:18:51.008 I/mono-stdout(21686):   at Android.Hardware.Camera.Open (System.Int32 cameraId) [0x00017] in /Users/builder/data/lanes/3819/96c7ba6c/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Hardware.Camera.cs:4480 
10-17 16:18:51.008 I/mono-stdout(21686):   at ZXing.Mobile.ZXingSurfaceView.OnSurfaceCreated () [0x00122] in <d2ded791291e4d068726d4015ae32fb0>:0 
10-17 16:18:51.013 I/mono-stdout(21686):   --- End of managed Java.Lang.RuntimeException stack trace ---
10-17 16:18:51.013 I/mono-stdout(21686): java.lang.RuntimeException: Fail to connect to camera service
10-17 16:18:51.013 I/mono-stdout(21686):    at android.hardware.Camera.native_setup(Native Method)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.hardware.Camera.<init>(Camera.java:423)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.hardware.Camera.open(Camera.java:375)
    at android.hardware.Camera.native_setup(Native Method)
    at android.hardware.Camera.<init>(Camera.java:423)
    at android.hardware.Camera.open(Camera.java:375)
    at md59737f11dc56b77608850b1f688b15dc2.ZXingSurfaceView.n_surfaceCreated(Native Method)
    at md59737f11dc56b77608850b1f688b15dc2.ZXingSurfaceView.surfaceCreated(ZXingSurfaceView.java:77)
    at android.view.SurfaceView.updateWindow(SurfaceView.java:602)
    at android.view.SurfaceView.access$000(SurfaceView.java:94)
    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:183)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:888)
10-17 16:18:51.013 I/mono-stdout(21686):    at md59737f11dc56b77608850b1f688b15dc2.ZXingSurfaceView.n_surfaceCreated(Native Method)
10-17 16:18:51.013 I/mono-stdout(21686):    at md59737f11dc56b77608850b1f688b15dc2.ZXingSurfaceView.surfaceCreated(ZXingSurfaceView.java:77)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.SurfaceView.updateWindow(SurfaceView.java:602)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.SurfaceView.access$000(SurfaceView.java:94)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:183)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:888)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2199)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2199)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
    at android.view.Choreographer.doCallbacks(Choreographer.java:614)
    at android.view.Choreographer.doFrame(Choreographer.java:584)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.Choreographer.doCallbacks(Choreographer.java:614)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.Choreographer.doFrame(Choreographer.java:584)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.os.Handler.handleCallback(Handler.java:733)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.os.Looper.loop(Looper.java:146)
10-17 16:18:51.013 I/mono-stdout(21686):    at android.app.ActivityThread.main(ActivityThread.java:5602)
10-17 16:18:51.013 I/mono-stdout(21686):    at java.lang.reflect.Method.invokeNative(Native Method)
10-17 16:18:51.013 I/mono-stdout(21686):    at java.lang.reflect.Method.invoke(Method.java:515)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5602)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
10-17 16:18:51.013 I/mono-stdout(21686):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-17 16:18:51.013 I/mono-stdout(21686):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-17 16:18:51.013 I/mono-stdout(21686):    at dalvik.system.NativeStart.main(Native Method)
10-17 16:18:51.018 E/ViewRootImpl(21686): sendUserActionEvent() mView == null
10-17 16:18:52.548 W/dalvikvm(21686): No implementation found for native Ldalvik/system/VMRuntime;.pauseGc:(Ljava/lang/String;)I
10-17 16:18:52.548 E/ActivityThread(21686): Pause GC
10-17 16:18:52.548 E/ActivityThread(21686): java.lang.reflect.InvocationTargetException
10-17 16:18:52.548 E/ActivityThread(21686):     at java.lang.reflect.Method.invokeNative(Native Method)
10-17 16:18:52.548 E/ActivityThread(21686):     at java.lang.reflect.Method.invoke(Method.java:515)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.pauseGC(ActivityThread.java:5525)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.access$1000(ActivityThread.java:175)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.os.Looper.loop(Looper.java:146)
10-17 16:18:52.548 E/ActivityThread(21686):     at android.app.ActivityThread.main(ActivityThread.java:5602)
10-17 16:18:52.548 E/ActivityThread(21686):     at java.lang.reflect.Method.invokeNative(Native Method)
10-17 16:18:52.548 E/ActivityThread(21686):     at java.lang.reflect.Method.invoke(Method.java:515)
10-17 16:18:52.548 E/ActivityThread(21686):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-17 16:18:52.548 E/ActivityThread(21686):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-17 16:18:52.548 E/ActivityThread(21686):     at dalvik.system.NativeStart.main(Native Method)
10-17 16:18:52.548 E/ActivityThread(21686): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: dalvik.system.VMRuntime.pauseGc:(Ljava/lang/String;)I
10-17 16:18:52.548 E/ActivityThread(21686):     at dalvik.system.VMRuntime.pauseGc(Native Method)
10-17 16:18:52.548 E/ActivityThread(21686):     ... 16 more
10-17 16:18:52.578 D/ZXing.Net.Mobile(21686): ZXingScannerFragment->OnResume exit`

**Comment by brepetti** [comment]
It looks like this goes out to more than just Nougat.  I'm seeing this on older devices now.

I was able to trace the issue back to ShutdownCamera in the ZXingSurfaceView

I removed the Task Factory wrapper and the issue was resolved.  My camera now shows on every rotation.  There is a slight delay but that is better than no camera at all.

**Comment by gustaveracosta** [comment]
I am having the same issue

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
