### ISSUE TITLE
Windows Phone 8.1 library missing

### ISSUE THREAD

**Issue by DottorPagliaccius** [Redth/ZXing.Net.Mobile#445]
I added this line

ZXing.Net.Mobile.Forms.WindowsPhone.ZXingScannerViewRenderer.Init();

in my wp 8.1 project, but it's missing from the last release (2.1.47)

_The type or namespace name 'WindowsPhone' does not exist in the namespace 'ZXing.Net.Mobile.Forms'_

**Comment by Redth** [comment]
Is this a Windows Phone 8.1 Silverlight application, or Native?  ZXing.Net.Mobile does not support Windows Phone 8.1 Native, only Silverlight.

**Comment by DottorPagliaccius** [comment]
And, of course, is Native. The project was added when I created the Xamarin.Forms project, I assumed it would work. So, I can't use ZXing.Net in a Native Windows Phone app?

**Comment by Redth** [comment]
You'll have to use either  WP Silverlight or a UWP project to use ZXing.Net.Mobile with Xamarin.Forms.  Basically, the managed API's necessary for getting camera preview buffer data were removed in WP8.1 Native for some weird reason.  So unfortunately, WP8.1 Native is not supported, and will never be.

**Comment by DottorPagliaccius** [comment]
Crystal clear. Thank you.
