### ISSUE TITLE
Device roration lock

### ISSUE THREAD

**Issue by mvegaca** [Redth/ZXing.Net.Mobile#446]
Hi!

I'm using your Nuget in my App. I'am having a problem with rotation with you component.
I'm managing device rotation overwriting ShouldAuthorotate method on IOs ViewControler, but when the application delegate the control to QR Reader component, if user rotate the phone and finish code reading on landscape, the Applications come back on landscape.

Is there any way to specify the component that it should not autorotate?

Thank you a lot and sorry for my english.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
