### ISSUE TITLE
Android Camera Zoom or Distance feature

### ISSUE THREAD

**Issue by alexsandro-xpt** [Redth/ZXing.Net.Mobile#447]
I propose this feature because in large QR Code, we have to put the device too much near of QR Code causing a lot of shadows and making scanning impossible.

I make a lot of tests in ZXing Android, with `MobileBarcodeScanner` and `ZXingScannerFragment` implementation.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
