### ISSUE TITLE
Zxing.Net.Mobile.WindowsUniversal AutoFocus crash

### ISSUE THREAD

**Issue by fabriziogueli** [Redth/ZXing.Net.Mobile#449]
Library version: 2.1.45

I want to report a random crash when i start the scan on my tablet (Alcatel 8085) with Windows 10.
The app freezes with a white screen with a red line in the middle and then the app crashes 4-5 seconds after the freeze.

Sometimes the library works as expected, but occasionally it crashes.

In the logs i can see:

AutoFocus requested
Exception thrown: 'System.Runtime.InteropServices.COMException' in ZXingNetMobile.dll
WinRT information: This object needs to be initialized before the requested operation can be carried out.
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll
WinRT information: This object needs to be initialized before the requested operation can be carried out.

**Comment by farlop** [comment]
+1

**Comment by bkaankose** [comment]
I experienced this issue today. It occurs when users tap on the page instantly to focus specific are before the scanner control even initialize the camera.

I will fix the issue and send a PR if no one's interested in fixing.
