### ISSUE TITLE
Navigation.PopAsync() problem on iOS 10 

### ISSUE THREAD

**Issue by schiari** [Redth/ZXing.Net.Mobile#451]
I'm using iOS 10 and I have implemented this library with the following code:

`MyAppLib.MyAppUtilitiesBarCodeReader MyBarCodeReader = new MyAppLib.MyAppUtilitiesBarCodeReader();  
var MyScannerPage = MyBarCodeReader.GetBarCodeReaderPage();

MyScannerPage.OnScanResult += (result) => {
//Stop scanning
MyScannerPage.IsScanning = false;
//Pop the page and show the result
Device.BeginInvokeOnMainThread(() => {
        Navigation.PopAsync();
        MyMachSerialNumber.Text = result.Text;
        });
};

//Display scanner
await Navigation.PushAsync(MyScannerPage);
`

On Android it's working fine, on iOS 10 after reading a barcode it goes back inside the function "OnScanResult" and execute the command Navigation.PopAsync(); which close the scanning page but after a second it closes also the current page where I have displayed the result!
It looks like it execute the Navigation.PopAsync() twice...

Please help..
Thank you

**Comment by techxperiment** [comment]
Have you tried using await Navigation.PopAsync(); ?

**Comment by techxperiment** [comment]
I see similar isssue on Ipad Mini iOS 9.3.5

**Comment by schiari** [comment]
@techxperiment did you find a solution? 
Just find out if I start the app the first time it's working fine, but if I try to scan a second time a bar code then I got this problem. If I close the app and remove it from the memory on my iPhone and start again from fresh, it's working the first time but again from the second scanning always closes the camera page and the page from where I call the camera

**Comment by Mika571** [comment]
I am also experiencing this on iOS but not Android for forms.

**Comment by Mika571** [comment]
I had this same problem but added in a member variable to keep track of when we have stopped scanning.
e.g.
```
public CustomScanPage() : base()
        {
            finishedScan = false;
            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingScannerView",
            };
            zxing.OnScanResult += (result) =>
                Device.BeginInvokeOnMainThread(async () => {

                    // Navigate away
                    if (!finishedScan)
                    {
                        // Stop analysis until we navigate away so we don't keep reading barcodes
                        zxing.IsAnalyzing = false;
                        await Navigation.PopAsync();
                        ScanComplete(result.Text);
                        finishedScan = true;
                    }
                });    
          ...
}
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
