### ISSUE TITLE
Exception with ZXing for Xamarin Forms

### ISSUE THREAD

**Issue by SvenCarstensen** [Redth/ZXing.Net.Mobile#452]
Hi,

when i stop scanning with IsScanning = false and then restart it with IsScanning = true, then the following exception will occur:

[ZXING] SetupCamera failed: System.AggregateException: One or more errors occurred. ---> Java.Lang.RuntimeException: startPreview failed
[ZXING]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[ZXING]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue\* args) [0x000a7] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
[ZXING]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue\* parameters) [0x00022] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:41 
[ZXING]   at Android.Hardware.Camera.StartPreview () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Hardware.Camera.cs:4700 
[ZXING]   at ZXing.Mobile.ZXingSurfaceView+<SetupCamera>d__26.MoveNext () [0x007e1] in <04a6c4a6536f4e76a10998845fe4c337>:0 
[ZXING]    --- End of inner exception stack trace ---
[ZXING] ---> (Inner Exception #0) Java.Lang.RuntimeException: startPreview failed
[ZXING]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[ZXING]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue\* args) [0x000a7] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
[ZXING]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue\* parameters) [0x00022] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:41 
[ZXING]   at Android.Hardware.Camera.StartPreview () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Hardware.Camera.cs:4700 
[ZXING]   at ZXing.Mobile.ZXingSurfaceView+<SetupCamera>d__26.MoveNext () [0x007e1] in <04a6c4a6536f4e76a10998845fe4c337>:0 
[ZXING]   --- End of managed Java.Lang.RuntimeException stack trace ---
[ZXING] java.lang.RuntimeException: startPreview failed
[ZXING]     at android.hardware.Camera.startPreview(Native Method)
[ZXING]     at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
[ZXING]     at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
[ZXING]     at android.view.View.performClick(View.java:5697)
[ZXING]     at android.widget.TextView.performClick(TextView.java:10826)
[ZXING]     at android.view.View$PerformClick.run(View.java:22526)
[ZXING]     at android.os.Handler.handleCallback(Handler.java:739)
[ZXING]     at android.os.Handler.dispatchMessage(Handler.java:95)
[ZXING]     at android.os.Looper.loop(Looper.java:158)
[ZXING]     at android.app.ActivityThread.main(ActivityThread.java:7225)
[ZXING]     at java.lang.reflect.Method.invoke(Native Method)
[ZXING]     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ZXING]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[ZXING] <---

Any hints?

Regards

Sven

**Comment by horacehylee** [comment]
Same issue, any fixes?

**Comment by dhompanera** [comment]
Same issue. I tested it on several devices and it happens only in Samsung devices.

**Comment by sbwaggoner** [comment]
Any progress on this? Causing a lot of hassle in my app.

**Comment by LGFox** [comment]
@dhompanera, I get this behavior on Samsung Galaxy S7 (android 6.0.1) as well. BUT it works on Samsung Galaxy S7 with android 7.0. Also it works on Xiaomi Redmi Note 2 (android 5.0). And now the most interesting point: this tutorial [app](https://developer.xamarin.com/recipes/android/other_ux/camera_intent/take_a_picture_and_save_using_camera_app/) from Xamarin do the same! It works everywhere except Samsung Galaxy S7 with android 6.0.1. Maybe a problem is between Samsung firmware and Xamarin... I'll continue to investigate this problem.

**Comment by LGFox** [comment]
@dhompanera Well, seems like the problem in my phone. Even native camera app doesn't work on my S7. I closed the ticket on Xamarin Android.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
