### ISSUE TITLE
ZXingScannerView not found...

### ISSUE THREAD

**Issue by CartBlanche** [Redth/ZXing.Net.Mobile#453]
Even though the Forms example creates the Grid and ZXingScannerView  in code, I wanted to embed both in the Xaml as per below...

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
        x:Class="GreenvaleBooks.CustomScanPage"
        xmlns:local="clr-namespace:ZXing.Net.Mobile.Forms">
    <ContentPage.Content>
        <Grid VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <local:ZXingScannerView 
                    x:Name="zxing"
                    VerticalOptions="FillAndExpand" 
                    HorizontalOptions="FillAndExpand" />
            <local:ZXingDefaultOverlay 
                    x:Name="overlay" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

Builds fine, but at runtime it is unable to find the `ZXingScannerView` class when `InitializeComponents()` is called. Have I overlooked something?

Thanks.

**Comment by chinkan** [comment]
I have same issue, i have added this namespace

`xmlns:zxing="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"`

and just only add this

`<zxing:ZXingScannerView>
</zxing:ZXingScannerView>`

still said ZXingScannerView not found

**Comment by chinkan** [comment]
Oh I found I had missing to add 

`ZXing.Net.Mobile.Forms.iOS.Platform.Init();`

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by CartBlanche** [comment]
I can't even remember why I needed this back in 2016😀. I better dig out my old projects.
