### ISSUE TITLE
Upgrade from 2.0.4.24 to 2.1.47 makes scanning QR Code less reliable

### ISSUE THREAD

**Issue by pauldiston** [Redth/ZXing.Net.Mobile#455]
Running on Windows Phone 8.0 Silverlight.

I found an issue in 2.0.4.24 where calling the Scan method of the MobileBarcodeScanner does not return from the await if the back button is pressed, so I upgraded to 2.1.47 however when scanning QR codes, if scanned in quick succession (i.e. before the scanner preview has fully had a chance to fire up) the return from calling Scan returns null.

Is there a way to improve the reliability of the scanner to what it was in version 2.0.4.24? I have tried the following which doesn't seem to help :-

`var options = MobileBarcodeScanningOptions.Default;

options.PureBarcode = true;
options.TryHarder = true;
options.InitialDelayBeforeAnalyzingFrames = 5000;
options.DelayBetweenAnalyzingFrames = 1000;

var result = await scanner.Scan(options);`

**Comment by redwolf2** [comment]
My guess is, that the problem is camera related. A camera is a single resource and can only be operated by one instance, unless it is build upon a complex service model. If the camera is closed, it may take some time in order to close and open the camera. You should use ContinuousScanning and keep the dialog open to achieve rapid scans.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
