### ISSUE TITLE
Preview not showing the second time ZXingScannerPage is navigated to

### ISSUE THREAD

**Issue by pauldiston** [Redth/ZXing.Net.Mobile#456]
I have downloaded the sample and run it on WP 8.0 and I press the Scan with Default Overlay button, the preview is shown and a barcode can be scanned. I then press the button again to scan another barcode however the preview is now black/blank however the barcode is still scanned.

Is there any resetting that needs to occur after the first run to enable the preview to be shown?

**Comment by pauldiston** [comment]
I have found that if the call to PopAsync is replaced with a call to PopToRootAsync then the preview can be see the second time.

**Comment by Mr-Pearce** [comment]
I have the same problem.
I also noticed that that if i navigate from an page to another the previous scanview turns gray while navigating to the second.

**Comment by mmiller1234** [comment]
PopToRootAsync did not work for me. I changed to a ModalAsync push and scanning 2 or more times worked as expected.

**Comment by davidbuckleyni** [comment]
Hi  I am haivng same issue of getting scan to work twice I am comming from a popup window button

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
