### ISSUE TITLE
How to change the scanner window and remove red line

### ISSUE THREAD

**Issue by bwwilliam** [Redth/ZXing.Net.Mobile#457]
I added the QR code scan to my first android app which is great. 
But, does any one know how to remove the redline in the middle, and make the scan window a square shape. 
My app is scanning QR code only , no bar codes. So, the rectangle shape window does not really look right. 
I would like to achieve something like this 
http://img.blog.csdn.net/20130902134540375?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQveGlhYW5taW5n/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast
Thank you.

**Comment by F1nZeR** [comment]
https://github.com/Redth/ZXing.Net.Mobile#custom-overlays

**Comment by patricoos** [comment]
`  var redLine = overlay.Children.First(x => x.BackgroundColor == new Color(1, 0, 0, 1));
            overlay.Children.Remove(redLine);`

**Comment by patricoos** [comment]
`var redLine = overlay.Children.First(x => x.BackgroundColor == Color.Red);
            overlay.Children.Remove(redLine);`

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
