### ISSUE TITLE
Initialize ZXing does not work in iOS and WindowsPhone

### ISSUE THREAD

**Issue by diegoflowers** [Redth/ZXing.Net.Mobile#458]
I developed a mobile application to scan QRCode in C # using Xamarin Forms.

I have issues starting MobileBarCodeScanning iOS and WindowsPhone.

I am using [this guide][1] as an example

The main code is in PCL, as I understand, must initialize the MobileBarCodeScanning on each platform. Android worked perfectly. I added the following line of code in MainActivity.cs:

    ZXing.Net.Mobile.Forms.Android.Platform.Init();

The guide also has a WindowsPhone and iOS example, which are located inside AppDelegate.cs and MainPage.xaml.cs:

    ZXing.Net.Mobile.Forms.iOS.Platform.Init();
    ZXing.Net.Mobile.Forms.WindowsPhone.ZXingScannerViewRenderer.Init();

But it does not work in iOS and shows no error, the application closes when I try to start the camera. WindowsPhone does not find it in ZXing.Net.Mobile.Forms, it gives the following error: 

> The type or namespace WindowsPhone does not exist in the namespace 'ZXing.Net.Mobile.Forms' (are you missing and assembly reference?)

On Android I had to add the permission to use the camera in Manifest.xml, I did not found anything like this for the other platforms.

I also found another way to boot via Android with the following line of code:

    ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);

It worked perfectly, but the other platforms gave error again. I've already try to uninstall and install all packages again.

Could help me with this case?

  [1]: https://github.com/Redth/ZXing.Net.Mobile

**Comment by redwolf2** [comment]
Try out the samples https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples to see how the reference implementation of initialization works.

**Comment by diegoflowers** [comment]
@redwolf2 Thanks for your answer, but i try and did not work...

In WindowsPhone i found this code in MainPage.cs on Sample:

`scanner = new MobileBarcodeScanner(this.Dispatcher);
            scanner.Dispatcher = this.Dispatcher;`

In my code gives the following error:

> 'MobileBarcodeScanner' does not contains a constructor that takes 1 arguments.

Sorry, also I forgot to warn you that my application is WindowsPhone 8.1. Is there a difference in the implementation?

**Comment by redwolf2** [comment]
Maybe use use the wrong platform Dlls
Goto https://github.com/Redth/ZXing.Net.Mobile/releases
Download the latest package for example ZXing.Net.Mobile.2.1.45.nupkg
Open it with a zip program. 
Inside you find lib\portable-net45%2Bnetcore45%2Bwpa81%2Bwp8\
Thats the files you want. Link them to your project.

**Comment by diegoflowers** [comment]
I tried and gave the same problem ..

> 'MobileBarcodeScanner' does not contains a constructor that takes 1 arguments.

I had previously installed the latest version of the package by Nuget.

**Comment by Virviil** [comment]
The same - ZXing.Net.Mobile.Forms.WindowsPhone is missing:
![untitled](https://cloud.githubusercontent.com/assets/3989623/20497377/f9a93302-b039-11e6-8870-27adfec8e852.png)

**Comment by vahidshahvar** [comment]
In ios you shoud add "Privacy - Camera Usage Description" in info.plist

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
