### ISSUE TITLE
EAN2 and EAN5 support

### ISSUE THREAD

**Issue by joseprl89** [Redth/ZXing.Net.Mobile#460]
# Goal

Need to be able to scan EAN2 and EAN5 barcodes.

# Why its not currently working

MobileBarcodeScanningOptions does not set the AllowedEANExtensions hint, thus the EAN2 and EAN5 barcodes are never read.

# How to fix

Modify MobileBarcodeScanningOptions to take an extra parameter to set the AllowedEANExtensions property instead of blocking consumers from using.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
