### ISSUE TITLE
Build Error after installing it

### ISSUE THREAD

**Issue by stesvis** [Redth/ZXing.Net.Mobile#463]
Hi, after installing the component I can't build my solution anymore. This is the error:
<pre>
Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/Xamarin.iOS/v1.0/Facades/System.Private.CoreLib.InteropServices.dll
</pre>

What am I missing? Thanks!

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
