### ISSUE TITLE
Broken on latest release of Windows 10 Mobile

### ISSUE THREAD

**Issue by sorCrer** [Redth/ZXing.Net.Mobile#464]
This no longer works after an update to Windows 10 Mobile. 10.0.14393.448

Released 09 November 2016

**Comment by faceoffers28** [comment]
What's broken? Can you provide a stack trace or any additional details?  

I have a Xamarin.Forms app. I have it working on version 1607 build 10.0.14393.67. I am using ZXing.Net.Mobile -Version 2.1.44 and ZXing.Net.Mobile.Forms -Version 2.1.44. What version of the packages are you running? Thanks!

**Comment by sorCrer** [comment]
That's the odd part. We don't get an exception it just shows a white screen when launching the scanner. This has worked for weeks until the Windows Mobile update last week. We will confirm our Windows version.

**Comment by sorCrer** [comment]
We're on Windows Mobile build 10.0.14393.448 and ZXing 2.1.44:

We're doing the following:

`public MainPage()
        {
 
            InitializeComponent();
 
            ZXingScannerViewRenderer.Init();
 
            LoadApplication(new Application());
        }
 
The initialization of the scannerview in the forms project
 
        public ScanVehiclePage()
        {
 
            _scannerView = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                Options = new ZXing.Mobile.MobileBarcodeScanningOptions
                {
                    PossibleFormats = new List<BarcodeFormat>
                    {
                        BarcodeFormat.QR_CODE
                    }
                },
                IsEnabled = true,
 
            };
 
            _scannerView.OnScanResult += OnScan;
 
            _overlay = new ZXingDefaultOverlay
            {
                TopText = "Hold your phone up to the barcode",
                BottomText = "Scanning will happen automatically",
                ShowFlashButton = _scannerView.HasTorch,
 
            };
 
            _overlay.FlashButtonClicked += (sender, e) =>
            {
                _scannerView.IsTorchOn = !_scannerView.IsTorchOn;
            };
 
            var grid = new Grid()
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };
            grid.Children.Add(_scannerView);
            grid.Children.Add(_overlay);
 
            _scannerView.IsScanning = true;
            _scannerView.IsAnalyzing = true;
 
            Content = grid;
 
            ScanComplete = delegate
            {
                Debug.WriteLine("Scan complete");
            };
 
            this.BindingContext = _overlay;
        }
`
![wp_ss_20161116_0001](https://cloud.githubusercontent.com/assets/5485008/20345893/e063a4d6-ac01-11e6-8283-63d13403047d.png)

**Comment by faceoffers28** [comment]
Take a look at this and see if that helps. https://github.com/Redth/ZXing.Net.Mobile/issues/409 You didn't include this in the code samples you provided, so I'm guessing this could be an issue. I'm not sure if it is the issue, though.

**Comment by sorCrer** [comment]
Thanks. This helped somewhat except we also had to include:

   `typeof(ZXingScannerViewRenderer).GetTypeInfo().Assembly,`
