### ISSUE TITLE
Problem with ZXing on iOS 10.1 (Xamarin)

### ISSUE THREAD

**Issue by Cyber1000** [Redth/ZXing.Net.Mobile#465]
Hi,

We are having some troubles with ZXIng on IOs 10.1.
On scanning we are getting this (we are using xamarin) while it crashes:

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

Here is a fix (at the end of the thread - in code of zxing - ZXingscannerview.cs), but I don't understand why this could fix the problem. Do you have a better fix? Is this a known problem?
https://forums.xamarin.com/discussion/77721/zxingscannerview-does-not-work-anymore-in-ios-10?

Thanks,
Cyber1000

**Comment by L4rS6** [comment]
Add this to your `Info.plist` file:
<key>NSCameraUsageDescription</key>
<string>Allow access to camera</string>

It worked for me on iOS 10.1.1

**Comment by jamespettigrew** [comment]
[This appears to be due to a bug in iOS 10 itself.
](https://forums.developer.apple.com/thread/62230)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
