### ISSUE TITLE
android version keep scanning but with no result on KitKat(19) & Marshmallow(23) version 

### ISSUE THREAD

**Issue by pofpof42** [Redth/ZXing.Net.Mobile#467]
Hi 

I have some problem with the lib , I succeed to compile and deploy some sample but the app never succeed to scan any barcode and keep trying, I tried many manipulation of different phone (both samsung 1 recent (23) 1 older (19))
and seems I forgot to do something 
it seems focus is not working but despite that I succeed to recognize some picture when I use the native zxing library 

would you please let me know which kind of option I can try ? or if I should share more details ? 

on some different note on several phone I noticed the front camera seems have a better native focus than the main one , any reason or is it just that autofocus function is not working on back camera? 

I was reusing the sample on https://github.com/Redth/ZXing.Net.Mobile, I use following library (downloaded from nuget) in VS2015 community
- xamarin support v4 : v23.0.1.3
- Zxing net mobile : v2.1.47
my compilation settings are the following :+1: 
- Compile android version (latest Android 7.0 Nougat)
- Minimum Android to target : 4.1 Nougat
- Target android Version : Compile using SDK version
I also recompiled directly the library with more recent version of V4 Lib (23.4.0) but with same result.

[MainActivity.txt](https://github.com/Redth/ZXing.Net.Mobile/files/595176/MainActivity.txt)

**Comment by pofpof42** [comment]
Hi 

it seems I did find a fix by recompiling the lib from sources and using 
TryHarder
TryInverted
AutoRotate
TryInverted
And specific EAN_13 format

furthermore , and I think this did really change result a compilation in ad-Hoc (no debug) seems to be the only way to get result

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
