### ISSUE TITLE
Uwp problem with long code-39 barcodes

### ISSUE THREAD

**Issue by fabriziogueli** [Redth/ZXing.Net.Mobile#468]
Library version: 2.1.45

Hi, i'm not able to scan for a particular code-39 barcode : 
https://s4.postimg.org/nvv8o6eot/barcode.jpg

A couple of times i was able to scan this barcode, but the process was extremely slow.

I'm using a tablet (Alcatel 8085) with Windows 10. 

Could someone  scan this barcode using the library?

**Comment by redwolf2** [comment]
Just a general note: For 1D codes the code type Code 128 is the best for most cases. It is more compact and will produce better results. The only reason to use Code39 is that it can be created using a font.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
