### ISSUE TITLE
Slow camera view within tabs

### ISSUE THREAD

**Issue by bwwilliam** [Redth/ZXing.Net.Mobile#469]
I came cross a problem. My app has 3 tabs, and the scanner view is inside one of the tabs. When swipe between the tabs, the camera tab (i.e. scanning tab) is slower than other two tabs to render. 
After googling many places, finally find this one
http://stackoverflow.com/questions/28183017/viewpager-swiping-lags-when-fragment-contains-camera-preview

I went and checked the source code, ZXingSurfaceView class does inherits from "public class ZXingSurfaceView : **SurfaceView**". Is there way you can please change it to TextureView? 
Thank you. 
William

**Comment by hmoratopcs** [comment]
Work in progress. See pulll request #459

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
