### ISSUE TITLE
Android ScanContinuously OnBackPressed not working

### ISSUE THREAD

**Issue by luanpablo-luizalabs** [Redth/ZXing.Net.Mobile#471]
Hello,

I'm trying to to scan continuously some barcodes, and when I attempt to return to my last activity (the one that calls `.ScanContinuously`) using the back button (which I believe it was to be the `Keycode.Back`).

The screen does nothing for a while and suddenly it becomes entirely black, when I keep pressing it, sometimes it crashes the app or returns to the camera (sometimes without my CustomOverlay)

In the activity I call the .ScanContinuously, I override the `OnBackPressed()` method, isn't the case of adding it to the ZxingActivity calling the `.Cancel()`?

Thanks a lot, this is an awesome and helpful lib.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
