### ISSUE TITLE
UWP, camera not stretched when on phone

### ISSUE THREAD

**Issue by Pebin** [Redth/ZXing.Net.Mobile#472]
Hi, I have weird black panels on the left and right side. Here are screenshots of what I mean

this is the app running by default

![wp_ss_20161121_0001 1](https://cloud.githubusercontent.com/assets/8281747/20515736/5d643c94-b093-11e6-9670-021a0168e4f7.png)

this screenshots when I hide the control buttons at bottom, but the panels are still there, just smaller

![wp_ss_20161122_0003 1](https://cloud.githubusercontent.com/assets/8281747/20515743/6ca02dee-b093-11e6-8681-28b8f37eca70.png)

here when i move the top bar down. The bottom bar will disappear so it will stretch a bit, but you can see that there are still the black panels on each side

![wp_ss_20161122_0002 1](https://cloud.githubusercontent.com/assets/8281747/20515858/c695c0e8-b093-11e6-8dae-e2dd634a9913.png)

when I run it on desktop, then there are no black panels and the orange corners are correctly centered (except on top because of the logo, which is fine). 

I noticed that when I hide the statusbar and the bottom control panel, the black panels disappear completely. But in the system camera, the bottom panel is open and there are no black panels. So it's not a system thing?

I am testing it on Lumia 640, thanks

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
