### ISSUE TITLE
Camera not released in Forms when the screen is locked

### ISSUE THREAD

**Issue by hmoratopcs** [Redth/ZXing.Net.Mobile#473]
If the screen is locked while scanning, the camera is not released. It's even possible to capture barcodes with the screen off. This causes fast battery draining.

Tested with FormsSample.Droid ([latest master version](https://github.com/Redth/ZXing.Net.Mobile/tree/0dc587690f1b88194ed5ae49e61a61aae74e6a75)) on Moto G.

The camera is released if the app is sent to background because ZXingSurfaceView.SurfaceDestroyed is called, but it's not called when the screen is locked or off. It's is also released in Sample.Android because ZXingScannerFragment.OnStop is called.

**Comment by hmoratopcs** [comment]
It seems that the Sample App has never shut down the camera on screen lock. It can be achieved changing MainActivity to inherit from FormsAppCompatActivity, because in that case ZXingScannerPage.OnDisappearing is called on screen lock. However, after [commit 8d83f66 (Merged refactoring of Android Camera / surface)](https://github.com/Redth/ZXing.Net.Mobile/commit/8d83f6638ce163e1d52cb557d301ae80f7054070) the camera is not restarted when the screen is unlocked.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
