### ISSUE TITLE
ZXingScannerFragment slow performance in tabs

### ISSUE THREAD

**Issue by bwwilliam** [Redth/ZXing.Net.Mobile#474]
My app has three tabs, and one of the tabs is the QR code scanner. All the tab headers remains at the top. 
The problem is that when I swipe between the tabs, each tab has its own fragment, it is slow to render the QR Scanner tab. 
I am using a framelayout which is replaced by ZXingScannerFragment for the scanner tab.
Is this the right way or right component to do it? 

Does anyone know any similar kind of app setup in Github? 

Thank you very much.

**Comment by dave2ma** [comment]
Is someone else dealing with this? Serious problem.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
