### ISSUE TITLE
Datamatrix is not working

### ISSUE THREAD

**Issue by Spelt** [Redth/ZXing.Net.Mobile#476]
Hi

It looks like Datamatrix is only working when the barcode is in the center of the image (not usable sort of speak).  This picture will not work. 
![image](https://cloud.githubusercontent.com/assets/12660181/20642675/5076bd10-b415-11e6-940f-b95d1814d6ac.png)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
