### ISSUE TITLE
ZXing.Net.Mobile.Forms doesn't work from nuget on UWP

### ISSUE THREAD

**Issue by tmm360** [Redth/ZXing.Net.Mobile#480]
I've a project with Xamarin.Forms, and I'm installing ZXing.Net.Mobile.Forms from nuget, v2.1.47.
It works under Android, but doesn't scan qrcodes on UWP. So I've tried to debug this.

I've downloaded the sample, and it works. After a lot of tests I've tried to remove libraries from nuget and added references to downloaded projects, the same used on the sample, and it works.

To reproduce this, try to remove all internal project references of `ZXing.Net.Mobile*` from `FormsSample` and `FormsSample.WindowsUniversal`, and add to these the nuget version of ZXing.Net.Mobile.Forms, and run `FormsSample.WindowsUniversal`. It will execute, but will not read any QRcode. I've not tried with other barcode types.

Edit: I'm running tests on desktop

**Comment by faceoffers28** [comment]
Take a look at this and see if that helps. You didn't reference this in your explanation, so I'm guessing this could be an issue. I'm not sure if it is the issue, though. Perhaps you are missing one of the assemblies. https://github.com/Redth/ZXing.Net.Mobile/issues/409

**Comment by tmm360** [comment]
Thank you, but I'm running in debug mode.

**Comment by midwan** [comment]
I can confirm this problem, not only with ZXing.Mobile.Forms but also with the current ZXing.Mobile nuget package.

Can't you update the nuget packages with the latest sources please?

**Comment by pbauwens** [comment]
Same here, bummer. Camera comes up but doesn't recognize any barcode.

**Comment by tmm360** [comment]
Solved by last release

**Comment by pradipshakya** [comment]
Hi All,

Any one can help please?

I am getting below error after adding NuGet packages "ZXing.Net.Mobile.Forms"

Severity	Code	Description	Project	File	Line	Suppression State
Error	Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ZXingNetMobile, Version=2.4.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'ZXingNetMobile.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver) QRCodeReader.Android

**Comment by pradipshakya** [comment]
Thanks for reply, I have fixed this issue by using old NuGet packages for Zing.Net.Mobile.Forms.
