### ISSUE TITLE
camera session not closed for MasterDetailPages  (UWP)

### ISSUE THREAD

**Issue by BenKenobi32** [Redth/ZXing.Net.Mobile#484]
I'm using Xamarin.Forms and I push and pop the Scanpage on top of an hierarchical navigation stack
in order to fill a texfield with the result.
But when I wrap a MasterDetailPages around that View , then the camera session won't finish correctly onScanResult (the camera's record light is still on) .

Example: I've added the following button to the Detailspage of
https://developer.xamarin.com/samples/xamarin-forms/Navigation/MasterDetailPage/
and tested it for UWP.

```
scanButton.Clicked += (sender, e) => {
                var scanPage = new ZXingScannerPage();
                scanPage.OnScanResult += (result) =>
                {
                    scanPage.IsScanning = false;
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        // do stuff with the result
                        Navigation.PopAsync();
                    });
                };
                this.Navigation.PushAsync(scanPage);
            };


```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
