### ISSUE TITLE
Not recognized Barcode on Transportation Container Seal

### ISSUE THREAD

**Issue by ericbrunner** [Redth/ZXing.Net.Mobile#487]
Hi ,

The barcode scanning works with very clean barcodes like: [that](http://arjunu.com/2015/08/android-barcode-detection-tracking-using-mobile-vision-api/) but I have to use it in transportation for container
seals and here it **does not work**!

I attached a screenshot. Please provide any help if I can setup some additional options to get it working.

My Code Setup:
Xamarin.Forms PCL with Android / iOS projects (all latest Xamarin SDK , all latest ZXing.Net.Mobile.Forms SDK)

thanks,
Eric
![not_recognized_barcode_on_seal](https://cloud.githubusercontent.com/assets/6480047/21263804/1093806e-c399-11e6-8022-1b8963af1ab6.png)

**Comment by F1nZeR** [comment]
Autofocus doesn't work in your case. There is a fix in master branch so it will be available in the next release.

**Comment by ericbrunner** [comment]
@F1nZeR Hi, Thanks for your reply. I missed to mention it only those not work on my "old" HTC 510 Desire Android phone (API LEVEL 19). On my "old" iPhone 4S OS 9.3.5 it works after a few seconds of trying to rotate my hardware seal. Here is my current code setting:

        private async void ScannerButtonOnClicked(object sender, EventArgs e)
        {
            //setup options
            var options = new MobileBarcodeScanningOptions
            {
                AutoRotate = false,
                TryHarder = true
            };

            //add options and customize page
            var scanPage = new ZXingScannerPage(options)
            {
                DefaultOverlayTopText = await LanguageMapper.Instance.GetTextAsync(LanguageMapping.TagScannerTop),
                DefaultOverlayBottomText = await LanguageMapper.Instance.GetTextAsync(LanguageMapping.TagScannerBottom),
                DefaultOverlayShowFlashButton = true
            };

            scanPage.OnScanResult += (result) =>
            {
                // Stop scanning
                scanPage.IsScanning = false;

                // Pop the page and show the result
                Device.BeginInvokeOnMainThread(() =>
                {
                    Navigation.PopAsync();
                    DisplayAlert("Scanned Barcode", result.Text, "OK");
                });
            };

            // Navigate to our scanner page
            await Navigation.PushAsync(scanPage);
        }


I currently try the `TryHarder = true` option setting. Can that fix my problem currently or do I have currently other options as a workaround?

Thanks in advance
Eric

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
