### ISSUE TITLE
Camera disposing problem

### ISSUE THREAD

**Issue by Franczi** [Redth/ZXing.Net.Mobile#488]
Hello,
My Xamarin Insights reported me about some problems with disposing Camera. This bug is affecting android version(5.0 and M). Sadly i cannot popagete this bug, i have only stack trace. 
I know that it isnt a lot of information but, i hope u will solve this.

Errors data:
http://pastebin.com/7mD0L9aw
http://pastebin.com/kJ0AtdPh

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
