### ISSUE TITLE
Possibility to select the FPS range on Android

### ISSUE THREAD

**Issue by fblockel** [Redth/ZXing.Net.Mobile#492]
Hi,
On XCover 3 devices, the FPS range that is selected by the current algorithm is 7.000 to 7.000 (available ranges are 7.000 to 7.000, 15.000 to 15.000, 15.000 to 30.000 and 30.000 to 30.000).
Could you please add a new delegate in the scanning options (like the one to select the resolution) to be able to override this algorithm ?
Thanks for your feedback and for the great work so far !

**Comment by Poketchu** [comment]
Oh wow.

Just bumped on this issue too. Same phone and I didn't expected this to be set in the plugins code.
Thanks for the hint @fblockel and yeah... a delegate to allow control over FPS should totally be added to the plugin. If the scanner falls under performance requirements this could add another parameter to manage performance.

Thanks anyway.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
