### ISSUE TITLE
Crash UWP when change orientation during scan

### ISSUE THREAD

**Issue by danieldotnet** [Redth/ZXing.Net.Mobile#493]
When I change while scanning the orientation from portarit to landscape, the app crash. UWP App (Win10). 
My Code:
`Dim scanner As MobileBarcodeScanner
            Dim optionen = New MobileBarcodeScanningOptions

            scanner = New MobileBarcodeScanner(Dispatcher)
            scanner.Dispatcher = Dispatcher

            optionen.PossibleFormats = New List(Of ZXing.BarcodeFormat) From {ZXing.BarcodeFormat.All_1D}
            'optionen.TryHarder = True
            optionen.AutoRotate = True

            'Tell our scanner to use the default overlay
            scanner.UseCustomOverlay = False

            'We can customize the top and bottom text of our default overlay
            scanner.TopText = "Hold camera up to barcode and tap on screen for focus"
            scanner.BottomText = "Press the 'Back' button to Cancel"
            scanner.AutoFocus()
            scanner.CameraUnsupportedMessage = "Camera not supported."

            Dim result = Await scanner.Scan(options:=optionen)
            If result IsNot Nothing Then

                txtSearchBarcode.Text = result.Text
                Call Number()

            End If`

**Comment by Adrianotiger** [comment]
This is the exception message I get from the debugger:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.ButtonRenderer.<>c__DisplayClass9_0.<UpdateContent>b__0(Object sender, RoutedEventArgs args)

The only workaround I found is to lock the orientation of the device.

**Comment by fenntunne** [comment]
We have submitted a pull to fix this issue. Pull #478 fixes this. Stil waiting for the final commit

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
