### ISSUE TITLE
Unable to decode from gallery image (null result)

### ISSUE THREAD

**Issue by Fralkayg** [Redth/ZXing.Net.Mobile#495]
I recently created a new project on Xamarin Forms PCL using this library. Im able to scan any code without problem, but another functionality that i need is to decode an image from the dispositive gallery, im retrieving the image in a byte[] (100% sure that the image is correct and obviously is a QR image that im able to scan). This is my code:

           //returns byte[] from image
           var image = await Task.Run(() => mediaController.BrowseGallery());
            if (image != null)
            {
                Bitmap bitmap = BitmapFactory.DecodeByteArray(image, 0, image.Length);
                var bin = new HybridBinarizer(new RGBLuminanceSource(image, bitmap.Width, bitmap.Height));
                var i = new BinaryBitmap(bin);
                var reader = new MultiFormatReader();
                var hints = new Dictionary<DecodeHintType, object>();
                hints.Add(DecodeHintType.PURE_BARCODE, "TRUE");
                hints.Add(DecodeHintType.POSSIBLE_FORMATS, new List<BarcodeFormat>() { BarcodeFormat.QR_CODE });                 
                reader.Hints = hints;
                var result = reader.decode(i, hints);

I have tested in so many ways but still cant figure why this isnt working.
I was following this unit test https://github.com/Redth/ZXing.Net.Mobile/blob/master/Tests/ZXing.Net.Mobile.NUnit/Test.cs

**Comment by redwolf2** [comment]
Try out `PlanarYUVLuminanceSource` instead of `RGBLuminanceSource`. Also make sure you receive a ARGB888 byte array. you need your byte array like { r, g, b, r, g, b, r, g, b ... }. It may contain an unessessary alpha component like { r, g, b, a, r, g, b, a, r, g, b, a ... } or worse, be 16-Bit and compressed to two bytes for all three r, g, b values ranging from 0 to 127.

**Comment by Fralkayg** [comment]
I did another test using an API (sending the byte array of the image in data.image class)


           Bitmap bmp;
            using (MemoryStream ms = new MemoryStream(data.image))
            {
                bmp = new Bitmap(ms);
            }
            using (bmp)
            {
                IBarcodeReader reader = new BarcodeReader();
                var result = reader.Decode(bmp);
                if (result != null)
                {
                    data.imageName = result.Text;
                }
            }

This way im able to decode correctly the image, getting the string that i expect from the QR Code image. Tried to do the same on my app but reader.decode doesnt have a overcharge that takes a bitmap as parameter.
Tried to apply what you told me, but i dont know how to see the format of my array.

**Comment by redwolf2** [comment]
`System.Drawing.Bitmap` != `Android.Graphics.Bitmap`. Images are mostly platform specific, therefore ZXing.Net is not relieant on them.

Have a look at the byte array. If the image is 640x480, the resulting byte array length have to be 640 * 480 * 3 = 921600 bytes

**Comment by Fralkayg** [comment]
Im using a 400x400 image, the byte array length is 21.246, not even close to 400x400x(something)

**Comment by redwolf2** [comment]
There is your problem. A 400x400 pixel image should have a bytes length of 480000, when passed to RGBLuminanceSource. 
My suggestion is, that you get the compressed image bytes in png or jpg format. 400 * 400 / 7 = 22857. Maybe your image is a "[binary image](https://en.wikipedia.org/wiki/Binary_image)". Thus it only consists of black and white pixel. A compression might be applied, shrinking it further down. 

You need to do something like this:

```
Bitmap image =  BitmapFactory.DecodeStream(Resources.OpenRawResource(Resource.Raw.test));
byte[] rgbBytes = GetRgbBytes(image);

private static byte[] GetRgbBytes(Bitmap image)
{
	var pixels = new List<int>();
	for (int y = 0; y < image.Height; y++)
		for (int x = 0; x < image.Width; x++)
			pixels.Add(image.GetPixel(x, y));
	var rgbBytes = new List<byte>();
	foreach (int pixel in pixels)
	{
		var c = new Color(pixel);
		rgbBytes.AddRange(new []{ c.R, c.G, c.B });
	}
	return rgbBytes.ToArray();
}
```

Here is the sample code

https://mega.nz/#!65EBEDaC

There might be a build in feature to do this in Android though.

**Comment by mjspk** [comment]
any code for ios side please

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by ognamala** [comment]
> There is your problem. A 400x400 pixel image should have a bytes length of 480000, when passed to RGBLuminanceSource. My suggestion is, that you get the compressed image bytes in png or jpg format. 400 * 400 / 7 = 22857. Maybe your image is a "[binary image](https://en.wikipedia.org/wiki/Binary_image)". Thus it only consists of black and white pixel. A compression might be applied, shrinking it further down.
> 
> You need to do something like this:
> 
> ```
> Bitmap image = BitmapFactory.DecodeStream(Resources.OpenRawResource(Resource.Raw.test));
> byte[] rgbBytes = GetRgbBytes(image);
> 
> private static byte[] GetRgbBytes(Bitmap image)
> {
> 	var rgbBytes = new List<byte>();
> 	for (int y = 0; y < image.Height; y++)
> 	{
> 		for (int x = 0; x < image.Width; x++)
> 		{
> 			var c = new Color(image.GetPixel(x, y))
> 			rgbBytes.AddRange(new []{ c.R, c.G, c.B });
> 		}
> 	}
> 	return rgbBytes.ToArray();
> }
> ```
> 
> So in your Code you need to do this:
> 
> ```
>        //returns byte[] from image
>        var image = await Task.Run(() => mediaController.BrowseGallery());
>         if (image != null)
>         {
>             Bitmap bitmap = BitmapFactory.DecodeByteArray(image, 0, image.Length);
>             byte[] rgbBytes = GetRgbBytes(bitmap);
>             var bin = new HybridBinarizer(new RGBLuminanceSource(rgbBytes, bitmap.Width, bitmap.Height));
>             var i = new BinaryBitmap(bin);
>             var reader = new MultiFormatReader();
>             var hints = new Dictionary<DecodeHintType, object>();
>             hints.Add(DecodeHintType.PURE_BARCODE, "TRUE");
>             hints.Add(DecodeHintType.POSSIBLE_FORMATS, new List<BarcodeFormat>() { BarcodeFormat.QR_CODE });                 
>             reader.Hints = hints;
>             var result = reader.decode(i, hints);
> ```
> 
> Here is the sample code
> 
> https://mega.nz/#!65EBEDaC
> 
> There might be a faster build in feature to do this in Android though, like Bitmap.GetBuffer().

Good evening, the sample code doesn’t seem to be available anymore - could you kindly re-upload? I am currently facing this issue on iOS and really need help on how to address this issue - would really appreciate. Thanks

**Comment by nchrisr** [comment]
@ognamala Check this out github.com/Redth/ZXing.Net.Mobile/issues/981 Let me know if that helps
