### ISSUE TITLE
Camera freezes on last scanned image

### ISSUE THREAD

**Issue by zzm388** [Redth/ZXing.Net.Mobile#496]
I am using the library to scan barcode badges in a xamarin forms project.
When a badge is successfully scanned, a new view is pushed showing details about the scanned barcode.
The user can either store the scanned barcode, or ignore it and continue scanning in either case.
But when the information view is poped from the stack, the camera view keeps displaying the last scanned image and does not return to live view.
I have tested this on android api version 23.
Can anyone point to the right direction?

This is the code:

_namespace xScan
{
    public class ScanPage : ContentPage
    {
        ZXingScannerView zxing;
        ZXingDefaultOverlay overlay;
        public ScanPage() : base()
        {
            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand
            };
            zxing.OnScanResult += (result) =>
                Device.BeginInvokeOnMainThread(async () => {
                    zxing.IsScanning = false;
                    GlobalValue.CurrentScan = result.Text;
                    await Navigation.PushAsync(new VisitorPage());
                });
            TimeSpan ts = new TimeSpan(0, 0, 0, 3, 0);
            Device.StartTimer(ts, () => {
                if (zxing.IsScanning) zxing.AutoFocus();
                return true;
            });
            overlay = new ZXingDefaultOverlay
            {
                ShowFlashButton = zxing.HasTorch,
            };
            overlay.FlashButtonClicked += (sender, e) => {
                zxing.IsTorchOn = !zxing.IsTorchOn;
            };
            var grid = new Grid
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };
            grid.Children.Add(zxing);
            grid.Children.Add(overlay);
            Content = grid;
            NavigationPage.SetHasNavigationBar(this, false);
        }
        protected override void OnAppearing()
        {
            base.OnAppearing();
            zxing.IsScanning = true;
            zxing.IsAnalyzing = true;
        }
        protected override void OnDisappearing()
        {
            zxing.IsAnalyzing = false;
            zxing.IsScanning = false;
            base.OnDisappearing();
        }
    }
}_

**Comment by BluePAZ** [comment]
Here's a workaround, take all the code from the constructor and put it in a function (named "reload" or something) and in your OnAppearing call it. Yes there is double work the first time it gets loaded (since it will load twice and momentary double memory before the gc comes around) But I consider that relatively minimal in the grand scheme.

**Comment by VakaGopi** [comment]
I am also getting same problem,  will you help me.....?

**Comment by seth35us** [comment]
Another option is to put this code in your OnAppearing()

var contentHolder = Content;
Content = null;
Content = contentHolder;

**Comment by CybAnkit** [comment]
Hello There,
I'm facing the same issue however i have used in xamarin forms and use the renderer in native android and ios. I'm facing issue with Android only. I'm uses below code reference for renderer.
https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Forms.Android/ZXingScannerViewRenderer.cs

Can anyone help me to resolve this issue?

**Comment by hxibrahim** [comment]
If anyone still has this problem, here is the answer 
[https://stackoverflow.com/questions/41382512/can-zxing-be-stopped-or-dispose-so-i-can-use-it-again/45116422#45116422](https://stackoverflow.com/questions/41382512/can-zxing-be-stopped-or-dispose-so-i-can-use-it-again/45116422#45116422).

It works if you write the OnAppearing() and OnDisappearing() methods in the same way as stated in the accepted answer.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
