### ISSUE TITLE
Android init ScannerViewRenderer

### ISSUE THREAD

**Issue by devneutz** [Redth/ZXing.Net.Mobile#498]
After installing the latest version of ZXing.Net.Mobile into my Xamarin.Forms project (v 2.3.3.180) I get the following error trying to initialize Xamarin.Forms.

`System.TypeLoadException: Could not load type ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer while decoding custom attribute: (null)`

at

```
protected override void OnCreate(Bundle savedInstanceState)
{
       base.OnCreate(savedInstanceState);
       Xamarin.Forms.Forms.Init(this, savedInstanceState);
       ZXing.Net.Mobile.Forms.Android.Platform.Init();
       Log.Debug(TAG, "SplashActivity.OnCreate");  
}
```

**Comment by trisco2001** [comment]
@devneutz I am seeing this issue as well. Were you able to resolve or work around it in any way?

**Comment by devneutz** [comment]
@trisco2001 Indeed I was. The error occurs only if you use the sample code like this:

```
var scanPage = new ZXingScannerPage ();

scanPage.OnScanResult += (result) => {
    // Stop scanning
    scanPage.IsScanning = false;

    // Pop the page and show the result
    Device.BeginInvokeOnMainThread (() => {
        Navigation.PopAsync ();        
        DisplayAlert("Scanned Barcode", result.Text, "OK");
    });
};

// Navigate to our scanner page
await Navigation.PushAsync (scanPage);

```
I was able to get it working by creating a custom ScannerPage:

```
 public CustomScanPage () : base ()
        {
            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand
            };
            zxing.OnScanResult += (result) => 
                Device.BeginInvokeOnMainThread (async () => {

                    // Stop analysis until we navigate away so we don't keep reading barcodes
                    zxing.IsAnalyzing = false;

                    // Show an alert
                    await DisplayAlert ("Scanned Barcode", result.Text, "OK");

                    // Navigate away
                    await Navigation.PopAsync ();
                });

            overlay = new ZXingDefaultOverlay
            {
                TopText = "Hold your phone up to the barcode",
                BottomText = "Scanning will happen automatically",
                ShowFlashButton = zxing.HasTorch,
            };
            overlay.FlashButtonClicked += (sender, e) => {
                zxing.IsTorchOn = !zxing.IsTorchOn;
            };
            var grid = new Grid
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };
            grid.Children.Add(zxing);
            grid.Children.Add(overlay);

            // The root page of your application
            Content = grid;
        }
```

You can find both examples [here](https://components.xamarin.com/gettingstarted/zxing.net.mobile.forms).

**Comment by trisco2001** [comment]
Great! I'll give it a shot. Thanks @devneutz

**Comment by DamianSuess** [comment]
Same issue here but did not work.
Using v2.4.1 of ZXing.Net.Mobile and ZXing.Net.Mobile.Forms, .NET Standard v1.4, and using MVVM style coding.

My Android MainActivit is also being declared via ``FormsAppCompatActivity`` whereas the sample uses, ``FormsApplicationActivity`` (_which is marked for deprecation by Xamarin_).

```
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
```

**Comment by bigbbri** [comment]
@DamianSuess I am getting this error also with my MainActivity referring to the deprecated FormsApplicationActivity.  I switched it to FormsAppCompatActivity and I'm still getting this error.  I'll dive deeper but wanted to share what I'm seeing.
Thanks,
Brian

**Comment by bbl-Laobu** [comment]
@trisco2001 Indeed, when running in release everything worked fine but in debug this error kept appearing. 
@devneutz solutions didn't work for me and I also tried by downgrading ZXing to earlier versions but without success. 

In the end, the good old 'Clean All', delete manually everything from the bin and obj folders (I always do so for all projects- common, iOS and Android) and Build All did the trick.  

I am on ZXing version 2.4.1, Forms version 3.1.0.637272. 

Hope this helps anyone...

**Comment by alvynfash** [comment]
I tried good old 'Clean All' but didnt help. Ended up downgrading to '2.3.2'

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
