### ISSUE TITLE
UWP Scanner does not work in NuGet package

### ISSUE THREAD

**Issue by claudiuslollarius** [Redth/ZXing.Net.Mobile#500]
Using the latest version from NuGet, MobileBarcodeScanner.Scan() never returns a result, even if a valid QR code is presented.

Compiling against the latest source works. Any chance you could fix the NuGet package too?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
