### ISSUE TITLE
Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference

### ISSUE THREAD

**Issue by straiser17** [Redth/ZXing.Net.Mobile#501]
Hi,
I have got a problem  with ScannerFragment in Xamarin.Android.  I created fragment just like in sample in newest version. Unfortunetly, when I try open activity, the following error occurs:

Method 'ZXing.Mobile.ZXingScannerFragment.StartScanning' not found.
 at xxxx.Views.ScannView.OnResume () [0x00041] in xxxx

Of course, this erroir ccurs in runtime. When I build app, everuthing is ok (StartScanning IS found).
I tried downgrade to version 1.5.4 and it worked ok but in 1.5.4 app crashes  when back  button is pressed.

EDIT:
Rebuild help, but now I have problem on pressing back button or closing fragmentactivity with scanner. Error:

UNHANDLED EXCEPTION:
02-27 11:50:45.411 I/MonoDroid( 3562): Java.Lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference
02-27 11:50:45.411 I/MonoDroid( 3562):   at (wrapper managed-to-native) Java.Interop.NativeMethods:java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
02-27 11:50:45.411 I/MonoDroid( 3562):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008f] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12079 
02-27 11:50:45.411 I/MonoDroid( 3562):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00068] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:31 
02-27 11:50:45.411 I/MonoDroid( 3562):   at Android.Views.View.Draw (Android.Graphics.Canvas canvas) [0x0002c] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.View.cs:12837 
02-27 11:50:45.411 I/MonoDroid( 3562):   at Syncfusion.SfDataGrid.ScrollViewer.Draw (Android.Graphics.Canvas canvas) [0x00000] in <9bb698f697c545b396d994d057ae13d9>:0 
02-27 11:50:45.411 I/MonoDroid( 3562):   at Android.Views.View.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.View.cs:12825 
02-27 11:50:45.411 I/MonoDroid( 3562):   at (wrapper dynamic-method) System.Object:26f37cd4-399e-491e-b135-512496f0a3b6 (intptr,intptr,intptr)
02-27 11:50:45.411 I/MonoDroid( 3562):   --- End of managed Java.Lang.NullPointerException stack trace ---
02-27 11:50:45.412 I/MonoDroid( 3562): java.lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.graphics.Canvas.drawRect(Canvas.java:1134)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at md5c91aceb59597f50fed702bd2c746cea3.GridCell.n_onDraw(Native Method)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at md5c91aceb59597f50fed702bd2c746cea3.GridCell.onDraw(GridCell.java:59)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16270)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15267)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16273)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15267)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15262)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16273)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at md5c91aceb59597f50fed702bd2c746cea3.ScrollViewer.n_draw(Native Method)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at md5c91aceb59597f50fed702bd2c746cea3.ScrollViewer.draw(ScrollViewer.java:184)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15267)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15262)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15262)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15262)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15262)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16040)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
02-27 11:50:45.412 I/MonoDroid( 3562): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.View.draw(View.java:16273)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2697)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.View.updateDisplayListIfDirty(View.java:15267)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2619)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2438)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2071)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.os.Handler.handleCallback(Handler.java:739)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.os.Looper.loop(Looper.java:224)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at java.lang.reflect.Method.invoke(Native Method)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-27 11:50:45.413 I/MonoDroid( 3562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
