### ISSUE TITLE
not read code 128

### ISSUE THREAD

**Issue by carlosalbertosousa** [Redth/ZXing.Net.Mobile#502]
hi, 
I can not read code 128.

![code128](https://cloud.githubusercontent.com/assets/6943564/23403997/b8158800-fdaa-11e6-8422-5c76a9aee68d.png)

**Comment by redwolf2** [comment]
The black bars might be too thick. Try to print out the code using a laser printer with a fitting dpi setting (no streched code) and try again.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
