### ISSUE TITLE
When exiting a screen with a ZxingScannerView and the torch is on, it stays on

### ISSUE THREAD

**Issue by kadamgreene** [Redth/ZXing.Net.Mobile#503]
If while on a Xamarin.Forms screen with a ZXingScannerView, if you turn on the torch/flash and then navigate away from the screen, the torch/flash doesn't turn off.  It does on Android.

I've tried to do ZXingScannerView.IsTorchOn = false during the OnDisappearing of the underlying form, but that doesn't do it.  I've tried to wrap it in Device.BeginInvokeOnMainThread, that didn't help.  It works fine if I push the Flash button again to turn it off, just not while exiting the screen...

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
