### ISSUE TITLE
BUG on WindowsUniversal Cancel() go back twice

### ISSUE THREAD

**Issue by neoDD69** [Redth/ZXing.Net.Mobile#505]
If you call ZXing.Mobile.MobileBarcodeScanner.Cancel() the class MobileBarcodeScanner call twice `rootFrame.GoBack()`
1st - on public override async void Cancel() at line ~84
2nd -  public override async Task<Result> Scan(MobileBarcodeScanningOptions options) at line ~68. after the tcsScanResult return the result the next block is called even th scan is done or canceled.

I've debugged and I've removed the call from Cancel() and it works fine:
```
 public override async void Cancel()
        {
            var rootFrame = RootFrame ?? Window.Current.Content as Frame ?? ((FrameworkElement)Window.Current.Content).GetFirstChildOfType<Frame>();
            var dispatcher = Dispatcher ?? Window.Current.Dispatcher;

            ScanPage?.Cancel();
            return;
            //await dispatcher.RunAsync(CoreDispatcherPriority.High, () =>
            //{
            //    if (rootFrame.CanGoBack)
            //        rootFrame.GoBack();
            //});
        }
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
