### ISSUE TITLE
Bad Reading Code 39

### ISSUE THREAD

**Issue by carlasampaio01** [Redth/ZXing.Net.Mobile#508]
Hi, Im using the ZXing plugin to scan barcodes. But Im having a problem when scanning forward slashes.
Per example if the result is 2222/F1 it replaces with 2222&1.

I found these replacements:

/N -> \
/F -> &
/D -> $
/B -> "
/K -> +
/A -> !
/G -> '

**Comment by F1nZeR** [comment]
Check this one https://github.com/Redth/ZXing.Net.Mobile/pull/441

**Comment by carlasampaio01** [comment]
Are you referring to UseCode39ExtendedMode = false ?
I can't find this option.

**Comment by Redth** [comment]
#523 should fix this
