### ISSUE TITLE
Android - Black screen if rotation is done fast

### ISSUE THREAD

**Issue by gustaveracosta** [Redth/ZXing.Net.Mobile#509]
Lets say you are in portrait mode and you quickly move the phone to landscape and comeback to portrait mode then the scanner fragment does not get instantiated and therefore the camera does not work (black screen takes over)

I have been trying to fix this whole day.

Any1 has any insight on this?
I have implemented the android Vision library and I don't have that problem by using RetainInstance = true; on the fragment. However, it does not work for the ZXing library.

**Comment by gustaveracosta** [comment]
fixed by delaying the scan by 100ms fixed the problem, there is something with parallel processing nature of scan function

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
