### ISSUE TITLE
UWP - Lumia 640/640XL - Crash on rotation

### ISSUE THREAD

**Issue by jennifer-leung** [Redth/ZXing.Net.Mobile#511]
Hi,

I am getting a crash on the Lumia 640 range using the nuget package in uwp.  Here is the exception message and stack:

An item with the same key has already been added.

   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Add[K,V](K key, V value)
   at ZXing.Mobile.ZXingScannerControl.<SetPreviewRotationAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ZXing.Mobile.ZXingScannerControl.<displayInformation_OrientationChanged>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

Can you please shed me some light on how to fix this?

Many Thanks
Jennifer

**Comment by MisterIsk** [comment]
Nokia Lumia 930 same exception on phone rotation.

**Comment by MisterIsk** [comment]
To bypass the ignored problem, I just fixed the auto rotation of the display before calling the scan and then return the settings back:

DisplayOrientations autoRotationPreferences;
...
autoRotationPreferences = DisplayInformation.AutoRotationPreferences;
DisplayInformation displayInfo = DisplayInformation.GetForCurrentView();
DisplayInformation.AutoRotationPreferences = displayInfo.CurrentOrientation;
...
DisplayInformation.AutoRotationPreferences = autoRotationPreferences;

**Comment by techfooninja** [comment]
huge shoutout to @MisterIsk for this idea. For anyone else, here's my renderer to make this work in UWP (NOTE: I'm using the ZXingScannerPage in my project):

`using MyProject.UWP.Renderers;
using Windows.Graphics.Display;
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using ZXing.Net.Mobile.Forms;

[assembly: ExportRenderer(typeof(ZXingScannerPage), typeof(ZXingFixedOrientationScannerPageRenderer))]
namespace MyProject.UWP.Renderers
{
    public class ZXingFixedOrientationScannerPageRenderer : PageRenderer
    {
        protected bool Initialized { get; set; }
        protected DisplayOrientations AutoRotationPreferences { get; set; }

        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null && !Initialized)
            {
                Initialized = true;
                AutoRotationPreferences = DisplayInformation.AutoRotationPreferences;

                e.NewElement.Appearing += (s, args) =>
                {
                    DisplayInformation displayInfo = DisplayInformation.GetForCurrentView();
                    DisplayInformation.AutoRotationPreferences = displayInfo.CurrentOrientation;
                };

                e.NewElement.Disappearing += (s, args) =>
                {
                    DisplayInformation.AutoRotationPreferences = AutoRotationPreferences;
                };
            }
        }
    }
}`

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
