### ISSUE TITLE
How can I wait for scan to finish and return to previous activity?

### ISSUE THREAD

**Issue by eestein** [Redth/ZXing.Net.Mobile#513]
I'm receiving this exception while trying to display a toast to the user:

> View=com.android.internal.policy.PhoneWindow$DecorView{128873 G.E...... R.....I. 0,0-640,135} not attached to window manager

`UserDialogs.Instance.Toast('message');`

The problem seems to be related to the toast being shown before the scan has completely disappeared. If I remove the toast it works fine. 

I tried `ContinueWith` as suggested here http://stackoverflow.com/questions/41018299/how-to-wait-for-the-android-activity-to-fully-resume-after-calling-zxing-qr-scan but it didn't work as well.

Is there a way to wait for the scan to completely disappear so I can display that toast to the user if needed?

**EDIT**
----
I just confirmed, if there was a way to wait for ZXing my problem would be solved:

```
var result = await Tools.ScanCode();

await Task.Delay(3000);
await HandleResult(result);
```

This code works, since after 3s the scanner has disappeared.

So... is there a way to wait for the scanner to disappear so I don't need the above (terrifying) code? :)

Thanks.

**Comment by bares43** [comment]
Is there any solution for this issue?

**Comment by Redth** [comment]
You could always wait for the OnAppearing (forms) or OnResume (android native) to be called before taking the next action after a result is received.
