### ISSUE TITLE
Please update nuget packages

### ISSUE THREAD

**Issue by horacehylee** [Redth/ZXing.Net.Mobile#515]
There are many bug fixes that are not included in the nuget releases.
Please kindly update the nuget packages.

Major bugs:
https://github.com/Redth/ZXing.Net.Mobile/commit/a1efa050cfdfad21ea35eed48e07834f7ab29df5

**Comment by alexsandro-xpt** [comment]
+1

**Comment by ConsentDevelopment** [comment]
+1

**Comment by KNSSoftware** [comment]
+1000

**Comment by alexsandro-xpt** [comment]
Where @Redth gonne?

**Comment by Redth** [comment]
Sorry folks, I'll get to this soon.

**Comment by jeromeliger** [comment]
+1

**Comment by Redth** [comment]
2.2.0 is out.
