### ISSUE TITLE
Barcode - 44 digits

### ISSUE THREAD

**Issue by jonathansantos15a** [Redth/ZXing.Net.Mobile#516]
Hi developers,

I have a sample Xamarin Forms application and i'm using Zxing.Net.Mobile.
I can read QR Codes, ITF Small codes but, I can't read barcodes that has 44 digits.
My ideia is with app, read bank slip some figure below:

http://s.glbimg.com/po/tt/f/original/2013/04/15/imagem-fake-banco.jpg

How do this?

It is my simples code:

`public partial class MainPage : ContentPage
{
public MainPage()
{
InitializeComponent();
}

    async private void openScanner_Clicked(object sender, EventArgs e)
    {
        var opts = new ZXing.Mobile.MobileBarcodeScanningOptions
        {
            PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE, ZXing.BarcodeFormat.ITF,
                ZXing.BarcodeFormat.All_1D, ZXing.BarcodeFormat.EAN_13, ZXing.BarcodeFormat.CODE_39, ZXing.BarcodeFormat.CODE_128,
                ZXing.BarcodeFormat.PDF_417, ZXing.BarcodeFormat.UPC_EAN_EXTENSION  
            }
        };

        opts.TryHarder = true;
        var barcodeReader = opts.BuildBarcodeReader();
        barcodeReader.Options.AllowedLengths = new[] { 44 };

        ZXingScannerPage scanPage = new ZXingScannerPage(opts);

        scanPage.OnScanResult += (result) => {

            Device.BeginInvokeOnMainThread(() => {
                Navigation.PopAsync();
                DisplayAlert("Scanned Barcode", result.Text, "OK");
            });
        };

        await Navigation.PushAsync(scanPage);
    }
}`

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
