### ISSUE TITLE
App crashes when pressing back button on Android phone when on camera

### ISSUE THREAD

**Issue by MarkConnelly1994** [Redth/ZXing.Net.Mobile#519]
Hi,

The app is crashing for me whenever I press the back button on an android phone when I'm on the barcode scanner camera. 

Any ideas why this is happening?

Cheers,
Mark

**Comment by KNSSoftware** [comment]
have you handled a null response, which is what you would get if you click back, without scanning a barcode.

if (result == null)
{// You have clicked back, and should not try to access result}

**Comment by MarkConnelly1994** [comment]
Hi KNS,

No I haven't handle the null response! So that is why it is crashing. I have this solution on my references so would I need to edit the references in order to handle this null response or would I do it within my own code?

(I am rather new to C# and Xamarin.Forms)

Thanks,

Mark

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
