### ISSUE TITLE
App crashes when attempting to zoom in on ScannerView

### ISSUE THREAD

**Issue by nickl-martin** [Redth/ZXing.Net.Mobile#520]
My app crashes when I make the pinch/expand gesture with 2 fingers on a ScannerView (also with DefaultOverlay).

I'm testing on a Galaxy S5, Android(v6.0.1) and this happens consistently as soon as I make the expand(unpinch) gesture. 

Here are the stack traces: [zoom_crash.txt](https://github.com/Redth/ZXing.Net.Mobile/files/876363/zoom_crash.txt)

It seems like maybe more than one finger is not accounted for?

**Comment by Redth** [comment]
I think this one's already fixed in master.  Could you try these artifacts and see if it's still happening? https://ci.appveyor.com/project/Redth/zxing-net-mobile/build/2.1.74/artifacts

**Comment by nickl-martin** [comment]
Thanks @Redth, that did the trick.

**Comment by utkarsh-bandekar** [comment]
@nickl-martin : i have a similar issue for ios : https://github.com/Redth/ZXing.Net.Mobile/issues/1087

Can you give your inputs

**Comment by nickl-martin** [comment]
@utkarsh-bandekar Sorry but I don't think I can be of much help. I'm still using this library but no longer need to be able to zoom in. I am just using the CameraBarcodeReaderView now.
