### ISSUE TITLE
After scan page reloads (cannot assign the value)

### ISSUE THREAD

**Issue by gayan1991** [Redth/ZXing.Net.Mobile#522]
In my UWP application I am using the library ZXing.Net.Mobile.Forms 2.1.47. After I have initialized the mobile barcode scanner, it shows me the camera with the rectangle shape for the barcode scan. I managed to scan retrieve the result through a message box. However, I am not able to assign that value to anything as the page reloads.

My code is as follow

At the constructor :        ZXing.Net.Mobile.Forms.WindowsUniversal.ZXingScannerViewRenderer.Init();

My method :

```
var obj= DataContext as Class;
            scanner = new ZXing.Mobile.MobileBarcodeScanner();
            scanner.TopText = "Hold the camera up to the barcode\nAbout 6 inches away";
            scanner.BottomText = "Wait for the barcode to automatically scan!";
            var result = await scanner.Scan();
            if (result != null)
                obj._cameraScannedBarcode = result.Text;
```

because of that I am never able assign the result to obj._cameraScannedBarcode

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
