### ISSUE TITLE
Samsung S7 setPreviewTexture failed

### ISSUE THREAD

**Issue by bhammer88** [Redth/ZXing.Net.Mobile#524]
stopping and starting the camera will cause the following exception;

E/ZXING   (17999): SetupCamera failed: System.AggregateException: One or more errors occurred. ---> Java.IO.IOException: setPreviewTexture failed

running on android 7.0...while other android versions will not have this error.

**Comment by PaulVrugt** [comment]
We are running into the same issue with a galaxy a5, trying to find a solution

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
