### ISSUE TITLE
Xamarin Forms | Checking camera access for Android Phone

### ISSUE THREAD

**Issue by KratiChauhan** [Redth/ZXing.Net.Mobile#529]
Hello

I am implementing the zxing library in xamarin form (PCL). I need to check if app does not have camera permission, i have to move user to another page. 

For achieve this, i am using dependency service of xamarin forms and calling native android class to check camera permission. 
What ever I do, i am always getting permission as "Granted".

What I have done so far in code : 

1. In  Mainactivity file, have added following 

`protected override void OnCreate(Bundle bundle)
		{
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar;

			base.OnCreate(bundle);

			global::Xamarin.Forms.Forms.Init(this, bundle);
			global::ZXing.Net.Mobile.Forms.Android.Platform.Init();

			LoadApplication(new App());
		}

		public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
		{
			global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);     
		}`

2. Created a class file which implements camera checking code in android. Code written in class file
`public CameraState GetCameraState()
		{
	

				MainActivity activity = Forms.Context as MainActivity;
				var permissionCheck = ContextCompat.CheckSelfPermission(activity.BaseContext.ApplicationContext, Manifest.Permission.Camera);
				var permissionCheck1 =  activity.BaseContext.ApplicationContext.CheckSelfPermission(Manifest.Permission.Camera);
				var permissionCheck2 = activity.CheckSelfPermission(Manifest.Permission.Camera);
				var permissionCheck3 = Forms.Context.CheckSelfPermission(Manifest.Permission.Camera);
`

all of the above ways always returns me status as "Granted"

Can someone please help me know what is the right way of checking camera permission in android using dependency service? I am sure it is not an unusal ask, but since i am new , i am not able to find what am i doing wrong. 
My guess says, my context against which i am checking the permission is not correct. Any help please

**Comment by MobileRez** [comment]
@KratiChauhan  I had a issue with the zxing and camera permissions, if you are using the latest release of the nuget package (2.2.9), you need to change the following on your MainActivity:
`ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);`
to be
`ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);`
as the code you tried is deprecated in the latest SDK. (basicly just remove the .Forms part of that line). 

see if that helps at all.

**Comment by shanmugasundharamselvadurai** [comment]
@ MobileRez
In MainActivity i used 
 
**One camera permission** 
**PermissionsHandler.OnRequestPermissionsResult(requestCode,** permissions, grantResults);

**Barcode permission**
**ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode,** permissions, grantResults);

Still app crashing when i open camera

**Comment by shanmugasundharamselvadurai** [comment]
Use this 

 **//camera
            PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            // barcode
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);**

**Comment by HexisSoftware** [comment]
Not working for me neither on Android V5.1.1 and V6

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
