### ISSUE TITLE
Navigating between CustomeScanPages takes long (about a half second)

### ISSUE THREAD

**Issue by Mr-Pearce** [Redth/ZXing.Net.Mobile#531]
Hi There,
I Have a xamarin Forms (Ios) Project with a MasterDetailPage and multiple navigatable CustomeScanPage (witch a ScanView each) as Details.

Scanpage1 -> Scanpage2 -> Scanpage3

I createt it like the CustomePage in your Sample [/Samples/Forms/Core/CustomScanPage.cs](https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Forms/Core/CustomScanPage.cs)

However when i am navigating back and forth it blocks the UI Thread for about a half second which freezes the complete UI while "IsScanning" is setting to true.

I Also Tried to add the same ScanView object(via IOC) inside the seperate ScanPages, let IsScanning = true all the Time and removed the OnAppearing and OnDissapearing swithes 
but that also let it lag between the pages.
Also when i navigate back from Scanpage 3 to 2 the scanner on 2 will stay off.

Even in your Xamarin Forms Sample the "IsScanning = true" blocks the UI Thread

Is ther an possibility to set IsScanning async without bothering the UI Thread or even let scanning on between pages?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
