### ISSUE TITLE
Nullref when navigation away from a scanner in a tabbar

### ISSUE THREAD

**Issue by lukethenuke** [Redth/ZXing.Net.Mobile#536]
This is based on the current master (33dfaa242d617f63face63aa270208ee31761af5) and only affects android, both emulator and actual device.

**Steps to reproduce**
1. Add a `TabbedPage` with a scanner children.
```c#
public class BugPage : TabbedPage
{
    public BugPage ()
    {
        var scanPage = new ZXingScannerPage();
        scanPage.OnScanResult += (result) =>
                Device.BeginInvokeOnMainThread(async () => await Navigation.PushAsync(new ContentPage()));
        Children.Add(scanPage);
     }
}
```
2. Scan a barcode

**Expected results**
Successfully navigate away from the page.

**Actual results**
The application crash with a null-reference exception. 

**Stack trace**
`
  at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <c4ef1b49b15c4fe7bacf4a7abbb8573b>:0 
  at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <c4ef1b49b15c4fe7bacf4a7abbb8573b>:0 
  at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <c4ef1b49b15c4fe7bacf4a7abbb8573b>:0 
  at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <c4ef1b49b15c4fe7bacf4a7abbb8573b>:0 
  --- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
  at (wrapper dynamic-method) System.Object:0022e34f-dd67-46bb-908f-d33511758af6 (intptr,intptr)
`

**Reason**
The null-reference happens at line 219 at `Source/ZXing.Net.Mobile.Android/CameraAccess/CameraController.cs` because the `CameraController#ShutdownCamera()` is called before the SurfaceChanged event and null the Camera property.

**Solution**
We have solved this by adding a null check for the Camera property in `CameraController#RefreshCamera`.

I can open a PR for the null check if you want :)

**Comment by SeeD-Seifer** [comment]
I get similar stack trace. I'm not using Xamarin.Forms, just Xamarin.Android but I'm also using tabs.

**Comment by pandazzurro** [comment]
Same error!
I use xamarin forms with Prism.
Error occur when add new ContentPage on ScannerPage and set False properties: IsAnalyzing, IsScanning.
Another problem occurs when return to ScannerPage.
I set True IsAnalyzing, IsScanning but Camera freeze images.


StackTrace
07-05 13:23:04.925 I/MonoDroid(28126): UNHANDLED EXCEPTION:
07-05 13:23:04.963 I/MonoDroid(28126): System.NullReferenceException: Object reference not set to an instance of an object.
07-05 13:23:04.963 I/MonoDroid(28126):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0 
07-05 13:23:04.963 I/MonoDroid(28126): --- End of stack trace from previous location where exception was thrown ---
07-05 13:23:04.963 I/MonoDroid(28126):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-05 13:23:04.963 I/MonoDroid(28126):   at (wrapper dynamic-method) System.Object:d5dc9ad8-3c18-49ca-8d21-b5d5bcff5f1f (intptr,intptr)

**Comment by Mardaneus86** [comment]
I have a similar error with Xamarin Forms, but only on the Android version. I can only reproduce it when a scan result is found while rotating the device orientation, and at the same time set `IsAnalyzing` and `IsScanning` to false.

**Comment by PaulARoy** [comment]
Same issue here on Xamarin.Android

**Comment by aphex3k** [comment]
+1

**Comment by izefler** [comment]
+1, do we have a solution?

**Comment by ptsiogas** [comment]
+1

**Comment by gaffkins** [comment]
+1

**Comment by samukbg** [comment]
+1

**Comment by filoe** [comment]
+1

**Comment by FreedCapybara** [comment]
Can manually add and remove the `ZXingScannerView` from the page in `OnAppearing/OnDisappearing`.

```cs
    public partial class ScanQRCodePage
    {
        private ZXingScannerView _scannerView;

        public ScanQRCodePage(ScanQRCodeViewModel viewModel)
        {
            InitializeComponent();
            ViewModel = viewModel;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            // Manually add the scanner view
            _scannerView = new ZXingScannerView();
            _scannerView.HorizontalOptions = LayoutOptions.Start;
            _scannerView.OnScanResult += OnScanResult;

            ScannerLayout.Children.Add(_scannerView, null, null, Constraint.RelativeToParent((parent) => parent.Width), Constraint.RelativeToParent((parent) => parent.Height));

            _scannerView.IsScanning = true;
        }

        public void OnScanResult(ZXing.Result result)
        {
            ViewModel.OnScanCommand.Execute(result);
        }

        protected override void OnDisappearing()
        {
            _scannerView.IsScanning = false;
            _scannerView.OnScanResult -= OnScanResult;

            ScannerLayout.Children.RemoveAt(0);

            base.OnDisappearing();
        }
    }
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
