### ISSUE TITLE
About front Camera

### ISSUE THREAD

**Issue by Fudozzo** [Redth/ZXing.Net.Mobile#538]
Good Afternoon, i'm using ZXing.Mobile with the rear camera of my devices without issues and it's working great. Now i'm having a strange issue with the front camera, it's not being used on 3 devices i tested.
I'm using Zxing.Net.Mobile 2.2.9 and i've encountered this issue on a Huawei Y5 (Phone), Wico Freddy (Phone), Asus K015 (Tablet).
I'm trying with the simplest code i could think of:
`MobileBarcodeScanner.Initialize(Application);`
`var scanner = new MobileBarcodeScanner();`
`MobileBarcodeScanningOptions opt = new MobileBarcodeScanningOptions()`
`{`
`    UseFrontCameraIfAvailable = true`
` };`
`var result = await scanner.Scan(opt);`

When the barcode scanner opens it uses the Back camera and in the log i see the following lines:
`01-28 03:51:03.249 D/ZXing.Net.Mobile(10099): Checking Number of cameras...`
`01-28 03:51:03.260 D/ZXing.Net.Mobile(10099): Found 2 cameras...`
`01-28 03:51:03.273 D/Mono    (10099): DllImport searching in: '__Internal' ('(null)').`
`01-28 03:51:03.273 D/Mono    (10099): Searching for 'java_interop_jnienv_get_int_field'.`
`01-28 03:51:03.273 D/Mono    (10099): Probing 'java_interop_jnienv_get_int_field'.`
`01-28 03:51:03.273 D/Mono    (10099): Found as 'java_interop_jnienv_get_int_field'.`
`01-28 03:51:03.280 D/ZXing.Net.Mobile(10099): Found Back Camera, opening...`

I'm missing something or i'm unlucky with these devices? I can try with some more phone models, but i don't think that it would solve the issue. Has someone tested a phone model that works for sure?

Thank you.

**Comment by mnesser** [comment]
Not sure if related. We have some issues regarding the front camera. We are unable to start “CameraFacing.Front” in release mode. The front facing camera starts fine in debug mode, when deployed using release the back camera is always launched.
It might be a linking problem 
Using v2.2.9. Xamarin native android. tested on multiple devices.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
