### ISSUE TITLE
Xamarin.Forms cannot scan 1d barcodes since version 2.2.0

### ISSUE THREAD

**Issue by Mr-Pearce** [Redth/ZXing.Net.Mobile#540]
Since i updated the nuget packages to 2.2(and above) i cannot scan 1D barcodes.
Tested EAN13, Interleaved two of five, Code39, 
2d Datamatrix works,
with version 2.1.47 everything works fine.

Also the DelayBetweenContinuousScans seems to be ignored
initialized with
```
        var  ScannerView = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                IsScanning = true,
                IsAnalyzing = true,
                Options =
                { 
                    DelayBetweenContinuousScans = 2000,
                    UseNativeScanning = true
                }
            };
```

**Comment by jackyshek** [comment]
I think your issue that seems as mine:
https://github.com/Redth/ZXing.Net.Mobile/issues/544

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
