### ISSUE TITLE
Auto Focus only working the first time

### ISSUE THREAD

**Issue by whiskeyboy9** [Redth/ZXing.Net.Mobile#541]
Hi,

i have encountered a problem with my Samsung Galaxy A3 2017. I am using a loop to autofocus .The first time the ZXingScannerView is initalized and the .AutoFocus() method is called it works as expected but then it stops until i manualy press on the ZXingScannerView.

```
            Device.StartTimer(TimeSpan.FromMilliseconds(3000), () =>
            {
                if(Scanner == null) { return false; } 
                else if (Scanner.IsScanning)
                {
                    Scanner.Focus();
                    Scanner.AutoFocus();
                }
                return true;
            });
```

I am using 
Xamarin.Forms v2.3.4.231
Zxing.Net.Mobile v2.2.9
Visual Studio 2015

**Comment by F1nZeR** [comment]
Autofocus should work automatically without that loop, give it a try.

**Comment by whiskeyboy9** [comment]
Ok, it did kind of work. Withouth .Autofocus() it will not recognize if it did poorly autofocus but most of the time it works.

The other thing is that on older phones the loop does a better job in rezognizeing the barcodes, but i think i will try around my self if i can get better results. I just wanted to know if i missed something.

Thank you.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
