### ISSUE TITLE
trouble with overlay

### ISSUE THREAD

**Issue by asulwer** [Redth/ZXing.Net.Mobile#542]
Thoughts on what i am doing wrong here?

```
ZXing.Mobile.MobileBarcodeScanner scanner = new ZXing.Mobile.MobileBarcodeScanner();
            
var options = new ZXing.Mobile.MobileBarcodeScanningOptions()
            {
                UseNativeScanning = true,
                TryHarder = true
            };

ZXingDefaultOverlay overlay = new ZXingDefaultOverlay();
scanner.UseCustomOverlay = true;
scanner.CustomOverlay = overlay;
```

I have an error when i assign 'overlay' to CustomOverlay

Error	CS0029	Cannot implicitly convert type 'ZXing.Net.Mobile.Forms.ZXingDefaultOverlay' to 'Android.Views.View'	Scangun.Android	MainPage.xaml.cs	87
Error	CS0029	Cannot implicitly convert type 'ZXing.Net.Mobile.Forms.ZXingDefaultOverlay' to 'Windows.UI.Xaml.UIElement'	Scangun.UWP	MainPage.xaml.cs	87

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
