### ISSUE TITLE
Xamarin.Forms iOS CPU usage high after dismissing ZXingScannerPage

### ISSUE THREAD

**Issue by Keflon** [Redth/ZXing.Net.Mobile#543]
Hello
On the iPhone if I show a ZXingScannerPage and later navigate away from it, the CPU remains running hot (30-40%)
This is how I present the Page (abridged):

    void Test(View customOverlay)
    {
       scanPage = new ZXingScannerPage(customOverlay: customOverlay);
       Xamarin.Forms.Application.Current.MainPage = scanPage;
       // CPU running at 30-40%. I'm okay with that.
    }

When I later set the Xamarin.Forms.Application.Current.MainPage to a different Page I find the CPU is still running at 30-40% for the duration of my app.

If however I show a ZXingScannerPage inside a NavigationPage like this:

    void Test(View customOverlay)
    {
       _scanPage = new ZXingScannerPage(customOverlay: customOverlay);
        NavigationPage np = new NavigationPage();
        np.PushAsync(_scanPage);
       Xamarin.Forms.Application.Current.MainPage = scanPage
    }

I find that when I set Xamarin.Forms.Application.Current.MainPage to a new Page, CPU usage returns to 0-1%, as it was prior to showing the ZXingScannerPage.

Unfortunately I can't use a NavigationPage in our app. so does anyone have any idea how I can solve this problem?

Thanks in advance,
Keith

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
