### ISSUE TITLE
Cannot Scan Barcode Horizontally after 2.2.0 updates [iOS]

### ISSUE THREAD

**Issue by jackyshek** [Redth/ZXing.Net.Mobile#544]
My iOS app is using Xamarin Forms and using the ZXing.Net.Mobile.Forms. And the app just allow portrait orientation. Also I have tried the sample that your provided.

After these trying, found this issue:
The scanning cannot recognized the barcode at [horizontal](http://imgur.com/a/Oxr26), but it work on [vertical](http://imgur.com/a/PDrTb). 

After Investigation, seems the problem occur after version 2.2.0 updates which make this happen. Even using `MobileBarcodeScanningOptions.TryHarder`, it is still not work.

**Comment by frankois944** [comment]
Same problem with ZXing.Net.Mobile

**Comment by buttifabio** [comment]
Same problem for me.
@jackyshek have you found a solution?

**Comment by jackyshek** [comment]
@buttifabio The current solution is downgrade to 2.1.47 version and use the ZXing.Net.Mobile on different platform until he/they fix the problem.

**Comment by sbilger** [comment]
Any updates on this? I am having the same issue on 2.2.9

**Comment by Mika571** [comment]
I too am having this problem

**Comment by jaydens** [comment]
+1

**Comment by thedee** [comment]
I have 2.2.9 installed and when using an IPad I can't scan a barcode when I am holding the IPad in Portrait view.   It works great when holding it in landscape.  Anything I can do to fix this?

**Comment by jmfronsee** [comment]
I take it no one is developing or supporting this project anymore?  No update or comments from the Devs in 6 months.  Make an awesome product, gets tons of people using it in their applications, then bounce.  Nice.

**Comment by Redth** [comment]
Sorry folks, I am looking into this.  Unfortunately FOSS means I don't get to spend as much time on the project as I'd like to always.

**Comment by neilcitruslime** [comment]
We also cannot scan in portrait mode on iOS only in when the phone is held in landscape. Great great software, but this one bug (or our lack of setup knowledge) means our app is now broken. 

Works great on Android and iOS if you hold a portrait app in landscape.

**Comment by Redth** [comment]
This is fixed in master now.  I have a bit more work to do with testing the various platforms before i can make another release.  But soon!

**Comment by neilcitruslime** [comment]
Jonathan


You sir are a squire and a gentleman. I look forward to the new release.

Regards,


Neil McQuillan
Managing Director
Citrus-Lime Limited
CLICKS AND MORTAR SPECIALISTS
neil@citruslime.com<https://amsprd0510.outlook.com/owa/redir.aspx?C=dQurJZWDk0SJBOad-I2yPSq3XjqFAM8IyDtHJuzO6KLaTb2eSQmcNDqnsMaKW6Zhy97oJn5axuk.&URL=mailto%3aneil%40citruslime.com> [email]
0845 890 1270  [tel]
0870 706 5088 [fax]

www.citruslime.com<https://amsprd0510.outlook.com/owa/redir.aspx?C=dQurJZWDk0SJBOad-I2yPSq3XjqFAM8IyDtHJuzO6KLaTb2eSQmcNDqnsMaKW6Zhy97oJn5axuk.&URL=http%3a%2f%2fwww.citruslime.com%2f> [web]



________________________________

**Comment by hemantksh** [comment]
@Redth Thanks for the effort to get the fix in place. Is the fix released yet?

**Comment by ameer214** [comment]
@hemantksh This issue has been fixed in the latest release (v2.3.2). @Redth, Thank you!

**Comment by dpcabral** [comment]
I have an Xamarin iOS app and I am having problems scanning, the app is set to portrait, can't change that.

The barcode I am testing with is CODE 39, I was using v2.1.47 but it was not consistently scanning my barcode, not even half the time. So I upgraded to v2.4.1.0 and now it's worse and every scan is wrong.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
