### ISSUE TITLE
Xamarin.Android.Support.Fragment

### ISSUE THREAD

**Issue by Philoow** [Redth/ZXing.Net.Mobile#545]
Hello,

V4 package has been split into multiple packages

> With this release, the v4 Support Library has been split into several smaller modules:
> 
> support-compat
> support-core-utils
> support-core-ui
> support-media-compat
> support-fragment

https://developer.android.com/topic/libraries/support-library/rev-archive.html

ZXing.Net.mobile have need to retarget and use the Xamarin.Android.Support.Fragment.

For exemple i can't support Toolbar for api < 21 since the v4 Support has been split. For example, error i got:

> FragmentStatePagerAdapter exists in 'Xamarin.Android.Support.Fragment, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

Thanks !

**Comment by sabvente** [comment]
Hi, I'm also having this issue.
I can't use other libraries, like `MvvmCross.Droid.Support.Fragment`, because they depend on `Xamarin.Android.Support.Fragment`.

Thank you!

**Comment by Redth** [comment]
You should be able to install the Xamarin.Android.Support.v4 package still which is now a type forwarder to resolve this error.
