### ISSUE TITLE
Customize the scannable area

### ISSUE THREAD

**Issue by pavanki-lpw** [Redth/ZXing.Net.Mobile#546]
The overlay feature is nice but functionality wise it is just there to mask the UI. 

Is there a way to customize the scannable area, I mean reduce the area that is scannable on the screen? When this can't be done there is no point in having the overlay right? The overlay does not really do anything.

If you try this app https://play.google.com/store/apps/details?id=com.google.zxing.client.android you can see that - if the barcode/qr code lies outside the scanning area, it does not process it. That is what I am looking for. Is this possible?

Guys, need your help... I would have done a pull request myself but I am a complete newb.

**Comment by nuwankarunapala** [comment]
Did you find a solution?

**Comment by simon10says** [comment]
any solution yet? 

I tried to set the width and height of the ZXingScannerView, but it also decreases the resolution

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
