### ISSUE TITLE
Inconsistent behaviour using Forms ZXingScannerView on Android

### ISSUE THREAD

**Issue by fredrikhaglund** [Redth/ZXing.Net.Mobile#547]
My goal is to have continuous scanning and the camera preview in the background of my main page when the user press a button to toggle scanning instead of popping up a new page.

To accomplish this I added the following XAML to my Main Page.
```xaml
            <zxing:ZXingScannerView x:Name="ScannerView"
                                    IsAnalyzing="{Binding IsAnalyzing}"
                                    IsScanning="{Binding IsScanning}"  />
```
And some wiring to handle the result and some events to stop scanning when putting the application in the background:

```csharp
        ScannerView.OnScanResult += model.HandleScanResultAsync;
    ...
        public async void HandleScanResultAsync(Result result)
        {
            var text = result.Text ?? string.Empty;

            Device.BeginInvokeOnMainThread(() =>
            { 
                IsAnalyzing = false;
                // Process scan
                IsAnalyzing = true; 
            }
        }
    ...
        protected override void OnDisappearing()
        {
            ScannerView.IsScanning = false;
            base.OnDisappearing();
        }
```

**Expected:** Setting IsScanning to true turns on preview and you start to receive scans. Setting IsScanning to false turn of preview.
**Actual:** On Android the Camera is Setup immediately when the View is created instead of when IsScanning is set to true and it preview is not turned off when IsScanning is set to false.

This usage of the ZXingScannerView may not be what it was designed for, so this issue could just be a platform specific difference in behaviour that never has been tested before, but anyway it forces me to throw my first attempt in the trashcan. 

Anyway, it would have been nice if the Android version of ZXingScannerView behaved in the same to enable this usage scenario so that is why I created the issue/feature request.

My workaround is to create ZXingScannerView and insert it in the view when the user wants to scan,  remove it from the Page and let it be destroyed and then start over creating a new instance. This appear to be stable approach on both iOS and Android but with a longer delay before you can start scanning on iOS.

**Environment**
Xamarin.Forms: 2.3.4.231
Zxing.Net.Mobile: 2.2.9
FastAndroidCamera: 2.0.0
Android: 7.1.1

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
