### ISSUE TITLE
DelayBetweenContinuousScans does not work on iOS

### ISSUE THREAD

**Issue by fredrikhaglund** [Redth/ZXing.Net.Mobile#548]
The logic for `DelayBetweenContinuousScans` on iOS seems flawed and does not work.

The logic in [`ZXing.Mobile.ZXingScannerView.DidOutputSampleBuffer()`](https://github.com/Redth/ZXing.Net.Mobile/blob/ec9e9df733d5d3d3c30bc53c5c8b542b76ba6ce0/Source/ZXing.Net.Mobile.iOS/ZXingScannerView.cs#L511) that decides if a frame should be analyzed looks like this:

```csharp
if (msSinceLastPreview < options.DelayBetweenAnalyzingFrames
    || (wasScanned && msSinceLastPreview < options.DelayBetweenContinuousScans)
    || working
    || CancelTokenSource.IsCancellationRequested)
    {
        ...
        return;
    }
    wasScanned = false;
```
Key to decide if `DelayBetweenContinuousScans` should be used is the volatile (!?!) variable `wasScanned`that is initialized to false and also set to false directly after the check.

Unfortunately there is no code (that I can find) that sets this to true when a code is scanned.

The logic appears to break after 2.2.5 in commit [iOS: Use raw pointer to CVPixelBuffer for decoding](https://github.com/Redth/ZXing.Net.Mobile/commit/4462d7fcea1b97471473ce27781b31d49cb89747#diff-34f40c7f892d77057f0e495452dde09aL529) when `wasScanned = true` is removed (probably by misstake).

**Comment by Redth** [comment]
Fixed via #549
