### ISSUE TITLE
Zxing scanning is working fine in Andriod But not in iOS

### ISSUE THREAD

**Issue by Padalingam** [Redth/ZXing.Net.Mobile#551]
i am following this tutorials https://components.xamarin.com/gettingstarted/zxing.net.mobile its working fine Andriod and i can able to read the barcode from Android app.
When i tried the same app in iOS scanning is not at all happening and i am not able to find the below API below API
 //Scan(MobileBarcodeScanningOptions options, bool useAVCaptureEngine)
scanner.Scan(options, true);
its giving me Scan method will accept only one argument 
Can any one help me for this issue

**Comment by jorisM96** [comment]
It look like you got the same problems as #558.
Does it recognises QR-codes on iOS? 
Turn you phone into landscape mode and try to scan.

**Comment by jackyshek** [comment]
It is the same bug https://github.com/Redth/ZXing.Net.Mobile/issues/544

**Comment by Padalingam** [comment]
@jorisM96  landscape scanning is working fine and when i scan QR-Code both the orientation, its fails to scan

**Comment by WebDucer** [comment]
Same here. We use Code39 and QRCode.

On Android all works fine. On iOS I can scan QRCode in any orientation, Code39 only if I turn in landscape orientation (screen is locked to be in portrait mode).

**Comment by shanmugasundharamselvadurai** [comment]
if downgrade to 2.1.47 and it is working portrait mode on iOS, and  Custom overlay not calling

**Comment by kcherdch** [comment]
I downgraded it to 2.1.47 and it's still not working in portrait mode in iOS.

**Comment by mrTR24** [comment]
same problem. Scan correctly in Portrait Orientation in Android . But In IOS does not scan in Portrait Oriented ... Must Rotate to Horizontal Orientation for barcode to be captured .

**Comment by shameemah07** [comment]
Problem: Have to rotate the phone to capture the barcode in IOS 
Version ZXING: 2.2.9

The problem got fixed when downgraded to Zxing version 2.1.47

**Comment by aphex3k** [comment]
downgrade did not work for me

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
