### ISSUE TITLE
How to Chose Camera (On Dual Camera Phones)

### ISSUE THREAD

**Issue by Mr-Pearce** [Redth/ZXing.Net.Mobile#553]
Is it possible to chose the used Camera on dual camera phones like the new Iphon7 Plus or like on the LG G5?
I have the G5 myself and ZXING uses the wide-angle camera wich is verry bad at scanning close barcodes.

**Comment by fredrikhaglund** [comment]
There is one option UseFrontCameraIfAvailable that is the only logic that affects which camera to use. Can not see any logic for any other type of selection.

You can have a look at the [logic for picking camera for Android here]
(https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Android/CameraAccess/CameraController.cs#L174) and [for iOS here](https://github.com/Redth/ZXing.Net.Mobile/blob/ec9e9df733d5d3d3c30bc53c5c8b542b76ba6ce0/Source/ZXing.Net.Mobile.iOS/ZXingScannerView.cs#L150)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
