### ISSUE TITLE
Apex Labs Dependency Install

### ISSUE THREAD

**Issue by mibzman** [Redth/ZXing.Net.Mobile#555]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Apex 1.5.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.0.3', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
```

After installing the zxing git subpackage and attempting to compile I'm unable to build.

I'd guess that this has something to do with setting `Project Options -> Build -> General -> Target Framework to 2.3 or higher.`, which I haven't been able to do since that option does not appear to exist in VS 2017 or VS 2015.  The closest thing that I can find docs for is `Project -> <ProjectName> Settings -> Build -> General`, which does not contain a target framework option.

![image](https://cloud.githubusercontent.com/assets/5358449/25708890/d08ff2d8-30b5-11e7-9257-d7b185942ab1.png)

Is there some other Xamarin setting I'm missing?

**Comment by F1nZeR** [comment]
Does Apex support Xamarin Android at all? As I can see there is no updates since 2012.

**Comment by mibzman** [comment]
That would make sense based off of the error message.  But if that's the case why is it used so much in ZXing.Net.Mobile.Android?

**Comment by Redth** [comment]
Not sure what you're doing here.  We do depend on FastAndroidCamera nuget which does require your project to target Android 4.0.3 or higher.
