### ISSUE TITLE
UWP : App crashing on PopAsync (updated)

### ISSUE THREAD

**Issue by Ieeyo** [Redth/ZXing.Net.Mobile#556]
Hey,

Could anyone explain me why app crashes when I use "PopModalAsync" on a modal containing a ZXingScannerView that's not scanning ? This occurs on UWP while it's working fine on iOS.

Thanks.

**Comment by Ieeyo** [comment]
Am I the only one out there having a NullReferenceException when closing the scanner's modal ? :O
It only occurs on UWP with a webcam plugged in and won't occur with no webcam.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
