### ISSUE TITLE
2.2.9 cannot scan barcodes (QR is fine)

### ISSUE THREAD

**Issue by mgj** [Redth/ZXing.Net.Mobile#558]
I recently added ZXing to my xamarin.iOS project as could successfully scan QR codes (default settings, no options provided). However, i was completely unable to scan any type of 1D barcodes (EAN8, EAN18). I downgraded to 2.1.47, and using the same code, i can now scan both QR and 1D barcodes.

I tried providing options for 2.2.9, allowing only 1D barcodes as PossibleFormats, but the only result of that was being unable to scan QR codes as well as 1D barcodes

**Comment by hareshkainth** [comment]
Ive updated to the latest nuget packages in all three projects (PCL, iOS and Droid) - 2.2.9 but only iOS is working.

Android is able to show the camera but the QR code is not getting detected whereby, the OnScanResult is never getting called.

Ive downgraded the packages and yet its still not scanning any QR code on Android.

Please, please can someone please help me?

Regards

**Comment by hemantksh** [comment]
I am using it in my Xamarin.Forms project and have similar issue.
The 1D barcodes do not scan at all. However, when I turn my phone to landscape mode, it scans. 

**Probably the iOS one is not processing 1D scans in portrait mode.**
It seems to work fine on Android though.
It is a blocker and would be helpful if this can be resolved early. Thanks.

**Comment by hareshkainth** [comment]
@hemantksh Any chance you can share your code? I would like to compare with what I've written? Im happy to share the code that I've got (its the same code on James's blog on the Xamarin website). 

I tried both landscape and portrait but the code is not getting scanned. The android app shows the camera and I can the see QR code but nothing is happening.

**Comment by hemantksh** [comment]
Nothing fancy. Pretty straight. This is Xamarin.Forms.

`
var options = new ZXing.Mobile.MobileBarcodeScanningOptions();

            options.PossibleFormats = new List<ZXing.BarcodeFormat>() {
                ZXing.BarcodeFormat.CODE_39,
                ZXing.BarcodeFormat.CODE_93,
                ZXing.BarcodeFormat.CODE_128,
                ZXing.BarcodeFormat.EAN_13,
                ZXing.BarcodeFormat.QR_CODE
            };

            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                Options = options
            };

            zxing.OnScanResult += (result) =>
            {
                Device.BeginInvokeOnMainThread(async () =>
                {
                    zxing.IsAnalyzing = false;  // stop analysis
                    g.LastScanResult = result;
                    await Navigation.PopAsync(animated: false);  // close view
                });
            };
`

**Comment by Lapinou42** [comment]
I noticed if I use the same code from FragmentActivity (in the sample code), the camera works nice but no QR Code detected.

If I use the sample code for using it with Activity, it works great. It seems it doesn't recognize anything when I use a Fragment / FragmentActivity.

- Native project (Xamarin.iOS / Xamarin.Droid)
- Nuget package version : 2.2.9
- Android API level 18 (not tested above)
- iOS : not tested yet

**Comment by jorisM96** [comment]
I've got the same problem. 
Everything works fine on Android but there are some problems on iOS.
The iOS varient only recognises linear codes in landscape mode.
Someone found a workaround or a solution for this?

**Comment by jackyshek** [comment]
it is the same bug https://github.com/Redth/ZXing.Net.Mobile/issues/544

**Comment by ahmedalejo** [comment]
> @hemantksh Any chance you can share your code?

@hareshkainth why didn´t you share your code in the first place. That would simply help out

**Comment by hareshkainth** [comment]
@hemantksh and @ahmedalejo Sorry all, I got busy looking at the source code and was trying to figure out how to fix the issue. 

Below is my code, note, it works on iOS but on Android it doesn't scan anything.

var scanPage = new ZXingScannerPage();
var options = new MobileBarcodeScanningOptions
 {
    AutoRotate = false,
    UseFrontCameraIfAvailable = false,
    TryHarder = true,
    PossibleFormats = new List<ZXing.BarcodeFormat>
    {
        ZXing.BarcodeFormat.QR_CODE
    }
};

scanPage = new ZXingScannerPage(options)
{
    DefaultOverlayTopText = "Align code within the frame",
    DefaultOverlayBottomText = string.Empty,
    DefaultOverlayShowFlashButton = true
};

 scanPage.OnScanResult += (result) =>
{
    // Stop scanning
    scanPage.IsScanning = false;

    // Pop the page and show the result
    Device.BeginInvokeOnMainThread(() =>
   {
       // Do something.
   };
};

**Comment by pdonovan** [comment]
I downgraded to 2.1.47 because of this bug, but it seems that 1D barcodes still take an awfully long time to be detected, if at all. That's on my cheap Android device, I've not checked iOS yet.

Any chance of a comment from the author? Perhaps there's a functionality change that isn't documented yet?

**Comment by vasva** [comment]
Hello, same problem, IOS does not analyzing in portrait mode, when I rotate 1D code vertically it get read. Pls help.

**Comment by jackyshek** [comment]
@pdonovan  The long time problem should be affected by the device. version 2.1.47 works fine for me. The author seems that does not review the issues on this project.

**Comment by shanmugasundharamselvadurai** [comment]
Its working in Landscape mode not portrait(iOS). how to fix it in Portrait mode?

**Comment by kentfonager** [comment]
Not working here either in portrait mode ... have downgraded to 2.1.47, which is working :-(

**Comment by VCG707** [comment]
same story here 2.1.47 is the solution for now

**Comment by beylkhanovdamir** [comment]
wrote direct message to @Redth twitter (@redth), hope that he fix this issue asap

**Comment by hareshkainth** [comment]
I've downgraded the plugin to version 2.1.47 for Android and I can confirm that my Android app can scan QR codes again.

**Comment by shanmugasundharamselvadurai** [comment]
Hi,

I downgraded to 2.1.47 and portrait mode is working. @kentfonager  Thanks man its working fine and my customOverlay not displaying. How to fix it ?

**Comment by beylkhanovdamir** [comment]
@shanmugasundharamselvadurai 

The binding context of the `ZXingDefaultOverlay ` view was never set, so you will not see any your UI changes on it...

current solution of problem for me now is declaring `ZXingDefaultOverlay ` in behind code (or in viewmodel) and then we need to set BindingContext for the declared `ZXingDefaultOverlay ` to itself

**Comment by raymondarvidsson** [comment]
Hi,

Seems like I have similar problems.
iOS 11, iPhone 7. Can scan QR-codes with no problems. But ean13 I only can scan if the code is vertical - not horizontal like I want! Look at images. Why why why??

![vertical-works](https://user-images.githubusercontent.com/24684821/30845565-42c7df6e-a294-11e7-8df1-14ea8b53a3cc.png)
![horizontal not working](https://user-images.githubusercontent.com/24684821/30845566-42ca6810-a294-11e7-96df-2cb4880c8ed6.png)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by AthraaFaraj** [comment]
> @hemantksh and @ahmedalejo Sorry all, I got busy looking at the source code and was trying to figure out how to fix the issue.
> 
> Below is my code, note, it works on iOS but on Android it doesn't scan anything.
> 
> var scanPage = new ZXingScannerPage(); var options = new MobileBarcodeScanningOptions { AutoRotate = false, UseFrontCameraIfAvailable = false, TryHarder = true, PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE } };
> 
> scanPage = new ZXingScannerPage(options) { DefaultOverlayTopText = "Align code within the frame", DefaultOverlayBottomText = string.Empty, DefaultOverlayShowFlashButton = true };
> 
> scanPage.OnScanResult += (result) => { // Stop scanning scanPage.IsScanning = false;
> 
> ```
> // Pop the page and show the result
> Device.BeginInvokeOnMainThread(() =>
> ```
> 
> { // Do something. }; };
dear I used zxing in web it open camera scan from camera webcam but not scan from camera of mobile, what I have to do to make it scan from the mobile of tye phone
