### ISSUE TITLE
UWP - Package creation and release build fails

### ISSUE THREAD

**Issue by takacsalbert** [Redth/ZXing.Net.Mobile#560]
With v2.2.9, the package creation and release build fails. It works in debug though. It is sure that without referencing ZXing.Net.Mobile in our solution does not fail. We use ZXing.Net instead to be able to ship the app. But we like ZXing.Net.Mobile very much, so please let us know how to solve this issue. We use a number of other nuget packages and it may interfere with another one.
Thank you very much for your kind help.

We get the following errors:
ILT0005: 'C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\Tools\nutc_driver.exe @"C:\git\simple\win10\Main\obj\x86\Release\ilc\intermediate\MDIL\Main.rsp"' returned exit code 1	Main	C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets	1192	
Error		Error: NUTC301B:Internal Compiler Error: Assembly 'C:\git\simple\win10\Main\obj\x86\Release\ilc\intermediate\ILTransformed\ZXingNetMobile.ildll' not found	Main	C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets	1192

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
