### ISSUE TITLE
Would be appreciated if you guys can privide code detail or sample of how to print barcode to printer (using Xamarin)? 

### ISSUE THREAD

**Issue by TohWei** [Redth/ZXing.Net.Mobile#561]
Hi,
I am encountering issue of how to print barcode generated on iphone to printer. 
I was actually passing the ZXingBarcodeImageView (which is the barcode I have generated in Xamarin.Forms) from Xamarin.Forms to my dependency service (PrintViewService) in iOS. 

Within my PrintViewService,  I have applied UIPrintInteractionController.SharedPrintController. 
And, I have converted the ZXingBarcodeImageView to UIView in iOS. So that I can get the ViewPrintFormatter. 

Unfortunately, I couldn't make it work for me.  But the print preview show Blank. 

Besides, I can't find much information about how to print barcode generated by ZXing in iphone directly to physical printer with Xamarin.  :(

I am using:
ZXing.Net.Mobile version 2.2.9
ZXing.Net.Mobile.Forms version 2.2.9

Hopefully, the ZXing.Net contributor can continue provide more sample not only on SCANNING and GENERATING but also on PRINTING (to printer). 

Thanks,
Jeff

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
