### ISSUE TITLE
Question: whats the difference between IsAnalizing and IsScaning?

### ISSUE THREAD

**Issue by noChamp** [Redth/ZXing.Net.Mobile#562]
hi
I am sorry if this is not the place to ask questions, but I didn't find any answers on google \ StackOverflow to the question: whats the difference between IsAnalizing and IsScaning?
thanks in advance

**Comment by Ieeyo** [comment]
"IsScanning" makes camera active and "IsAnalyzing" tries to scan something I guess.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
