### ISSUE TITLE
Autofocus issue

### ISSUE THREAD

**Issue by AertsIT** [Redth/ZXing.Net.Mobile#564]
Hi, 

I have a separate thread for calling autofocus on android, the only problem is that autofocus only starts working after i have or enabled torch or manual focused one time. Anybody any clue how to fix this?

Code:
```
        public void autoFocusSystem()
        {
            do
            {
                Thread.Sleep(2000);
                scanner.AutoFocus();
                Console.WriteLine("Autofocus");
            } while ( scanResults == null && isScanning );
        }

        public async Task<string> ScanAsync()
        {
            Console.WriteLine("Start Scanning");
            Thread focusThread = new Thread(new Runnable(autoFocusSystem));
            isScanning = true;
            focusThread.Start();
            scanResults = await scanner.Scan(setOptions);
            isScanning = false;
            if (scanResults != null)
            {
                return scanResults.Text;
            } else {
                return null;
            }
        }
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
