### ISSUE TITLE
2.2.9 not scanning QR codes on Android

### ISSUE THREAD

**Issue by donmesserli** [Redth/ZXing.Net.Mobile#567]
I have a Xamarin.Forms app which has been working for about a year. It was using 2.1.0-beta1 and worked fine.  I recently updated it to 2.2.9 and now it won't scan QR codes under Android. It works fine under iOS. I went back to 2.1.12 and it works; but very slowly.

**Comment by leonardocastillo** [comment]
Hi, same happens to me.

I include 
MobileBarScanner.Initialize (Application);

before the scan method, and works.

**Comment by donmesserli** [comment]
This is a Form app. My code is exactly like the Forms sample in the source. It uses a ZXing.Net.Mobile.Forms.ZXingScannerView.  I don't know where your code would go.

**Comment by leonardocastillo** [comment]
just before the scan method. 

Example:
MobileBarcodeScanner.Initialize (Application);  				
MobileBarcodeScanner scanner; 				
scanner = new MobileBarcodeScanner();  				
scanner.UseCustomOverlay = false;  				
		//Start scanning 				
var result = await scanner.Scan();

**Comment by donmesserli** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Is this for Xamarin.Forms?


Sent from Yahoo Mail for iPhone


On Thursday, June 8, 2017, 2:39 PM, leonardocastillo <notifications@github.com> wrote:


just before the scan method.

Example:
MobileBarcodeScanner.Initialize (Application);  
MobileBarcodeScanner scanner; 
scanner = new MobileBarcodeScanner();  
scanner.UseCustomOverlay = false;  
//Start scanning 
var result = await scanner.Scan();

**Comment by donmesserli** [comment]
Is this in your shared code (i.e. ContentPage) or in an Android activity?

BTW - With my current code, the camera activates and I can see the QR Code; but it just doesn't recognize it and scan it.

**Comment by leonardocastillo** [comment]
Yes is a shared code. But i have another project with android activity with same result. 

And Yes, my app recognize and scan QR codes without problem.

**Comment by pedrofcj** [comment]
@donmesserli did you manage to fix it?
I had a similar issue but I was able to fix by setting "IsScanning" and "IsAnalyzing" to true (ZXingScannerView object) on "OnAppearing()" event on my ContentPage

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
