### ISSUE TITLE
Implement QRCode recognition as VideoEffect (similar to FaceDetectionEffect) usable with MediaCapture

### ISSUE THREAD

**Issue by Liero** [Redth/ZXing.Net.Mobile#568]
There are built in classes like SceneAnalasysEffect resp FaceDetectionEffect in UWP, see [scene-analysis-for-media-capture](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/scene-analysis-for-media-capture#face_detection_effect)

I would like to see manage UI and MediaCapture myself. Usage would be very familiar to what we already know from UWP sample apps:

```csharp
var definition = new QrCodeDetectionEffectDefinition(); 
_qrCodeDetectionEffect = (QrCodeDetectionEffect)await _mediaCapture.AddVideoEffectAsync(definition, MediaStreamType.VideoPreview); 
_qrCodeDetectionEffect .DesiredDetectionInterval = TimeSpan.FromMilliseconds(33);
// Start detecting qr codes 
_qrCodeDetectionEffect.Enabled = true; 
_qrCodeDetectionEffect.CodesDetected += QrCodeDetectionEffect_CodesDetected;

void QrCodeDetectionEffect_CodesDetected(QrCodeDetectionEffect sender, QrDetectedEventArgs args) 
{ 
   foreach (Windows.Media.VideoAnalysis.DetectedCode qrCode in args.ResultFrame.DetectedCodes) 
   { 
       BitmapBounds qrCodeRect = qrCode.BoundingBox; 
      // Draw a rectangle on the preview stream for each qrCodeRect 
   } 
}
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
