### ISSUE TITLE
ScannerView not work in a page nested in NavigationPage

### ISSUE THREAD

**Issue by anuith** [Redth/ZXing.Net.Mobile#569]
I created a `QRCodePage` with `ScannerView`

QRCodePage.xaml

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                xmlns:qr="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"
                xmlns:local="clr-namespace:Project.Namespace"
                x:Class="Project.Namespace.Pages.QRCode.QRCodePage">

        <ContentPage.Icon>tab_icon_qrcode.png</ContentPage.Icon>

        <ContentPage.BindingContext>
            <local:QRCodePageViewModel />
        </ContentPage.BindingContext>
        
        <ContentPage.ToolbarItems>
            <ToolbarItem Text="Close" Clicked="CloseButton_Clicked" />
        </ContentPage.ToolbarItems>

        <ContentPage.Content>
            <Grid BackgroundColor="Black">
                <qr:ZXingScannerView
                    x:Name="ScannerView" Margin="0.1"
                    HorizontalOptions="Fill"
                    VerticalOptions="CenterAndExpand"
                    OnScanResult="Scanner_OnScanResult" />
                <Label
                    VerticalOptions="Start"
                    BackgroundColor="#7F000000" TextColor="White"
                    Text="{Binding ResultText}" />
                <Image
                    VerticalOptions="End"
                    Source="footer_green.png" />
            </Grid>
        </ContentPage.Content>
    </ContentPage>

And call it within a modal :

    Navigation.PushModalAsync(new Namespace.Pages.QRCode.QRCodePage(OnQRCodeScanResult));

With the `OnQRCodeScanResult` function :

    private async void OnQRCodeScanResult(string text)
    {
        await Navigation.PopModalAsync();
        await DisplayAlert("QR Code Result", text, "OK");
    }

It's worked fine until I need to display this page with system navigation bar on top. So I changed the calling method to :

    Navigation.PushModalAsync(new NavigationPage(new Pages.QRCode.QRCodePage(OnQRCodeScanResult))
    {
        BarBackgroundColor = Color.DarkRed,
        BarTextColor = Color.White
    });

And it's not working anymore.

**Comment by matteopiccioni** [comment]
I have the same issue

**Comment by vjlomocso** [comment]
This is still not working for me. Same if wrapped in TabbedPage. But I found a workaround. If I don't include the ZXingScannerView in XAML and programmatically add it to the OnAppearing method override, it works as expected.

**Comment by PaulVrugt** [comment]
@vjlomocso 

This is because the package on nuget doesn't include this fix yet

**Comment by vjlomocso** [comment]
@PaulVrugt 
Is there any scheduled date on when it will be available?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
