### ISSUE TITLE
ZXing barcode IPad Portrait view

### ISSUE THREAD

**Issue by thedee** [Redth/ZXing.Net.Mobile#572]
I am having some issues with ZXing tool with Xamarin.Forms and on the IOS (ipad) platform. When I hold the IPad in the landscape position everything works find with scanning a barcode. When I hold the Ipad in the portrait (vertical) position and try to scan a barcode it doesn't work. It won't read the barcode until I rotate the barcode to a verticle (top/bottom) position. This seems to work fine on an Android no matter how I hold my phone. Just wondering if there is something I am missing?

Essentially my current code is as follows:

```
var scanPage = new ZXingScannerPage ();
// Navigate to our scanner page
await Navigation.PushAsync (scanPage);

scanPage.OnScanResult += (result) => 
{
    // Stop scanning
    scanPage.IsScanning = false;

    // Pop the page and show the result
    Device.BeginInvokeOnMainThread (async () => 
    {
        await Navigation.PopAsync ();        
        await DisplayAlert("Scanned Barcode", result.Text, "OK");
    });
};
```

Issue was also logged in the Xamarin forums at:
https://forums.xamarin.com/discussion/97422/zxing-barcode-reader

**Comment by carlasampaio01** [comment]
Is there a solution now?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
