### ISSUE TITLE
How do you build and run from source code - Error loading zxing.portable.csproj

### ISSUE THREAD

**Issue by DrBilitski** [Redth/ZXing.Net.Mobile#573]
How do you build and run from source code?
When I load the solution Zxing.Net.Mobile.sln, I get Error loading zxing.portable.csproj

I am trying to debug some issues I am having with scanning with iOS.

**Comment by micjahn** [comment]
I think the sources from the ZXing.Net submodule is missing in your case. You have to update the ZXing.Net submodule via git.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
