### ISSUE TITLE
Xamarin Forms sample doesn't build

### ISSUE THREAD

**Issue by julesx** [Redth/ZXing.Net.Mobile#574]
It complains about not knowing what a `Result` object is from a scan operation.

it is also using an older version of XF.

**Comment by DennisWelu** [comment]
This is a blocking issue for me even using the latest 2.x release, XF 2.5.1.527436. I've been keeping ZXing.Net.Mobile.Forms on version 2.3.2 the past few months to workaround.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
