### ISSUE TITLE
Latest Version is not Working in Xamarin.Form for iOS

### ISSUE THREAD

**Issue by dktechindia** [Redth/ZXing.Net.Mobile#576]
Latest version is not working in the XAMARIN.FORMS project. When Placed barcode in front of the camera then nothing happens. Below is my code :
` var scanPage = new ZXing.Mobile.MobileBarcodeScanner();

            scanPage.TopText = "Place the barcode between the red line";
            scanPage.CameraUnsupportedMessage = "Camera doesnt supports AUTOFOCUS.";
            scanPage.BottomText = "If it it is not scanning, turn FLASH on";
            scanPage.CancelButtonText = "<< Back";
            scanPage.FlashButtonText = "Toggle Flash";
            scanPage.UseCustomOverlay = false;
            scanPage.AutoFocus();
            ZXing.Result result = null;
            result = await scanPage.Scan(new MobileBarcodeScanningOptions
            {
                TryHarder = false,
                AutoRotate = false,
                UseNativeScanning = true,
                PossibleFormats = GetAvailableFormats(),
            });
            if (result != null && !string.IsNullOrWhiteSpace(result.Text))
            {
                await ProcessResult(result.Text);
            }`

The same code is working fine with good scanning speed for Windows and Android.

I have downgraded the version then it starts working but it is takes lot of time to detect the barcode. When I turn Flash on then it detects easily.

What I need to change to make it work in iOS like it is working in other platforms?

**Comment by julesx** [comment]
happening to me as well

**Comment by dktechindia** [comment]
I haven't tried it in landscape mode.

Please post here if you get any solution.

**Comment by QiMata** [comment]
Same problem. It is no longer working in iOS. Page appears but no on scan result.

**Comment by rohitvipin** [comment]
same issue cant get it to work in Portrait.

**Comment by beylkhanovdamir** [comment]
the same shit with landscape only for me

**Comment by rkorsak** [comment]
I have the same issue.  I was able to downgrade to 2.1.47 and get it to work.  I haven't tested every version in between, so hopefully there's a more recent one that works, but if you're in a rush then hopefully this helps.

**Comment by kcherdch** [comment]
Downgrading the 2.1.47 doesn't help. Seems like the owner has abandoned this project since there's no update for months.

**Comment by DottorPagliaccius** [comment]
Same issue here, I'm using version 2.1.47 which works fine.

**Comment by pedrofcj** [comment]
I had a similar issue but I was able to fix by setting "IsScanning" and "IsAnalyzing" to true on "OnAppearing()" event on my page (Xamarin Forms project, PCL)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
