### ISSUE TITLE
Torch not reactivated after orientation change

### ISSUE THREAD

**Issue by Ljusnan** [Redth/ZXing.Net.Mobile#577]
Hi, I have a button which toggles the torch with each Click event. When the torch is activated and I turn my phone to landscape mode, the torch is now off. It should be reactivated. I think this have to be fixed in OnConfigurationChanged in the ZxingActivity. Could you please look into this?

**Comment by Ljusnan** [comment]
I think I found the problem. You should also use ConfigChanges.ScreenSize to detect orientation change.
[Activity(Label = "CustomScanner", ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.KeyboardHidden | ConfigChanges.ScreenLayout | **ConfigChanges.ScreenSize**)]

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
