### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by roycornelissen** [Redth/ZXing.Net.Mobile#578]
Any chance there will be a version of ZXing.Net.Mobile soon which supports .NET Standard?

**Comment by ericbrunner** [comment]
See section "Referencing Non .NET Standard Libraries" maybe helpful. You can reference any PCL in .NET Standard you only need to install Xamarin.Forms 2.3.5.256-pre6 and add the PackageTargetFallback https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/

**Comment by mnusr** [comment]
Any plans for this?

**Comment by bradwyoung** [comment]
I have started a new Xamarin project and was getting ready to add this component and just ran into this issue.  Based on what I read, it seemed to me like going with .NET standard was the best direction to go today, preparing for the future.  So, are their plans to support this?  Is there a work around?  I am still early on with my project and barcode scanning is going to be a core part, so if I need to start over I would like to know.  If support for .NET standard is being worked on I could wait a little while.

**Comment by bradwyoung** [comment]
The other night when I was looking into this, I read @ericbrunner comment and went to the link but the article starts out talking upgrading and conversion.  As a result I glossed over it and determined it was not a solution.  With a fresh mind this morning, I started looking into this again and the solution is in that article and it is super simple.  So, to hopefully save somebody else some time I am going to include the solution here.   Xamarin.Forms 2.4 is out so you do not have to install a pre-release version, now.  In Visual Studio, right click on the shared .NET standard project and select 'Edit projectname.csproj'.  Then add PackageTargetFallback to the PropertyGroup section

```xml
<PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>
  </PropertyGroup>
```

This makes the project compatible with portable libraries.  You can then install the ZXing Xamarin forms Nuget package and everything works as expected.

**Comment by PaulVrugt** [comment]
I'm also waiting for .net standard support. Any news on this?

**Comment by mnusr** [comment]
Same here, now Xamarin's shared project is .NET Standard by default.
Any updates on this?

**Comment by dberroa** [comment]
Same. Starting new projects forces .NET Standard.

**Comment by devinZhou102** [comment]
Yeah，I‘m waiting for it too, now Xamarin's shared project is .NET Standard by default.
Any updates on this?

**Comment by 1cinisra1** [comment]
08/01/2018 I'm still wating for it, rayos.

**Comment by AgileCodeCO** [comment]
Please support .NET Standard,

**Comment by pablogarnica** [comment]
Hi, somebody knows when support for :NET standar will be available ? or if there are any workarround. Thank you.

**Comment by ericbrunner** [comment]
@pablogarnica see @bradwyoung comments at the begin. You can reference non .Net Standard in .Net Standard project

**Comment by pablogarnica** [comment]
​Thank you  for  your response​.

I need  ina Xamarin Project, but MicroSoft removes Xamarin PCL type  of
project.


anyway Thank you


Best Regards.



*Pablo Garnica S.*
Desarrollo de Software .Net
pablogarnica@gmail.com
pablogarnica@hotmail.com
SKYPE: pablo-garnica
Bogotá D.C. - Colombia
Cel. 315 - 469 9870

2018-01-11 15:04 GMT-05:00 Eric Brunner <notifications@github.com>:

**Comment by AgileCodeCO** [comment]
I pablo, i have a new xamarin forms project using .net standard 2.0 and I could use non .net standard libraries.  I my case I'm using a library compiled in framework 4.6 and after editing this line of code in the .csproj file it is working ok.

`<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>    
    <AssetTargetFallback>$(AssetTargetFallback);net46;</AssetTargetFallback>
  </PropertyGroup>`

**Comment by pablogarnica** [comment]
Thank you...

I will try.....


Best Regards

*Pablo Garnica S.*
Desarrollo de Software .Net
pablogarnica@gmail.com
pablogarnica@hotmail.com
SKYPE: pablo-garnica
Bogotá D.C. - Colombia
Cel. 315 - 469 9870

2018-01-12 17:18 GMT-05:00 AgileCodeCO <notifications@github.com>:

**Comment by godrose** [comment]
@AgileCodeCO  
For me It was added with warnings and results in exception in runtime.
Waiting for .net standard support. 
Maybe will just fork this repo

**Comment by ConfusedTA** [comment]
Just getting started with latest versions of VS and Xamarin for an app targeting iOS & Android which is going to be heavily based around barcode scanning, so adding my wishes for support for .Net Standard support!

**Comment by knight1219** [comment]
Is someone has a working sample with .net standard 2.0, can they upload it please?

**Comment by AgileCodeCO** [comment]
I have a working example with barcode scanner.  My code above:

1. Edit the .csproj

`<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>    
    <AssetTargetFallback>$(AssetTargetFallback);net46;</AssetTargetFallback>
  </PropertyGroup>`

2. Add nuget package 
![image](https://user-images.githubusercontent.com/11727573/35416518-58388bf6-01f7-11e8-95a9-8f5b1e9af103.png)

3. Create a Content page for scanner

![image](https://user-images.githubusercontent.com/11727573/35416577-8de06b16-01f7-11e8-9ccb-46cb7bc95d2f.png)

4. This is the code behind of the content page. In this example I'm opening this page in a modal.

`ZXingScannerView zxing;
        ZXingDefaultOverlay overlay;

        public event EventHandler<string> BarcodeReaded;

        public BarcodeScanner()
        {
            InitializeComponent();

            var options = new MobileBarcodeScanningOptions
            {
                AutoRotate = false,
                UseFrontCameraIfAvailable = false,
                TryHarder = true,
                PossibleFormats = new List<ZXing.BarcodeFormat>
                    {
                       ZXing.BarcodeFormat.EAN_8, ZXing.BarcodeFormat.EAN_13
                    }
            };

            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                Options = options
            };

            zxing.OnScanResult += (result) =>
                Device.BeginInvokeOnMainThread(async () =>
                {

                    // Stop analysis until we navigate away so we don't keep reading barcodes
                    zxing.IsAnalyzing = false;

                    BarcodeReaded?.Invoke(this, result.Text);

                    // Navigate away
                    await Navigation.PopModalAsync();
                });

            overlay = new ZXingDefaultOverlay
            {
                TopText = "Sostenga su teléfono sobre el código de barras",
                BottomText = "El código se escaneará automaticamente",
                ShowFlashButton = zxing.HasTorch,
            };

            overlay.FlashButtonClicked += (sender, e) =>
            {
                zxing.IsTorchOn = !zxing.IsTorchOn;
            };

            var abort = new Button
            {
                Text = "Cancelar",
                VerticalOptions = LayoutOptions.End,
                TextColor = Color.FromHex("#FFF"),
                BackgroundColor = Color.FromHex("#4F51FF")
            };

            switch (Device.RuntimePlatform)
            {
                case Device.iOS:
                    abort.HeightRequest = 40;
                    break;
                case Device.Android:
                    abort.HeightRequest = 50;                    
                    break;
            }

            abort.Clicked += (object s, EventArgs e) =>
            {
                zxing.IsScanning = false;

                Device.BeginInvokeOnMainThread(async () =>
                {
                    await Navigation.PopModalAsync();
                });
            };

            var grid = new Grid
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };

            grid.Children.Add(zxing);
            grid.Children.Add(overlay);
            grid.Children.Add(abort);

            // The root page of your application
            Content = grid;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            zxing.IsScanning = true;
        }

        protected override void OnDisappearing()
        {
            zxing.IsScanning = false;

            base.OnDisappearing();
        }`

5. In the android project you have to include this code in MainActivity.cs

`public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }`

6. Modify AndroidManifest with this permissions: 

`  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.FLASHLIGHT" />`

7. Modify info.plist to include this:

`<key>NSCameraUsageDescription</key>
	<string>Message</string>`

**Comment by jlhernandez1388** [comment]
@ConfusedTA 
I was having the same problem as you and it's the Live Player. Once I connected my Android and deployed the app, everything was working. That exception must be that it can't find the camera.

Hope this helps!

**Comment by ydydxhg** [comment]
Hi @AgileCodeCO 

I tried your solution, but my app crashed on start, with null reference exception. I didnt event implement the code, just add the nuget package and the deploy. 

Do you know what was wrong with this?

Thanks

**Comment by AgileCodeCO** [comment]
In my case I received the same error, but after clean and build the android project it works.

**Comment by ydydxhg** [comment]
@AgileCodeCO, so did you add the nuget package in both the form project and the android project?

**Comment by AgileCodeCO** [comment]
That's correct, you should import the package in all projects (Shared, Android, IOS or UWP if you have it).

**Comment by ydydxhg** [comment]
@AgileCodeCO

Great, that works for me now. I cleaned the whole solution and rebuild it

Thanks so much

**Comment by gmarbury** [comment]
The project you depend on ZXing.Net (https://github.com/micjahn/ZXing.Net) has created a NetStandard2.0 build a few days ago. Maybe now is a good time to add it to your project too.

**Comment by AdamGrzesiak** [comment]
I am also waiting for .NS 2 support

**Comment by knocte** [comment]
In the duplicate issue https://github.com/Redth/ZXing.Net.Mobile/issues/675 @Redth said "There's a 2.4.0-beta1 on nuget which has this. Please give it a try!"

**Comment by Terry1511512** [comment]
When using  the Xamarin Forms version of  2.4.0-beta 1, I get the following error when building:

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ZXingNetMobile, Version=2.4.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'ZXingNetMobile.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Ids2A.Android

**Comment by AdamGrzesiak** [comment]
@Terry1511512 
Check if it works on a device. I had the same problem when I run app on emulator and it turned out that this is because my emulator does not handle a camera.

**Comment by Terry1511512** [comment]
When compiling with Zxing.Net.Mobile.Forms it still get the original error:

Exception while loading assemblies: System.IO.FileNotFoundException: 
Could not load assembly 'ZXingNetMobile, Version=2.4.1.0, 
Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono 
for Android profile?
File name: 'ZXingNetMobile.dll'
    at 
Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference 
reference, ReaderParameters parameters)
    at 
Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver 
resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean 
topLevel)
    at 
Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver 
resolver)

**Comment by PaulVrugt** [comment]
@Terry1511512 see issue #703 
This is probably your problem

**Comment by Terry1511512** [comment]
Could very well be.
Mine is from a brand new project not after an update.

**Comment by PaulVrugt** [comment]
@Terry1511512 
that doesn't make any difference. The package is the package, it doesn't matter whether you update the package or install it from scratch

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by roycornelissen** [comment]
Awesome work @Redth! Thanks for persisting 😄
