### ISSUE TITLE
Error OnScanResult event

### ISSUE THREAD

**Issue by kam0u** [Redth/ZXing.Net.Mobile#579]
I update from an outdated version of ZXing.Net.Mobile (2.1.12) to the latest one (2.2.9)

Now i can't build my project because i get the following error:
CS0012: The type 'Result' is defined in an assembly that is not referenced. You must add a reference to assembly 'zxing.portable, Version=2.1.12.0, Culture=neutral, PublicKeyToken=null'.

My project has already referenced the zxing.portable.dll version 2.2.9.0 witch is expected after the update.

This is a snippet of my code, that was working fine before the update

            var opt = new MobileBarcodeScanningOptions
            {
                TryHarder = true,
                UseNativeScanning = true,
                PossibleFormats =
                    new List<BarcodeFormat>()
                    {
                        BarcodeFormat.All_1D,
                        BarcodeFormat.QR_CODE
                    }
            };

            scanPage = new ZXingScannerPage(opt, relative = CreateCustomOverlay());

            //This where i get the error
            scanPage.OnScanResult += (newResult) =>
            {
                scanPage.IsScanning = false;

                Device.BeginInvokeOnMainThread(() =>
                {
                    var result = string.Empty;

                    if (newResult != null)
                    {
                        if (newResult.BarcodeFormat == BarcodeFormat.CODE_39 && newResult.Text != string.Empty)
                            result = calculateCheckDigit(newResult.Text);
                        else
                            result = newResult.Text;

                        if (entrBarcode.IsVisible)
                            entrBarcode.Text = result;
                        else
                            entrBarcodeNoKeyboard.Text = result;
                    }

                    OnScannerResult?.Invoke(this, result);
                });
            };

**Comment by bmacadam** [comment]
I had a similar problem a few weeks ago.  Check to see if the source code for the zxing.portable project is actually there on your computer.  It is a submodule within the github project so if you download the source code as a zip file, the contents of the ZXing.Net folder will not be there.  You have to go to the ZXing.Net project and download it there.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
