### ISSUE TITLE
 Possible formats сonstraints (Android platform)

### ISSUE THREAD

**Issue by Alex-Dobrynin** [Redth/ZXing.Net.Mobile#580]
If set to possible formats only one item: QR_CODE, it also scans other formats like barcode.
It happens only on Android, on iOS it works like a charm.
exapmle of usage in PLC:
` var scanner = new ZXing.Mobile.MobileBarcodeScanner();

var opt = new ZXing.Mobile.MobileBarcodeScanningOptions();
opt.PossibleFormats.Add(ZXing.BarcodeFormat.QR_CODE);
			
var result = await scanner.Scan(opt); `

**Comment by Nanook** [comment]
I am also seeing this issue.  My app is Android only so cannot verify if IOS is working. 

I can verify that **2.1.47 works correctly** and that 2.2.5 and 2.2.9 do not. I have not tested any other versions.

I have included 2 snippets of code that demonstrate the methods I have tried. First an example of what works in 2.1.47 and not the current release

```
            List<BarcodeFormat> bco = new List<BarcodeFormat>();

            if (_2dMode)
            {
                bco.Add(BarcodeFormat.PDF_417);
                bco.Add(BarcodeFormat.DATA_MATRIX);
                bco.Add(BarcodeFormat.QR_CODE);
            }

            if (_1dMode || (!_1dMode && !_2dMode))
                bco.Add(BarcodeFormat.All_1D);

            _options.PossibleFormats = bco;
```

and to test if it was the All_1D mask I have also tried to to work around the issue by adding the items individually.

```
            if (_2dMode)
            {
                bco.Add(BarcodeFormat.PDF_417);
                bco.Add(BarcodeFormat.DATA_MATRIX);
                bco.Add(BarcodeFormat.QR_CODE);
            }

            if (_1dMode || (!_1dMode && !_2dMode))
            {
                bco.Add(BarcodeFormat.CODABAR);
                bco.Add(BarcodeFormat.CODE_39);
                bco.Add(BarcodeFormat.CODE_93);
                bco.Add(BarcodeFormat.CODE_128);
                bco.Add(BarcodeFormat.EAN_8);
                bco.Add(BarcodeFormat.EAN_13);
                bco.Add(BarcodeFormat.ITF);
                bco.Add(BarcodeFormat.RSS_14);
                bco.Add(BarcodeFormat.RSS_EXPANDED);
                bco.Add(BarcodeFormat.UPC_A);
                bco.Add(BarcodeFormat.UPC_E);
            }

            _options.PossibleFormats = bco;
```

When stepping through the code when only 1dMode is set to true. The scanner will always scans any barcode. I removed all .Add calls so only CODE_128 was specified and still it scanned anything I pointed the camera at.

**Comment by ApeksIT** [comment]
Same issue here on Android. Setting the constraint doesn't have any effect. Implementing a check method is an option as a work-a-round, but obviously defeats the purpose of the BarcodeFormat option.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
