### ISSUE TITLE
Android ZXing keeps crashing when its just displaying camera

### ISSUE THREAD

**Issue by Toine-db** [Redth/ZXing.Net.Mobile#581]
Did anyone see this behavior or messages before? 
I'm not scanning or focusing , etc.
(options are set to scan BarcodeFormat.CODE_128, BarcodeFormat.PDF_417)

Suddenly it gives (at random times, using latest ZXing for Xamarin on Android only)

07-05 16:56:28.155 D/Mono    ( 7859): GC_BRIDGE waiting for bridge processing to finish
07-05 16:56:28.214 I/art     ( 7859): Explicit concurrent mark sweep GC freed 5841(481KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 23MB/39MB, paused 854us total 56.976ms
07-05 16:56:28.216 D/Mono    ( 7859): GC_TAR_BRIDGE bridges 123 objects 8610 opaque 21292 colors 125 colors-bridged 123 colors-visible 123 xref 11 cache-hit 0 cache-semihit 0 cache-miss 2 setup 0.24ms tarjan 12.09ms scc-setup 0.34ms gather-xref 0.03ms xref-setup 0.00ms cleanup 0.43ms
07-05 16:56:28.216 D/Mono    ( 7859): GC_BRIDGE: Complete, was running for 60.76ms
07-05 16:56:28.216 D/Mono    ( 7859): GC_MINOR: (Nursery full) time 36.59ms, stw 37.41ms promoted 457K major size: 4144K in use: 3446K los size: 9216K in use: 7355K
07-05 16:56:30.296 E/mono-rt ( 7859): Stacktrace:
07-05 16:56:30.296 E/mono-rt ( 7859): 
07-05 16:56:30.296 E/mono-rt ( 7859):   at <unknown> <0xffffffff>
07-05 16:56:30.296 E/mono-rt ( 7859):   at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr) <0x0003f>
07-05 16:56:30.296 E/mono-rt ( 7859):   at (wrapper alloc) object.AllocVector (intptr,intptr) [0x0008a] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.296 E/mono-rt ( 7859):   at ZXing.Common.BitMatrix..ctor (int,int) [0x0003b] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.296 E/mono-rt ( 7859):   at ZXing.Common.HybridBinarizer.binarizeEntireImage () [0x00059] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.Common.HybridBinarizer.get_BlackMatrix () [0x00001] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.BinaryBitmap.get_BlackMatrix () [0x00011] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.PDF417.Internal.Detector.detect (ZXing.BinaryBitmap,System.Collections.Generic.IDictionary`2<ZXing.DecodeHintType, object>,bool) [0x00001] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.PDF417.PDF417Reader.decode (ZXing.BinaryBitmap,System.Collections.Generic.IDictionary`2<ZXing.DecodeHintType, object>,bool) [0x00009] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.PDF417.PDF417Reader.decode (ZXing.BinaryBitmap,System.Collections.Generic.IDictionary`2<ZXing.DecodeHintType, object>) [0x00003] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.MultiFormatReader.decodeInternal (ZXing.BinaryBitmap) [0x00055] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.MultiFormatReader.decodeWithState (ZXing.BinaryBitmap) [0x00011] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.297 E/mono-rt ( 7859):   at ZXing.BarcodeReaderGeneric`1<T_REF>.Decode (ZXing.LuminanceSource) [0x00089] in <f555e0a951974e28bef029338a77fd54>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.DecodeFrame (ApxLabs.FastAndroidCamera.FastJavaByteArray) [0x000ce] in <7c7c485bd9034360a95deed1c4c824b8>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at ZXing.Mobile.CameraAccess.CameraAnalyzer/<>c__DisplayClass27_0.<HandleOnPreviewFrameReady>b__0 () [0x0000e] in <7c7c485bd9034360a95deed1c4c824b8>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.InnerInvoke () [0x00010] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.Execute () [0x00011] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.ExecutionContextCallback (object) [0x00006] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00073] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00004] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.298 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) [0x00054] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.ExecuteEntry (bool) [0x0005e] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859):   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00002] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00075] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859):   at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0001f] in <3fe7570511ba4102b1280417244c7c4b>:0
07-05 16:56:30.299 E/mono-rt ( 7859): /proc/self/maps:

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
