### ISSUE TITLE
Doesn't recognise scan until app re-opened on Android (2.2.9)

### ISSUE THREAD

**Issue by brucewilkins** [Redth/ZXing.Net.Mobile#582]
In a Xamarin Forms app, ZXing is setup as follows:

```
protected override void OnCreate(Bundle bundle)
        {
            ...
            ZXing.Net.Mobile.Forms.Android.Platform.Init();
            ////ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);            

            Forms.Init(this, bundle);
            LoadApplication(new App(kernel));
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);            
        }
```

When using 2.1.47 the app would crash after requesting permissions using:

`ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);`

Since upgrading to 2.2.9 the app no longer crashes after requesting permissions but scanning doesn't work until the app is re-opened. The camera initialises but doesn't recognise a QR code. Scanning is done using `<zxing:ZXingScannerView   IsScanning="True" IsAnalyzing="True"`

Calling MobileBarcodeScanner.Initialize(Application);  doesn't seem to have any effect.

Please advise a work around (or fix) for either permissions crash on 2.1.47, or scanning not working on 2.2.9.

iOS works as expected.

**Comment by Ryuasd** [comment]
I've also the same problem. After it ask the permission for the camera, the OnScanResult in never called after scanning QR Code.
If you reopen the ZXingScannerPage then it scan correctly.

Any workaround? I can't deliver an app where customers need to start a scan, then back or close, and scan again..

**Comment by Redth** [comment]
Well for now you can ask for the permissions a bit sooner manually in your app, but yes this needs to be fixed.

**Comment by MatthewGerber** [comment]
@Redth I am still seeing this error in 2.4.1. The app does not crash after requesting permissions, but scanning doesn't work until the app is re-opened (or scanning is restarted). Related to #717.
