### ISSUE TITLE
Torch not working properly

### ISSUE THREAD

**Issue by Auhmaan** [Redth/ZXing.Net.Mobile#584]
The torch options within `MobileBarcodeScanner` ( `ToggleTorch` / `Torch` ) don't work as intended. After using any of them to turn the torch on, the `IsTorchOn` property reports that the torch is on while is not.

The code I'm using to show a scanner and toggle the torch is the following:

    private void ReadQRCode() {
        Task.Run( async delegate {
            try {
                MobileBarcodeScanner
                    mobileBarcodeScanner = new MobileBarcodeScanner();

                View
                    mobileBarcodeScannerCustomOverlay = LayoutInflater.Inflate( Resource.Layout.ZXingScannerCustomOverlayLayout, null );

                mobileBarcodeScannerCustomOverlay.ApplyThemeColor();

                mobileBarcodeScannerCustomOverlay.FindViewById<ImageButton>( Resource.Id.ZXingScannerCustomOverlay_TorchToggle ).Click += ( eventSender, eventArgs ) => {
                    mobileBarcodeScanner.ToggleTorch();

                    if( mobileBarcodeScanner.IsTorchOn ) {
                        ( eventSender as ImageButton ).SetColorFilter( Resources.GetColor( Resource.Color.White ) );
                    } else {
                        ( eventSender as ImageButton ).SetColorFilter( Resources.GetColor( Utils.AppColorResourceId ) );
                    }
                };

                mobileBarcodeScanner.UseCustomOverlay = true;
                mobileBarcodeScanner.CustomOverlay = mobileBarcodeScannerCustomOverlay;

                ZXing.Result
                    result = await mobileBarcodeScanner.Scan();

                if( result != null ) {
                    // Do something...
                }
            } catch( Exception exception ) {
                Utils.LogException( exception );
            }
        } );
    }

**Comment by Ljusnan** [comment]
Does your app have the flashlight permission?

**Comment by Auhmaan** [comment]
No, I had not the flashlight permission set on the manifest. At the time, I made a quick search on the [Manifest.permission](https://developer.android.com/reference/android/Manifest.permission.html) page Google has listing the, supposed, full list of permission within Android.

It seems that the list is incomplete. I've managed to discover the permission, and added it to the manifest.

Either way, shouldn't this library make an extra check? Having it returning `true` on `IsTorchOn` can be somewhat frustrating for someone who doesn't know that much about Android, like me.

**Comment by Ljusnan** [comment]
For beginners this is in the readme:

_The Camera permission should be automatically included for you in the AndroidManifest.xml however if you would like to use the Torch API's you will still need to add the Flashlight permission yourself. You can do this by using the following assembly level attribute:

[assembly: UsesPermission (Android.Manifest.Permission.Flashlight)]_

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
