### ISSUE TITLE
UWP front camera. How to show mirrored picture ?

### ISSUE THREAD

**Issue by reinisnud** [Redth/ZXing.Net.Mobile#585]
Hello I am totally loving ZXing, just have this issue with front camera that it shows direct image not mirrored and it is hard to aim QR code thats why. How is it possible to show the image mirrored like in all built in camera Apps?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
