### ISSUE TITLE
sample code keep crashing on start

### ISSUE THREAD

**Issue by muteddisk** [Redth/ZXing.Net.Mobile#586]
Hi,
I've downloaded the sample code. however, when I build the package and run it on actual samsung s4 the app keeps crashing on start. I tried to see with logcat. here's the log. for what I see this is the error 
Time	Device Name	Type	PID	Tag	Message
07-11 09:54:18.977	Samsung SGH-I337M	Warning	1045	System.err	java.io.FileNotFoundException: /data/app/com.altusapps.zxingnetmobile-1: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at android.content.pm.PackageParser.getHashValueOfPackage(PackageParser.java:5071)
	at com.android.server.pm.PackageManagerService.saveHash(PackageManagerService.java:18033)
	at com.android.server.pm.PackageManagerService.access$5100(PackageManagerService.java:325)
	at com.android.server.pm.PackageManagerService$21.run(PackageManagerService.java:18018)
07-11 09:52:38.919	Samsung SGH-I337M	Debug	1045		TIMA: QCOM_send_command--int8_t QCOM_send_command(TIMA_handle_t, void*, uint32_t, void*, uint32_t, uint32_t)

------

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
