### ISSUE TITLE
Android crash after receiving result and use Navigation.PushAsync

### ISSUE THREAD

**Issue by CR4567** [Redth/ZXing.Net.Mobile#588]
Hi,

after I upgrade to the recent version (2.8) I get an error in my code. 
I'm using a ZXingScannerPage which is pushed to the NavigationStack (not modal).
And then I use following code for the result:

```
scanPage.OnScanResult += (result) =>
{
  Device.BeginInvokeOnMainThread(async() =>
    {
      scanPage.IsAnalyzing = false;
       scanPage.IsScanning = false;
	if (!scanFinished)
       {
	     scanFinished = true;
            UserDialogs.Instance.ShowSuccess(AppResources.SUCCESS);
	    EasierLifeApp.Current.Navigation.PushAsync(new WelcomePage(result.Text));
	}
    });
};
```

This code worked before. But now I get an error in the CameraController. ([Stacktrace.txt](https://github.com/Redth/ZXing.Net.Mobile/files/1155931/Stacktrace.txt)
) This happens only when Push to the Stack. A pop is still working but not wanted.

I looked a little bit into the code and for me it looks like this methods are called because of the SurfaceChanged. But why did it change? It's completely working in iOS, so maybe also related the new FastCamera of android.

Any ideas?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
