### ISSUE TITLE
Android: FragmentScanning is not working

### ISSUE THREAD

**Issue by Zexuz** [Redth/ZXing.Net.Mobile#589]
The example that is [here](https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Android/Sample.Android/FragmentActivity.cs) is not working for me. 

* Downloaded the whole source code. 
* Lunched the Android.Sample project. 
* Added ZXing via nuget version 2.2.9

Every other sample worked, but not that one.

Also tried to implement this is my own app and that did not work either, then I tried to download the sample app and run that one. It also did not work.

App was run on Android, Oneplus 3T, Android version 7.1.

**Comment by advdm** [comment]
I am experincing the same issue.
Works fine on Android 5 and Android 6.0.1

**Comment by furiousbuilder** [comment]
Same bug, any solutions?

**Comment by Zexuz** [comment]
@furiousbuilder look into Google.Vision, that is what I'm doing

**Comment by furiousbuilder** [comment]
Thanks @Zexuz, I'll try! I'll search some samples for Xamarin

**Comment by lijo007** [comment]
I too had same issue and I got it fixed...it's due to the delay of commit of fragment transaction.

Add SupportFragmentManager.ExecutePendingTransactions(); just after commit to forcefully do this.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
