### ISSUE TITLE
new iOS 10/Xamarin version doesn't scan in Portrait in newer versions of ZXing.Net

### ISSUE THREAD

**Issue by xDelivered-Patrick** [Redth/ZXing.Net.Mobile#590]
Now will only scan in Landscape mode. 
Portrait mode does not call the event ScanResult. 

Have reverted to a few combinations of nuget packages, and on a very small test project with no success. I imagine it's related to the new mono versions that shipped with recent versions of Xamarin/Visual Studio.

**Comment by xDelivered-Patrick** [comment]
Can confirm a rollback to 2.1.47 works. 
It must be applied to both ZXing.Net.Mobile and ZXing.Net.Mobile.Forms to fix the issue.

**Comment by agrigg** [comment]
+1 I'm seeing this as well

**Comment by Eiskaltereistee** [comment]
+1

**Comment by dlloyd525** [comment]
+1 Same here

**Comment by aphex3k** [comment]
Hello?

**Comment by lewixlabs** [comment]
Today, with latest nuget version, adding
`qrcodeScannerView.Options.UseNativeScanning = true;`
forces iOS to use AVCaptureEngine and it solved this issue (scanning working in landscape mode only) letting me scan in portrait mode too.

I know it's not the most "elegant" solution :) but i think it's a workaround, keeping latest (.net standard compliant) ZXing Nuget version

P.S.: trying this workaround with android all working without issue.

Hi!
Lewix

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
