### ISSUE TITLE
Music starts playing randomly when using the zxing scanner

### ISSUE THREAD

**Issue by mheijkant** [Redth/ZXing.Net.Mobile#594]
I created a default Xamarin Project added ZXing and followed the sample to start the scanner.
I't doesn't always work, but most of the times it does; when starting the scanner, not using it and then returning to the previous screen, "Google Music Play" is started and play's music.
The app is running on a Samsung S5 Neo, Andois 6.0.1.

I'ts weird, but does anyone have a simular problem?

**Comment by jbustillos** [comment]
Bump, error present on Galaxy J1 mini

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
