### ISSUE TITLE
Generate QR_CODE  Chinese garbled

### ISSUE THREAD

**Issue by l2999019** [Redth/ZXing.Net.Mobile#595]
My Code

            barcode = new ZXingBarcodeImageView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingBarcodeImageView",
            };
            barcode.BarcodeFormat = ZXing.BarcodeFormat.QR_CODE;
            //barcode.BarcodeOptions.PureBarcode;
            barcode.BarcodeOptions.Width = 300;
            barcode.BarcodeOptions.Height = 300;
            barcode.BarcodeOptions.Margin = 10;
            //Set here in Chinese
            barcode.BarcodeValue ="中文";

            Content = barcode;

The generated image scan is garbled

**Comment by micjahn** [comment]
You should set the character set:
`barcode.BarcodeOptions = new ZXing.QrCode.QrCodeEncodingOptions
{
   CharacterSet = "GB2312",
   Width = 300,
   Height = 300,
   Margin = 10
}`

**Comment by l2999019** [comment]
Thank you for your answer
But I did not find it CharacterSet = "GB2312" this property
Maybe I used the reason for ZXing.Net.Mobile.Forms
I found the solution
The code is as follows:
            barcode.BarcodeFormat = ZXing.BarcodeFormat.QR_CODE;
            ///this
            var date = barcode.BarcodeOptions.Hints.ContainsKey(ZXing.EncodeHintType.CHARACTER_SET);
            if (!date)
            {
                barcode.BarcodeOptions.Hints.Add(ZXing.EncodeHintType.CHARACTER_SET, "UTF-8");
            }
            ///End

**Comment by KoKoHomask** [comment]
public Stream ConvertImageStream(string text, int width = 300, int height = 130)
        {

            var barcodeWriter = new ZXing.Mobile.BarcodeWriter
            {
                Format = ZXing.BarcodeFormat.QR_CODE,
                Options = new ZXing.Common.EncodingOptions
                {
                    Width = width,
                    Height = height,
                    Margin = 10,
                }
            };
            var date=barcodeWriter.Options.Hints.ContainsKey(ZXing.EncodeHintType.CHARACTER_SET);
            if (!date)
            {
                barcodeWriter.Options.Hints.Add(ZXing.EncodeHintType.CHARACTER_SET, "UTF-8");
            }
            barcodeWriter.Renderer = new ZXing.Mobile.BitmapRenderer();
            var bitmap = barcodeWriter.Write(text);
            var stream = new MemoryStream();
            bitmap.Compress(Bitmap.CompressFormat.Png, 100, stream);  // this is the diff between iOS and Android
            stream.Position = 0;
            return stream;
        }

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
