### ISSUE TITLE
ZXingScannerView crash after navigation and device orientation change

### ISSUE THREAD

**Issue by hamalaiv** [Redth/ZXing.Net.Mobile#596]
I'm experiencing a crash on Android with ZXingScannerView. After navigating away from the page that contains ZXingScannerView and then rotating the device I get the following NullReferenceException:

    08-02 07:18:06.136 I/MonoDroid( 3315): UNHANDLED EXCEPTION:
    08-02 07:18:06.164 I/MonoDroid( 3315): System.NullReferenceException: Object reference not set to an instance of an object.
	08-02 07:18:06.164 I/MonoDroid( 3315):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0 
	08-02 07:18:06.164 I/MonoDroid( 3315):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0 
	08-02 07:18:06.164 I/MonoDroid( 3315):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0 
	08-02 07:18:06.164 I/MonoDroid( 3315):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0 
	08-02 07:18:06.164 I/MonoDroid( 3315): --- End of stack trace from previous location where exception was thrown ---

**Edit**
This occured when I set IsScanning to false before navigating away from the view. If the IsScanning is left to true the crash does not happen.

**Comment by voydz** [comment]
Can confirm this. This is reproducible with the steps mentioned from @hamalaiv

**Comment by mddoct** [comment]
Can confirm this issue. Occurs also when navigating away to a page having navigation bar switched off (what means screen size change, similar to orientation change).
I was NOT able to prevent the crash by setting IsScanning to true.

**Comment by mohammadomt** [comment]
Same problem here!

**Comment by nickkimbrough** [comment]
I can confirm my application also has this bug. I have locked the orientation for the time being to prevent it from happening.

**Comment by kyluke** [comment]
I can confirm, I am also facing this issue.

```
Exception android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object 
at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <4335976d2d864b7aa7f7e46cc3f3f4a6>:0 at 
ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <4335976d2d864b7aa7f7e46cc3f3f4a6>:0 at 
ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <4335976d2d864b7aa7f7e46cc3f3f4a6>:0 at 
ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <4335976d2d864b7aa7f7e46cc3f3f4a6>:0 --- End of stack 
trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [
0x0000c] in <37a31ccf08fd4f20af64d9ebed234ebe>:0 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (
System.Object state) [0x00000] in <37a31ccf08fd4f20af64d9ebed234ebe>:0 at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 
() [0x00000] in <86811389e9d14b249a525993913127e5>:0 at Java.Lang.Thread+[REDACTED_DOMAIN_NAME] () [0x00008] in 
<86811389e9d14b249a525993913127e5>:0 at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [
0x00008] in <86811389e9d14b249a525993913127e5>:0 at (wrapper dynamic-method) System.Object:beb9acdb-0851-4c22-991d-8c9b0fbdfd56 (
intptr,intptr) 
```

**Comment by ptsiogas** [comment]
System.NullReferenceException: Object reference not set to an instance of an object   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0    at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0    at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0    at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cae231546d874fcd9cbfc1cb24cbe39e>:0    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <cae231546d874fcd9cbfc1cb24cbe39e>:0    at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <a658b77358e142748ca622c19c1e27b5>:0    at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a658b77358e142748ca622c19c1e27b5>:0    at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <a658b77358e142748ca622c19c1e27b5>:0    at (wrapper dynamic-method) System.Object:f86bf7af-2993-4a49-a544-1c0463c8fb8d (intptr,intptr)

**Comment by helzgate** [comment]
Does anyone know where we can gracefully catch this error?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
