### ISSUE TITLE
Unhandled Exception while scanning and rotating device on UWP

### ISSUE THREAD

**Issue by kedrzu91** [Redth/ZXing.Net.Mobile#598]
Library: ZXing.Net.Mobile.Forms version 2.2.9
Platform: UWP, Release version
Phones: 
    Lumia 930 (RM-1045), OS build 10.0.14393.1480
    Lumia 640 LTE (RM-1072), OS build 10.0.14393.1066

I'm trying to scan QR code with following code:

```
var scanPage = new ZXingScannerPage();
scanPage.OnScanResult += result =>
{
    scanPage.IsScanning = false;
    if (!string.IsNullOrEmpty(result.Text))
	{
		Device.BeginInvokeOnMainThread(async () =>
		{
			await Navigation.PopAsync();
			await DoSomethingWithResult(result.Text);
		});
	}
};

await Navigation.PushAsync(scanPage);
```

When I rotate device while scanning, app crashes with following exception:

> 
> System.ArgumentException: An item with the same key has already been added.
>    at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Add[K,V](K key, V value)
>    at ZXing.Mobile.ZXingScannerControl.<SetPreviewRotationAsync>d__78.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ZXing.Mobile.ZXingScannerControl.<displayInformation_OrientationChanged>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
>    at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Add[K,V](K key, V value)
>    at ZXing.Mobile.ZXingScannerControl.<SetPreviewRotationAsync>d__78.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ZXing.Mobile.ZXingScannerControl.<displayInformation_OrientationChanged>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

I've tested this on other phones (Lumia 950 XL , OS build 10.0.15063.483, Lumia 532  OS build 10.0.14393.1480)  and issue does not occurre.

**Comment by techfooninja** [comment]
Hitting the same issue. I got around this using a renderer to make this work in UWP (NOTE: I'm using the ZXingScannerPage in my project):

```
using MyProject.UWP.Renderers;
using Windows.Graphics.Display;
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using ZXing.Net.Mobile.Forms;

[assembly: ExportRenderer(typeof(ZXingScannerPage), typeof(ZXingFixedOrientationScannerPageRenderer))]
namespace MyProject.UWP.Renderers
{
    public class ZXingFixedOrientationScannerPageRenderer : PageRenderer
    {
        protected bool Initialized { get; set; }
        protected DisplayOrientations AutoRotationPreferences { get; set; }

        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null && !Initialized)
            {
                Initialized = true;
                AutoRotationPreferences = DisplayInformation.AutoRotationPreferences;

                e.NewElement.Appearing += (s, args) =>
                {
                    DisplayInformation displayInfo = DisplayInformation.GetForCurrentView();
                    DisplayInformation.AutoRotationPreferences = displayInfo.CurrentOrientation;
                };

                e.NewElement.Disappearing += (s, args) =>
                {
                    DisplayInformation.AutoRotationPreferences = AutoRotationPreferences;
                };
            }
        }
    }
}
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
