### ISSUE TITLE
zxing.portable missing from checkout

### ISSUE THREAD

**Issue by SummersT** [Redth/ZXing.Net.Mobile#599]
Full disclosure...this is probably user error, but I'm missing the zxing.portable project in the source for ZXing.Net.Mobile.Forms solution.  The solution references Source\ZXing.Net\Source\lib\zxing.portable.csproj but I don't see this on the website either.

**Comment by micjahn** [comment]
The sources from the ZXing.Net submodule are missing in your case. You have to update the ZXing.Net submodule via git.

**Comment by SummersT** [comment]
I think I understand.  The ZXing.Net folder is "ZXing.Net @ 2a30ba9" which didn't clone to me.  The ZXing.Net folder is empty.
