### ISSUE TITLE
ZXingScannerPage OnScanResult event is raised to often

### ISSUE THREAD

**Issue by thetrust3343** [Redth/ZXing.Net.Mobile#601]
When i am scanning, the Event OnScanResult is raised up to 4 times. In my example it then opens 4 times the same page.
`var scanPage = new ZXingScannerPage(new  ZXing.Mobile.MobileBarcodeScanningOptions() { PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE}});         
            scanPage.DefaultOverlayShowFlashButton = true;

            scanPage.OnScanResult += (result) =>
            {
                scanPage.IsScanning = false;
                scanPage.IsAnalyzing = false;

                Device.BeginInvokeOnMainThread(async () =>
                {
                    await Navigation.PopAsync();
                    Navigation.PushAsync(new QuestionPage(), result.Text));
                    //await DisplayAlert("Scanned Barcode", result.Text, "OK");
                });
            };`

**Comment by justjoeyuk** [comment]
Yeah, I get this @thetrust3343 - were you using a Nexus?

**Comment by LentoMan** [comment]
It would have been nice with a setting to only accept one result and then disable scanning/analyzing, for now you can try setting the **DelayBetweenContinuousScans** value to something like 5000 (ms) in your MobileBarcodeScanningOptions.

**Comment by thetrust3343** [comment]
@justjoeyuk 
No i'm using a Samsung Galaxy S5 and a HTC One M8. But what @LentoMan wrote works fine as a simple workaround.

**Comment by wegascee** [comment]
I have the same problem on iPhone/iPad. `PopModalAsync()` is therefore called too often, which crashes the app with

>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection

I'm using ZXing.Net.Mobile 2.2.9 and ZXing.Net.Mobile.Forms 2.2.9. The advice from LentoMan didn't help. Now I upgraded to 2.3.2 without success.

My solution for now is that I use a variable to prevent calling `PopModalAsync()` too often like [here](https://stackoverflow.com/a/43476170/426227).

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
