### ISSUE TITLE
Forms - IOS: Scanner don't scan

### ISSUE THREAD

**Issue by jonahbohlmann** [Redth/ZXing.Net.Mobile#603]
Hi,
i have this code: 
```csharp
var formatList = new List<ZXing.BarcodeFormat>() {
	/*ZXing.BarcodeFormat.All_1D,
	ZXing.BarcodeFormat.AZTEC,
	ZXing.BarcodeFormat.CODABAR,
	ZXing.BarcodeFormat.CODE_128,*/
	ZXing.BarcodeFormat.CODE_39,
	/*ZXing.BarcodeFormat.CODE_93,
	ZXing.BarcodeFormat.DATA_MATRIX,*/
	//ZXing.BarcodeFormat.EAN_13,
	//ZXing.BarcodeFormat.EAN_8,
	/*ZXing.BarcodeFormat.IMB,
	ZXing.BarcodeFormat.ITF,
	ZXing.BarcodeFormat.MAXICODE,
	ZXing.BarcodeFormat.MSI,
	ZXing.BarcodeFormat.PDF_417,
	ZXing.BarcodeFormat.PLESSEY,
	ZXing.BarcodeFormat.QR_CODE,
	ZXing.BarcodeFormat.RSS_14,
	ZXing.BarcodeFormat.RSS_EXPANDED,
	ZXing.BarcodeFormat.UPC_A,
	ZXing.BarcodeFormat.UPC_E,
	ZXing.BarcodeFormat.UPC_EAN_EXTENSION*/
};

var options = new ZXing.Mobile.MobileBarcodeScanningOptions()
{
	TryInverted = true,
	TryHarder = true,
	PossibleFormats = formatList,
}; 

scanPage = new ZXingScannerPage(options, null);

scanPage.OnScanResult += (result) =>
{
	scanPage.IsScanning = false;

	Device.BeginInvokeOnMainThread(() =>
	{
	    Navigation.PopModalAsync();
		DisplayAlert("Scanned Barcode", result.Text, "OK");
	});
};

await Navigation.PushModalAsync(scanPage);
```

The View and Camera starts successful, but the result event is never fired.
I checked very much Codes but never get any right result.

Can anybody help me?

**Comment by Eiskaltereistee** [comment]
Fixed: have a look at this issue: https://github.com/Redth/ZXing.Net.Mobile/issues/590

Downgraded to older version.

**Comment by Hyeonmyeong-Ji** [comment]
iOS 10 over..... Info.plist Add
	<key>NSCameraUsageDescription</key>
	<string>Can we use your camera</string>

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
