### ISSUE TITLE
Use torch setting

### ISSUE THREAD

**Issue by JKorsten** [Redth/ZXing.Net.Mobile#608]
Hey,

I'm trying to use the torch in my app using ZXing. This works for me.
But now people are requesting a feature which is also available in the ZXing android app, which is the setting to set Torch setting to On/Off/Automatic.
Is this possible?

Kind regards,

Jeroen Korsten

**Comment by miragedmuk** [comment]
Unfortunately I too have had issues with the torch settings on the latest version of Zxing.net.mobile and my Samsung Galaxy S7 running API 24.

No matter what I tried Zxing gave me a false result for ZXingScannerPage.HasTorch.  

I decided to determine how to do this myself within the droid xamarin project using DI from the PCL.  It seems that the Android.Hardware.Camera class is obsolete/deprecated in later versions of android and we have to now use Android.Hardware.Camera2

It's a nice simple call using the new method - create an instance of CameraManager then using that you can issue CameraManager.SetTorchMode("0", true)

Loaded my app, activated the torch hit the scan button to bring up the ZXingScannerPage created earlier.. flash goes off!!

Investigating the code it appears that this Zxing library implements the deprecated Android.Hardware.Camera class which has limited (seems ok turning torch off) functionality on later versions of the Android OS.

ZXing.Net.Mobile/Source/ZXing.Net.Mobile.Android/CameraAccess/Torch.cs

It may be possible to issue a pull request, I'm quite new to github so not fully sure how that works.  If we decide to use it ourselves I'm considering forking my own copy of the code to implement both versions of the camera/torch api.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
