### ISSUE TITLE
System.MissingMethod

### ISSUE THREAD

**Issue by jonahbohlmann** [Redth/ZXing.Net.Mobile#611]
Hi,

I use xamarin forms and the xamarin forms version of zxing.

I have the newest version in my android project. 
On iOS it works fine.

On Android I got the following error after starting the Scanner:
![screenshot 2017-08-24 16 09 33](https://user-images.githubusercontent.com/9147768/29670331-a74ce5be-88e6-11e7-91ef-3ba23fee39e1.png)

Does anybody have an idea?

**Comment by mobiletonster** [comment]
I get the same issue but only on Android 6.0 version. 8.0 works fine, 7.1 works fine...just 6.0...not sure what the issue is.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
