### ISSUE TITLE
ZXingScannerFragment not working

### ISSUE THREAD

**Issue by HakanCelikMK1** [Redth/ZXing.Net.Mobile#612]
I've tried to use ZXingScannerFragment to embed the scanner into my activity, but it doesn't recognize any barcodes. I'm using Xamarin.Android for this project.

I've also downloaded Sample.Android project from here and installed ZXing.Net.Mobile 2.2.9 from NuGet into it. Normal scanning works perfectly, but when I tap Fragment Scaner button, scanner shows but doesn't recognize a 1D or 2D barcode. 

I've even tried to PauseAnalysis / ResumeAnalysis to no effect.

I'm at a loss, since ZXingScannerFragment is using the same underlying engine.
Any help would be appreciated very highly.

My environment 
Windows 10 Enterprise x64 : Version 10.0.15063 Build 15063
Microsoft Visual Studio Enterprise 2015 : Version 14.0.25431.01 Update 3
Microsoft .NET Framework : Version 4.7.02046
Xamarin : 4.6.0.297 (4a8abec)
Xamarin.Android : 7.4.0.19 (0cd0214)
Java : jdk1.8.0_112
Andorid SDK up to date

P.S. : If it makes any difference, I'm testing on a Samsung Galaxy Note 3 with Android 5.0.

**Comment by Drutol** [comment]
I'm experiencing the same issue, oddly running continuous scanning in sample app makes scanner fragment in my app work...

**Comment by lijo007** [comment]
I having same issue and I got it fixed...it's due to the delay of commit of fragment transaction.

Add SupportFragmentManager.ExecutePendingTransactions(); just after commit to forcefully do this.

**Comment by HakanCelikMK1** [comment]
@lijo007 Thank you, excellent finding. I've made the sample work using your solution. Now I can make my app work too.
Great job !

**Comment by LionetChen** [comment]
@lijo007 Thanks a million! Saved my day
