### ISSUE TITLE
OnScanResult doesn't fire when resuming XF App

### ISSUE THREAD

**Issue by markleavesley** [Redth/ZXing.Net.Mobile#618]
Hello,

I'm using more or less the "usage" example from the XF site (https://components.xamarin.com/gettingstarted/zxing.net.mobile.forms). This works fine until I go to another app and come back. When I come back the camera is on and focussing on barcodes but the OnScanResult event doesn't fire.

This is on Android 7 (HTC 10), I don't have a UWP or iOS device to try it on. Latest versions of everything (XF, VS, nugets, etc)

I'm fairly new to XF so maybe I am missing something?

Thanks

**Comment by markleavesley** [comment]
OK, this seems to be a debug build/VS issue. I removed the app from my phone, made an APK in release mode and installed that...works fine.

Still be interesting to know if this is a known issue/a workaround as it makes debugging a little difficult, but not a major problem.

**Comment by Redth** [comment]
Hard to say without a good repro but I did fix a similar bug on Android in the latest release.
