### ISSUE TITLE
DelayBetweenAnalyzingFrames not working with ZXingScannerFragment.

### ISSUE THREAD

**Issue by lijo007** [Redth/ZXing.Net.Mobile#619]
Tried to use the ZXingScannerFragment with similar way provided in sample code and also tried using CustomOverlay as well. Well most of the features works but DelayBetweenAnalyzingFrames  and CustomOverlay not working with this in android. Also I was stuck when i am trying to provide a click listner for camera view and which also fails by not catching events. Anyone please help me on these.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
