### ISSUE TITLE
Crash : CameraController.ApplyCameraSettings() - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by AlexDarbyFujitsuGmail** [Redth/ZXing.Net.Mobile#620]
I am getting the following crash -

   CameraController.ApplyCameraSettings() - Object reference not set to an instance of an object

Xamarin Forms - 2.3.4.270 
ZXing.Net.Mobile version - 2.2.9
ZXing.Net.Mobile.Forms version - 2.2.9
Platform - Android
Device - Galaxy S5 mini
Android version - 6.0.1

Is this fix available in a existing pull request?

**Comment by tbalcom** [comment]
I see the same error in a plain Xamarin.Android app running on Android 6.0.

It looks like PR #635 attempts to fix this issue. Has anyone confirmed? Is there a planned NuGet package update?

**Comment by fgiacomelli** [comment]
Same problem for me, I enter in a page where the camera is automatically opened from viewmodel, and this is my stacktrace:
CameraController.ApplyCameraSettings ()
System.NullReferenceException: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.

CameraController.ApplyCameraSettings ()
CameraController.RefreshCamera ()
CameraAnalyzer.RefreshCamera ()
ZXingSurfaceView+<SurfaceChanged>d__5.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object:923f32d9-c7b7-4ca4-bbf8-d70fd409785e (intptr,intptr)

**Comment by Darth-Alex** [comment]
I can not confirm that PR #635  fixes the Problem. I think the Camera.Open() is still failing if it gets called again. Do you also get the Message: Failed to Connect to Camera Service?

**Comment by PaulVrugt** [comment]
seeing the same issue, using an emulator of android 4.4

**Comment by awaescher** [comment]
This issue still exists with ZXing.Net.Mobile.Forms 2.3.2 and Xamarin.Forms 2.5.0

**Comment by filoe** [comment]
Still the same issue...

**Comment by jaybowman** [comment]
Same issue, Tried to use Ver 2.4.1 and I was getting reference errors that I could not fix. So I tried version 2.3.1 and had same issue on Android Tablet V 7.1, But when i tested on Android 6.0 the app worked Correctly. Using Latest Xamarin.Forms 3.2.0.87...

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
