### ISSUE TITLE
ZXing.Net.mobile does not focus small barcodes

### ISSUE THREAD

**Issue by rpontigg** [Redth/ZXing.Net.Mobile#621]
ZXing.Net.mobile does not recognize small barcode. Camera does not focus the small barcodes on small items.

**Comment by EqoTime** [comment]
yes i need a help too... is there a option to zoom in the camera?

**Comment by devperson** [comment]
I need this too

**Comment by VahidShir** [comment]
I used `**Scale**` property and got slightly better results.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
