### ISSUE TITLE
Cannot scan ean13 horizontal view

### ISSUE THREAD

**Issue by raymondarvidsson** [Redth/ZXing.Net.Mobile#622]
When I try to scan ean13 codes I have to rotate the barcode 90 degreese. Look at the images - it makes no sence!!

QR code works perfect!

iOS11, iPhone 7.

![horizontal not working](https://user-images.githubusercontent.com/24684821/30845642-adf85f16-a294-11e7-95db-8f89c192f754.png)
![vertical-works](https://user-images.githubusercontent.com/24684821/30845641-adf4ac18-a294-11e7-82a1-dac5b9b324c4.png)

**Comment by karpie28** [comment]
@raymondarvidsson 
Hey, I'm haing the same problem, did you find some answer for that?

**Comment by raymondarvidsson** [comment]
Hi @karpie28 

Yes I really think I did! Tried to find anything regarding this in my emails but couldn´t find anything. And I cannot find my project files eighter. Don´t use that projekt any more. 

But i´m pretty sure I fixed it! Did I rotate some component 90 degreese? Sorry, really cant remember. Has the component at all been updated? I gave it up because it had not been updated for two years or so. Doesn´t feel good...

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
