### ISSUE TITLE
Unable to read large QR Codes with Xamarin

### ISSUE THREAD

**Issue by PMarsh-UB** [Redth/ZXing.Net.Mobile#624]
Hello All,

I've implemented the Zxing library into a Xamarin Forms application. And most devices struggle to decode large QR Codes (see first comment for example size). This also seems to be the case for other APIs such as Google's Vison API. So, I can't figure out if it is due to the library or the Xamarin framework...

However, here is my implementation:

Library versions:

- Zxing.net.Mobile: 2.2.9
- Xamarin-forms: 2.3.4.270 and Xamarin-forms: 2.4.0.18342

Here are the different methods I've implemented:

```
var options = new ZXing.Mobile.MobileBarcodeScanningOptions
{
    PossibleFormats = new List<ZXing.BarcodeFormat>
    {
        ZXing.BarcodeFormat.QR_CODE
    },
    TryHarder = false,
    AutoRotate = false,
    TryInverted = false
};

var scanner = new ZXing.Mobile.MobileBarcodeScanner
{
    TopText = "Up",
    BottomText = "Down"
};



var data = await scanner.Scan(options);
 // The await never finishes
```

```
TaskCompletionSource<string> scanCompletion = new TaskCompletionSource<string>();
var options = new ZXing.Mobile.MobileBarcodeScanningOptions
{
    PossibleFormats = new List<ZXing.BarcodeFormat>
    {
        ZXing.BarcodeFormat.QR_CODE
    },
    TryHarder = false,
    AutoRotate = false,
    TryInverted = false,
};

var scanPage = new ZXingScannerPage(options);
scanPage.AutoFocus();
scanPage.Title = "QR Code";
scanPage.OnScanResult += (result) =>
{
    try
    {
        Android.Util.Log.Error("ZXING", "Barcode!!!!");
        scanCompletion.SetResult(result.Text);
    }
    catch(Exception excep)
    {
        Android.Util.Log.Error("ZXING", excep.Message);
        Android.Util.Log.Error("ZXING", excep.StackTrace);
    }
}; // This is never called

await App.Navigation.PushAsync(scanPage);
var resultQr = await scanCompletion.Task;
await DisplayAlert("QR Code", resultQr, "OK");
await App.Navigation.PopAsync();
```

I'm aware of #278 and the application isn't crashing, only not scanning. The app is built without arm64-v8a.

I've attached the logs of when the application is running. (The NullReferenceException at the end is not important. I don't catch anything if the user force quits the scanner with the back key. Only a test app at the moment)

[ZxingScanLog.log](https://github.com/Redth/ZXing.Net.Mobile/files/1333851/ZxingScanLog.log)

Thanks.

Peter.

**Comment by PMarsh-UB** [comment]
I think this is due to large QR Codes. Here is one of my test QR Codes and it struggles to decode it (sometimes it will but, in most cases, never does):

![testQRCode](https://user-images.githubusercontent.com/32305453/31997381-1747a1c6-b98c-11e7-835e-b4e72f7d09b9.png)

**Comment by PMarsh-UB** [comment]
This also occurs in the Forms sample in the /Samples directory. The only time the scan is scanned is when it takes up the entire preview surface. Also, it sometimes badly decodes the Qr Code (a random 6-7 digit number is returned).

**Comment by Redth** [comment]
That... Sure is a big qr code. You could try playing with the resolution used in scanning via the cameraresolutionselector delegate on the scanning options...

**Comment by PMarsh-UB** [comment]
Thanks for the advice but, even at the highest resolution it struggles to decode it. The strange thing is that on native Android applications it seems to work fine (Not 100% sure about ZXing but, with the Google Vision API this is the case).

**Comment by Redth** [comment]
I just briefly tested your barcode on my Nexus 5X, and I'm actually fairly impressed with how it scans.  I do agree it's not entirely quick, but it's still usable in my opinion.

I know in the past what others have done approaching this problem is changed their strategy around the barcode.  You may or may not have control over the barcodes themselves, but if you do, why store such a large amount of data in it?  Could you instead store a _pointer_ to whatever data you're accessing and look it up once you scan the pointer/id in?

Eventually I want to get the Google Play Services Vision stuff integrated with this library as an option which it sounds like does a fine job of scanning in your case, but I'm not quite there yet (and want to do it so it's not a requirement - eg: it'll be an extra nuget package you can pull in to make it happen).

**Comment by PMarsh-UB** [comment]
The main reason the QR Code is large is because the data stored in it is encrypted. This is for security reasons and not something that I can change easily. My original post was called "Unable to read QR Code on Galaxy S7 - Android 6.0.1 API 23" as the S7 is the device I'm having a lot of trouble with. My Honor 6X works fine aswell. I went on the assumption that if one device struggled with the largness of the QR Code, there would probably be others and changed the post name. I can't figure out what the S7 does differently compared to the device where the QR Code works well. I've tried my application on 19 different phones (physical and emulated) and only the S7 seems to have this problem so far.

The Google API also works well but, not on the S7 either.

**Comment by Redth** [comment]
I wonder if somehow the preview buffer's image format is slightly different than expected... That's super weird the S7 is specifically having issues.  Unfortunately I don't have access to one of those devices to do any testing here with.

**Comment by PMarsh-UB** [comment]
It is highly possible. Something I haven't tested with ZXing but I have with the Google API, is give the QR Code image (PNG) directly to the decoding function. I did this by loading the image bytes into a Bitmap and replacing the OnPreview bytes. The Google API decodes it instantly.

**Comment by Tetius** [comment]
I have similar issue on Galaxy Tab A. I suspect that this happens on tablet devices (or devices with big screens), as it works perfectly fine on android phones.

**Comment by PMarsh-UB** [comment]
I've have fiddled quite a bit with this and cropping the input frame before giving it to the decode function helped with performance (seems logical especially with large screens). I use the LuminanceSource class crop function.

**Comment by Redth** [comment]
Region / cropping is something I've wanted to support for some time... Perhaps with the way luminances are handled now it's more feasible to do this, I should have another look at implementing it.

**Comment by PMarsh-UB** [comment]
If this helps out:
```
LuminanceSource fast = new FastJavaByteArrayYUVLuminanceSource(fastArray, width, height, 0, 0, width, height); // _area.Left, _area.Top, _area.Width, _area.Height);
if(width > 640 && height > 440)
{
  fast = fast.crop((width - 512) / 2, (height - 512) / 2, 512, 512);
}
if (rotate)
  fast = fast.rotateCounterClockwise();
result = barcodeReader.Decode(fast);
```

This is how I crop to the middle 512x512 image of the raw NV21 image in Android. This is in the CameraAnalyzer class.

**Comment by akhilgite** [comment]
I am facing the same issue. Some phones able to read large QR code but some phones failed to read QR code (tested on vivo v11). Does anyone know  the solution?

**Comment by knocte** [comment]
@akhilgite: you could try compiling the 'dev' branch of this repo to see if it improves the situation for you, as I see some performance fixes there that could help with this problem.

**Comment by abreucruz** [comment]
Hi Guys,  I'm facing the same issue, The scan works fine in Android but in iOS the camera open to start scanning the barcode but the results never trigger it was working fine but now it stop working.

**Code:**
var scanResults = await scanner.Scan(options); //Results never trigger in iOS keeps waiting and waiting...

I'm pointing the camera to the QRcode and then scan function never return a result.
