### ISSUE TITLE
.IsAnalyzing not working on my Xamarin.Forms.Droid project

### ISSUE THREAD

**Issue by CarsonCG** [Redth/ZXing.Net.Mobile#625]
On my QR-code ContentPage, the view is initialized with a zxing scanner named 'scanner' in the xaml, then some logic is done to determine if it is the first time the user is seeing this view. If it is the first time, then I set scanner.IsAnalyzing and scanner.IsVisible to true in the view's initialization. If the user is coming back to the QR-code page, then i set scanner.IsAnalyzing and scanner.IsVisible to false in the view's initialization. This all works fine on my .iOS project, but for some reason, for the .Droid project, the scanner turns on the camera regardless and looks like as if scanner.IsAnalyzing is true when in fact it is false, I even Debuged and confirmed this.
Here is the simplest way I thought to do this.
```
public partial class ScanQRCodePage : ContentPage
{
                ScanQRCodeViewModel vm;

		public ScanQRCodePage()
		{
			InitializeComponent();

                        vm = new ScanQRCodeViewModel();

                        BindingContext = vm;

			if (Application.Current.Properties.ContainsKey("FirstShowing"))
			{
				if ((bool)Application.Current.Properties["FirstShowing"])
				{
                                        scanButton.IsVisible = false;
                                        scanButton.IsEnabled = false;
					scanner.IsScanning = true;
					scanner.IsAnalyzing = true;
                                        scanner.IsEnabled = true;
                                        scanOverlay.IsVisible = true;
                                        scanOverlay.IsEnabled = true;
				}
				else
				{
					scanButton.IsVisible = true;
					scanButton.IsEnabled = true;
					scanner.IsScanning = false;
					scanner.IsAnalyzing = false;
                                        scanner.IsEnabled = false;
                                        scanOverlay.IsVisible = false;
                                        scanOverlay.IsEnabled = false;
				}
			}
                 }

                protected override void OnDisappearing()
		{
			base.OnDisappearing();

                        Application.Current.Properties["FirstShowing"] = false;
		} 
}
```

Application.Current.Properties["FirstShowing"] is set to true in App.OnStart if that matters

**Comment by CarsonCG** [comment]
Found my own workaround. Just don't use xaml to create the ZXingScannerView if you are working on Xamarin.Forms. There is a glitch that causes the scanner to misbehave if constructed via xaml. Work around this issue by keeping all ZXingScannerView related construction in the code-behind or VM and the scanner will listen properly across all platforms.

**Comment by CarsonCG** [comment]
I don't want to close this because the bug still exists.

**Comment by ryanherman** [comment]
Downgrade to 2.1.47

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
