### ISSUE TITLE
ZXingBarcodeImageView not rendering on iOS

### ISSUE THREAD

**Issue by girishv6991** [Redth/ZXing.Net.Mobile#626]
The following code works fine for Android and UWP. `ZXingBarcodeImageView` is not rendering on iOS. 

I have initialized in the `AppDelegate.cs` as shown below

```
global::Xamarin.Forms.Forms.Init();
ZXing.Net.Mobile.Forms.iOS.Platform.Init();
LoadApplication(new App());
return base.FinishedLaunching(app, options);
```

Here is the `ContentView` for displaying the QRCode.
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AZCommute.QRResult">
    <ContentView.Content>
    </ContentView.Content>
</ContentView>
```
Here is the `MainPage.xaml`
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AZCommute"
             x:Class="AZCommute.MainPage">
    <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
        <Label Text="QR Code Generator" HorizontalOptions="Center"/>
        <local:QRResult x:Name="qrResult"/>
    </StackLayout>
</ContentPage>
```

Here is my code for generating the QR Code

```
barcode = new ZXingBarcodeImageView
{
    	HorizontalOptions = LayoutOptions.FillAndExpand,
 	VerticalOptions = LayoutOptions.FillAndExpand,
};
barcode.BarcodeFormat = ZXing.BarcodeFormat.QR_CODE;
barcode.BarcodeOptions.Width = 500;
barcode.BarcodeOptions.Height = 500;
barcode.BarcodeOptions.Margin = 10;
barcode.BarcodeValue = "ZXing.Net.Mobile";

qrResult.Content = barcode;
```

**Edit**
After adding 
```
WidthRequest = 410,
HeightRequest = 410,
```
to `ZXingBarcodeImageView` initialization, the qrcode is rendered, but, aspect ratio is lost.

**Comment by andreslon** [comment]
any solution?

**Comment by yuv4ik** [comment]
Thanks for sharing the workaround.

**Comment by knocte** [comment]
I have the opposite problem, it shows in iOS but not Android.

**Comment by knocte** [comment]
> I have the opposite problem, it shows in iOS but not Android.

And setting WidthRequest and HeightRequest is a workaround that works...

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by VladimirPlatun** [comment]
I Have same problemon iOS
 <zxing:ZXingBarcodeImageView BarcodeFormat="EAN_13" 
                                                 BarcodeValue="{Binding SelectedProduct.Barcode}" 
                                                 WidthRequest="220" HeightRequest="90"
                                                 HorizontalOptions="Center"
                                                 VerticalOptions="Center">
                        <zxing:ZXingBarcodeImageView.BarcodeOptions>
                            <zxcm:EncodingOptions Width="220" Height="90" />
                        </zxing:ZXingBarcodeImageView.BarcodeOptions>
                    </zxing:ZXingBarcodeImageView>
