### ISSUE TITLE
Random unhandled exception when screen goes dark

### ISSUE THREAD

**Issue by jorisvergeer** [Redth/ZXing.Net.Mobile#627]
My device went to sleep during scanning and then my app crashes and produces this stack trace:

09-29 18:00:10.207 I/MonoDroid( 4833): UNHANDLED EXCEPTION:
09-29 18:00:10.252 I/MonoDroid( 4833): System.NullReferenceException: Object reference not set to an instance of an object.
09-29 18:00:10.252 I/MonoDroid( 4833):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0 
09-29 18:00:10.252 I/MonoDroid( 4833): --- End of stack trace from previous location where exception was thrown ---
09-29 18:00:10.252 I/MonoDroid( 4833):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <2e14bb2dd93a405e81838369ed72695b>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0 
09-29 18:00:10.252 I/MonoDroid( 4833):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0 
09-29 18:00:10.253 I/MonoDroid( 4833):   at (wrapper dynamic-method) System.Object:fce4a240-9b0b-4206-ac04-e368c5c504a0 (intptr,intptr)

**Comment by OlegKlym** [comment]
Have this issue too after lock screen while scanning. Reproduce only on Android

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
