### ISSUE TITLE
iOS - Attempt to present <ZXing_Mobile_ZXingScannerViewController:  on <Xamarin_Forms_Platform_iOS_PlatformRenderer: > whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by dlloyd525** [Redth/ZXing.Net.Mobile#628]
We are attempt to use ZXing.Net.Mobile, version 2.2.9, in an iOS Xarmin PCL application using iOS 11.0.2.  When we attempt to scan, from a modal form, we see the following message in the debug window.

Attempt to present <ZXing_Mobile_ZXingScannerViewController: 0x129bb00f0> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x127e102a0> whose view is not in the window hierarchy!

The scan window never displays.  If we display the form as not modal, the scanning window appears properly.  

We believe this worked properly prior to the iOS11 upgrade.  Looking through the issues, it appears that this was fixed some time ago. 

We would prefer starting the scanner from a modal form if possible. I will note that it works properly on android.

Thank you for any assistance.

Dan

**Comment by Enoges** [comment]
Same problem here.

**Comment by dlloyd525** [comment]
To address my issue changed - 
		public MobileBarcodeScanner ()
		{
			foreach (var window in UIApplication.SharedApplication.Windows)
			{
				if (window.RootViewController != null)
				{
					appController = window.RootViewController;
					break;
			        }
			}
		}

To
		public MobileBarcodeScanner ()
		{
                    var window = UIKit.UIApplication.SharedApplication.KeyWindow;
                    var vc = window.RootViewController;
                    while (vc.PresentedViewController != null)
                    {
                       vc = vc.PresentedViewController;
                     }
                   return new ZXing.Mobile.MobileBarcodeScanner(vc);
                }

Credit goes to this thread - https://forums.xamarin.com/discussion/24689/how-to-acces-the-current-view-uiviewcontroller-from-an-external-service

**Comment by any2info** [comment]
@dlloyd525 we are using the nuget package of ZXing.Net.Mobile Version 2.4.1 and we also have this problem. The fix you suggest sound pretty strait forward so i decided to download the github repository and build a version with this fix but the downloaded version fails to build on my and my colleague's machine. how did you apply this fix?

**Comment by ignasbagdonas** [comment]
> @dlloyd525 we are using the nuget package of ZXing.Net.Mobile Version 2.4.1 and we also have this problem. The fix you suggest sound pretty strait forward so i decided to download the github repository and build a version with this fix but the downloaded version fails to build on my and my colleague's machine. how did you apply this fix?

Hey, 

Just create factory for MobileBarcodeScanner for ios.
```
public class MobileBarcodeScannerFactory
    {
        public MobileBarcodeScanner GetScanner()
        {
            return new MobileBarcodeScanner(GetTopViewController()); 
        }

        private UIViewController GetTopViewController()
        {
            var viewController = UIApplication.SharedApplication.KeyWindow.RootViewController;
            while (viewController.PresentedViewController != null)
            {
                viewController = viewController.PresentedViewController;
            }
            return viewController;
        }
    }
```

**Comment by Mattia541993** [comment]
worked for me! Thanks!

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
