### ISSUE TITLE
ZXing (iOS) not resetting camera settings

### ISSUE THREAD

**Issue by Mysame** [Redth/ZXing.Net.Mobile#630]
After doing a succesful scan (and closing the component), the camera settings do not get reset.

This is referenced in https://github.com/Redth/ZXing.Net.Mobile/issues/491 , where the issue talks about the AutoFocus not working properly.

However, I find that the resolution I passed to the ZXing component also deforms any pictures taken after a succesful scan.

So, in my app, if I scan a barcode, then use the camera afterwards to take a picture, the picture output of the camera will be deformed to fit ZXing's picture resolution.

Has anyone found a way to properly reset the camera after ZXing has used it?

**Comment by salamoun** [comment]
I can confirm this issue. +1 for fix in future release...

**Comment by mwerickson** [comment]
I too am seeing this issue.  +1 for fix in future release

**Comment by THplusplus** [comment]
I'm having the same issue. This needs fixing.

**Comment by Robbert-jansen** [comment]
Also seeing this issue

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
