### ISSUE TITLE
[Android] Scanning works very bad

### ISSUE THREAD

**Issue by F1nZeR** [Redth/ZXing.Net.Mobile#634]
It is hardly possible to scan any barcode.
Works from time to time only on perfectly focused barcodes.

I'm using latest sources.

**Comment by Redth** [comment]
Can you elaborate? What kind of image analysis times are you seeing? Do you think this has anything to do with autofocus problems?

**Comment by F1nZeR** [comment]
I was trying on QR code & barcode128 (analysis time is about 100ms per frame).
Even on focused pictures it is very hard to get value from barcode, so autofocus, I guess, is not the only problem we have.

**Comment by Redth** [comment]
have you pulled master as of today?  I'm not seeing the same thing you are here on my nexus 5x.  i'll try a couple more devices here too.

**Comment by Redth** [comment]
I just tested on:
 - Nexus 4
 - Nexus 5
 - Moto G1

All the barcodes I tried (QR Code, Code 128, Code 39, Aztec) scan very quickly.

The Moto G1 is a bit slow in the image analysis (like 800ms or so) but it still scans just fine.

**Comment by Redth** [comment]
Also tested on an ancient Samsung running API 15.  Works fine here too.

**Comment by F1nZeR** [comment]
I was trying sample app (with yesterday sources) on my Xiaomi Mi6 and on Galaxy s8.
On real things it works not very good at all while on barcode pictures from google it works pretty well.
Damn, maybe zxing has some problems with that kind of images, anyway original java-based zxing app from google play works better.
Also I've tested with Google Vision (on pr branch) - it works better but not so much difference here.
Anyway I'm going to investigate that problem deeper.

**Comment by Redth** [comment]
I just tried a few boxes with various barcodes on them (UPC and QR Code) on my Nexus 4... It seems to scan fine for me.

I wonder if Samsung / Xiaomi have anything odd going on with their image data.... 

The only thing I can really think of is that I switched to using the native java pointer for the image buffer, but technically that should still result in the same data I was getting before.

**Comment by F1nZeR** [comment]
The problem was in barcode generation software. Resulted barcodes are hardly detectable by zxing engine while vision api works better in this case.

**Comment by ztl8702** [comment]
> while vision api works better in this case. 

@F1nZeR Were you referring to this: https://www.nuget.org/packages/Xamarin.GooglePlayServices.Vision/?

**Comment by F1nZeR** [comment]
@ztl8702 yes
