### ISSUE TITLE
Extra "I" at the beginning of barcode result - Autofocus not working

### ISSUE THREAD

**Issue by VictorK1902** [Redth/ZXing.Net.Mobile#636]
All of the following 2 issues are reproduced-able in both iOS and Android

---------

1. Extra "I" at the beginning of barcode result

I set up the scanner to scan only Code39 and QR. For some reason, upon scanning result, there's always an extra "I" character at the beginning. So for example, this is the expected result

    ABC123456

This is what's actually being returned:

    IABC123456

Since I'm using the component mainly for reading VIN, I added a hot fix by stripping off this "I" since (I think) VIN doesn't start with an "I" ever. 

Multiple people have helped me test and confirm this on their devices as well.

Does someone have a similar issue?

----------

2. Autofocus not working - both on Android and iOS

The problem is after a successful scan, I'm unable to go open the scanner and scan again. The barcode is never read. I think this has something to do with the camera setting not being reset as the other issue has addressed [here - Issue#630](https://github.com/Redth/ZXing.Net.Mobile/issues/630).
I tried working around by adding the AutoFocus button but it doesn't seem to work either, regardless of my preset breakpoint was hit.

------------

My XF codes:

Inside my ViewModel I set up the ZXingScannerPage to be reused whenever user hits the Scan button:

    ZXingScannerPage scanPage;    
    void buildScannerPage() {    
        StackLayout customOverlay = new StackLayout {
            HorizontalOptions = LayoutOptions.FillAndExpand,
            VerticalOptions = LayoutOptions.FillAndExpand,
            Orientation = StackOrientation.Vertical
        };
        var autoFocusButton = new Button() {
            HorizontalOptions = LayoutOptions.End,
            VerticalOptions = LayoutOptions.Start,
            Margin = new Thickness(10),
            Text = "Auto Focus",
            FontSize = 12, HeightRequest = 30, WidthRequest = 80,
            Command = new Command(()=> {
                scanPage.AutoFocus();
            })     
        };
        var topPart = new StackLayout {
            HorizontalOptions = LayoutOptions.FillAndExpand,
            VerticalOptions = LayoutOptions.Start,
            BackgroundColor = new Color(0, 0, 0, 0.4),
            Orientation = StackOrientation.Vertical, HeightRequest = 180
        };
        var btmPart = new StackLayout {
            HorizontalOptions = LayoutOptions.FillAndExpand,
            VerticalOptions = LayoutOptions.EndAndExpand,
            BackgroundColor = new Color(0, 0, 0, 0.4),
            Orientation = StackOrientation.Vertical, HeightRequest = 180
        };
        topPart.Children.Add(autoFocusButton);
        customOverlay.Children.Add(topPart);
        customOverlay.Children.Add(btmPart);
        
        // Scanner Page
        var options = new MobileBarcodeScanningOptions() {
            PossibleFormats = new List<BarcodeFormat>() {
                BarcodeFormat.CODE_39, BarcodeFormat.QR_CODE
            }
        };
        scanPage = new ZXingScannerPage(options, customOverlay);
        scanPage.OnScanResult += (result) => {
            Device.BeginInvokeOnMainThread(async () => {
                // need to screenshot and display after
                scanPage.IsAnalyzing = false;
                if (result.Text.Substring(0, 1).ToLower().Equals("i")) {
                    VINNumber = result.Text.Substring(1, (result.Text.Length - 1));
                } else {
                    VINNumber = result.Text;
                }
                ExecuteDecodeVINCommand();
                await Navigation.PopAsync();
            });
        };
    }

**Comment by bmacadam** [comment]
The reason you are reading "I" at the start of a VIN barcode is because it is really there.  If you read the barcode with a Symbol scanner, you would get the same result.  You need to check for the leading "I" and then strip it off in your code.
