### ISSUE TITLE
Draw square and draw custom text during error

### ISSUE THREAD

**Issue by montecillodavidacn** [Redth/ZXing.Net.Mobile#639]
Draw square and draw custom text during error. 

Hi I have successfully drawn a square in the `ZXingScannerFragment.cs`, customizing the `ZXingOverlayView.cs`.

But my issue is the text that is used to display some errors is not drawn timely and also is not drawn when calling `Invalidate()`. 

**PS: I have overrided also `Invalidate()` method to check if it actually calls it and it successfully calls but unfortunately the text is not drawn the moment I called `Invalidate()`**

Did I miss something?

**Comment by F1nZeR** [comment]
Any code example?

**Comment by montecillodavidacn** [comment]
Oh I already fixed it.

**Comment by montecillodavidacn** [comment]
I will provide information later on. For now for others I just used the `PostInvalidateDelayed` to the coordinates where the draw should happen.
