### ISSUE TITLE
UWP zxing mobile mirror preview

### ISSUE THREAD

**Issue by festalius** [Redth/ZXing.Net.Mobile#642]
Hi,

I am using zxing mobile version for a window 10 tablet uwp application to scan QR codes.
i am scanning with the front cam and want to mirror the preview to make it feel more natural.

how can i do this? I dont think it is possible atm.

**Comment by F1nZeR** [comment]
Yeah, right now it is not implemented (but easily can be).
For now it is important to understand if it should be optional via some property or behaviour by default.

**Comment by festalius** [comment]
I think it should be default for front camera's, so if "UseFrontCameraIfAvailable" is able to set the camera to the front one, the preview should be mirrored.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
