### ISSUE TITLE
UseFrontCameraIfAvailable dosen't work

### ISSUE THREAD

**Issue by Pix0u** [Redth/ZXing.Net.Mobile#645]
I can set UseFrontCameraIfAvailable in a MobileBarcodeScanningOptions but I can set it to true or false, it doesn't change anythig, it use the Back Camera. It is possible to use the Front Camera?
```
var options = new MobileBarcodeScanningOptions
            {
                AutoRotate = false,
                UseFrontCameraIfAvailable = true

           };

var result = await scanner.Scan(options);
```

**Comment by F1nZeR** [comment]
Platform? Device?

**Comment by Pix0u** [comment]
I'm doing an android app with Xamarin
