### ISSUE TITLE
Autofocus working only one time with CustomOverlay

### ISSUE THREAD

**Issue by MichaMoll** [Redth/ZXing.Net.Mobile#647]
I tried the last Version (2.3.2) on Android with VS2017.
If I use the Standard Overlay, the Auto Focus worked very well. But if I use a CustomOverlay the Auto Focus only works one time (when the view is started). After that, I can call AutoFocus(), but it has no effect.
I tried this only on Samsung Mobile Phone (S5, S7, S7 edge).
Here is the my Code snippet:

var scanner = new ZXing.Mobile.MobileBarcodeScanner();
ZXing.Mobile.MobileBarcodeScanningOptions options = new ZXing.Mobile.MobileBarcodeScanningOptions()
{
TryHarder = true,
AutoRotate = true,
};
ZXing.Result result = null;

scanner.UseCustomOverlay = true;
ScanView myCustomOverlay = new ScanView(context, scanner, Caption);
scanner.CustomOverlay = myCustomOverlay;

                new Thread(new ThreadStart(delegate
                {
                    while (result == null && scanner != null)
                    {
                        scanner.AutoFocus();
                        Thread.Sleep(3000);

                    }
                })).Start();
            
            scanner.TopText = Caption;
            result = await scanner.Scan(options);
            scanner = null;
            if (result != null)
                return result.Text;
            else
                return "";

Is this a bug? Or doing I something wrong?

Kind regards

Michael Moll

**Comment by RichMcLaren** [comment]
Hi @MichaMoll 

It works for me. I'm using this code inside of OnAppearing method

```
TimeSpan ts = TimeSpan.FromMilliseconds(2000);
Device.StartTimer(ts, () =>
{
	if (i_scanner.IsScanning)
	{
		i_scanner.AutoFocus();
		return true;
	}
	return false;
});

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
