### ISSUE TITLE
Barcode Image resize [Not working]

### ISSUE THREAD

**Issue by Willjobs94** [Redth/ZXing.Net.Mobile#650]
I would like to fill a container with the generated Barcode Image, I have tried changing the `width` and `height` properties of the BarcodingOptions property, but nothing seems to work, any idea.

![screenshot 2017-11-22 21 14 09](https://user-images.githubusercontent.com/10265964/33155851-7bbcf210-cfca-11e7-9d56-2963d3f75373.png)

Platform: Xamarin.Forms.
Plugin version: 2.3.2

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
