### ISSUE TITLE
Cast FlashCommand to ICommand instead of Command

### ISSUE THREAD

**Issue by cmxl** [Redth/ZXing.Net.Mobile#651]
https://github.com/Redth/ZXing.Net.Mobile/blob/3c0aae501e723f195c599a1eb9cf4cc1839929c9/Source/ZXing.Net.Mobile.Forms/ZXingDefaultOverlay.cs#L122

I think this is just a typo, but breaks my custom implementation of ICommand that i use for FlashCommand

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
