### ISSUE TITLE
barcodeWriter generate error

### ISSUE THREAD

**Issue by Reda11** [Redth/ZXing.Net.Mobile#652]
I am trying to generate a QR code using this library ( Zxing.net.mobile from nugget)

I am getting a syntax error at the instaniation line :

   `var writer = new ZXing.Mobile.BarcodeWriter();`

The scanning works fine, but when i try to generate i get this Error :

`
Error   CS0234  The type or namespace name 'BarcodeWriter' does not exist in 
the namespace 'ZXing.Mobile' (are you missing an assembly reference?)`

why is BarcodeWriter not recognized even thought the library is correctly installed ?

**Comment by yangshuairocks** [comment]
I have the same problem. Do you know why this happens?
