### ISSUE TITLE
Using GenericMultipleBarcodeReader for scanning Multiple barcodes. 

### ISSUE THREAD

**Issue by DevRach** [Redth/ZXing.Net.Mobile#653]
Hey, 

I am new to ZXing.net library and trying to use it to read multiple barcodes (3) in one go, I got to know that I need to use the feature, **GenericMultipleBarcodeReader**. Has anyone tried that and could possibly share some sample code? 

I tried to use ScanContinuously and I don't think it suits my purpose of scanning in one go. Could you please help? 

Thanks

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
