### ISSUE TITLE
barcode distance 

### ISSUE THREAD

**Issue by clausthalVK** [Redth/ZXing.Net.Mobile#654]
I am using Zxing library for barcode scanning in xamarin android app on VUZIX M300 smart glasses.. every thing works fine but the only issue is the distance. I am not able to detect barcode placed more than 30cm away from the device.. 
Any help wourl be appreciated

**Comment by F1nZeR** [comment]
You can try to use higher camera resolution - check options.

**Comment by hansellserrano** [comment]
clausthalVK, how do you obtain the Select Button (Third Button on VUZIX M300) on VUZIX M300
 event

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
