### ISSUE TITLE
Black Screen after AppResume

### ISSUE THREAD

**Issue by Darth-Alex** [Redth/ZXing.Net.Mobile#655]
Today I found out a Issue on Xamarin Forms (Android) - iOS works well.

Zxing is Initialized in the Constructor.
Permissions are correctly set.

Steps to Reproduce:
1. Navigate to the Scanner Page. (don't scan anything)
2. Click on the "Home" Button which brings you to the start Screen.
3. Navigate Back in the App with the Android "App-Switcher"
-> Now you get a Black Screen.

if I go back into the app the Method `protected override void OnAppearing()` is called. 
here I set `zxing.IsScanning = true;`

If I navigate inside my App like Navigate away from scanner Page and navigate back - everything works pretty fine.

Zxing Version: 2.3.2 and also tested with 2.3.1
XamarinForms Version: 2.5.0.91635

Works on iOS 10-11 on iPhone SE, 7, X
Does not Work on Android 6,7 on Galaxy S7, Huawei P8, LG G3

**Comment by dberroa** [comment]
This is happening to me as well.

**Comment by eggeggss** [comment]
My solution is when page OnAppearing , add ZXingScannerView to layout's subview ,when OnDisappearing remove it from layout's subview

**Comment by dberroa** [comment]
@eggeggss Do you also set IsScanning to false when you do that? I'm also encountering the same issue and want to know exactly how you solved it so I can give it a shot.

Does that also work for UWP? Desktop.

**Comment by eggeggss** [comment]
you can refer to worawutt's solution , https://github.com/Redth/ZXing.Net.Mobile/issues/659
createscannerview at onappearing i don't know the uwp be work or not

**Comment by gtbuchanan** [comment]
I've debugged this a little bit and discovered it's because `_cameraAnalyzer.SetupCamera()` is only called in `ZXingSurfaceView.SurfaceCreated`, but `SurfaceCreated` isn't called on a resume. Therefore, the camera gets shut down during sleep in `SurfaceDestroyed` and never set up again. If you rotate the device while the scanner is black, the scanner starts right up again.
