### ISSUE TITLE
Unable to scan in an Android Marshmallow up to Oreo but i was able to make it work on lollipop

### ISSUE THREAD

**Issue by winstongubantes** [Redth/ZXing.Net.Mobile#658]
Something is going wrong with then scan in an Android Marshmallow up to Oreo but i was able to make it work on lollipop. Error it has something to do with the surfaceviewchanged event.

05-02 18:30:56.825 D/ZXing.Net.Mobile( 5892): Found 0 cameras...
05-02 18:30:56.825 D/ZXing.Net.Mobile( 5892): Finding Back camera failed, opening camera 0...
05-02 18:30:56.835 W/CameraBase( 5892): An error occurred while connecting to camera: 0
05-02 18:30:56.845 W/CameraBase( 5892): Camera service died!
05-02 18:30:56.845 E/ZXING   ( 5892): Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
05-02 18:30:56.845 E/ZXING   ( 5892):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
05-02 18:30:56.845 E/ZXING   ( 5892):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/4009/3a62f1ea/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
05-02 18:30:56.845 E/ZXING   ( 5892):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/4009/3a62f1ea/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
05-02 18:30:56.845 E/ZXING   ( 5892):   at Android.Hardware.Camera.Open (System.Int32 cameraId) [0x00017] in /Users/builder/data/lanes/4009/3a62f1ea/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Hardware.Camera.cs:4478 
05-02 18:30:56.845 E/ZXING   ( 5892):   at ZXing.Mobile.ZXingSurfaceView+<SetupCamera>d__26.MoveNext () [0x0029e] in <04a6c4a6536f4e76a10998845fe4c337>:0 
05-02 18:30:56.845 E/ZXING   ( 5892):   --- End of managed Java.Lang.RuntimeException stack trace ---
05-02 18:30:56.845 E/ZXING   ( 5892): java.lang.RuntimeException: Fail to connect to camera service
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.hardware.Camera.<init>(Camera.java:568)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.hardware.Camera.open(Camera.java:405)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.n_surfaceChanged(Native Method)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.surfaceChanged(ZXingSurfaceView.java:69)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:740)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:215)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2599)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7520)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.Choreographer.doFrame(Choreographer.java:622)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.os.Handler.handleCallback(Handler.java:739)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.os.Looper.loop(Looper.java:148)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at android.app.ActivityThread.main(ActivityThread.java:7303)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at java.lang.reflect.Method.invoke(Native Method)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-02 18:30:56.845 E/ZXING   ( 5892): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-02 18:30:56.845 D/ZXing.Net.Mobile( 5892): Checking android.permission.CAMERA...

**Comment by Plofstoffel** [comment]
Is this not due to Android.Hardware.Camera being obsolete?
Is there a road map to enable Android.Hardware.Camera2?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
