### ISSUE TITLE
Camera freezes on last scanned image while Re-scan

### ISSUE THREAD

**Issue by CybAnkit** [Redth/ZXing.Net.Mobile#659]
Hello All / @Redth ,
I have used ZXing to Scan QR Code. I'm facing two different issue with different version of ZXing.

Steps which I'm following:
- Open Camera for scan.
- Cancel the scanning.
- Open Camera for Re-scan.

**Issue With ZXing.Net.Mobile Version 2.1.47**
- Initially camera scanned properly however if i cancel and re-open it take 12-18 seconds to re-open camera for scanning.
- So I have updated ZXing.Net.Mobile with latest stable version as well as i have tried with all latest version of 2.1.47.

**Issue With ZXing.Net.Mobile version > 2.1.47**
- Now #1 issue resolved with update and now camera open quickly for re-scan however it freeze on last scanned image however if i move to QRCode it still scanned properly but freeze on last scanned image.

I'm uses ZXing on Xamarin forms so i have created Renderer in Native. Below is the link the way i have used renderer in Andriod.
"https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.Forms.Android/ZXingScannerViewRenderer.cs"

Xamarin forms version: 2.4.0.280

Please help me to find the solution for above issue.

Thanks in advance,
Ankit

**Comment by worawutt** [comment]
I'm uses ZXing on Xamarin Forms too.
Android: until latest version 3.0.2  camera still freeze if u set IsScanning = false, I resolved by remove old ZXingScannerView from container (for me is Grid) and re-create again

**Comment by CybAnkit** [comment]
@worawutt ,
Thanks for the reply , can you please provide your ZXingScannerView code so i can try to check with it.

**Comment by worawutt** [comment]
sorry for wrong version, latest version is 2.3.2

You can remove 'Device.BeginInvokeOnMainThread' If you call CreateScanner()/ReleaseScanner from UI Thread

`
public partial class MyScanPage : BaseContentPage
{
    ZXingScannerView scanner;

    void CreateScanner()
    {
        ReleaseScanner();

        Device.BeginInvokeOnMainThread(() => {
            scanner = new ZXingScannerView {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingScannerView",
                IsScanning = true,
                IsAnalyzing = true
            };
            scanner.OnScanResult += Scanner_OnScanResult;
            cameraGrid.Children.Add(scanner);
        });
    }

    void ReleaseScanner()
    {
        Device.BeginInvokeOnMainThread(() => {
            if (scanner != null) {
                scanner.IsTorchOn = false;
                scanner.IsAnalyzing = false;
                scanner.IsScanning = false;
                scanner.IsVisible = false;
                scanner.OnScanResult -= Scanner_OnScanResult;
                cameraGrid.Children.Remove(scanner);
                scanner = null;
            }
        });
    }

    void Scanner_OnScanResult(ZXing.Result result)
    {
        Device.BeginInvokeOnMainThread(() => {
            scanner.IsAnalyzing = false;
            ViewModel.BarcodeResult = result.Text;
        });
    }

    protected override void OnDisappearing()
    {
        ReleaseScanner();
        base.OnDisappearing();
    }

}`

**Comment by dberroa** [comment]
@worawutt Where do you call CreateScanner() in your example. In on appearing?

**Comment by worawutt** [comment]
@dberroa I have toggle button click event to call Create/Release scanner in another ui layer.
You can see I have cameraGrid to be container of ZXingScannerView.

**Comment by leroygumede** [comment]
@worawutt  Works perfect when you have multiple scanners . It's just sad that we have to do this, Its the plugins job to close itself.  Its like turning of a car by always taking out the battery

**Comment by davidbuckleyni** [comment]
I am running into same issue on re scanns please see my code below 

[code]
public async  void  BtnScanStockTakeItem_Clicked(object sender, EventArgs e)
{    

     var scanPage = new ZXingScannerPage();
     scanPage.ToggleTorch();
     scanPage.IsScanning = true;               
     await Navigation.PushAsync(scanPage);
     scanPage.OnScanResult += (result) =>
     {


      // Stop scanning
      scanPage.IsScanning = false;

      // Pop the page and show the result
      Device.BeginInvokeOnMainThread(async () =>
    {
        await Navigation.PopAsync();
    }
}
I am then calling the above from another button method lets say the saved function

private async void SaveFunction(object sender, EventArgs e)
{

        foreach (var item in transferList)
        {

            int z = await restServices.PostStockTakeTransaction(item);
        }
        Preferences.Set("StockTakeWarehouse", pickStockTake.SelectedIndex);
        WarehouseName = pickStockTake.SelectedItem.ToString();
        bool x = await DisplayAlert("Test", "Item Saved", "ReScan", "Cancel");
        if (x)
        {
             BtnScanStockTakeItem_Clicked(sender, e);
            //this is where it rescans the item
        }
 }

[/code]

The scanner pops up fine but doesnt permit scanning any ideas.

**Comment by EddieGreen** [comment]
Hmmm... same issue solved a different way. Using XAML control declaration, with code behind.

If I set `IsScanning=false` then scanning never resumes. However, if instead I set `IsAnalyzing = false` I can scan again when setting `IsAnalyzing = true`.

```
        private void ScanButton_OnClicked(object sender, EventArgs e)
        {
            BarcodeImageView.IsVisible = false;

            BarcodeScanView.IsVisible = true;
            BarcodeScanView.**IsScanning = true**;
            BarcodeScanView.**IsAnalyzing = true**;
        }
```

```
        private void Handle_OnScanResult(Result result)
        {
            if(string.IsNullOrWhiteSpace(result.Text))
            {
                return;
            }

            if(!result.Text.StartsWith("TemperatureController", StringComparison.Ordinal))
            {
                return;
            }

            Device.BeginInvokeOnMainThread(() =>
            {
                App.SavedSettings.DeviceName = result.Text;

                App.Database.SaveSettingsAsync(App.SavedSettings);

                BarcodeScanView.IsVisible = false;
                BarcodeScanView.**IsAnalyzing = false**;

                UpdateBarcodeImageView();
            });
        }
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
