### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by curia-damiano** [Redth/ZXing.Net.Mobile#660]
Hi,
I download the source codes. I've tried the Android and Forms projects, and they require the zxing.portable project, that can't be found.
Can you please suggest me how I could compile them?
Regards, Damiano

**Comment by vlkam** [comment]
Don't download, clone the repo. Then the project will be compiled

**Comment by oneday521** [comment]
Clone the repo,Then the project can not complile

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by curia-damiano** [comment]
Thank you Jonathan, I have seen you have a new release in these days :-)
