### ISSUE TITLE
Use safe area layout guides for AVCaptureScannerView 

### ISSUE THREAD

**Issue by MarcoMiltenburg** [Redth/ZXing.Net.Mobile#661]
The AVCaptureScannerView view does not use the safe area layout guide that's available in iOS 11. This is needed to properly support the new iPhone X. Now the cancel button is too close to the rounded corner of the screen and the home indicator area.

![image](https://user-images.githubusercontent.com/6213937/34211029-282188c6-e598-11e7-88c8-e5ddc880123e.png)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
