### ISSUE TITLE
Java.Lang.ClassNotFoundException: Didn't find class 

### ISSUE THREAD

**Issue by san3jaya** [Redth/ZXing.Net.Mobile#662]
When starting the application it occurred following error.

![2017-12-22_11h26_38](https://user-images.githubusercontent.com/8122779/34287019-706732a2-e70a-11e7-9874-944fc03bcc14.png)

Sample Project: 
[App2.zip](https://github.com/Redth/ZXing.Net.Mobile/files/1581532/App2.zip)

**Comment by Panhavorn** [comment]
I got the same error on android, but it work find on ios.
![zxing](https://user-images.githubusercontent.com/14119328/34611582-a386f31c-f258-11e7-8d5c-d58e3219f631.png)

**Comment by Ignomar** [comment]
I'm having the same problem. The project is a new empty project based on Xamarin for Android (not Xamarin.Forms).
The app is being developed with Visual Studio 2017, using the latest versions of Visual Studio and Xamarin.
For the app, we are using Android 7.1 Nougat as Target Framework, and the latest ZXing.Net.Mobile nuget (v2.3.2)
Anyone has a solution for this?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
