### ISSUE TITLE
Android Forms - OnNewIntent For NFC Scanning Not Called On Some Devices While Scanning QRCodes

### ISSUE THREAD

**Issue by dberroa** [Redth/ZXing.Net.Mobile#664]
I have a xamarin forms app in which the first page is a QR and NFC scanner, which is the main point of the app. 

On my test Galaxy Note 3 and Galaxy Nexus running Android 5 and 4.0.3, I can have my main QR scanner view scan and read NFC tags.

On my test LG G5 running Android 7, NFC will not work in app while the scannerview has a camera preview.

I'm wondering if Zxing forms is overriding the NfcAdapter.foregroundDispatch intents or the OnNewIntent method in some way that is preventing the scan from happening. If I removed the scanner view from the page, then NFC works perfectly. A mentioned, this only happens on my one up to date device.

Does Zxing hook into mainactivty events at all or does anyone know why scanning with this framework prevents NFC reading? The code below is all one needs for NFC reading so it should be easy to reproduce.

My main activity code is as follows.

    public class MainActivity : FormsAppCompatActivity
    {
        private NfcAdapter adapter;
        private INFC nfcImplementation;

        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            //Enable experimental fast renderers.
            Forms.SetFlags("FastRenderers_Experimental");

            Forms.Init(this, bundle);

            //Load up the zxing framework.
            ZXing.Net.Mobile.Forms.Android.Platform.Init();

            //Load up the user dialogs plugin.
            UserDialogs.Init(() => this);

            //Set our nfc implementation for Android.
            nfcImplementation = DependencyService.Get<INFC>() as INFC;

            //Get our NFC adapter.
            adapter = NfcAdapter.GetDefaultAdapter(this);

            //Call the init method to give it the adapter we created.
            INFCImplementation.Init(adapter);

            LoadApplication(new App());
        }

        protected override void OnResume()
        {
            //Call the base method.
            base.OnResume();

            //Check if we have an NFC adapter.
            if (adapter != null && adapter.IsEnabled)
            {
                //Create the NDEF filter.
                IntentFilter ndefFilter = new IntentFilter(NfcAdapter.ActionNdefDiscovered);

                //Add all allowed mime types.
                ndefFilter.AddDataType("*/*");

                //Enable the foreground dispatch.
                adapter.EnableForegroundDispatch
                (
                    this,
                    PendingIntent.GetActivity(this, 0, new Intent(this, GetType()).AddFlags(ActivityFlags.SingleTop), 0),
                    new[] { ndefFilter, new IntentFilter(NfcAdapter.ActionTechDiscovered), new IntentFilter(NfcAdapter.ActionTagDiscovered) },
                    new String[][] { new String[] { "android.nfc.tech.Ndef" } }
                );
            }
        }

        protected override void OnPause()
        {
            //Call the base method.
            base.OnPause();
            
            //Disable the foreground dispatch.
            adapter.DisableForegroundDispatch(this);
        }

        protected override void OnNewIntent(Intent intent)
        {
            //Call the base method.
            base.OnNewIntent(intent);

            //Check if this is the NFC intent.
            if (intent != null && (NfcAdapter.ActionNdefDiscovered.Equals(intent.Action) 
                || NfcAdapter.ActionTechDiscovered.Equals(intent.Action) || NfcAdapter.ActionTagDiscovered.Equals(intent.Action)))
            {
                //Start the NFC scan processing with the passed in tag.
                nfcImplementation.StartNFCScan(intent.GetParcelableExtra(NfcAdapter.ExtraTag) as Tag);
            }
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            //Call the base method.
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            //Check with the permissions plugin.
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            //Check with the zxing plugin.
            ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }

**Comment by PaulVrugt** [comment]
We're experiencing the same issue

**Comment by dberroa** [comment]
Sadly I have not found a solution to this yet.

**Comment by PaulVrugt** [comment]
After some research I found out the problem is not in the scanner component.

The issue is specific to some phones. Among others, the Nexus 5X disables the NFC chip when the camera is enabled. Apparently they discovered some issue with the camera when the NFC chip was enabled, and decided to fix this by disabling the NFC chip altogether when the camera is enabled.

I've created a pull request (#736) that doesn't really fix the issue, but fixes the IsScanning bindable property so you can disable the camera property to allow NFC scanning. Not sure if this fixes you scenario, but it might get you closer to a solution

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
