### ISSUE TITLE
OnScanResult Image from Camera View Finder

### ISSUE THREAD

**Issue by adamzucchi** [Redth/ZXing.Net.Mobile#666]
Is it currently possible within the OnScanResult event to get the image from the camera's view finder?  More or less I want to "take a picture" of what the scanner was reading when that event fires.

Thanks!

**Comment by Slaymd** [comment]
Hi @adamzucchi did you find a solution for this issue ?

I need also to take a picture of the camera stream ! 😉

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
