### ISSUE TITLE
IOS11 v2.3.2  barcodes decoded with asterisk

### ISSUE THREAD

**Issue by fizze** [Redth/ZXing.Net.Mobile#667]
I'm using Xamarin Forms on iOS11 using ZXing.Net.Mobile 2.3.2 and ZXing.Net.Mobile.Forms 2.3.2 and Xamarin.Forms 2.5.0.121934.

These are the options I use
`
            var options = new ZXing.Mobile.MobileBarcodeScanningOptions(); 
            options.AutoRotate = true;
            options.TryHarder = true;
            options.TryInverted = true;
            options.AssumeGS1 = false;
            options.CharacterSet = "ISO-8859-1";

            options.PossibleFormats = new System.Collections.Generic.List<ZXing.BarcodeFormat>();
            options.PossibleFormats.Add(ZXing.BarcodeFormat.DATA_MATRIX);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.All_1D);
			
            options.UseCode39ExtendedMode = false;
`

I'm using the options above and not the native AVCaptureEngine. Barcodes seem to be decoded in general, but the first, fifth, etc. character are always replaced by asterisks.

So instead of 

`0123456789`

here http://barcode4j.sourceforge.net/images/example-code128.svg
I get 

`*1234*6789`

This is a sample barcode that is well-known to work. It was created using barcode4j.

I've tried to alter options, but couldn't find any combination that returns a different result.
It doesn't matter whether I try to use Code128, Code39, datamatrix, etc. The behaviour is always the same regarding the asterisks.

Any ideas how to fix this?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
