### ISSUE TITLE
ZXing.BarcodeReader or ZXing.QrCode.QRCodeReader not decode 

### ISSUE THREAD

**Issue by maxpower80** [Redth/ZXing.Net.Mobile#668]
Hello everyone, I have tried to use zxing (version 0.16.2.0 for .net 3.5) and I can not decode this QR image, I have searched for other similar errors and I have tried solutions such as setting TRY_HARDER or PURE_BARCODE parameters but the result is the same: decode function returns null. I have tried in the online application https://zxing.org/w/decode.jspx to attach the image and there if decoding is achieved. Please, could you tell me what may be happening? Thank you very much and greetings.

**Comment by charmosz** [comment]
Hi. I have the same problem. How did you solve it ? I also tried combinaisons of tryharder and purbarcode but it doesn't work.
Thanks
