### ISSUE TITLE
NuGet package 2.3.2 is missing Windows Phone 8.0 / 8.1 Silverlight assemblies

### ISSUE THREAD

**Issue by mariorasch** [Redth/ZXing.Net.Mobile#669]
Version 2.2.9 of the ZXing.Net.Mobile.Forms NuGet package contained Windows Phone 8.0 / 8.1 Silverlight assemblies:

- ZXing.Net.Mobile.Forms.2.2.9
    - lib
        + MonoAndroid403
        + portable-net45+netcore45+wpa81+wp8
        + UAP10
        - wp8
            - ZXing.Net.Mobile.Forms.dll
            - ZXing.Net.Mobile.Forms.WindowsPhone.dll
        + Xamarin.iOS10

But version 2.3.2 of the ZXing.Net.Mobile.Forms NuGet package completely lacks the Windows Phone 8.0 / 8.1 Silverlight assemblies:

- ZXing.Net.Mobile.Forms.2.3.2
    - lib
        + MonoAndroid403
        + portable-net45+netcore45+wpa81+wp8
        + UAP10
        + Xamarin.iOS10

Is this intended or just a packging mistake?

Thanks in advance & best regards!

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
