### ISSUE TITLE
Result ResultPoints not matching position of the scanned barcode.

### ISSUE THREAD

**Issue by RudolphL** [Redth/ZXing.Net.Mobile#670]
I have the scanner full screen, in a grid with some stacklayouts on top of it so I can use the camera in a small area. I need to recognize the position of the barcode and only do something when it is in that specific area. 

When I see the barcode in the desired area and I check the ResultPoints, they are not in the bounds of the area I am seeing it in. Does someone knows a way to calculate this? The ResultPoints are relative to what?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by JTOne123** [comment]
Looks like 3.0 beta5 does not work on UWP

![image](https://user-images.githubusercontent.com/3457140/99265835-d0197980-282a-11eb-8c4b-3dac72dc7c32.png)
