### ISSUE TITLE
Get raw image in byte[] format from Output recoreder of iOS

### ISSUE THREAD

**Issue by ysmoradi** [Redth/ZXing.Net.Mobile#672]
As far as I understand, in iOS, Output recorder captures video. Then it choose some frames to be scanned to find barcodes. It creates something called **luminanceSource** then it calls decode of barcode reader.

https://github.com/Redth/ZXing.Net.Mobile/blob/c37890cb6b40734e69750ea7b51b37ce4bb94d7b/Source/ZXing.Net.Mobile.iOS/ZXingScannerView.cs#L493

How can I get that raw image from luminanceSource (CVPixelBufferBGRA32LuminanceSource)? I want to run OCR using another library at the same time this library is trying to find some barcodes.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
