### ISSUE TITLE
NetStandard Support

### ISSUE THREAD

**Issue by dansiegel** [Redth/ZXing.Net.Mobile#673]
NetStandard support is a common requirement these days. It would be great if the next release could ship with netstandard support in addition to/or in lieu of PCL

**Comment by Pinox** [comment]
agree, with most libs upgrading this would be an awesome addition. Xamarin also supports .net standard from middle last year.

**Comment by PaulVrugt** [comment]
This is a duplicate item see https://github.com/Redth/ZXing.Net.Mobile/issues/578

**Comment by dansiegel** [comment]
@PaulVrugt I didn’t see the existing issue. Thank for pointing out the duplicate
