### ISSUE TITLE
Small barcode detection issue

### ISSUE THREAD

**Issue by XamarinApps** [Redth/ZXing.Net.Mobile#678]
Hello,
We are trying to build a Xamarin mobile android application that will detect the datamatrix (2D)  barcodes.  We have the item size and length of barcodes is 12mm to 12 mm. it seems barcodes longer than 3 cm are detected very good. But if they become smaller than 2 cm it's pretty difficult to detect them (even at TryHarder mode) because they are probably too small for 6 inches distance (from camera to the target) to be detected and when you put the camera closer it can't (auto)focus at the target.

Is there a way to configure the library so it can detect smaller barcodes at the same recommended 6 inches distance or maybe focus at smaller distance (12mm X 12mm)? Maybe some kind of Macro mode?

Thank you.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
