### ISSUE TITLE
Example app crashes when back button is pressed and ZXingScannerView is NOT scanning

### ISSUE THREAD

**Issue by bojan96** [Redth/ZXing.Net.Mobile#680]
Steps to reproduce:

- Start debugging UWP project
- Tap on label on main page
- Scan QR code, ZXingScannerView will disappear after successful scan
- Press back button, Application crashes.

Stack trace:
```
   at Windows.System.Display.DisplayRequest.RequestRelease()
   at ZXing.Mobile.ZXingScannerControl.<StopScanningAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ZXing.Mobile.ZXingScannerControl.<StopScanning>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

Exception message:

> A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

If you click on scan again button and then on back button, app will not crash.

Sample project:
[ZXingScannerViewTest.zip](https://github.com/Redth/ZXing.Net.Mobile/files/1736823/ZXingScannerViewTest.zip)

**Comment by michaelmontero** [comment]
In Android throw a NullPointerException, when can handle it.

**Comment by AArayeshi** [comment]
I have same NullPointerException error in android.

**Comment by Simba-Mupfunya** [comment]
Noticed the same issue and it is July! Working around it by stopping the scan process in the "onDisappearing" override of the view in question. Need this fixed properly though.

**Comment by Goncharuk-Nikita** [comment]
Да, у меня такая же проблема

**Comment by Goncharuk-Nikita** [comment]
Yea, i have the same issue

**Comment by ajmmurray** [comment]
Are there any solutions to this problem? I have encountered the same situation today.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
