### ISSUE TITLE
it sometimes requests camera permission when it isn't used

### ISSUE THREAD

**Issue by cansado2930** [Redth/ZXing.Net.Mobile#681]
Hello,
Some users have seen as on the UWP app and Android app show the message that it requests the camera permission when app isn't using the zxing module. Have you had this problem? Do you know some advice in order to fix this problem? 
Thank you!

**Comment by VahidShir** [comment]
I confirm this issue too. I'm using scanner view in one of my TabbedPage tabs.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
