### ISSUE TITLE
Cant Scan 1D Barcode in Android

### ISSUE THREAD

**Issue by santanudoors** [Redth/ZXing.Net.Mobile#682]
I am using the following code to Scan the barcodes using zXing Version 2.3.2

var options = new MobileBarcodeScanningOptions
            {
                AutoRotate = false,
                UseFrontCameraIfAvailable = false,
                TryHarder = true,
                DelayBetweenAnalyzingFrames=150,
                InitialDelayBeforeAnalyzingFrames=150,
                DelayBetweenContinuousScans=1000,
                UseNativeScanning=false,
                

                PossibleFormats = new List<ZXing.BarcodeFormat>
                {
                    ZXing.BarcodeFormat.CODE_39,
                    ZXing.BarcodeFormat.CODE_93,
                    ZXing.BarcodeFormat.CODE_128,
                    ZXing.BarcodeFormat.EAN_13,
                    ZXing.BarcodeFormat.QR_CODE
                }
            };
            var scan = new ZXingScannerPage(options);

            await Navigation.PushAsync(scan);

            scan.OnScanResult += (result) =>
            {
                Device.BeginInvokeOnMainThread(async () =>
                {
                   await Navigation.PopAsync();
                    txt_Barcode.Text = result.Text;
                });
            };

But unfortunately any of the barcodes & QR Codes can't be scanned, can anyone help me am I doing anything wrong.

The camera is showing scanning the code but its not showing the result.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
