### ISSUE TITLE
Please support .net standard

### ISSUE THREAD

**Issue by JaeWLee** [Redth/ZXing.Net.Mobile#685]
Please guys...

**Comment by jgiacomini** [comment]
A beta version is released with .net standard support

**Comment by Nixon-Joseph** [comment]
Full version just released with .net standard support.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
