### ISSUE TITLE
QRCode Image is blur

### ISSUE THREAD

**Issue by JaeWLee** [Redth/ZXing.Net.Mobile#687]
![untitled](https://user-images.githubusercontent.com/35772429/37195616-f7bdea14-23b6-11e8-8acc-2669ad2e4bb8.png)

BarcodeValues is 1

**Comment by ArtjomP** [comment]
Change height & width on generation 300 is ok

**Comment by JaeWLee** [comment]
I already set height and width 300

           <zxing:ZXingBarcodeImageView BarcodeFormat="QR_CODE"
                                         HeightRequest="300"
                                         WidthRequest="300"
                                         HorizontalOptions="Center"
                                         VerticalOptions="Center"
                                         BarcodeValue="{Binding BarcodeValue}" />

**Comment by ArtjomP** [comment]
```
             xmlns:zxcm="clr-namespace:ZXing.Common;assembly=zxing.portable"
       
     <zx:ZXingBarcodeImageView.BarcodeOptions>
                <zxcm:EncodingOptions Width="300" Height="300" />
            </zx:ZXingBarcodeImageView.BarcodeOptions>
```

**Comment by JaeWLee** [comment]
Oh my goodness, Thanks guys

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
