### ISSUE TITLE
Unable to replicate barcode scanner demo app impressive performance with Xamarin

### ISSUE THREAD

**Issue by asterixorobelix** [Redth/ZXing.Net.Mobile#689]
Hi

Thanks for the great Nuget package!

I have implemented an Android fragment which is opening the scanner. However, my app is struggling to decode what is an admittedly large qr code. The thing is that both of your demo apps on the google play store dont struggle at all - they decode the qr code almost instantly.

Do you think you could help by listing the settings for the app? Particularly the [ZXing Test app](https://play.google.com/store/apps/details?id=com.google.zxing.client.androidtest), the Scan QR code option is extremely fast. For the [Barcode Scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en), the best settings are:  Decode QR Codes and Data Matrix and Use auto focus. I see that the MobileBarcodeScanningOptions object has options which cannot be ticked in the settings section of the app. Is it possible that one of those options is what is improving performance? Maybe DelayBetweenContinuousScans or something? Alternatively, could the custom overlay on the scanning view be helping decode the qr code?

My code:
```
_scanner = new MobileBarcodeScanner();

            try
            {
                var options = new MobileBarcodeScanningOptions
                {
                    PossibleFormats = new System.Collections.Generic.List<ZXing.BarcodeFormat> 
                              { 
                                 ZXing.BarcodeFormat.QR_CODE, ZXing.BarcodeFormat.DATA_MATRIX 
                              },
                    TryHarder = false,
                    AutoRotate = false,
                    DisableAutofocus = false
                    
                };
                _result = await _scanner.Scan(options)
                    .ConfigureAwait(false);
            }
            catch (Exception e)
            {
                Mvx.Error($"Unable to scan :: {e.Message}");
                return string.Empty;
            }
            return _result?.Text ?? string.Empty;
```

**Comment by gtbuchanan** [comment]
The apps you linked to on Google Play are not using this library. They are using the [original ZXing library](https://github.com/zxing/zxing) written in Java. ZXing.Net.Mobile is using a port of ZXing written in C# ([ZXing.Net](https://github.com/Redth/ZXing.Net)).

**Comment by asterixorobelix** [comment]
Thanks for the input Taylor.

Would you be able to help me in translating the settings from those apps
into the .net port?

If I want to scan qr codes exclusively, as quickly as possible, which
settings should I use in the .net port? The qr codes contain strings as a
payload and are fairly large.

Regards,
Nathan Stasin

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
