### ISSUE TITLE
Google Glass

### ISSUE THREAD

**Issue by JudgeyK** [Redth/ZXing.Net.Mobile#690]
I have tried for days now to get ZXing working through Zamarin for Visual Studio in C# using online samples and my project has no errors,  deploys without issue but when I open the App on the Glass,  the overlay pops up saying to point to the QRCode and then the app just closes straight away without error.  I have everything in a Try..Catch so its not trapping any exception.

I would have thought the view through the Camera would appear through the overlay but it doesn't seem to open the camera before it closes.  I have the below in the manifest ;
   
<uses-permission android:name="android.permission.CAMERA" />

Can anybody help as I've spent over £1000 for these glasses to try and implement something at work and I'm getting nowhere ...

UPDATE: I managed to get the Exception, 

Java.Lang.RuntimeException: setParameters failed

I am using ZXingNetMobile Version v4.0.30319

Kind Regards

JudgeyK

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
