### ISSUE TITLE
How can I set the initial zoom value ?

### ISSUE THREAD

**Issue by CrustyApplesniffer** [Redth/ZXing.Net.Mobile#694]
Hello,

I wonder if there is a way to set the initial zoom value to, for exemple 150%.

Thank you

**Comment by CrustyApplesniffer** [comment]
Any help available ?

**Comment by Kilepicunicorncom** [comment]
Manage to find a solution? Need help

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
