### ISSUE TITLE
2.4.0 Beta nuget packages broken

### ISSUE THREAD

**Issue by filoe** [Redth/ZXing.Net.Mobile#697]
Creating a new xamarin forms project, installing the forms packages for *all* projects.
Building the project fails with the following error:

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ZXingNetMobile, Version=2.4.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

**Comment by davidcourtneypower** [comment]
Can confirm this issue is happening to me too on a new project.

**Comment by jmelendez025** [comment]
Same problem here.

**Comment by christophedemey** [comment]
Same problem here with version 2.4.1 

Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ZXingNetMobile, Version=2.4.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
Bestandsnaam: ZXingNetMobile.dll
   bij Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   bij Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   bij Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	App6.Android

**Comment by freezersharp** [comment]
This piece of crap doesn't work anymore, I guess...
I hate te fast evolution of Xamarin, many components stop working suddently :@

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
