### ISSUE TITLE
Changelog not updated since v2

### ISSUE THREAD

**Issue by Devvox93** [Redth/ZXing.Net.Mobile#698]
I'm performing maintenance on an app using ZXing.Net.Mobile v1.4.7.1 and am in doubt if I should/need to upgrade to v2.x (current latest stable is 2.3.2).
I wanted to check out the changelog for breaking changes or special additions, but this hasn't been updated since the v1.4.7.1 version I am on now.
Is it possible to have this info added or is it published elsewhere?

I know this is not a technical issue, but an issue with this repo/product nonetheless.
Apologies if I should have contacted in a different way.

**Comment by Mr-Pearce** [comment]
Latest is 2.4.1 and there is still no update on that file

**Comment by Devvox93** [comment]
I see there is sort of a changelog in the releases-part on Github.
It should be copied into the Changelog.MD file, but at least the info is there.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
