### ISSUE TITLE
Object reference not set to an instance of an object at ZXing.Mobile.ZxingActivity.OnCreate

### ISSUE THREAD

**Issue by kyluke** [Redth/ZXing.Net.Mobile#699]
The library crashed with the following error:

```
Exception android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object at ZXing.Mobile.ZxingActivity.OnCreate (Android.OS.Bundle bundle) [0x00038] in <efea63011d3948ec87ca87e2f7054e32>:0 at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <fa0798f662a44733ac6f432f05b7b43b>:0 at (wrapper dynamic-method) System.Object.4441cf90-4518-4163-a3db-495bec50c38e(intptr,intptr,intptr) 
```

Any ideas on what the issue could be? The device in question was running Android 4.4.4

**Comment by kyluke** [comment]
@greg-dickie, No, I haven't solved this.

**Comment by greg-dickie** [comment]
Thanks @kyluke. I will see if I can provide some more information and test cases.

**Comment by kyluke** [comment]
Happened again on a Nexus 6 & a Nexus 7.
@Redth, is there any resolution for this, or can you recommend a way to gracefully deal with the error?

**Comment by kyluke** [comment]
Another crash on a Nexus 6 device. There seems to be an issue directly related to the Nexus line.

**Comment by kyluke** [comment]
Good day, another crash was reported on a Nexus 6 running Android 7.1.1

```
Fatal Exception: md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object
       at ZXing.Mobile.ZxingActivity.OnCreate(Android.OS.Bundle bundle)[0x00038](ZxingActivity0x00038.cs:1)
       at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)[0x00011](Activity0x00011.cs:1)
       at   at (wrapper dynamic-method) System.Object.12(intptr,intptr,intptr).(unknown.cs:1)
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by lassana** [comment]
The crash also occurs in 3.0 version but I believe this is some sort of Google's anti-malware check. We receive quite a lot of "NRE at ZxingActivity.OnCreate" crashes, and they are *always* from Pixel 3a or Nexus 6, and the locale is *always* en_US, even though we have zero users from United States.

The crash can easily be reproduced by launching ZxingActivity manually although you need a rooted device:

```
$ adb shell
$ su
# am start -n your.application.id/crc6480997b3ef81bf9b2.ZxingActivity
```

The actual activity name may be different in you app but [can be easily found](https://stackoverflow.com/q/6547703/1348726).

Ideally ZXing should not crash in this case so developers wouldn't be spammed with such crash reports.
