### ISSUE TITLE
2.4.1 update apparently needs manual reference to zxing.net.mobile in android projects

### ISSUE THREAD

**Issue by PaulVrugt** [Redth/ZXing.Net.Mobile#701]
Hello,

After upgrading zxing.net.mobile.forms to 2.4.1, i got error in the android projects that the namespace android was not found in ZXing.Net.Mobile. I had to manually include the zxing.net.mobile package in the android projects for it to work again. This was not neccesary in earlier versions of the forms library. It automatically had a dependency to the zxing.net.mobile package.

**Comment by sushibear** [comment]
I tried that too but no success. Uninstalled ZXing.Net.Mobile and Zwing.Net.Mobile.Forms then readded both to the Android project. Nothing. An other idea what might be wrong here?

**Comment by PaulVrugt** [comment]
Nope, adding the manual reference to ZXing.Net.Mobile did the trick for me. Does the package reference list any dlls under it in the android project?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sushibear** [comment]
I added one dll (ZXing.Net.Mobile.Forms.Android) to my references and that worked. But I can not access the namespace ZXing.Net.Mobile.Android.

It works flawless with Version 2.3.1 btw. so I did a roll back. :(

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
