### ISSUE TITLE
Missing ZXing.Net.Mobile.Android after Update 2.4.1 

### ISSUE THREAD

**Issue by sushibear** [Redth/ZXing.Net.Mobile#703]
I too just installed the update to 2.4.1 and have several issues here.

1. ZXing.Net.Mobile.Forms.Android.dll was not referenced (fixed that manually)
2. A ZXing.Net.Mobile.Android.dll does not exist after installing the NuGet package!?

I then tried cloning from master and compiling the ZXing.Net.Mobile.Forms.Android from source but it's asking me to install the Android SDK Platform 15, even though I have already all SDKs > 23 installed!?

Since there is a dependency to Xamarin.Android.Support.v4 (v25.4.0.1) I checked my version. I got 25.4.0.2 so this should not be the problem!? 

Something seems to be wrong here!? Any ideas?

**Comment by AdamGrzesiak** [comment]
Did you try to install also ZXing.Net.Mobile (not only ZXing.Net.Mobile.Forms)?

**Comment by sushibear** [comment]
Yes, both were installed.

**Comment by aherrick** [comment]
I'm seeing this too i my Forms App. Upgrading to 2.4.1 ZXing.Net.Mobile.Forms.Android.dll was not referenced. Rolled back to previous stable.

**Comment by aherrick** [comment]
I just installed ZXing.Net.Mobile Android Manually and it fixed the issue.

**Comment by wuhuangjia** [comment]
so 2.4.1 need manually installed, can't from nuget?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by marios-dev** [comment]
Had the same problem, issue was dealt with by adding zxing.net.mobile as well
