### ISSUE TITLE
The function of sweep code can be enhanced, and the speed of scanning and the beauty of interface are enhanced.

### ISSUE THREAD

**Issue by ghd258** [Redth/ZXing.Net.Mobile#705]
The function of sweep code can be enhanced, and the speed of scanning and the beauty of interface are enhanced. 
![qq 20180407073120](https://user-images.githubusercontent.com/4811375/38448336-211c7598-3a36-11e8-99ad-e3da3a68d04c.jpg)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
