### ISSUE TITLE
Permission handling not working after recent update

### ISSUE THREAD

**Issue by titonton** [Redth/ZXing.Net.Mobile#706]
in version 2.4.1, the PermissionHandler does not exist anymore. Do the permissions have to be handled on our own from now on? The changelog also seems to be far behind as well.

**Comment by PaulVrugt** [comment]
See #701

**Comment by titonton** [comment]
I figured the problem that same day. I forgot to come back and say that. thanks for the reply though.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
