### ISSUE TITLE
Android sample can not load zxing.portable project current release

### ISSUE THREAD

**Issue by Ultimatewidder** [Redth/ZXing.Net.Mobile#707]
Hello, 

with the current release in VS 2017 the  zxing.portable project can not load. The warning message is translated to english like "IDE0006	Error on loading the project. Some projectfeatures... are deactivated".

What can I do to load it successfully?

Kind regards

**Comment by PaulVrugt** [comment]
See #701

**Comment by Ultimatewidder** [comment]
Hello Paul, thanks for the hint.
In my first trying I downloaded the files  as zip archive. Today I i cloned it and everything works fine. The problem shows only up when downloading the zip archive. I redownloaded today again the zip archive and the problem showed up again. Seems like something is missing or corrupted in the zip archive.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
