### ISSUE TITLE
Panasonic FZ F1 zxing camera not working once integrated barcode scanner(Point of service) started

### ISSUE THREAD

**Issue by abhinavsk90** [Redth/ZXing.Net.Mobile#708]
Hi,

I have a requirement of scanning barcode both through the camera as well as the integrated barcode. our current scenario is when we open the zxing camera and close it and then start the integrated barcode then zxing camera stops working.

I am using the sample of barcode scanner : https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BarcodeScanner

and zxing : https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/WindowsUniversal/Sample.WindowsUniversal

Code: // after successful creation, claim the scanner for exclusive use and enable it so that data received events are received.
claimedScanner = await scanner.ClaimScannerAsync();

after claimedScanner initialized, zxing camera is not opening. Seems POS is utilizing some camera resource which should not supposed to be as both are different units.

Same scenario is working as expected in Honeywell CT50.

Please let us know if any solution

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
