### ISSUE TITLE
System.TypeLoadException right after starting the app

### ISSUE THREAD

**Issue by Zsoltimester** [Redth/ZXing.Net.Mobile#711]
Hello,

Approximately 2 days ago my templates worked, but today even with just starting a new project and adding ZXing.Net.Mobile.Forms package, starting the debug I got an exception in my MainActivity.cs on line global::Xamarin.Forms.Forms.Init(this, bundle):

System.TypeLoadException has been thrown
Could not load type ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer while decoding custom attribute: (null)

Any advise?

Thanks,

Zsolt
Visual Studio for Mac 7.4.2

**Comment by ufuf** [comment]
How did you solve this?
