### ISSUE TITLE
Scanner not working after App resume

### ISSUE THREAD

**Issue by Darth-Alex** [Redth/ZXing.Net.Mobile#712]
Zxing Used: 2.4.1
XamarinForms: 2.5.0.122203

First try:
Scan QR Code: Works Fine

Steps to Reproduce:
Go To Scanner View
Bring app to Background
Resume into App
Scanner seems to work (Camera displays the QR Code)
Scan seems not to be triggered

I tried it in a clean Solution... Here is the code:

`ZXingScannerView zxing;
        ZXingDefaultOverlay overlay;

        public QrScannerPage () : base()
		{
            zxing = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingScannerView",
            };
            zxing.OnScanResult += (result) =>
            Device.BeginInvokeOnMainThread(async () => 
            {
                // Stop analysis until we navigate away so we don't keep reading barcodes
                zxing.IsAnalyzing = false;

                // Show an alert
                await DisplayAlert("Scanned Barcode", result.Text, "OK");

                zxing.IsAnalyzing = true;

                // Navigate away
                //await Navigation.PopAsync();
            });

            overlay = new ZXingDefaultOverlay
            {
                TopText = "Hold your phone up to the barcode",
                BottomText = "Scanning will happen automatically",
                ShowFlashButton = zxing.HasTorch,
                AutomationId = "zxingDefaultOverlay",
            };
            overlay.FlashButtonClicked += (sender, e) => {
                zxing.IsTorchOn = !zxing.IsTorchOn;
            };
            var grid = new Grid
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };
            grid.Children.Add(zxing);
            grid.Children.Add(overlay);

            // The root page of your application
            Content = grid;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            zxing.IsScanning = true;
            zxing.IsAnalyzing = true;
        }

        protected override void OnDisappearing()
        {
            zxing.IsScanning = false;
            zxing.IsAnalyzing = false;

            base.OnDisappearing();
        }`

**Comment by Thetyne** [comment]
Same for us. test on Android.

**Comment by Simon755** [comment]
Same here, any workaround?

**Comment by egz019** [comment]
Scanner is not working upon resuming to the app? anyone figure it out?

**Comment by andrewbaranov** [comment]
The same probrem! Need help !

**Comment by egz019** [comment]
@andrewbaranov What we did here was we added the control once the app appears. We put the adding of the zxing control in the OnAppearing() and for disappearing(OnDisappearing()) we also remove the control. Hope it helps.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
