### ISSUE TITLE
On Android camera permission is not asked again after being denied once. (never show again is not selected)

### ISSUE THREAD

**Issue by vikram-ma** [Redth/ZXing.Net.Mobile#713]
Version

ZXing.Net.Mobile : 2.3.2
ZXing.Net.Mobile.Forms : 2.3.2

Android targetSdkVersion = 26

In my Xamarin form app, I have a custom scan page similar to 
https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Forms/Core/CustomScanPage.cs

When I first open this page, camera permission is asked, if I deny the permission, close this screen and go back to this screen, permission is not asked again. "never ask again" is not selected when permission is denied. However if I restart the app, the permission is asked.

Any solution for this? Thanks

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by ParsaGachkar** [comment]
Any update on this issue? Is there no way to ask for permission again? i thought this was an os limitation on android until i checked on WhatsApp application. So, it is possible to ask for permission again if it was rejected. Can anyone help me fix this issue in my app?

**Comment by ParsaGachkar** [comment]
Any update on this issue? Is there no way to ask for permission again? i thought this was an os limitation on android until i checked on WhatsApp application. So, it is possible to ask for permission again if it was rejected. Can anyone help me fix this issue in my app?
