### ISSUE TITLE
MaxiCode not scanning

### ISSUE THREAD

**Issue by ankiitbansal** [Redth/ZXing.Net.Mobile#715]
Xamarin iOS MaxiCode is not scanning. Any solution for this.

**Comment by micjahn** [comment]
MaxiCode only works with PureBarcode = true because there exists no real detector.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
