### ISSUE TITLE
Android 7 ZXingScannerPage orientation

### ISSUE THREAD

**Issue by masterwotikar** [Redth/ZXing.Net.Mobile#719]
I've set the screen orientation to Portrait for my app and the ZXingScannerPage worked perfect with it. After a Android update the orientation of the app is still portrait but the ZXingScannerPage is landscape. Even if i disable auto screen rotation in Android OS.

Added a customoverlay to the scanner and set AutoRotate = false and also to true but no effect.

Figured out that the problem exists on a Android 7 Tab. Another tab with Android 4.2 doesn't have this problem.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
