### ISSUE TITLE
iOS Console Spam "Too soon between frames"

### ISSUE THREAD

**Issue by gtbuchanan** [Redth/ZXing.Net.Mobile#721]
As soon as the scanner view is displayed on iOS, "[Too soon between frames](https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.iOS/ZXingScannerView.cs#L458)" is spammed to the console multiple times per second. This continues even after the scanner view is destroyed.

Example:

> 2018-05-03 09:58:06.942 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:06.968 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.010 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.107 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.135 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.176 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.275 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.301 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.343 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.440 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.468 Ewn.Mobile.iOS[44162:3894780] Too soon between frames
> 2018-05-03 09:58:07.510 Ewn.Mobile.iOS[44162:3894780] Too soon between frames
> 2018-05-03 09:58:07.606 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.635 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.676 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.777 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.801 Ewn.Mobile.iOS[44162:3894754] Too soon between frames
> 2018-05-03 09:58:07.843 Ewn.Mobile.iOS[44162:3894754] Too soon between frames

Needless to say, this is extremely annoying and unnecessary.

**Comment by Twillen** [comment]
You can reduce the amount of spam by reducing the delay between analyzing frames.

**Comment by mrexodia** [comment]
This worked for me:

```
zxing.Options.DelayBetweenAnalyzingFrames = 5;
zxing.Options.DelayBetweenContinuousScans = 5;
```

**Comment by yoshcraft** [comment]
@mrexodia where did you put our two line of code ?

**Comment by mrexodia** [comment]
Search for DelayBetweenAnalyzingFrames in this repository. I dropped this library in favor of swift since my use case was super simple.

**Comment by barmouta** [comment]
Yes, it works! In the constructor of your (Xamarin forms) custom page:
public AddBarcodePage()
		{
			InitializeComponent();
            BindingContext = new AddBarcodePageViewModel();

            zxing.Options.DelayBetweenAnalyzingFrames = 5;
            zxing.Options.DelayBetweenContinuousScans = 5;
        }

Also don't forget to add:

protected override void OnDisappearing()
        {
            zxing.IsScanning = false;
            base.OnDisappearing();
        }

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by joepb** [comment]
Curiously the default values of `DelayBetweenAnalyzingFrames` and `DelayBetweenContinuousScans` are 150 and 1000. 
So why does setting them to 5 help...? 🤔

**Comment by justintoth** [comment]
I can confirm that setting the two delay values to 5 works!!
