### ISSUE TITLE
How to initialize  MobileBarcodeScanner.Initialize (Application) for android

### ISSUE THREAD

**Issue by satyansh-sagar** [Redth/ZXing.Net.Mobile#722]
Its mentoned that for xamarin forms for android we have to include  MobileBarcodeScanner.Initialize (Application); line. 
Where to write this line , I am getting an error 'object reference not set to an instance of an object'.

Please if anyone have got this working help me out.

**Comment by gtbuchanan** [comment]
No, that is what you call for Xamarin Android. For Xamarin Forms in the Android project you call:

    ZXing.Net.Mobile.Forms.Android.Platform.Init();

This is clearly mentioned in the Xamarin Forms section of the README.

**Comment by gamegeartw** [comment]
I can't use 
`ZXing.Net.Mobile.Forms.Android.Platform.Init();
this is my Error code

> CS0234  C# The type or namespace name 'Forms' does not exist in the namespace (are you missing an assembly reference?)
I use ZXing.Net.Mobile version 2.4.1
plz help me to fix error

**Comment by omelhus** [comment]
Install the package ZXing.Net.Mobile.**Forms** from Nuget.

**Comment by fzany** [comment]
> Its mentoned that for xamarin forms for android we have to include MobileBarcodeScanner.Initialize (Application); line.
> Where to write this line , I am getting an error 'object reference not set to an instance of an object'.
> 
> Please if anyone have got this working help me out.

I also have the same issue right now

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by xshiiiidev** [comment]
On the version 2.4.1

the documentation initialization for Xamarin Forms Android

```
Xamarin.Essentials.Platform.Init(Application);
ZXing.Net.Mobile.Forms.Android.Platform.Init();
```

is not working for android and keeps throwing this error.

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

**Comment by tnewell** [comment]
I'm just going to leave this here to confirm what xshiiiidev said. The call to the _Initialize_ method needs to be in the main activity class of the Android project, in _OnCreate_, not the main project. Otherwise you get the object reference error. Place it after the _Platform.Init_ call and things should start working.

Otherwise, thanks to the developers for doing this port. This package made my life so much easier.

**Comment by Fortuntato** [comment]
> 
> 
> On the version 2.4.1
> 
> the documentation initialization for Xamarin Forms Android
> 
> ```
> Xamarin.Essentials.Platform.Init(Application);
> ZXing.Net.Mobile.Forms.Android.Platform.Init();
> ```
> 
> is not working for android and keeps throwing this error.
> 
> `System.NullReferenceException: 'Object reference not set to an instance of an object.'`
> 
> Edit:
> 
> Alright I found the solution from this issue link: #873
> 
> You have to initialize it on the Xamarin Forms Android Main Activity like this
> 
> `ZXing.Net.Mobile.Forms.Android.Platform.Init(); ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);`
> 
> or like this
> 
> `ZXing.Mobile.MobileBarcodeScanner.Initialize (Application);`
> 
> Can someone please kindly update the documentation. I spent the whole night looking for what's wrong in my code, only to see it's the documentation problem.
> 
> @Redth please thanks.

For me the second option seems to be fine. Glad to have found this thread pretty soon, cheers!

**Comment by voh83** [comment]
This doesn't work with F#, I can not use Application in the MainActivity.fs for Android. If I include following the :

```
        base.OnCreate (bundle)
        Xamarin.Essentials.Platform.Init(this, bundle)
        Xamarin.Forms.Forms.Init(this, bundle)
        ZXing.Net.Mobile.Forms.Android.Platform.Init();
        ZXing.Mobile.MobileBarcodeScanner.Initialize(Application)
        this.LoadApplication(App())
```

the error is the following:
 
`This function takes too many arguments, or is used in a context where a function is not expected`

Can someone help me with this?
