### ISSUE TITLE
Xamarin.Forms crash

### ISSUE THREAD

**Issue by filoe** [Redth/ZXing.Net.Mobile#724]
When removing the view, there sometimes occurs the following error:

System.NullReferenceException: Object reference not set to an instance of an object.

> 05-13 14:22:17.509 I/art     ( 2850): Thread[2,tid=2855,WaitingInMainSignalCatcherLoop,Thread*=0xaed32000,peer=0x12c740a0,"Signal Catcher"]: reacting to signal 3
> 05-13 14:22:17.587 I/art     ( 2850): Wrote stack traces to '/data/anr/traces.txt'
> 05-13 14:22:19.268 I/MonoDroid( 2850): UNHANDLED EXCEPTION:
> 05-13 14:22:19.269 I/MonoDroid( 2850): System.NullReferenceException: Object reference not set to an instance of an object.
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <57b37b10a314448c8d6b2b9155539100>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <57b37b10a314448c8d6b2b9155539100>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <57b37b10a314448c8d6b2b9155539100>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__5.MoveNext () [0x0006b] in <57b37b10a314448c8d6b2b9155539100>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850): --- End of stack trace from previous location where exception was thrown ---
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
> An unhandled exception occured.
> 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <ff199c98c3f84852925dd37a0ef6113a>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <ff199c98c3f84852925dd37a0ef6113a>:0 
> 05-13 14:22:19.269 I/MonoDroid( 2850):   at (wrapper dynamic-method) System.Object.409c003c-b2e3-4eb0-8de7-aa4d097447eb(intptr,intptr)
> 05-13 14:22:19.272 W/art     ( 2850): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by NiPfi** [comment]
I had a similar crash on
`LoadApplication(new App());`
but cleaning the Solution in VisualStudio solved the issue for me

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
