### ISSUE TITLE
Version Conflict with Xamarin.Android.Support.Compat

### ISSUE THREAD

**Issue by MasoudShah** [Redth/ZXing.Net.Mobile#726]
In the last version (v2.4.1) I keep facing the error below. It doesn't happen in the previous version (v2.3.2). Because of this, I'm unable to update it to the last one.
```
Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 {Project NameSpace} -> Xamarin.Android.Support.Design 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
 {Project NameSpace} -> ZXing.Net.Mobile 2.4.1 -> Xamarin.Android.Support.v4 25.4.0.1 -> Xamarin.Android.Support.Compat (= 25.4.0.1).
```
In the dependencies it's noted that it needs _Xamarin.Android.Support.v4 (>= 25.4.0.1)_ but I don't know why it only works with the exact version and not newer.

**Comment by David1930** [comment]
I solved it by below method but I am afraid it is correct method.
But anyway I am running it by below method.
1. NUGET Package Manager --> installed Tab --> Xamarin.Android.Support.Design 
   --> change Version 
          v27.0.2 --> v25.4.0.1 
2. then you can normally install ZXing.Net.Mobile 2.4.1
3. Finally you have to Set Target Compile Version upper than Android 7.0

**Comment by davidm** [comment]
I see this too.  Notice this commit https://github.com/Redth/ZXing.Net.Mobile/commit/64d6583d9da4a91280670e6582adc4f4ec212669 upped it from 25.4.0.1 to 25.4.0.2 at least.

**Comment by davidm** [comment]
I see this too.  Notice this commit https://github.com/Redth/ZXing.Net.Mobile/commit/64d6583d9da4a91280670e6582adc4f4ec212669 upped it from 25.4.0.1 to 25.4.0.2 at least, but it hasn't been released yet on nuget.

**Comment by xsv24** [comment]
I'm having the same issue updating to android 9, any chance in supporting Xamarin.Android.Support.* 28.0.0.1?

>Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 28.0.0.1 directly to project.

> {NameSpace} -> Xamarin.Android.Support.CustomTabs 28.0.0.1 ->  
> Xamarin.Android.Support.Compat (= 28.0.0.1)  
> {NameSpace}-> ZXing.Net.Mobile 2.4.1 -> Xamarin.Android.Support.v4 25.4.0.1   > -> Xamarin.Android.Support.Compat (= 25.4.0.1)

**Comment by Slywire** [comment]
Any updates on this issue yet? I'm also experiencing issues and need to upgrade to 28.0.0.1

**Comment by SvenCarstensen** [comment]
Same issue here....

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by bzd3y** [comment]
@Redth Those 3.x versions look like they are still beta. Is that ever going to change?
