### ISSUE TITLE
Crash/Stop camera-scan in last frame in some devices. v. 2.1.47 and v.2.4.1

### ISSUE THREAD

**Issue by devbbras** [Redth/ZXing.Net.Mobile#730]
So, I'am having a problem. 
When my OnDisappearing() is called with "zxingView.IsScanning = false;", my scan stop working (normal until here) and I try to resume my camera with my  OnAppearing(), with "zxingView.IsScanning = true;" and not resume, it crashes in last frame that camera stop, and I can't resume scan work. 

I remember that occurred in some devices.

Is There a solution for this? How I know when camera stop?

Thank you.

CODE:
```
namespace CameraTest
{
    public class CameraPage:ContentPage
    {
        ZXingScannerView zxingView;
        StackLayout stackLayout;
        Button button;
        public CameraPage()
        {
            zxingView = new ZXingScannerView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                AutomationId = "zxingScannerView",
                IsAnalyzing = true,
                IsEnabled = true,
                IsScanning = true,
            };

            zxingView.OnScanResult += (result) =>
            {
                Navigation.PushAsync(new MainPage());
            };

            button = new Button();
            button.Clicked += (s, e) =>
            {
                Navigation.PushAsync(new MainPage());
            };

            stackLayout = new StackLayout
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,

                Children =
                {
                    zxingView,
                    button,
                }
            };

            Content = stackLayout;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
            zxingView.IsScanning = true;
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();
            zxingView.IsScanning = false;
        }
    }
}
```

**Comment by wireless-r** [comment]
I have problems with setting `IsScanning` value differently also. Try to only set `IsAnalyzing = false;` and `IzAnalyzing = true;`. Let `IsScanning = true;` all the time.

**Comment by devbbras** [comment]
Thanks for your reply...

Yeah, I already knew that solution but I have a problem with that,

Seems like that if I set `IsScanning = true`, camera doesn't turn off, it keeps on. I worried about that, because my app drains a lot of battery with that implementation. I really need to turn off camera, in order to save battery.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
