### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by jorgetinocomx** [Redth/ZXing.Net.Mobile#732]
Hi everybody. 
I´m trying to install this package trhough nuget in VS2017 but I´m getting this error:
This happens to me only in 2.4.1 version. 2.3.2 version works like a charm.

Attempting to gather dependency information for package 'ZXing.Net.Mobile.Forms.2.4.1' with respect to project 'XExample.Android', targeting 'MonoAndroid,Version=v6.0'
Gathering dependency information took 1.84 sec
Attempting to resolve dependencies for package 'ZXing.Net.Mobile.Forms.2.4.1' with DependencyBehavior 'Lowest'
**Unable to resolve dependencies.**

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
