### ISSUE TITLE
Unable to scan Code39

### ISSUE THREAD

**Issue by ajithbabu** [Redth/ZXing.Net.Mobile#733]
Hi,
I'm trying to scan the Code39 formatted barcode.
If the barcode has fewer values like 1231214,14123 then it gives me a result. But it is not scanning the barcodes that are having values more than 32digits.
I'm attaching the barcode image which is failed to scan.
![barcode](https://user-images.githubusercontent.com/37439027/40663125-a579ff82-6375-11e8-99f8-e139aaa2dbf0.gif)

Please help me to resolve this issue.
Thanks,
Ajithbabu

**Comment by bobwhitten** [comment]
Hmmm...   Initially, I could not get it to scan either.  I tried my iPhone app (not xamarin, not ZXing), and it scanned it.  Then I tried my Xamarin App again -- it worked.  For reference, using a Galaxy S7.   But it takes a while.    I'm wondering if this is a camera resolution issue?  Are you scanning off of paper, or the screen (which has it's own resolution)?

**Comment by ajithbabu** [comment]
I tried to scan a barcode in my CPU, it was not working.. It is having lengthy barcode values also more thin lines.  Actually my intention is to scan the VIN of cars.

**Comment by smoro88** [comment]
Were anyone of you able to figure out a workaround like ajithbabu I am trying to scan CAR VIN's with this package.    See below for sample.

![VIN2](https://user-images.githubusercontent.com/29660459/72347442-38954880-36a6-11ea-80d0-1854828734c8.jpg)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
