### ISSUE TITLE
Use torch while scanning

### ISSUE THREAD

**Issue by ajithbabu** [Redth/ZXing.Net.Mobile#735]
Hi,

Do i need to use custom overlay to turn on the torch while scanning?
Currently i'm not using any custom overlay, and tried calling the method ToggleTorch() but i don't see the torch light.

Thanks,
Ajithbabu

**Comment by RudolphKalp** [comment]
I am also facing the same problem! I see there is some kind of functionality available in their demo app on play store but I don't know how to implement this actively in an application.

**Comment by zlannin** [comment]
For Android make sure you have the Flashlight permission in your manifest

**Comment by dodocs** [comment]
Check if you are not turning torch too fast (right after initialization). It might be that, you call ToggleTorch() while camera was not initialized yet, ex. right after InitializeComponent() or setting IsTorchOn to True. Library is not checking that and if you do it like that, Torch won't start. Look for the commnet "I/ZXing.Net.Mobile(14310): Run camera first" in the VS output window. If you find it, it is your case and you should start Torch a bit later.

**Comment by VitorRigoni** [comment]
@dodocs is right. I was having this issue even if I attached a handler to the `Appearing` event and calling ToggleTorch() from there. Awaiting the navigation and then toggling the torch fixed the issue.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
