### ISSUE TITLE
Iphone X camera scans ok, but ZXing cannot

### ISSUE THREAD

**Issue by yowl** [Redth/ZXing.Net.Mobile#737]
I have this poor quality code which will not scan using ZXing.  However open the standard camera app on and iPhone X and it scans and redirects off to Safari.  I couldn't get the built in camera to work on an iphone 6 or 7.  I've tried setting the AVCaptureSession and UseNativeScanning but it still does not scan.  What options do you think best reflect what the built in camera app does?

![wontscan](https://user-images.githubusercontent.com/2720041/40935110-acba87c2-67fc-11e8-945d-7a398cf31812.png)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
