### ISSUE TITLE
Clean GitHub Check Out Does Not Compile

### ISSUE THREAD

**Issue by InnerScript** [Redth/ZXing.Net.Mobile#742]
When downloading the project, and importing into a clean Visual Studio Community 2017 installation, the project does not compile right away, even after platform dependencies are installed correctly.

Principally, project dependencies such as ZXing.Net are setup to load as an external .csproj, rather than NuGet, with little indication as to how to correctly configure import and assuming certain folder structures.

Most importantly, there is no documentation on how to check out a clean copy and setup the project, so bugs and enhancements can be added. This makes the first step for anyone choosing to assist with this project digging through .csproj files to try and resolve how it is setup.

**Comment by knocte** [comment]
Hey @InnerScript , I reproduced your problem if cloning without cloning the submodules, but don't reproduce it if I clone with --recursive flag, can you try this?

**Comment by InnerScript** [comment]
Can confirm that --recursive fixed the issue for me, using the same toolset. Thank you for the quick feedback!

May I suggest that be added to a developer guide, for future contributors? (I may be one shortly)
