### ISSUE TITLE
CustomOverlay does not exist in MobileBarcodeScanner

### ISSUE THREAD

**Issue by RudolphKalp** [Redth/ZXing.Net.Mobile#745]
I cannot use a custom overlay with MobileBarcodeScanner as there is no property available to assign a custom overlay to. This is the error that I get when I want to assign a view to that property.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MobileBarcodeScanner' does not contain a definition for 'CustomOverlay' and no extension method 'CustomOverlay' accepting a first argument of type 'MobileBarcodeScanner' could be found (are you missing a using directive or an assembly reference?)	ScannerTesting	C:\Users\kalpr\Source\Repos\ScannerTesting\ScannerTesting\ScannerTesting\MainViewModel.cs	88	Active

**Comment by azacchino** [comment]
Please see:

https://github.com/Redth/ZXing.Net.Mobile/blob/master/Samples/Android/Sample.Android/MainActivity.cs

you need include these using:
``` cs
using ZXing;
using ZXing.Mobile;
using ZXing.Net.Mobile.Forms;
```

and add the nugets pkg:
ZXing.Net.Mobile
ZXing.Net.Mobile.Forms

regards

**Comment by Wonderdch** [comment]
Still didn't work.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
