### ISSUE TITLE
App crash after requesting camera permission

### ISSUE THREAD

**Issue by steve-allan** [Redth/ZXing.Net.Mobile#750]
The allow/deny permission appears, requesting access to the camera. Click 'allow' and the app crashes with the message 'Value cannot be null. Parameter name: handle'.
On a second run through the permission has already been granted and the camera opens correctly.

Anyone else had this happen?

**Comment by sbirdius** [comment]
In Android MainActivity.cs , in OnRequestPermissionsResult function , replace 

global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);

with 

ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);

It should be ok now.

**Comment by steve-allan** [comment]
Thanks for the reply.
I'm not using Xamarin Forms so I don't have the global line to change.
I installed version 2.3.1 and had the same problem. If I allow Zxing to deal with the permission request itself I get the same "Value cannot be null" message.

**Comment by zhlavinka** [comment]
I just subscribed to this issue this morning. I can confirm that the workaround suggested by @sbirdius works for XF. I'm using Xamarin Forms 3.1.0.583944. I downgraded ZXing.Net.Mobile and ZXing.Net.Mobile.Forms from 2.4.1 to 2.3.1 (in my PCL and Android projects) and the issue no longer appears.

**Comment by stackunderflows** [comment]
I'm having this issue with Xamarin Forms too. I was using 2.4.1 and tried downgrading to 2.3.1, but it didn't fix the problem. Is there anyone maintaining this project?

**Comment by spsteve10** [comment]
Im having this same issue with 2.4.1 running Xamarin.Forms 3.1.  Crash after permission request on Android 6 Samsung Galaxy 6.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by stackunderflows** [comment]
I moved on to firebase ML for barcode scanning. Microsoft made bindings nugets for iOS and Android. It works great and is free.
