### ISSUE TITLE
iOS 12 Zxing does not work

### ISSUE THREAD

**Issue by ntkyen** [Redth/ZXing.Net.Mobile#751]
I am developing an application using Xamarin forms version 3.0.0.550146.
Using ZXing.Net.Mobile v2.4.1, it works well on both Android and iOS devices but seems I can not get the scanning result on iOS 12.
Is there any one have same problem?

**Comment by ntkyen** [comment]
i checked and saw it works well, dont know the reason but i close this issue.

**Comment by Alexabreu007** [comment]
Hi, how did you solve the problem in iOS.

**Comment by ntkyen** [comment]
hi @Alexabreu007 
I did not do anything, somehow it works again.
