### ISSUE TITLE
How to increase QR code recognition rate and speed

### ISSUE THREAD

**Issue by wml2017** [Redth/ZXing.Net.Mobile#752]
iOS camera app can recognize a QR easily and fast (less than 1 second and don't need to move iPhone) no matter what kind of angle between iPhone when the QR code within the reasonable distance .  Many other apps' QR code scanners also can scan QR codes very fast and easily. But ZXing.Net.Mobile is very hard to do it with the same condition. To scan the QR code successfully by my app with ZXing.Net.Mobile component, I have to change the phone's angle and the distance between phone and a QR code no matter the phone is an iPhone or Android phone even though I tried to change MobileBarcodeScanningOptions' paramters.  Also, ZXing can not recognize some QR codes but iPhone Camera can do it without any speed issue. My app uses the newest ZXing.Net.Mobile (v2.4.1) and the C# code:

        private async void btnScanQRcode_Clicked(object sender, EventArgs e)
        {
            var options = new MobileBarcodeScanningOptions
            {
                AutoRotate = true,
                UseFrontCameraIfAvailable = false,
                TryHarder = true,
                PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE },
                DelayBetweenAnalyzingFrames = 200,
                TryInverted = true,
                DisableAutofocus = false
            };
            var customOverlay = new StackLayout
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.EndAndExpand

            };
            ZXingScannerPage scanPage = new ZXingScannerPage(options, customOverlay: customOverlay);

            //TimeSpan ts = new TimeSpan(0, 0, 0, 2, 0);
            //Device.StartTimer(ts, () => {
            //    if (scanPage.IsScanning)
            //        scanPage.AutoFocus();
            //    return true;
            //});

            scanPage.OnScanResult += (result) =>
            {
                // Stop scanning
                scanPage.IsScanning = false;

                // Pop the page and show the result
                Device.BeginInvokeOnMainThread(async () =>
                {
                  //use result.Text to do something

                    await Navigation.PopAsync();
                });
            };

            // Navigate to our scanner page
            await Navigation.PushAsync(scanPage);

        }

Any suggestion to solve this issue?

**Comment by stephanemathis** [comment]
I have the same issue. It's very hard to make the scanner find my datamatrix.

**Comment by PauchardThomas** [comment]
Same issue... Iphone can't read QR Code with a color background != white and a white code...

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
