### ISSUE TITLE
Scan just in a given section

### ISSUE THREAD

**Issue by jonahbohlmann** [Redth/ZXing.Net.Mobile#753]
Hi, 
I have created a custom overlay. It is a fullscreen camera where at the top and buttom a black BoxView is (With transparency).

In the middle of the top and bottom BoxView is a blue scanner line.

Now I want that the scanner ONLY use the section between the top and bottom box.

Is there any option? How can I do that?

**Comment by Eiskaltereistee** [comment]
No idea?

**Comment by Redth** [comment]
Tracking this in #791
