### ISSUE TITLE
Xamarin iOS: not able to scan long linear 1d barcodes 

### ISSUE THREAD

**Issue by ankiitbansal** [Redth/ZXing.Net.Mobile#754]
Xamarin iOS: not able to scan long linear 1d barcodes . It either takes infinite time to scan or scan wrong value.

any solution?

**Comment by Narasegowda** [comment]
Got into same problem. Have you found any solution.

**Comment by ankiitbansal** [comment]
Yes, i tried reducing the camera resolution along with landscape mode and
it worked

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
