### ISSUE TITLE
Scanning the same QR code gives different results 

### ISSUE THREAD

**Issue by leelatoo** [Redth/ZXing.Net.Mobile#757]
Hi,

We have included Zxing scanner in our Xamarin.Forms application to scan QR codes.

Take a QR code (which contains the string "0;0;0;1;200;0;1;10;34;0;0;0;25;0;1;1;0;1;10").

Scan the qr code using ZXing scanner returns "0;0;0;1;200;0;1;10;34;0;0;0;25;0;1;1;0;1;10". In this case, it works as expected.

Scan the same qr code, the scanner returns the result "5610297328". It is NOT the expected string.

Can you please help us solve this problem? Is there any property to be set in ZxingScanner before scanning?

Thanks,
Leela

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
