### ISSUE TITLE
Zxing dosen't show the camera in some devices

### ISSUE THREAD

**Issue by zirocool** [Redth/ZXing.Net.Mobile#758]
Sory for my bad English.I used documentation of Zxing https://github.com/Redth/ZXing.Net.Mobile for implementing it on xamarin.android for barcode detector app. It is working fine on phones with android 6.0 and detect all kind of barcodes, But on phones with android 7.0 and higher, instead of camera it shows a page with my default color theme and shows buttons and textview that i have in layout. If i blindly without any camera put a barcode in front of camera it can detect it. so my only problem is i cannot see camera but it is working somehow.I searched Entire web but i cannot find anything useful.And yes i have permissions for camera and flashlight in manifest.This is my code for permissions:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
    {
        global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
    }
    protected override void OnResume()
    {
        base.OnResume();

        if (ZXing.Net.Mobile.Android.PermissionsHandler.NeedsPermissionRequest(this))
            ZXing.Net.Mobile.Android.PermissionsHandler.RequestPermissionsAsync(this);
    }
```

This is my code for initialize scanner

```
protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);
        MobileBarcodeScanner.Initialize(Application);
        SetContentView(Resource.Layout.xlRealMain);
        scanner = new MobileBarcodeScanner();

        this.Window.AddFlags(WindowManagerFlags.Fullscreen);
        btnbarcode = FindViewById<Button>(Resource.Id.barcode);
        btnbarcode .Click += async delegate {

            //Tell our scanner to use the default overlay
            scanner.UseCustomOverlay = false;

            //Start scanning
            var result = await scanner.Scan();

            HandleScanResult(result);
    }
    void HandleScanResult (ZXing.Result result)
    {
        string msg = "";

        if (result != null && !string.IsNullOrEmpty(result.Text))
            msg = "Found Barcode: " + result.Text;
        else
            msg = "Scanning Canceled!";

        this.RunOnUiThread(() => Toast.MakeText(this, msg, 
        ToastLength.Short).Show());
    }
```

ok please help me

**Comment by dhawal-mcs-fm** [comment]
I am facing the same issue on few devices on Android 5.1.

**Comment by dhawal-mcs-fm** [comment]
[https://github.com/Redth/ZXing.Net.Mobile/issues/739](url)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
