### ISSUE TITLE
code 128 barcodes giving false positive when scanned at an angle

### ISSUE THREAD

**Issue by ankiitbansal** [Redth/ZXing.Net.Mobile#760]
We are using Zxing.net.mobile with possible formats as code 39, Aztec and Code 128.

When we are scanning code 128 barcodes from some angle then we are getting false positive values from 2 out of 40 times (intermittently) i.e. random values like we are scanning 123456 but we are getting 3@&!.

Scanning options set as below:

  var options = new ZXing.Mobile.MobileBarcodeScanningOptions()
                    {
                        TryInverted = true,
                        AutoRotate = false,
                        TryHarder = false,
                        DelayBetweenAnalyzingFrames = 5,
                        DelayBetweenContinuousScans = 5,
                        InitialDelayBeforeAnalyzingFrames = 4,
                        PossibleFormats = new System.Collections.Generic.List<ZXing.BarcodeFormat>() {
                    ZXing.BarcodeFormat.AZTEC,
                   ZXing.BarcodeFormat.CODE_39,
                    ZXing.BarcodeFormat.CODE_128}};

we have set try harder = false to handle this. if we set try harder as true then the rate of false positive values is increasing. 

Is this a known issue and we have any solution to this? Or is this something we need to live with. 

Also we want your recommendation for using Zxing API for hospital based products where we expect 0 tolerance to false positives.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
