### ISSUE TITLE
Is this lib supporting only scanning using a camera or it also supports attached devices such as handheld wire-connected barcode scanners?

### ISSUE THREAD

**Issue by dbnex14** [Redth/ZXing.Net.Mobile#764]
I am looking for a solution to use a wired (or bluetooth) connected external barcode scanner such as Honeywell Xenon or Zebra DS series or some others.  So, camera barcode scanning is no option as it is slow.  Does this library supports that for Xamarin.Forms  with .NETStandard 2.0 for all 3 head projects IOS, Android, and UWP.

**Comment by Redth** [comment]
If the platform API's don't detect this as a camera, it won't work.  No plans otherwise.
