### ISSUE TITLE
Show scanned barcode to next page.

### ISSUE THREAD

**Issue by jsicad** [Redth/ZXing.Net.Mobile#765]
How can I pass the value of result.text to another page instead of displaying on DisplayAlert. Your help is highly appreciated.

private async void ButtonScanDefault_Clicked(object sender, EventArgs e)
{
scanPage = new ZXingScannerPage();
scanPage.OnScanResult += (result) =>
{
scanPage.IsScanning = false;
Device.BeginInvokeOnMainThread(() =>
{
Navigation.PopModalAsync();
DisplayAlert("Scanned Barcode", result.Text, "OK");
});
};
await Navigation.PushModalAsync(scanPage);
}

**Comment by burtybob** [comment]
The way I am doing for placeholders is by exposing the text box on the next page via a class level property that I can then call:
```
TestPage
{
Entry e;
public string BarcodeText
{
 get
{
return e.Text;
}
set
{
e.Text = value;
}
}
```

While I use "PlaceHolder" in my real sample should also work for the "Text" property as well

**Comment by zwilkin** [comment]
@jsicad 
Another option would be to pass the result through a class constructor when initializing navigation to the new page.  Make sure to make your scanning result an `async` method and use proper `await` identifiers so that you can correctly handle navigation.

For Example:
'''c#
private async void ButtonScanDefault_Clicked(object sender, EventArgs e)
{
    scanPage = new ZXingScannerPage();
    scanPage.OnScanResult += (result) =>
    {
        scanPage.IsScanning = false;
        Device.BeginInvokeOnMainThread(async () =>
        {
            await Navigation.PopModalAsync();    // Dismiss the camera
            await Navigation.PushAsync(new YourNewPage(result));    // Display the new page
        });
    };
    await Navigation.PushModalAsync(scanPage);
}
'''

Create a constructor for the new page like this:
'''
public YourNewPage(ZXing.Result result)
{
    InitializeComponent();

    // Do what you want with your result - such as assign the text value to a UI label
    // Example:
    barcode_label.Text = result.Text;
}
'''

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
