### ISSUE TITLE
"AndroidRuntimeException: Only the original thread ..."

### ISSUE THREAD

**Issue by wireless-r** [Redth/ZXing.Net.Mobile#766]
I have an app that scans fine for a long time, 50+ scans. Then suddenly it crashes at random.

>08-02 09:10:51.364 I/MonoDroid( 1831): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6375)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:921)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4691)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.View.invalidateInternal(View.java:11802)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.View.invalidate(View.java:11766)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.view.View.invalidate(View.java:11750)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at md51558244f76c53b6aeda52c8a337f2c37.FormsImageView.n_invalidate(Native Method)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at md51558244f76c53b6aeda52c8a337f2c37.FormsImageView.invalidate(FormsImageView.java:53)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.widget.ImageView.invalidateDrawable(ImageView.java:231)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:368)
08-02 09:10:51.364 I/MonoDroid( 1831): 	at android.graphics.drawable.Drawable.setVisible(Drawable.java:683)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1417)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.View.dispatchDetachedFromWindow(View.java:13568)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2835)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2835)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2835)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4221)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4194)
08-02 09:10:51.365 I/MonoDroid( 1831): 	at android.view.ViewGroup.removeView(ViewGroup.java:4125)

[Link to Hastebin with full exception](https://hastebin.com/owerixihag.log)

I am not sure why the `removeView` methods are called. I am not calling it, so it can be in the ZXing.

ScannerPage.xaml

```xaml
<zxing:ZXingScannerView x:Name="ScannerView"
    Result="{Binding ScanResult, Mode=OneWayToSource}"
    ScanResultCommand="{Binding ScanResultCommand}"
    IsScanning="{Binding IsScanning}"
    IsAnalyzing="{Binding IsAnalyzing}" />
<zxing:ZXingDefaultOverlay x:Name="ScannerOverlay"
    BottomText="Scanning will happen automatically"
    ShowFlashButton="False"/>
```

ScannerPageViewModel.cs (stripped of irrelevant parts)

```cs
[PropertyChanged.AddINotifyPropertyChangedInterface]
internal class ScannerPageViewModel : INavigatedAware
{
    public ScannerPageViewModel(IScannerService scannerService, IUserDialogs dialogs, IPopupNavigation popups, IScreenService screen)
    {
        ScanResultCommand = new Command(ProcessBarcode);
    }

    public ICommand ScanResultCommand { get; }

    /// <summary>
    /// Show info dialog box with ticket info.
    /// </summary>
    private async Task ShowInfoScanResult(string message)
    {
        var popup = new PopupViews.InfoScanResult(Popups, message);
        popup.Disappearing += (se, ev) => IsAnalyzing = true;
        await Popups.PushAsync(popup);
    }

    private void ProcessBarcode()
    {
        Device.BeginInvokeOnMainThread(async () =>
        {
            if (ScanResult != null && !string.IsNullOrEmpty(ScanResult.Text))
            {
                // Disable the scanner after one barcode is found.
                IsAnalyzing = false;

                var source = new CancellationTokenSource();

                // Show loading animation if scanning takes >1 second.
                var t = Task.Run(async () =>
                {
                    await Task.Delay(1000, source.Token);
                    Device.BeginInvokeOnMainThread(ShowLoading);
                });

                // Call the web service to process the barcode.
                var scanResponse = await ScannerService.ScanBarcode(ScanResult.Text, ScanningSession, SelectedScanAction);

                if (scanResponse.IsSuccessful)
                {
                    var scanResult = scanResponse.Data;
                    if (scanResult.Success)
                    {
                        var json = scanResult.BarcodeInfo;
                        var message = ParseJsonBarcodeInfo(json);

                        if (SelectedScanAction == ScanAction.Information)
                            await ShowInfoScanResult(message);
                        else
                            await ShowOkScanResult(message);
                    }
                    else
                    {
                        await ShowErrorScanResult(scanResult.FaultDescription);
                    }
                }
                else
                {
                    ShowScanRequestError(scanResponse.ErrorMessage);
                }

                source.Cancel(); // Cancel loading animation timer.
                HideLoading();
                Screen.SetFullscreen();
                source.Dispose();
            }
        });
    }
```

**Comment by nekszer** [comment]
Device.BeginThreadInvoke(() => {
    // ... view logic
   // view.Text= result;
});

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
