### ISSUE TITLE
iOS ZXingScannerView is zoomed in

### ISSUE THREAD

**Issue by cbartonnh** [Redth/ZXing.Net.Mobile#768]
I have a XF Forms app that is using ZXingScannerView and it appears that the camera is zoomed in 3X and it is having a tough time scanning complex QR codes. Android is not zoomed and is working fine.

Any way to change the zoom factor for iOS?

**Comment by heartquake** [comment]
I have the same problem. Android is fine but iOS camera is zoomed.

**Comment by Kilepicunicorncom** [comment]
Anyone found a fix to this? Am having the same problem :(

**Comment by heartquake** [comment]
I ended up resizing the scanner view to the devices display size. It helped.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
