### ISSUE TITLE
Camera seems not released correct after scan page is closed

### ISSUE THREAD

**Issue by neolithos** [Redth/ZXing.Net.Mobile#769]
I use ZXingScannerPage in combination with an buildin-scanner.
If the camera starts working the buildin-scanner turns of. And resumes after the video capturing is closed. This works well with the photo app.

But not with the ZXingScannerPage. Why? Where I have to look?

**Comment by knocte** [comment]
@neolithos can you test this pull request? https://github.com/Redth/ZXing.Net.Mobile/pull/725 It seems related.

**Comment by neolithos** [comment]
I can not build the library:

```
The assembly 'Cake.Android.SdkManager, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.XCode, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.Xamarin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.Xamarin.Build, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.SemVer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.MonoApiTools, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
Error: Der Typ "Cake.Core.CakeTaskBuilder`1" in der Assembly "Cake.Core, Version=0.30.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.
```

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
