### ISSUE TITLE
Use Front Camera

### ISSUE THREAD

**Issue by dktechindia** [Redth/ZXing.Net.Mobile#771]
Is there any option where I can give option to the user to use  the front camera while camera is open for scanning.

I want to give user option to toggle between front and back camera when camera is open for scanning.

**Comment by zwilkin** [comment]
To set the scanner to use the front-facing camera (if device has one), instantiate a new `ZXingScannerPage` with the following:

`ZXingScannerPage scanPage = new ZXingScannerPage(new MobileBarcodeScanningOptions() { UseFrontCameraIfAvailable = true });`

You can then obtain the results like normal using:
`scanPage.OnScanResult += (barcode) =>
                    {
                        scanPage.IsScanning = false;

                        Device.BeginInvokeOnMainThread(() =>
                        {
                            // Perform barcode operations here
                        });
                    };`

**Comment by TBMSam** [comment]
Hello guys,

unfortunately, when adding 

`MobileBarcodeScanningOptions opts = new MobileBarcodeScanningOptions() { UseFrontCameraIfAvailable = true };`

I get an error message saying

> The type or namespace-name "MobileBarcodeScanningOptions" could not be found (maybe a using-directive or assembly-reference is missing).

Can you tell me what I have to import to get him to know the `MobileBarcodeScanningOptions` class?

**Comment by hemang0811** [comment]
> Hello guys,
> 
> unfortunately, when adding
> 
> ```
> MobileBarcodeScanningOptions opts = new MobileBarcodeScanningOptions() { UseFrontCameraIfAvailable = true };
> ```
> 
> I get an error message saying
> 
> > The type or namespace-name "MobileBarcodeScanningOptions" could not be found (maybe a using-directive or assembly-reference is missing).
> 
> Can you tell me what I have to import to get him to know the `MobileBarcodeScanningOptions` class?

using ZXing.Mobile;

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by krishnapt123** [comment]
It is not scan a small qr code in some times
