### ISSUE TITLE
Nothing happens after clicking

### ISSUE THREAD

**Issue by PawelCyrklaf** [Redth/ZXing.Net.Mobile#777]
Hi :)
I am trying to do a barcode scanner in Xamarin using ZXing based on this page: github.com/Redth/ZXing.Net.Mobile

I've been fighting this since yesterday and I have no idea what might be wrong, the videos are working and in my case I have no chance :(

I use vs 2017 Community and packages:

-  ZXing.Net.Mobile.Forms - 2.4.1
-  ZXing.Net.Mobile - 2.4.1
- Xamarin.Forms - 3.1.0.697729

My project to download if someone would like to see the whole code: [http://cyrklaf.eu/skaner.rar](http://cyrklaf.eu/skaner.rar)
I'm missing ideas, like a simple thing, and the problems themselves

My code:
```
scanPage = new ZXingScannerPage ();
             scanPage.OnScanResult + = (result) =>
             {
                 scanPage.IsScanning = false;
                 Device.BeginInvokeOnMainThread (() =>
                 {
                     Navigation.PopAsync ();
                     DisplayAlert ("Scanned Barcode", result.Text, "OK");
                 });
             };
             await Navigation.PushAsync (scanPage);
```

**Comment by gabrielrvd** [comment]
Hi, I had same problem here. Just remove all packages with name ZXing from your project and then install again, clean the solution e deploy again. Sorry english is not my native language...

**Comment by PawelCyrklaf** [comment]
> Hi, I had same problem here. Just remove all packages with name ZXing from your project and then install again, clean the solution e deploy again. Sorry english is not my native language...

I solved my problem :) When i have ZXing.Net.Mobile.Forms - 2.4.1 nothing happens after clicking, when i change version from 2.4.1 to 2.3.2 all works fine :)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
