### ISSUE TITLE
Detection/Autofocus speed on Android, compared to Barcode Scanner app

### ISSUE THREAD

**Issue by MattiaDurli** [Redth/ZXing.Net.Mobile#78]
Hello, I'm testing the library, using the latest version. 
Everything works, but testing the sample app and the Barcode Scanner app, that should be using the same java library, in the same devices (Asus TF300T and LG4X P880), the sample app is much slower in detecting the barcode than the Barcode Scanner.
Is there anything I can do to improve detection speed? 
Actually I think the problem is in autofocus, the Barcode Scanner app focuses much more quickly. 
Thanks! Mattia

**Comment by swarankargaurav1** [comment]
> Ok, seeing as I've now implemented most (all) of these suggestions I'll be closing the issue. Please open a new issue if you have any other specific ideas for improving performance.

i want to move up and down the laser in scanner app using Zxing. how to implement it. if it is not available in this dependency then how to implemement this type of animation.
