### ISSUE TITLE
Why there is no new release since Last 5 months

### ISSUE THREAD

**Issue by tomnorg** [Redth/ZXing.Net.Mobile#780]
Since last 5 months there is no update from ZXing.Net.Mobile ? Why there is no update?

**Comment by knocte** [comment]
I second this, especially because there have been fixes in master in this last 6 months that haven't been released to nuget. It would be great to update ZXing.Net submodule too, it would help me debug an issue. @Redth ping

**Comment by rkshnair** [comment]
@Redth Could you please confirm any ETA for next release? Or is it going to stop further update / development for this project.

**Comment by Evolutionlab** [comment]
its a shame because its a good library but there are some interesting pull request abandoned (bugfixes, TextureView and Google Vision API) also the submodule is old.
Lets hope that someone brings the project back to life :)

**Comment by Redth** [comment]
Been busy, too busy...  Going to try and get a release out with some of the changes and PR's that are now in `dev` branch.

**Comment by Evolutionlab** [comment]
This is awesome :) i was just checking this because i'm about to start a new project that need barcode scanning. Thank you! and btw good job also with Xamarin Essentials, is pure awesomeness :)

**Comment by knocte** [comment]
@Redth why dev branch? a pre-release to nuget first and then merge back to master when official release?

**Comment by knocte** [comment]
> Yup

Cool. When are you posting a pre-release? Would be nice to get it as a christmas present :)

PS: Actually, the convention is usually keep latest development in `master` branch (even if unstable), and use other branches for outlining what is stable (e.g. a `stable` branch). This is more discoverable because then you don't need to switch to `dev` to find the latest version of the sources.

**Comment by knocte** [comment]
ping

**Comment by dberroa** [comment]
Update on when a release will occur?

**Comment by dm-CaT** [comment]
Any news?

**Comment by knocte** [comment]
@redth ping

**Comment by mrutter** [comment]
Any news?

**Comment by lazmeister** [comment]
Looks like @Redth Replied on this post. A full rewrite is happening but he is trying to push it to Xamarin team which really makes sense. https://github.com/xamarin/Xamarin.Forms/issues/7934 scroll down to his reply. Also feature is now "under consideration" https://github.com/xamarin/Xamarin.Forms/projects/5#card-27656349

**Comment by lazmeister** [comment]
I would also recommend you vote for the feature if you wish to see Xamarin include this as a native feature https://github.com/xamarin/Xamarin.Forms/projects/5#card-27656349

**Comment by davidbuckleyni** [comment]
thanks  @lazmeister  and @Redth  I think if we had this would help allot of programmers could really compete with the native developers most business-driven apps have a requirement of some form of scanning especially .warehouse style applications.

**Comment by davidbuckleyni** [comment]
@lazmeister  how do i vote

**Comment by lazmeister** [comment]
Click on the item from my link above and on the right hand side click the Thumbs up to give it more traction. That's all I can think of for this to get more attention. ![image](https://user-images.githubusercontent.com/3281599/75499884-5fc78100-5999-11ea-8bbc-8dead6a17ba6.png)

**Comment by Redth** [comment]
Sorry for the delay... Been tough to find time for this.  I have 3.0.0 prerelease out and the code is completely restructured.  Should be easier going forward!
