### ISSUE TITLE
andorid version 8.1

### ISSUE THREAD

**Issue by rakibahamed111** [Redth/ZXing.Net.Mobile#783]
zxing .net is not working on android 8.1

now how can i work with this

**Comment by zwilkin** [comment]
@rakibahamed111 What exactly does "not working" mean. Please be more specific

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
