### ISSUE TITLE
Freeze camera view after code has been recognized

### ISSUE THREAD

**Issue by michaelschattgen** [Redth/ZXing.Net.Mobile#786]
Is there a way to freeze the ScannerView after it scanned a QR code?

I want to continously scan QR codes with some kind of validation in between. It would be nice to freeze the cameraview so it is obvious to the user that the code is recognized while the app is validating the QR code.

**Comment by juanagu** [comment]
same error

**Comment by Redth** [comment]
Sorry, this is not possible, and no plans for it.
