### ISSUE TITLE
Errors after installing

### ISSUE THREAD

**Issue by wayne-o** [Redth/ZXing.Net.Mobile#787]
Errors after installing:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `zxing.portable`, referenced by `ZXing.Net.Mobile.Forms`. Please add a NuGet package or assembly reference for `zxing.portable`, or remove the reference to `ZXing.Net.Mobile.Forms`.	TicketReader.Android		```	



```Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `ZXingNetMobile`, referenced by `ZXing.Net.Mobile.Forms.Android`. Please add a NuGet package or assembly reference for `ZXingNetMobile`, or remove the reference to `ZXing.Net.Mobile.Forms.Android`.	TicketReader.Android	```		


```Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `zxing.portable`, referenced by `ZXing.Net.Mobile.Forms`. Please add a NuGet package or assembly reference for `zxing.portable`, or remove the reference to `ZXing.Net.Mobile.Forms`.	TicketReader.Android			

```

**Comment by Mohanadabusbib** [comment]
I have the same problem

**Comment by mike-01** [comment]
Thank you, bruzkovsy. That fixed it for me.

**Comment by ruwaidyousuf** [comment]
Thanks bruzkovsky, you saved my time 👍

**Comment by Surajvbinorkar** [comment]
Thanks bruzkovsky, it work for me :)

**Comment by kmkart2000** [comment]
It Is Ok

**Comment by DomAlexRod** [comment]
Worked for me!

**Comment by FabianSilva** [comment]
it is posible that ZXing.Net.Mobile.Forms depends on ZXing.Net.Mobile to avoid this? I'm new to xamarin and I was lucky that found this, but for newcomers is hard to start and things like this can take time to fix... thanks you

**Comment by InDieTasten** [comment]
The readme should be more clear about that I think. Many people are running into this.

**Comment by Redth** [comment]
3.0.0 should make this all work much more nicely!

**Comment by jaysonragasa** [comment]
@Redth - So I just installed the pre-release 3.1.0 beta the reason is that in the "stable" release, IsScanning is not behaving properly I think. By default, I'd like to set the IsScanning to true, but when I set to false and then true again, it does not scan anymore. I thought I give the 3.1.0 a try. I installed on the Android platform and netstandard project

But I get trap with reference-hell the say
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		XA2002: Can not resolve reference: `zxing.portable`, referenced by `OpenTrackBase`. Please add a NuGet package or assembly reference for `zxing.portable`, or remove the reference to `OpenTrackBase`.		 	0	
```
