### ISSUE TITLE
CalledFromWrongThreadException error in Android 8.1

### ISSUE THREAD

**Issue by nologinatgit** [Redth/ZXing.Net.Mobile#792]
I have the following code to scan (it is called from a Fragment): 

     view.FindViewById<Button>(Resource.Id.btnQRScan).Click += (sender, args) =>
      {
        Activity.SafeRunOnUi(async () => await QRCodeScanning(view, Resource.Id.)
        );
      };

    private async Task QRCodeScanning(View view, int resourceID)
    {    
      MobileBarcodeScanner.Initialize(Activity.Application);

      var scanner = new MobileBarcodeScanner();

      try
      {
        var result = await scanner.Scan();
        if (result != null)
        {
           Activity.SafeRunOnUi(() => textView.Text = result.Text);
        }
        else
        {
          Activity.SafeRunOnUi(() => textView.Text = "No result");
        }
      }
      catch (System.Exception ex)
      {
        throw;
      }

When the scan opens and either I touch Back or scan a code, the application crashes (no exception is catched, even in the UnhandledException handler).

I have the following exception output:

> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523] Pending exception android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.view.ViewRootImpl.checkThread() (ViewRootImpl.java:7682)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at android.view.ViewParent android.view.ViewRootImpl.invalidateChildInParent(int[], android.graphics.Rect) (ViewRootImpl.java:1248)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.view.ViewRootImpl.invalidateChild(android.view.View, android.graphics.Rect) (ViewRootImpl.java:1243)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.view.View.invalidateInternal(int, int, int, int, boolean, boolean) (View.java:15594)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.view.View.invalidate(int, int, int, int) (View.java:15526)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.view.View.invalidateDrawable(android.graphics.drawable.Drawable) (View.java:19987)
> 12-21 13:23:11.829 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.Drawable.invalidateSelf() (Drawable.java:450)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.LayerDrawable.invalidateDrawable(android.graphics.drawable.Drawable) (LayerDrawable.java:990)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.Drawable.invalidateSelf() (Drawable.java:450)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.invalidateOwningView() (AnimatedVectorDrawable.java:1589)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.onAnimationEnd(int) (AnimatedVectorDrawable.java:1764)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.callOnFinished(android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT, int) (AnimatedVectorDrawable.java:1772)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:523] 
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531] JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.view.ViewRootImpl.checkThread() (ViewRootImpl.java:7682)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at android.view.ViewParent android.view.ViewRootImpl.invalidateChildInParent(int[], android.graphics.Rect) (ViewRootImpl.java:1248)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.view.ViewRootImpl.invalidateChild(android.view.View, android.graphics.Rect) (ViewRootImpl.java:1243)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.view.View.invalidateInternal(int, int, int, int, boolean, boolean) (View.java:15594)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.view.View.invalidate(int, int, int, int) (View.java:15526)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.view.View.invalidateDrawable(android.graphics.drawable.Drawable) (View.java:19987)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.Drawable.invalidateSelf() (Drawable.java:450)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.LayerDrawable.invalidateDrawable(android.graphics.drawable.Drawable) (LayerDrawable.java:990)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.Drawable.invalidateSelf() (Drawable.java:450)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.invalidateOwningView() (AnimatedVectorDrawable.java:1589)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.onAnimationEnd(int) (AnimatedVectorDrawable.java:1764)
> 12-21 13:23:11.830 F/zygote  (11763): runtime.cc:531]   at void android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.callOnFinished(android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT, int) (AnimatedVectorDrawable.java:1772)

I removed setting the textview values, but even a single Scan causes exception. It looks like some kind of drawable manupulation causes the error.

What should I try?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
