### ISSUE TITLE
'mobilebarcodescanner' does not contain a definition for 'initialize'

### ISSUE THREAD

**Issue by Manticorus** [Redth/ZXing.Net.Mobile#801]
Greetings

I am using NuGet package ZXing.Net.Mobile. When i upgrade to version 2.4.1 line `MobileBarcodeScanner.Initialize(Activity.Application);` is suddenly highlighted and intelisense says 'mobilebarcodescanner' does not contain a definition for 'initialize'. When i revert back to 2.3.2 it works. Any idea what am i missing?

**Comment by chrisella** [comment]
Exactly the same issue for me currently, 2.3.2 is working like a dream, but 2.4.1 errors with Initialize not being defined on MobileBarcodeScanner

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
