### ISSUE TITLE
Xamarin iOS - When using ScanContinuously, aft 40-50 attempts, scanner is not able to connect to camera

### ISSUE THREAD

**Issue by ankiitbansal** [Redth/ZXing.Net.Mobile#803]
Hi @Redth 

We have implemented the zxi.ng.net.mobile for our Xamarin iOS Application. We are using ScanContinuously mode for the scanner. 
If user has opened closed the scanner 40-50 times, then scanner shows black screen, overly opened but viewfiender is not displayed. 

Scenario: Open barcode scanner using button, hit cancel - repeat this 40-50 times. 

For cancel, we are using scanner.cancel(). 

Can you please let us know if its a known issue on iOS?

**Comment by ankiitbansal** [comment]
hi team,

any update.. we are getting this issue after 80 consecutive scans

**Comment by ankiitbansal** [comment]
its happening with the default layout implementation

**Comment by titonton** [comment]
I don't think the @Redth is maintaining this anymore

**Comment by ankiitbansal** [comment]
@titonton  yeah I think so as we are not getting any response back.

**Comment by Redth** [comment]
Can you try the 3.x series?  If this is still an issue, please open a new github issue.
