### ISSUE TITLE
Unable to scan QR Code generated with option Shift_JIS encoding character  (Xamarin Android)

### ISSUE THREAD

**Issue by shishir42** [Redth/ZXing.Net.Mobile#805]
Unable to scan QR code generated with option Shift_JIS encoding character
https://zxing.appspot.com/generator/

Sample QR code:
https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=Shift_JIS&chl=abc

QR Configuration:
![image](https://user-images.githubusercontent.com/815899/53077923-20aa5880-3519-11e9-926a-ceaeb447b43c.png)

But i am able to scan when i enable the "Use Shared Runtime" option from packaging properties in project setting from Visual Studio 2017 version 15.7.2

![capture](https://user-images.githubusercontent.com/815899/53077839-f6589b00-3518-11e9-8db1-a80f008d06aa.PNG)

Please provide the feedback on the same

**Comment by shishir42** [comment]
Xamarin ZXing Version 

![image](https://user-images.githubusercontent.com/815899/53078629-a37fe300-351a-11e9-92f0-ada9bcb68951.png)

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
