### ISSUE TITLE
Samsung Galaxy Tab S4 sporadic Reboot after _scanner.Cancel();

### ISSUE THREAD

**Issue by PatGet** [Redth/ZXing.Net.Mobile#809]
Device: Samsung Galaxy Tab S4
I´m using ScanContinuously to process STRUCTURED_APPEND QR Codes.
When i finaly have all needed parts I call _scanner.Cancel(); to end Scanning and force close of the Preview Stream Page.
Sometimes the Tablet does a full reboot than. Today this happend just once,  yesterday nearly every second try.
Whats the best way to go forward? Provide some log? Trying to debug the current cide or dev branch? If so, how to compile the code? VS2017 says "the referenced project '..\ZXing.Net\Source\lib\zxing.portable.csproj' does not exist.". The Build scipts fail with errors too.

**Comment by PatGet** [comment]
Tested a bit more: Tablet also reboots after a simpe "var res  = await _scanner.Scan();"

**Comment by PatGet** [comment]
Fixed the zxing portable issue with a "git clone https://github.com/Redth/ZXing.Net.Mobile --recurse-submodules". Missed that submodule thing. Hopefully i can find something within the lib.

**Comment by PatGet** [comment]
It seems like it only happens with the nuget version. If i compile myself and/or copycode to my solution it works. Difference would be MonoAndroidVersion. Is that possible?

**Comment by PatGet** [comment]
The difference is the following PR: [https://github.com/Redth/ZXing.Net.Mobile/pull/714](https://github.com/Redth/ZXing.Net.Mobile/pull/714) . For now i include a lot of code in my Project but I would really love to see a new Nuget Release.

**Comment by PatGet** [comment]
Because I had issues with my build agents I currently host my self compiled version as https://www.nuget.org/packages/Patget.ZXing.Net.Mobile.Forms/

**Comment by Redth** [comment]
I hope you can give the 3.x series a try.  If there's optimizations you have that you'd be willing to send a PR in for, the code base is much simpler to work with now.  Sorry for the issues.
