### ISSUE TITLE
Are there anyway to detect multiple qr code and the image which detected

### ISSUE THREAD

**Issue by slam023** [Redth/ZXing.Net.Mobile#812]
Is there a way to detect multiple QR code at the same time and retrieve the image that got detected.

I looked at the code in CameraAnalyser.cs  decodeFrame function. I can see it decode one QR code and there is a FastJavaByteArray used for decoding. I assume the FastJavaByteArray was an image of the current frame. Am I right? 

I want to decode 2 QrCodes at the sametime used to locate the cropping location of the image so I can extract the image.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
