### ISSUE TITLE
GS1-DataBar Stacked Omni - Is Not scanning

### ISSUE THREAD

**Issue by Yogeswaran3** [Redth/ZXing.Net.Mobile#814]
Hi All,

I tried to scan a barcode of type "GS1-DataBar Stacked Omni" but the Zxing library is not scanning the barcode. Do anyone had this issue before in Zxing.net,mobile library.

I have directly tried from the sample, it also not working. Let me know if anyone have found a solution for this issue.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by omarpiani** [comment]
With the beta is still not working to me
