### ISSUE TITLE
Xamarin Android : Not able to scan Maxicode format and getting Empty value for RSS-Extended.

### ISSUE THREAD

**Issue by poorneshv15** [Redth/ZXing.Net.Mobile#816]
I am not able to scan Maxicode Barcode and In case of RSS-Expanded I am able to scan but I am getting empty value on scanning the Bar code. Please refer the below code :

          ```
  //Start scanning
```
            MobileBarcodeScanner scanner = new MobileBarcodeScanner()
            {
                UseCustomOverlay = false
            };
            MobileBarcodeScanningOptions options = new MobileBarcodeScanningOptions();
            options.TryHarder = true;
            options.PossibleFormats.Add(ZXing.BarcodeFormat.CODE_39);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.CODE_128);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.CODE_93);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.AZTEC);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.CODABAR);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.MAXICODE);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.RSS_14);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.RSS_EXPANDED);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.UPC_A);
            options.PossibleFormats.Add(ZXing.BarcodeFormat.ITF);
            var result = await scanner.Scan(options);
```
```
Any help with this issue? Thanks.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
