### ISSUE TITLE
Is this project still being maintained? What are your alternatives?

### ISSUE THREAD

**Issue by L0G1C** [Redth/ZXing.Net.Mobile#819]
I've noticed a lot of the commits are from several years ago and the CI build is failing. We're looking for a bar-code scanning solution and I'm afraid to jump into a library that is growing stale. Can anyone recommend a good alternative library? Is it still worth using this one?

**Comment by titonton** [comment]
You can either create your own custom renderers for each platform or find some packages out there for that does the same thing for Xamarin.Android and Xamarin.iOS respectively. A bit of work, but it's an alternative.

**Comment by trilm208** [comment]
paid sdk like Scandit

**Comment by RhomGit** [comment]
I think an update is planned?
https://github.com/Redth/ZXing.Net.Mobile/issues/780

perhaps @Redth is waiting on the dependency project maintainer @micjahn to perform their major refresh first?

https://github.com/micjahn/ZXing.Net/issues/172

**Comment by lazmeister** [comment]
check my notes from #780 , Also vote on this being a native feature of Xamarin: https://github.com/xamarin/Xamarin.Forms/projects/5#card-27656349

**Comment by Redth** [comment]
Sorry, it's been tough finding time for the project.  I've finally done some work here and there's a 3.x prerelease out.

**Comment by RhomGit** [comment]
Very excited about this. Thanks @Redth , best news I've had all week!

**Comment by lazmeister** [comment]
@Redth Your efforts are always greatly appreciated! Get some rest and thank you!

**Comment by thomasgalliker** [comment]
@Redth thanks a lot for investing your spare time in projects like this. Many people seem to forget that so much effort is put into open source projects without ever directly gaining a single dollar with it. 

How do you think will ZXing.Net.Mobile library advance in the future? Do you have any roadmap which you can share with us? And furthermore: Do you think it would be an idea to scale the project up to get more work done here? I see there are many open issues and pull requests waiting for review/correction/merging, but it all comes down to you. I can totally understand that this costs a lot of time and effort but I think this library could have much more success if there was more progress. Do you agree (at least partly)? :)
