### ISSUE TITLE
How to prevent barcode scanning in overlay but only in the cutout

### ISSUE THREAD

**Issue by christophedemey** [Redth/ZXing.Net.Mobile#822]
Hi

I am using following basic code to create the scanview :
```
<zxing:ZXingScannerPage xmlns="http://xamarin.com/schemas/2014/forms"
                        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                        x:Class="HomeHub.Views.ScanCodePage"
                        xmlns:zxing="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"
                        Title="Full screen" OnScanResult="Handle_OnScanResult" IsScanning="true">

</zxing:ZXingScannerPage> 
```
This creates a nice see-through overlay with a cutout in the middle which i really like.
The problem i am having with this is that it scans barcodes in the see-throug overlay.
I would only want barcodes to be scanned from the cutout but want to retain the see-through overlay for orientation ofcourse.

Is there a way to detect this or an option to not allow this to happen ?

Thanks!

**Comment by hemang0811** [comment]
You are not the only one looking for this. Check issue #791. But unfortunately there is no way around currently. See issue #87 for more information.

**Comment by christophedemey** [comment]
@hemang0811 thx.
