### ISSUE TITLE
[iOS] Unable to scan QR Code with inverted color

### ISSUE THREAD

**Issue by PauchardThomas** [Redth/ZXing.Net.Mobile#824]
Hello,

I'm facing a big issue : I can't scan this Qrcode on all iOS devices while it's working really well on Android : 

![frame](https://user-images.githubusercontent.com/9884985/60099529-1fec3200-9758-11e9-99f1-2a1e72c9a3bc.png)

My code : 

```
                zXingScannerView = new ZXingScannerView();

                zXingScannerView.IsAnalyzing = true;
                zXingScannerView.IsScanning = true;

                zXingScannerView.Options.TryHarder = true;
                zXingScannerView.Options.TryInverted = true;

                zXingScannerView.Options.DelayBetweenContinuousScans = 20;
                zXingScannerView.Options.DelayBetweenAnalyzingFrames = 200;

                zXingScannerView.OnScanResult += ZXingScannerView_OnScanResult;
```

XF 3.6
Zxing.Net.mobile v2.4.1
Zxing.Net.Mobile.forms v2.4.1

My customer asking me to be  able to scan every QR Code so I'm in a delicate situation at the moment.

Any idea?

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
