### ISSUE TITLE
running qr scanner from App.xaml.cs

### ISSUE THREAD

**Issue by kenny128** [Redth/ZXing.Net.Mobile#827]
I have tried first running from a ContentPage

            ZXingScannerPage scanPage = new ZXingScannerPage(customOverlay: new QrOverlay());
            scanPage.OnScanResult += (result) => {
                scanPage.IsScanning = false;
                Device.BeginInvokeOnMainThread(() => {
                    scanner.Navigation.PushAsync(new DetailsPage());
                });
            };

            await navigation.PushAsync(scanPage);

That works... but then I wanted the App to immediately start on the QR Scanner so i moved the code into App.xaml.cs. Looking like... 

                ZXingScannerPage scanner = new ZXingScannerPage (customOverlay: new QrOverlay());
                scanner.OnScanResult += (result) =>
                {
                    scanner.IsScanning = false;
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        scanner.Navigation.PushAsync(new DetailsPage());
                    });
                };
                MainPage = new NavigationPage(scanner);

... and the camera shows up but it doesn't scan codes. I can't figure out what is wrong. The IsScanning is set to true.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
