### ISSUE TITLE
UWP app + Surface Go Camera Not Working

### ISSUE THREAD

**Issue by rughvi** [Redth/ZXing.Net.Mobile#828]
Hi,
I am having some trouble with the ZXing barcode scanner on Surface Go.
I have created a Xamarin Forms app for iOS/UWP to scan barcodes.
On Surface Pro, app asks user for camera permission and opens camera and scans a barcode through camera.
On Surface Go, app does not even asks for user permission. 
On Surface Go, I have even enabled camera for my app through Settings -> Privacy -> Camera -> Apps. Still no joy.

Camera is Intel(R) AVStream Camera 2500. This is the same camera in Surface Pro also. Driver driver details are also same.

ZXing barcode camera is not working in Surface Go.

Any help is highly appreciated.

Thanks.

**Comment by rughvi** [comment]
Update:
I had to untick/disable 'Compile with .NET Native tool chain' to make to work in RELEASE mode on Surface GO.
But looks like that is not allowed by the App Store.

**Comment by Redth** [comment]
Sounds like something is getting linked out.  You might want to refer to this doc: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/#target-invocation-exception-when-using-compile-with-net-native-tool-chain
