### ISSUE TITLE
Binding is not working with BarcodeType property

### ISSUE THREAD

**Issue by InfroLab** [Redth/ZXing.Net.Mobile#829]
I have a following XAML code
`                                            <forms:ZXingBarcodeImageView  BarcodeFormat="{Binding Type}" BarcodeValue="{Binding Barcode}" HeightRequest="40" WidthRequest="200">
                                                <zx:ZXingBarcodeImageView.BarcodeOptions>
                                                    <zxcm:EncodingOptions Width="200" Height="40" PureBarcode="True"/>
                                                </zx:ZXingBarcodeImageView.BarcodeOptions>
                                            </forms:ZXingBarcodeImageView>`

I have a method that changes the value of the BarCodeFormat property. This method is binded to a button. When I press the button nothing changes. I expect QR-code to change into Code 128.

Also, if I add the XAML code above into a ListView tag and creat a list of barcodes of different types and bind it to ListView, the content of the ListItems will all be QR codes despite the BarcodeFormat.

**Comment by Redth** [comment]
Should be fixed in 3.0.0-beta5.  Please try it and open a new issue if you still have problems.  Thanks.

**Comment by renibal** [comment]
Hi,

thanks for the great work on the nuget package. 
Currently I am facing the same issue with the 3.0.0 beta 5 package and Xamarin.Essentials 1.6.1 - preview . 
All bindings work well in xaml code beside the BarcodeFormat. I tried to set it via code, but no success in any way. Any binding lead to a data matrix code. Only hard coding can create the different formats.

Any recommendation?
Thanks in advance.

<zxing:ZXingBarcodeImageView x:Name="BarCodeImageView"  BarcodeFormat="{Binding BarCodeFormat}"  BarcodeValue="{Binding BarCode}" BarcodeOptions="{Binding EncodingOptions}"  WidthRequest = "250" HeightRequest = "250"  VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
                </zxing:ZXingBarcodeImageView>
