### ISSUE TITLE
Small barcode detection issue

### ISSUE THREAD

**Issue by AlexMerle** [Redth/ZXing.Net.Mobile#83]
Hello,

First of all, thank you very much for porting the library.

We are trying to build a Xamarin application that will detect the I2of5 barcodes. We have a bunch of different labels depending on the item size and length of barcodes vary from 1.5 to 6 cm. Barcodes longer than 3 cm are detected very good. But if they become smaller than 2 cm it's pretty difficult to detect them (even at TryHarder mode) because they are probably too small for 6 inches distance (from camera to the target) to be detected and when you put the camera closer it can't (auto)focus at the target.

I've tested the original Barcode Scanner app by ZXing Team (https://play.google.com/store/apps/details?id=com.google.zxing.client.android) and it looks like it can focus the camera at closer distance, 3 inches or something, at the same device.

Is there a way to configure the library so it can detect smaller barcodes at the same recommended 6 inches distance or maybe focus at smaller distance (3-4 inches)? Maybe some kind of Macro mode?

Thank you.

**Comment by ankiitbansal** [comment]
We @Redth we are also facing this issue, any help you can do please  let us know. We are not able to scan smaller barcodes.

**Comment by grayter1** [comment]
What about version 3? Is this problem solved? I really need  a reliable scanner in my app, but app will scan only very  tiny barcodes (stickers on front hdd drives)

**Comment by elvijs-scopetechnology** [comment]
It might be that not the highest camera resolution gets picked up. Can try this solution to pick highest available

```
ScanView.Options = new MobileBarcodeScanningOptions()
{
    CameraResolutionSelector = (List<CameraResolution> availableResolutions) =>
    {
        var entry = availableResolutions.Select(r => new
        {
            PixelCount = r.Width * r.Height,
            Resolution = r
        })
            .OrderByDescending(entry => entry.PixelCount)
            .First();

        return entry.Resolution;
    },
};
```
