### ISSUE TITLE
Using Zing .net Mobile in scanning app

### ISSUE THREAD

**Issue by davidbuckleyni** [Redth/ZXing.Net.Mobile#830]
I have a scanning app that needs to promt the user one record at a time of a list of items which is glbalbomsource but I have included the code  after   await Navigation.PushAsync(scanPage); but its repeating the code for every item and not waiting for the scan action to complete it should prompt the user for qty and then move to the next item in the list 

It works fine once but then crashes out when i place it in a loop

      private async void BtnBeginBomSessions_Clicked(object sender, EventArgs e)
        {
  
            Fuel_StockWarehouseInfoBins binInfo = new Fuel_StockWarehouseInfoBins();
            var scanPage = new ZXingScannerPage();
            scanPage.ToggleTorch();
            scanPage.IsScanning = true;

            await Navigation.PushAsync(scanPage);
            foreach (var itemx in globalBomSource.Where(w => w.Status != 1 && w.Quantity != w.QuantityToTransfer && w.isHeaderSubassembly != true))
            {
                var item = globalBomSource.Where(w => w.Status != 1 && w.Quantity != w.QuantityToTransfer && w.isHeaderSubassembly != true).OrderBy(o => o.BinName).FirstOrDefault();

                await DisplayAlert("Fuel", $"Please goto Bin Location {item.BinName} for Item { item.Description} Qty Required { item.Quantity}", "Ok");

            
                var resultcode = txtCode.Text;

                scanPage.OnScanResult += (result) =>
                {
                    string barcode = result.Text;
                //var item = globalBomSource.Where(w => w.BarCode == barcode && w.Status != 1 && w.Quantity != w.QuantityToTransfer && w.isHeaderSubassembly != true).OrderBy(o => o.BinName).FirstOrDefault();

                if (item != null)
                    {
                    // Stop scanning
                    scanPage.IsScanning = false;

                    // Pop the page and show the result
                    Device.BeginInvokeOnMainThread(async () =>
                        {

                                    int x = await PlayBeep();

                                    hasScanned = false;
                                    var resultQty = await Plugin.DialogKit.CrossDiaglogKit.Current.GetInputTextAsync("Fuel", $"Please goto  Bin Location {item.BinName} for Item { item.Description} Qty Required { item.Quantity}", null, Keyboard.Numeric);

                                    if (resultQty != null)
                                    {
                                        Int32.TryParse(resultQty, out int resultValue);
                                        if (resultValue == 0)
                                        {
                                            await DisplayAlert("Fuel", "Quantity cannot be zero or empty", "Ok");
                                            return;
                                        }

                                        if (resultValue > item.FreeStockQty)
                                        {
                                            await DisplayAlert("Fuel", "Stock Quantity Exceeded,Try Again", "Ok");
                                            return;
                                        }

                                        if (resultValue > item.Quantity)
                                        {
                                            await DisplayAlert("Fuel", "You cannot transfer more than required.", "Ok");
                                            return;
                                        }

                                        string errorMessage = "";
                                        if (PickDoctors.SelectedItem == null)
                                        {
                                            errorMessage += " select a doctor";

                                        }

                                        if (pickTheater.SelectedItem == null)
                                        {
                                            errorMessage += "select a theater ";

                                        }

                                        if (errorMessage != "")
                                        {
                                            string message = "";
                                            message = $"Please, {errorMessage}";

                                            await DisplayAlert("Fuel", message, "OK");
                                            return;
                                        }

                                        await SaveBomTransFer(barcode, resultValue);
                                

                            }

                                });
                       

                    }
                    else
                    {
                        DisplayAlert("Fuel", "Item does not exist or has been scanned already, please try again", "OK");

                    }

                };
                continue;

            }
        }

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
