### ISSUE TITLE
Adding a button bottom left of the scan window to close it

### ISSUE THREAD

**Issue by davidbuckleyni** [Redth/ZXing.Net.Mobile#832]
Hi I was wondering if their was a way to close the window but have it done on a button or even a piece of text saying the word close we want to allow the scanning function to repeat however with the scan window up the user does not have a way to close it so i need some kind of overlay i am using the        var scanPage = new ZXingScannerPage();

Method to scan the barcode.

**Comment by Redth** [comment]
You can use a custom overlay.  There are examples of this in the samples.
