### ISSUE TITLE
*** The first time issue of ZXingScannerView on Android ***

### ISSUE THREAD

**Issue by wml2017** [Redth/ZXing.Net.Mobile#840]
The ZXingScannerView with ZXing.Net.Mobile.Forms and ZXing.Net.Mobile 2.4.1 has the first time issue on Android (the old version of ZXing such as 2.3.2 may not have this issue for the old version of Xamarin.Form). Install the app with this component, it can't scan  QR code at the first time. After quit the app or the page with ZXing, and enter the page with ZXingScannerView, the problem is solved. Please fix it. Thanks!

**Comment by mtsrdr** [comment]
same here

**Comment by Twelve57** [comment]
Same for me, no problem on the iOS solution (Xamarin project)

**Comment by MaxxDelusional** [comment]
I had to use a previous version of the library because of this issue.

**Comment by Redth** [comment]
Fixed in latest 3.0 series.
