### ISSUE TITLE
Update Android Support libs to API 28

### ISSUE THREAD

**Issue by JRosanowski** [Redth/ZXing.Net.Mobile#844]
As of Nov 1 2019 new apps and app updates require API 28. Because ZXing uses Android Support lib 25 it means that all Android Support 28 libs to have to be included as direct references when using PackageReference. Is there any chance that the support version could be upgraded?

**Comment by tipa** [comment]
As the Android Support libraries are deprecated now, it would be even better if the dependencies could be updated to AndroidX

**Comment by Redth** [comment]
Done in 3.x.  If you target MonoAndroid10.0 it will use AndroidX.

**Comment by gil-rodrigues** [comment]
> Done in 3.x. If you target MonoAndroid10.0 it will use AndroidX.

Sorry to write on an "old" issue. You talk about 3.x, but the latest nuget I can see is 2.4.1. Am I seeing something wrong?
@Redth
