### ISSUE TITLE
iPhone 11 throw Unexpected AVMetadataObjectType: humanBody Error in Zxing

### ISSUE THREAD

**Issue by AshishtChetu** [Redth/ZXing.Net.Mobile#846]
When we calling the Scan method in iOS, then we started getting an ArgumentOutOfRangeException throwing "Unexpected AVMetadataObjectType: humanBody" when called on  iphone 11's. So how we can resolve it?

**Comment by mondayuk** [comment]
I had the same problem and have found a workaround. Problem appears to be a couple of new MetaData types introduced by the newer devices. Xamarin intercepts the string literals for these and converts them to an Enumeration, but these were only added recently (see [here](https://github.com/xamarin/xamarin-macios/commit/532059daf6a9a066cf0677b61fc1602d48eebc2f#diff-9767bdcac465cf4ddaa570a455138dac)),

As a result this library will need to be rebuilt using the later version, however as a workaround you can prevent the ZXIng library hitting this line by specifying one or more barode formats in the options. I did it like this:
`                    options.PossibleFormats.Add(BarcodeFormat.All_1D);
                    options.PossibleFormats.Add(BarcodeFormat.QR_CODE);`

**Comment by Surkhojb** [comment]
Hello.

Our customers reported us a crash with Iphone 11 and Iphone 11 Pro and we tested our app to catch the error:

 Unexpected AVMetadataObjectType: humanBody Error

I've been trying different options to avoid the crash in those devices but i didn't have any luck.

Could you update the library with the last version of this changes from Xamarin.IOS.

Thanks in advise.

**Comment by AshishtChetu** [comment]
@Surkhojb  for now you add below set of code and things will work fine.

      var options = new ZXing.Mobile.MobileBarcodeScanningOptions();
            options.PossibleFormats = new List<ZXing.BarcodeFormat>() {
    ZXing.BarcodeFormat.All_1D, ZXing.BarcodeFormat.QR_CODE
};
            var result = await scanner.Scan (options,true);

**Comment by Surkhojb** [comment]
@AshishtChetu Thanks, the code is working as expected!!

**Comment by Redth** [comment]
This should be better now as I've added some checks to discard scans if these types are detected.  Apple may add new ones in the future that need checking against.
