### ISSUE TITLE
Is IsScanning bindable?

### ISSUE THREAD

**Issue by stesvis** [Redth/ZXing.Net.Mobile#848]
I see that IsScanning in ZXingScannerView is a bindable property, but it does not implement the PropertyChanged event.

So when I bind it to a ViewModel property it works on load, but when I change its value it won't apply to the view.

**Comment by abdul-wasey** [comment]
> I see that IsScanning in ZXingScannerView is a bindable property, but it does not implement the PropertyChanged event.
> 
> So when I bind it to a ViewModel property it works on load, but when I change its value it won't apply to the view.

IsScanning Value is not changing even in the code-behind file. When page reload then it's value set from Xaml Compilation

**Comment by Redth** [comment]
Duplicate of #710
