### ISSUE TITLE
Scan Machine-Readable Passport / Zone (MRZ)

### ISSUE THREAD

**Issue by jrahma** [Redth/ZXing.Net.Mobile#853]
Hi,

Is it possible using ZXing to scan Machine-Readable Passport / Zone (MRZ) and parse the result?

How?

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by Redth** [comment]
If [ZXing.Net](https://github.com/micjahn/ZXing.Net) doesn't support it upstream, neither will this (and it appears it's not supported).
