### ISSUE TITLE
Android ZXingBarcodeImageViewRenderer sometimes throwing errors when used inside a carousel

### ISSUE THREAD

**Issue by alessandroghizzardi** [Redth/ZXing.Net.Mobile#855]
I'm using a ZXingBarcodeImageView in Xamarin Forms inside a carousel, but sometimes with a lot of items it throws a "No data bytes provided" error at runtime. 
It seems that the binding engine is slower than the element renderer, and initializing the barcodeValue to string.empty throws this exception.
To workaround this issue, I've reimplemented a customrenderer changing the line at row 50 also checking for string empty:

            if (formsView != null && !string.IsNullOrWhiteSpace(formsView.BarcodeValue))

I'd submit it as a change request but I don't know how to do it on Github

**Comment by knocte** [comment]
can you just submit a .diff file here?

**Comment by alessandroghizzardi** [comment]
> can you just submit a .diff file here?

Hi Knocte, 
I cloned the repo and I saw that the dev branch is already fixed. Any reason why it has not been released?

**Comment by knocte** [comment]
Good question. I'm not the maintainer, you should ask @Redth.

That being said you might find what you need in the fork that is here: https://github.com/nblockchain/ZXing.Net.Xamarin (also published in nuget)

**Comment by alessandroghizzardi** [comment]
> https://github.com/nblockchain/ZXing.Net.Xamarin (also published in nuget)

Thank you, but that fork's last relase also is updated as of 2017 and without the fix!

**Comment by acaliaro** [comment]
@alessandroghizzardi ciao. I have a similar issue with collectionview. Have you find a solution?

**Comment by alessandroghizzardi** [comment]
> @alessandroghizzardi ciao. I have a similar issue with collectionview. Have you find a solution?

Hi, 
I've reimplemented my CustomRendere using the code from the source, and added the code from my first post in the source.
I saw that the last development branch has the same fix, so you should also try to not use the github version but use that instead.

**Comment by Redth** [comment]
This should be fixed in 3.0.0-beta5.  Please try it, and open a new issue if it is not.
