### ISSUE TITLE
Recognising QR code in an image imported from gallery. Possible ?

### ISSUE THREAD

**Issue by pawanshakya** [Redth/ZXing.Net.Mobile#862]
Hi, 
I have been using this for scanning in my Xamarin, Forms project. 

Will it be possible to recognise QR code from an image imported from gallery and process that result? So that we can process the result directly from image rather than camera scan.

**Comment by Redth** [comment]
Sure, you just need to create your own `BarcodeReader<T>` implementation to deal with `UIImage` types.  There's already a `RGBLuminenceSourceiOS` class you can use.  Here's a sample:

```csharp
using System;
using Foundation;
using UIKit;
using ZXing;
using ZXing.Mobile;

public class UIImageBarcodeReader : BarcodeReader<UIImage>, IBarcodeReader
{
    static readonly Func<UIImage, LuminanceSource> defaultCreateLuminanceSource =
        (img) => new RGBLuminanceSourceiOS(img);

    public UIImageBarcodeReader()
        : this(null, defaultCreateLuminanceSource, null)
    {
    }

    public UIImageBarcodeReader(Reader reader,
        Func<UIImage, LuminanceSource> createLuminanceSource,
        Func<LuminanceSource, Binarizer> createBinarizer
    )
        : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer)
    {
    }

    public UIImageBarcodeReader(Reader reader,
        Func<UIImage, LuminanceSource> createLuminanceSource,
        Func<LuminanceSource, Binarizer> createBinarizer,
        Func<byte[], int, int, RGBLuminanceSource.BitmapFormat, LuminanceSource> createRGBLuminanceSource
    )
        : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer, createRGBLuminanceSource)
    {
    }
}
```

Then you can use it like this:

```csharp
var reader = new UIImageBarcodeReader();
var result = reader.Decode(UIImage.FromFile("..."));
```

**Comment by hpinfosys** [comment]
Thank You

**Comment by ognamala** [comment]
> Sure, you just need to create your own `BarcodeReader<T>` implementation to deal with `UIImage` types. There's already a `RGBLuminenceSourceiOS` class you can use. Here's a sample:
> 
> ```cs
> using System;
> using Foundation;
> using UIKit;
> using ZXing;
> using ZXing.Mobile;
> 
> public class UIImageBarcodeReader : BarcodeReader<UIImage>, IBarcodeReader
> {
>     static readonly Func<UIImage, LuminanceSource> defaultCreateLuminanceSource =
>         (img) => new RGBLuminanceSourceiOS(img);
> 
>     public UIImageBarcodeReader()
>         : this(null, defaultCreateLuminanceSource, null)
>     {
>     }
> 
>     public UIImageBarcodeReader(Reader reader,
>         Func<UIImage, LuminanceSource> createLuminanceSource,
>         Func<LuminanceSource, Binarizer> createBinarizer
>     )
>         : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer)
>     {
>     }
> 
>     public UIImageBarcodeReader(Reader reader,
>         Func<UIImage, LuminanceSource> createLuminanceSource,
>         Func<LuminanceSource, Binarizer> createBinarizer,
>         Func<byte[], int, int, RGBLuminanceSource.BitmapFormat, LuminanceSource> createRGBLuminanceSource
>     )
>         : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer, createRGBLuminanceSource)
>     {
>     }
> }
> ```
> 
> Then you can use it like this:
> 
> ```cs
> var reader = new UIImageBarcodeReader();
> var result = reader.Decode(UIImage.FromFile("..."));
> ```

Good afternoon @Redth ! 

Not sure if I am missing something but, is there an equivalent version of this code for Android ? How would one go about to read an image from Gallery on Android ?

Thanks!

**Comment by KevinAnass** [comment]
> > Sure, you just need to create your own `BarcodeReader<T>` implementation to deal with `UIImage` types. There's already a `RGBLuminenceSourceiOS` class you can use. Here's a sample:
> > ```cs
> > using System;
> > using Foundation;
> > using UIKit;
> > using ZXing;
> > using ZXing.Mobile;
> > 
> > public class UIImageBarcodeReader : BarcodeReader<UIImage>, IBarcodeReader
> > {
> >     static readonly Func<UIImage, LuminanceSource> defaultCreateLuminanceSource =
> >         (img) => new RGBLuminanceSourceiOS(img);
> > 
> >     public UIImageBarcodeReader()
> >         : this(null, defaultCreateLuminanceSource, null)
> >     {
> >     }
> > 
> >     public UIImageBarcodeReader(Reader reader,
> >         Func<UIImage, LuminanceSource> createLuminanceSource,
> >         Func<LuminanceSource, Binarizer> createBinarizer
> >     )
> >         : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer)
> >     {
> >     }
> > 
> >     public UIImageBarcodeReader(Reader reader,
> >         Func<UIImage, LuminanceSource> createLuminanceSource,
> >         Func<LuminanceSource, Binarizer> createBinarizer,
> >         Func<byte[], int, int, RGBLuminanceSource.BitmapFormat, LuminanceSource> createRGBLuminanceSource
> >     )
> >         : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer, createRGBLuminanceSource)
> >     {
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can use it like this:
> > ```cs
> > var reader = new UIImageBarcodeReader();
> > var result = reader.Decode(UIImage.FromFile("..."));
> > ```
> 
> Good afternoon @Redth !
> 
> Not sure if I am missing something but, is there an equivalent version of this code for Android ? How would one go about to read an image from Gallery on Android ?
> 
> Thanks!

do you find any think for xamarin forms

**Comment by programatix** [comment]
This is for android
```
using Android.Graphics;
using System;
using Xamarin.Forms;
using ZXing;

namespace ...
{
    public class BitmapBarcodeReader : BarcodeReader<Bitmap>, IBarcodeReader
    {
        private static readonly Func<Bitmap, LuminanceSource> defaultCreateLuminanceSource =
            (img) =>
            {
                int[] pixels = new int[img.Width * img.Height];
                byte[] rgbRaw = new byte[img.Width * img.Height * 3];
                img.GetPixels(pixels, 0, img.Width, 0, 0, img.Width, img.Height);

                int rgbOffset = 0;
                for (int pixelOffset = 0; pixelOffset < pixels.Length; pixelOffset++)
                {
                    int inVal = pixels[pixelOffset];

                    //Get the pixel channel values from int
                    var r = (byte)((inVal & 0x00ff0000) >> 16);
                    var g = (byte)((inVal & 0x0000ff00) >> 8);
                    var b = (byte)(inVal & 0x000000ff);

                    rgbRaw[rgbOffset++] = r;
                    rgbRaw[rgbOffset++] = g;
                    rgbRaw[rgbOffset++] = b;
                }

                return new RGBLuminanceSource(rgbRaw, img.Width, img.Height);
            };

        public BitmapBarcodeReader()
            : this(null, defaultCreateLuminanceSource, null)
        {
        }

        public BitmapBarcodeReader(Reader reader,
            Func<Bitmap, LuminanceSource> createLuminanceSource,
            Func<LuminanceSource, Binarizer> createBinarizer
        )
            : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer)
        {
        }

        public BitmapBarcodeReader(Reader reader,
            Func<Bitmap, LuminanceSource> createLuminanceSource,
            Func<LuminanceSource, Binarizer> createBinarizer,
            Func<byte[], int, int, RGBLuminanceSource.BitmapFormat, LuminanceSource> createRGBLuminanceSource
        )
            : base(reader, createLuminanceSource ?? defaultCreateLuminanceSource, createBinarizer, createRGBLuminanceSource)
        {
        }
    }
}
```

Usage example,
```
var bitmap = BitmapFactory.DecodeFile(...);
var reader = new BitmapBarcodeReader();
var result = reader.Decode(bitmap);
```
