### ISSUE TITLE
Camera settings not being reset (iOS)

### ISSUE THREAD

**Issue by Robbert-jansen** [Redth/ZXing.Net.Mobile#863]
This was an issue before an is still present in 3.0.0 beta

#630 & #491 for details

**Comment by Redth** [comment]
Interesting.  So #491 mentions something about `captureDevice.AutoFocusRangeRestriction = AVCaptureAutoFocusRangeRestriction.Near;`.  My assumption would have been the OS would reset things after use, but maybe it's on a per app basis?  Any more detail you can add describing the behaviour would be helpful.  I'll try and reproduce it here.

**Comment by Robbert-jansen** [comment]
If you use camera from within the app AFTER using zxing,  AutoFocusRangeRestriction  will be set to near, unless you manually change it through native code it'l stay that way.

**Comment by Redth** [comment]
There's a bunch of settings that get set along with this.  I wonder if they should _all_ be reverted?

**Comment by Robbert-jansen** [comment]
That would probably be the most _correct_ way to do it, and i think most people will probably expect that is what happens.

I know it took me a LONG time to find out what was happening with the camera, as I just assumed it must have been a bug in the camera plugin i use or in iOS itself, only after a tester noticed it was happening only after scans did i figure out ZXing was the culprit, so resetting everything sounds like the safest/best way to go to prevent any future issues like this.

**Comment by Redth** [comment]
Sounds good, I'll start a PR which preserves and reverts to the original settings.

**Comment by Robbert-jansen** [comment]
Great!
