### ISSUE TITLE
Scanning ISBN's EAN13 followed by 3of9 series. no.

### ISSUE THREAD

**Issue by mheijkant** [Redth/ZXing.Net.Mobile#866]
Some comics have an ISBN (EAN13) Barcode followed by a 3of9 series. no.
But scanning both at the same time doesn't work for me.
So when scanning several titles only the EAN13 is recognised and they al have the same barcode so I can't differentiate between them.
Question: is it possible to scan both the barcode and the series no. at the same time?
so the endresult could be like: 871096600042704 = 8710966000427 + 04

**Comment by Redth** [comment]
Can you share a sample image of this barcode?

**Comment by mheijkant** [comment]
I've added 2 samples. One that has the same ISBN from the same series and one that has different ISBN's that belong to the same series. But there are also book samples to be found that have an ISBN with an attached "suggested retail price", for which, if it is possible, it can be used too.

![20200314_152105](https://user-images.githubusercontent.com/30508071/76683957-40229080-6608-11ea-9d80-7671a16e2b74.jpeg)
![20200314_145032](https://user-images.githubusercontent.com/30508071/76683958-43b61780-6608-11ea-9d42-df2b2694cbc1.jpeg)

**Comment by Redth** [comment]
Thanks.  I wonder if these are considered two separate barcodes technically.  If that's the case this library can't handle that just, but i'm working on another major update which includes the ability to scan multiple barcodes in the frame at a time (the core ZXing.Net has always supported this)

**Comment by Redth** [comment]
I tried these with decode multiple in a frame, and it wouldn't pick it up.  I also tried just scanning the rightmost part, and it doesn't detect that either.  I'd suggest posting these images at [ZXing.Net](https://github.com/micjahn/ZXing.Net) in an issue and seeing if @micjahn has any ideas.  He's the real brains and author behind the logic that does the actual scanning of the pixels :)

**Comment by mheijkant** [comment]
Thanks for the effort. I will give it a try, at ZXing.net. Can you please keep this issue open so I might add some comments/results later on.

**Comment by micjahn** [comment]
ZXing.Net supports the UPC/EAN extensions. But the 2-character extension result isn't added to the normal "Text" property. It is added to the "ResultMetadata" property of the result object.
Here is a small snippet that should clarify this.
```
                if (result.ResultMetadata.ContainsKey(ResultMetadataType.UPC_EAN_EXTENSION))
                {
                    txtContent.Text += " UPC/EAN Extension: " + result.ResultMetadata[ResultMetadataType.UPC_EAN_EXTENSION].ToString();
                }
```
There is no need to call "DecodeMultiple".

**Comment by mheijkant** [comment]
Thanks @micjahn for your response.
This is exactely what I was looking for.
Works perfectly.
