### ISSUE TITLE
Android: Android sample app doesn't ignore shaded areas in the overlay when scanning for QR/Bar code

### ISSUE THREAD

**Issue by asednev** [Redth/ZXing.Net.Mobile#87]
Original Barcode Scanner app based on ZXing java library does an outstanding job ignoring any possible QR codes in the shaded areas in overlay. ZXing.Net.Mobile implementation, however, disregards what's shaded in overlay and still looks for QR codes in the full frame. 

Please see the screenshot below, I expect "A2 PART" being scanned nonetheless "TEST" gets scanned every single time when I point a camera the way it's on the screenshot.

Is this by design? Is there a way to achieve the behavior I expect?

Thanks

![screenshot_2014-01-23-07-23-51](https://f.cloud.github.com/assets/3236025/1986058/2a7b27a0-8447-11e3-9f60-0ba8b36fb929.png)

**Comment by ljj901224** [comment]
I wonder to konw ,does this problem has been resovled? because i have encountered the same scene.

**Comment by ljj901224** [comment]
I wonder to konw ,has this problem been resovled? because I have encountered the same scene.

**Comment by ljj901224** [comment]
has this problem been solved,I encounted the same scene.

**Comment by bmacadam** [comment]
I also think this would be a useful feature.  In my case there are two barcodes in close proximity on a sticker and sometimes users think that the scanner is not working properly when in fact the issue is that the scanner is picking up the wrong barcode and it doesn't pass the validation test.  I would expect that it might also improve performance if you are only checking 50% of the original preview image.

I also have to scan data matrix barcodes and it would be great if I could have a small square view finder.

**Comment by Redth** [comment]
I don't disagree that it would be a useful feature :)  Just need some time to implement it (on ALL platforms - which is what takes so much effort).

**Comment by Tebra** [comment]
Any new information regarding this feature?

We are facing a problem which this feautre would solve immediately.

**Comment by christophedemey** [comment]
Hi, any news on how to not have this behaviour ? Is there any workaround ?

Thanks.

**Comment by aashish181188** [comment]
> I would definitely like something like this. When I'm scanning 1D barcodes I'd ideally like to restrict it to scan a rectangular (landscape view); whereas when scanning 2D I'd like to restrict it to a square.

@Redth , Is this issue fixed. Currently we are implementing barcode scan using ZXing in our Xamarin Forms project and we are facing issue with scanner. The scanner scans the barcode which not even in focus i.e. red line. It is a blocker for us, Kindly assist on this.

Any hint/tips appreciated.

Thanks,
Aashish

**Comment by Redth** [comment]
Track this in #791
