### ISSUE TITLE
ScanContinuously throw NullReferenceException in Android and crash

### ISSUE THREAD

**Issue by huangjinshe** [Redth/ZXing.Net.Mobile#873]
It all normal in iOS, but Android still crash.
```
 bool RequestCamera = await CheckCamera();
if (!RequestCamera)
{
      return;
}

var options = new ZXing.Mobile.MobileBarcodeScanningOptions();
options.PossibleFormats = new List<ZXing.BarcodeFormat>() { ZXing.BarcodeFormat.EAN_8, ZXing.BarcodeFormat.EAN_13 };

var scanner = new ZXing.Mobile.MobileBarcodeScanner();
scanner.CancelButtonText = "Back";

options.DelayBetweenContinuousScans = 3000;


// This place throw exception
scanner.ScanContinuously(options, x =>
{
                
});
```

The Exception:

> 
> **System.NullReferenceException:** 'Object reference not set to an instance of an object.'
> 
> [0:] Catch in CurrentDomainOnUnhandledException:   System.NullReferenceException: Object reference not set to an instance of an object.
>   at ZXing.Mobile.MobileBarcodeScanner.GetContext (Android.Content.Context context) [0x0001f] in <819b29aa6d91462699e19a679be55a44>:0 
>   at ZXing.Mobile.MobileBarcodeScanner.ScanContinuously (Android.Content.Context context, ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1[T] scanHandler) [0x0000e] in <819b29aa6d91462699e19a679be55a44>:0 
>   at ZXing.Mobile.MobileBarcodeScanner.ScanContinuously (ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1[T] scanHandler) [0x00001] in <819b29aa6d91462699e19a679be55a44>:0 
>   at Pages.ViewModel.<get_GoCommand>b__33_17 () [0x00169] in E:\Project\TestProject\Pages\ViewModel.cs:514 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)
>   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)
> 03-14 11:06:18.259 E/mono-rt (21363): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
> 03-14 11:06:18.259 E/mono-rt (21363):   at ZXing.Mobile.MobileBarcodeScanner.GetContext (Android.Content.Context context) [0x0001f] in <819b29aa6d91462699e19a679be55a44>:0 
> 03-14 11:06:18.259 E/mono-rt (21363):   at ZXing.Mobile.MobileBarcodeScanner.ScanContinuously (Android.Content.Context context, ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1[T] scanHandler) [0x0000e] in <819b29aa6d91462699e19a679be55a44>:0 
> 03-14 11:06:18.259 E/mono-rt (21363):   at ZXing.Mobile.MobileBarcodeScanner.ScanContinuously (ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1[T] scanHandler) [0x00001] in <819b29aa6d91462699e19a679be55a44>:0 
> 03-14 11:06:18.259 E/mono-rt (21363):   at Pages.ViewModel.<get_GoCommand>

The carema request no problem, I did click allow. 
Also I put initialization code for the ZXing in Android MainActivity-OnCreate:

```
 base.OnCreate(savedInstanceState);
 ZXing.Net.Mobile.Forms.Android.Platform.Init();
```

**Comment by huangjinshe** [comment]
I fixed this problem by changed the:

`ZXing.Net.Mobile.Forms.Android.Platform.Init(); `

to :

```
ZXing.Net.Mobile.Forms.Android.Platform.Init(); 
ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);
```
..............., Update the main page of this project or fix this bug guys....

**Comment by Redth** [comment]
You can also use `Xamarin.Essentials.Platform.Init(Application);`

**Comment by Redth** [comment]
@huangjinshe updated the readme... In the future if you find something like this, you should consider submitting a PR....

**Comment by huangjinshe** [comment]
@Redth Of course, At least I need to confirm it from you before do that...

Also My `Essentials` Already used like this:

`Xamarin.Essentials.Platform.Init(this, savedInstanceState);`
