### ISSUE TITLE
Update Readme for Android permission handling

### ISSUE THREAD

**Issue by radioactiveman** [Redth/ZXing.Net.Mobile#915]
According to the code and compiler warnings, using `OnRequestPermissionsResult()` from the [Android Permission Handler](https://github.com/Redth/ZXing.Net.Mobile/blob/master/ZXing.Net.Mobile/Android/PermissionsHandler.android.cs#L15) is deprecated. The Readme still suggests to use this though. Please clarify this.

**Comment by Lydecker** [comment]
Yup -documentation is well out of date for v3 of this plugin.

As long as you have Essentials 1.5.x - there is no need for anything extra in the `OnRequestPermissionsResult()` on android from our findings...

**Comment by knocte** [comment]
> The Readme still suggests to use this though.

Can you open a PullRequest please?

**Comment by radioactiveman** [comment]
> Can you open a PullRequest please?

Sure, see #950.
