### ISSUE TITLE
"Barcode Found" but result handler not called

### ISSUE THREAD

**Issue by TimHi** [Redth/ZXing.Net.Mobile#934]
Hello, I'm using the following code to scan for a QR code, apparently the scanning works because when pointing the camera to a QR code _[ZXing.Net.Mobile] Barcode Found_ is logged from ZXing, however my defined HandleScanResult function is not called, am I registering the callback wrong?

```
        void scan()
        {
            var opts = new MobileBarcodeScanningOptions
            {
                PossibleFormats = new List<ZXing.BarcodeFormat> {
                    ZXing.BarcodeFormat.DATA_MATRIX,
                    ZXing.BarcodeFormat.QR_CODE
                },
                CameraResolutionSelector = availableResolutions => {

                    foreach (var ar in availableResolutions)
                    {
                        Console.WriteLine("Resolution: " + ar.Width + "x" + ar.Height);
                    }
                    return null;
                }
            };

            scanFragment.StartScanning(HandleScanResult, opts);

        }

        private void HandleScanResult(ZXing.Result obj)
        {
            if (obj.Text.IsNullOrEmpty()) //BREAKPOINT HERE, NEVER REACHED
            {
                return;
            }
        }
```

**Comment by TimHi** [comment]
When googling further I found this issue:  #643 implementing the solution suggested by @ElteHupkes (thank you very much btw! :)) seems to resolve this issue. 
I'll leave this issue open as I think this could use either a fix or some documentation.

**Comment by knocte** [comment]
What version of ZXing.Net.Mobile are you using?

**Comment by Fischer96** [comment]
Doesnt work

**Comment by TimHi** [comment]
I'm using the following packages: 
ZXing.Net.Mobile.Core, Version=2.4.1.0
ZXing.Net.Mobile.Forms, Version=2.4.1.0
ZXing.Net.Mobile.Forms.Android, Version=2.4.1.0
ZXingNetMobile, Version=2.4.1.0
zxing.portable, Version=0.16.2.0

**Comment by knocte** [comment]
> I'm using the following packages:
> ZXing.Net.Mobile.Core, Version=2.4.1.0
> ...

Well, the reason of why the issue you referenced is closed is because it could be already fixed in the 3.0.0-beta version. Please test this version.

**Comment by Cheesebaron** [comment]
Running 3.0.0-beta5 and still have this issue on Android.

**Comment by Cheesebaron** [comment]
It is a timing issue it seems.

`scanner` in `ZXingScannerFragment` gets set up in `OnCreateView` which is a lifecycle method. However, in the `FragmentActivity` code the call to `StartScanning` happens after the `Fragment` is initialized. This means that `OnCreateView` hasn't been called yet, and the internal `Scan()` method isn't called and callback is never hooked up.

**Comment by TimHi** [comment]
I believe you are correct, in the end a coworker implemented a workaround for this, looking at our code he added a delay before setting up the scanner. The whole setup etc is still called in OnCreateView 

```
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults)
        {
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            var lbNotGrantedPermission = Array.Exists<Permission>(grantResults, permission => permission != Permission.Granted);

            if (lbNotGrantedPermission == true)
            {
                // Some permissions were not granted
                moCameraPermissionsDescription.Visibility = ViewStates.Visible;
            }
            else
            {
                // All permissions were granted
                Handler loHandler = new Handler();
                Action loAction = () =>
                {
                    SetUpScanner();
                };

                // We need some delay due to animated transition between the fragments. Also, without delay
                // the scanner don't work right after permissions were granted(only the first time)
                **loHandler.PostDelayed(loAction, miSetupScannerDelay);**
            }
        }
```

**Comment by ElteHupkes** [comment]
@Cheesebaron Yes, that was exactly my conclusion here: https://github.com/Redth/ZXing.Net.Mobile/issues/643#issuecomment-357204858. I actually thought this had been resolved by now. Anyway, the workaround I added there probably still does the trick.

**Comment by Cheesebaron** [comment]
Ah, yes. You are right. Not sure what the better approach would be though. I don't like the delay code.

Perhaps, just check if callback was set in `OnCreateView`, and call `StartScanning` if so. This way it doesn't automatically start scanning if someone didn't call `StartScanning` already.
