### ISSUE TITLE
Not able scan Barcode

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [Redth/ZXing.Net.Mobile#958]
Hi All,

I am not able to scann Below BARCODE for Some Thirdpaty app is able to Scan.Can You Please help is there any way to scan below Image

![image](https://user-images.githubusercontent.com/5734910/98827293-b65be900-245c-11eb-9681-6689ecfde6f6.png)

**Comment by meJevin** [comment]
@RAMESHKUMAR502, how is this related to the library?

**Comment by Redth** [comment]
You could ask in the upstream project: https://github.com/micjahn/ZXing.Net

But I expect there's too much noise in that barcode to scan.
