### ISSUE TITLE
Call to Scan method for app running on iOS aborts after displaying camera.

### ISSUE THREAD

**Issue by tnewell** [Redth/ZXing.Net.Mobile#960]
Pressing Scan button on UI to invoke barcode scanning does bring up the camera, but library routine aborts after that (see Debug Output below), so no scanning happens. Clicking Cancel on screen does come back to async calling method, but obviously delivers null result. This happens with 2.4.1 or newer 3.0.0 (beta) libraries. I am using mechanism that allows app to be deployed to iOS device from Visual Studio 2019 via Hot Load. Scanning works great on virtual Android and UWP emulators and on physical Android 7" tablet.

Hardware
-----------------------------------------------------
iPhone XR
iOS 14.2

Main Xamarin App
-----------------------------------------------------

Xamarin.Forms (5.0.0.1709-pre4) - Was 4.8.0.1687
ZXing.Net.Mobile (3.0.0-beta5) - Was 2.4.2
ZXing.Net.Mobile.Forms (3.0.0-beta5) - Was 2.4.1

iOS-specific library
-----------------------------------------------------

Added to info.plist (did have an issue with camera not coming up at all, but this solved it)

  <key>NSCameraUsageDescription</key>
  <string>Require access to camera to scan barcodes</string>

XAML
-----------------------------------------------------

<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="SandboxXamarinApp.TaskPage" Title="{Binding TaskCaption}" x:Name="Tasks" CurrentPageChanged="Tasks_CurrentPageChanged">

    <ContentPage x:Name="InventoryTab" Title="Inventory" Appearing="InventoryTab_Appearing">

        <StackLayout Orientation="Vertical" Padding="0,10,0,0">

            <StackLayout Orientation="Horizontal" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" IsVisible="{Binding IsError}">
                <Label Text="{Binding ErrorMessage}" WidthRequest="160" TextColor="Red" FontAttributes="Bold" VerticalTextAlignment="Center"></Label>
            </StackLayout>

            <StackLayout Orientation="Horizontal" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" IsVisible="{Binding InvokeScanner}">
                <Button Text="SCAN" CornerRadius="3" BorderColor="Black" BackgroundColor="Red" Clicked="InvokeScanner_Clicked"></Button>
            </StackLayout>

        </StackLayout>

    </ContentPage>

</TabbedPage>

Code
-----------------------------------------------------
private async void InvokeScanner()
{
    try
    {
        MobileBarcodeScanner scanner = new MobileBarcodeScanner();

        var result = await scanner.Scan(new ZXing.Mobile.MobileBarcodeScanningOptions()
        {
            PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.QR_CODE },
        });

        if (result != null)
        {
            System.Diagnostics.Debug.WriteLine(String.Format("Result = |{0}|", result.Text));

            Barcode = result.Text;
        }
    }
    catch (Exception ex)
    {
        System.Diagnostics.Debug.WriteLine(ex.ToString());
    }
}

private void InvokeScanner_Clicked(object sender, EventArgs e)
{
    TheApp.DataModel.CurrentSubmission = null;
    ViewModel.Update(TheApp.Equipment, TheApp.FailureReasons, TheApp.DataModel);

    TheApp.LastAction = "Scan";

    Barcode = null;

    InvokeScanner();
}

Debug Output
-----------------------------------------------------

[0:] Page changed to 'Inventory'.
[0:] 'Inventory' tab appearing. TaskPage.CurrentPage = 'Inventory'.
2020-11-23 17:41:25.167 Xamarin.PreBuilt.iOS[1057:116251] Starting to scan...

2020-11-23 17:41:25.233 Xamarin.PreBuilt.iOS[1057:116251] ZXingScannerView.Setup() took 56.525 ms.
2020-11-23 17:41:25.233 Xamarin.PreBuilt.iOS[1057:116251] StartScanning

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================

	Native stacktrace:
=================================================================

	0x102174120 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x10216acbc - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash
	0x102177a60 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug

	0x1f3482290 - /usr/lib/system/libsystem_platform.dylib : <redacted>

	0x102306b14 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_collapse_struct_name

	0x1023122c8 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : _ZL15param_iter_next14IteratorActionPvPKcmS0_Pj

	0x10230c0b4 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_invoke_trampoline

	0x1023121a4 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_arch_trampoline

	0x102312d48 - /private/var/containers/Bundle/Application/40CAA00D-ECA6-4552-8072-FE752B49E775/SandboxXamarinApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_arm64_common_trampoline

	0x1c37d5634 - /System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture : <redacted>
	0x1c37d5360 - /System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture : <redacted>
	0x1c389cfd8 - /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture : <redacted>
	0x1c3b07860 - /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture : <redacted>

	0x1a9c64db0 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1a9c6812c - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1a9c79c08 - /usr/lib/system/libdispatch.dylib : <redacted>

	0x1a9c6bfd8 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1a9c6cc5c - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1a9c76d78 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1f3488804 - /usr/lib/system/libsystem_pthread.dylib : _pthread_wqthread
	0x1f348f75c - /usr/lib/system/libsystem_pthread.dylib : start_wqthread

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1023069f4):0x1023069e4  a8 83 5e f8 09 00 80 52 09 01 00 39 a8 03 5f f8  ..^....R...9.._.
0x1023069f4  09 01 40 39 69 0f 00 34 a8 03 5f f8 09 01 c0 39  ..@9i..4.._....9
0x102306a04  29 8d 00 71 e8 03 09 aa 08 7d 40 d3 1f 69 01 f1  )..q.....}@..i..
0x102306a14  e8 13 00 f9 68 0b 00 54 08 00 00 90 08 21 31 91  ....
h..T.....!1.

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

2020-11-23 17:42:05.751 Xamarin.PreBuilt.iOS[1057:116251] Stopping...

[0:] 'Inventory' tab appearing. TaskPage.CurrentPage = 'Inventory'.
[HotReload] (2020-11-23 17:42:21.9): INFO: (SandboxXamarinApp.iOS) Stopped Hot Reload session due to ExplicitlyEnded ...
[HotReload] (2020-11-23 17:42:21.9): INFO: Stopped Hot Reload session.
The app has been terminated.

**Comment by dienbien001** [comment]
Same here. Work great on Android, but not on iOS.
I'm using iOS 14.2 too

**Comment by PJTewkesbury** [comment]
Hi,
I also get the same error on iOS device using V14.2 and same code works without errors on Android. VS2019 v16.8.2, Xamarin forms V4.8.0.1687, ZXing V2.4.1

**Comment by Redth** [comment]
Ahh yes I think this all just needs to be recompiled with newer xamarin.ios and re-released.  I believe there were some changes to trampoline code to mitigate some MDM related issues that could be interfering with this.

New version is coming shortly.

**Comment by DerLud3** [comment]
So i got the same error. Is it working and when, how can i fix my code?
