### ISSUE TITLE
Does ZXing, scanner work with Ios 14.2 ?

### ISSUE THREAD

**Issue by MurrayJack** [Redth/ZXing.Net.Mobile#961]
Hi, 

we have had an app running for a while using the barcode scanning app, this has all worked perfectly for ages, now we have some customers upgrading to ios 14.2 this scanner has stopped working and only shows a blank screen..

So my question is does this work with ios14.2? I noticed the nuget seems to have been abandoned and has seen no changes for about 9 months

thanks

Murray

**Comment by JCTRoth** [comment]
Hi MurrayJack,
I can confirm that ZXing 3.0 works greate on iOS 14.2 .

Blackscreen did only occur if there has been a problem with the permissions.
-> Permission management on Android 5-11 works.
So maybe this will solve your problem:

```C#
if(Device.RuntimePlatform == Device.iOS)
{
var status = await Permissions.CheckStatusAsync<Permissions.Camera>();
if(status != PermissionStatus.Granted)
{
status = await Permissions.RequestAsync<Permissions.Camera>();
}
if (status != PermissionStatus.Granted)
{
return;
}
}

// Init. Your ZXing page here
````

**Comment by dienbien001** [comment]
@JCTRoth can you share your code or sample that work on ios? I'm getting problem with ios 14.2, call Scan method work fine, but barcode cannot be scanned. Sample of @Redth does not work either.

**Comment by JCTRoth** [comment]
@dienbien001 If you tell me more precisely what is not working then I might be able to help you. But still you can try this: https://www.youtube.com/watch?v=kwVtlT3E7fw

**Comment by MurrayJack** [comment]
Hi thanks, everyone, some rejigging of the code worked, we must have been doing something strange that ios14.2 didn't like

alls good now
