### ISSUE TITLE
Will this work with Xamarin Forms 5 Beta?

### ISSUE THREAD

**Issue by chuckgiddens** [Redth/ZXing.Net.Mobile#962]
Can I use this with Xamarin Forms Version 5 yet?  I ask because no matter what I do, the camera is reported as NOT AVAILABLE on iOS and Android.

Thanks!

**Comment by ekjuanrejon** [comment]
@chuckgiddens 

Did you manage to get it to work.. now that 5 is released?

**Comment by Redth** [comment]
Updating to use forms 5 stable shortly.
